import * as THREE from './vendor/three.module.js';
import * as CANNON from './vendor/cannon-es.js';

const $=id=>document.getElementById(id);
const stage=$('stage'), host=$('scene');
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.5;host.appendChild(renderer.domElement);
const scene=new THREE.Scene();scene.fog=new THREE.Fog(0x8d75b5,24,51);
const camera=new THREE.PerspectiveCamera(45,1,.1,80);camera.position.set(0,6.7,17.3);camera.lookAt(0,1.4,-4.5);
scene.add(new THREE.HemisphereLight(0xfff4df,0x664783,2.5));
const sun=new THREE.DirectionalLight(0xffffff,3.2);sun.position.set(-4,12,8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-20;sun.shadow.camera.right=20;sun.shadow.camera.top=20;sun.shadow.camera.bottom=-20;sun.shadow.bias=-.0004;scene.add(sun);
const fill=new THREE.PointLight(0xffa7ca,70,30);fill.position.set(6,6,-5);scene.add(fill);
const mat=(color,roughness=.72,metalness=0,extra={})=>new THREE.MeshStandardMaterial({color,roughness,metalness,...extra});
const frosting=[0xf39dbb,0xb58ce2,0x8dd5c7,0xf8ca79,0x96b9e8];
const doughMat=mat(0xc78950),sprinkleMats=[mat(0xffeb8e),mat(0x83d5dd),mat(0xe778ad),mat(0xffffff),mat(0x8d6cbc)];
const world=new CANNON.World({gravity:new CANNON.Vec3(0,-19.5,0)});world.allowSleep=true;world.defaultContactMaterial.friction=.45;world.defaultContactMaterial.restitution=.24;
const groundMat=new CANNON.Material('ground'),donutPhys=new CANNON.Material('donut');world.addContactMaterial(new CANNON.ContactMaterial(groundMat,donutPhys,{friction:.65,restitution:.36}));
const entities=[],decor=[],targets=[],crumbs=[];let milk=null,donut=null,ammo=0,score=0,level=0,down=0,shot=false,won=false,aiming=false,dragStart=null,shotAt=0,flightTimeout=null,broken=false,loading=false,muted=false,audio=null,lastCall=0;
const levels=[
 {title:'The first knock',label:'01 / THE COUNTER',desc:'Topple the cans.',mission:'Knock over the cans',goal:3,ammo:5,objects:[[-1.15,'can'],[0,'can'],[1.15,'can']]},
 {title:'Stack attack',label:'02 / STACK ATTACK',desc:'A little chaos goes a long way.',mission:'Topple the stack',goal:5,ammo:6,objects:[[-1.4,'box'],[0,'box'],[1.4,'box'],[-.7,'can',2.23],[.7,'can',2.23]]},
 {title:'The milk run',label:'03 / THE MILK RUN',desc:'Avoid the milk. Soggy donuts crumble.',mission:'Clear the cans',goal:4,ammo:6,milk:true,objects:[[-2.5,'can'],[-1.45,'can'],[1.45,'can'],[2.5,'can']]},
 {title:'Domino dough',label:'04 / DOMINO DOUGH',desc:'One good hit starts a chain.',mission:'Tip the dominoes',goal:6,ammo:7,objects:[[-2.7,'domino'],[-1.65,'domino'],[-.6,'domino'],[.45,'domino'],[1.5,'domino'],[2.55,'domino']]},
 {title:'Double trouble',label:'05 / DOUBLE TROUBLE',desc:'The milk is in the way again.',mission:'Clear the counter',goal:7,ammo:8,milk:true,objects:[[-2.75,'box'],[-1.75,'can'],[-.8,'can'],[.8,'can'],[1.75,'can'],[2.75,'box'],[-2.1,'can',2.18],[2.1,'can',2.18]]},
 {title:'The grand slam',label:'06 / GRAND SLAM',desc:'Leave no stack standing.',mission:'Demolish the finale',goal:9,ammo:10,milk:true,objects:[[-3,'domino'],[-2,'domino'],[-1,'domino'],[1,'domino'],[2,'domino'],[3,'domino'],[-2.45,'can',2.36],[-1.45,'can',2.36],[1.45,'can',2.36],[2.45,'can',2.36]]}
];
function addMesh(geometry,material,x,y,z,shadow=true){const m=new THREE.Mesh(geometry,material);m.position.set(x,y,z);m.castShadow=shadow;m.receiveShadow=true;scene.add(m);decor.push(m);return m}
function makeStaticBox(x,y,z,w,h,d,color,physical=true){const m=addMesh(new THREE.BoxGeometry(w,h,d),mat(color),x,y,z);if(physical){const b=new CANNON.Body({mass:0,material:groundMat});b.addShape(new CANNON.Box(new CANNON.Vec3(w/2,h/2,d/2)));b.position.set(x,y,z);world.addBody(b)}return m}
makeStaticBox(0,-.48,-3,30,.9,29,0x423154);makeStaticBox(0,.05,-7.4,10,.8,5.4,0xf2c889);makeStaticBox(0,.46,-7.4,10,.07,5.4,0xffe9b9,false);
for(let i=0;i<8;i++){let plank=makeStaticBox(-5.55+i*1.58,-.03,1.5,.025,.05,10.5,0x75618c,false);plank.receiveShadow=false}
makeStaticBox(0,-.05,1.5,11,.16,9.5,0x9c83b9,false);
// The counter rim catches strays and gives the set a toy-like silhouette.
makeStaticBox(0,.08,-10.1,10.3,.28,.18,0xc9906f);makeStaticBox(-5.08,.08,-7.4,.18,.28,5.5,0xc9906f);makeStaticBox(5.08,.08,-7.4,.18,.28,5.5,0xc9906f);
const back=addMesh(new THREE.PlaneGeometry(80,35),new THREE.MeshBasicMaterial({color:0xb495d0}),0,12,-20,false);
const stripe=addMesh(new THREE.PlaneGeometry(80,3),new THREE.MeshBasicMaterial({color:0xdcb3d0}),0,7,-19.9,false);
const permanentDecorCount=decor.length;
const ballShape=new CANNON.Sphere(.38);
function makeBody(mesh,shape,mass,x,y,z,kind,opts={}){const b=new CANNON.Body({mass,material:kind==='donut'?donutPhys:undefined,linearDamping:opts.damping??.15,angularDamping:.14});b.addShape(shape);b.position.set(x,y,z);b.sleepSpeedLimit=.12;b.sleepTimeLimit=.8;world.addBody(b);entities.push({mesh,body:b,kind,...opts});return b}
function cylinderShape(r1,r2,h){return new CANNON.Cylinder(r1,r2,h,12)}
function addSprinkles(group,radius,count){for(let i=0;i<count;i++){let a=Math.random()*Math.PI*2,r=radius+(Math.random()-.5)*.26;let p=new THREE.Mesh(new THREE.CapsuleGeometry(.023,.1,2,4),sprinkleMats[i%sprinkleMats.length]);p.position.set(Math.cos(a)*r,Math.sin(a)*r,.16+Math.random()*.045);p.rotation.z=a+(Math.random()-.5)*1.3;group.add(p)}}
function donutMesh(index,crumb=false){const g=new THREE.Group();const dough=new THREE.Mesh(new THREE.TorusGeometry(crumb?.38:.44,crumb?.14:.18,12,36),doughMat);dough.castShadow=true;g.add(dough);let top=new THREE.Mesh(new THREE.TorusGeometry(crumb?.38:.44,crumb?.075:.102,8,36),mat(frosting[index%frosting.length],.48));top.position.z=.13;top.castShadow=true;g.add(top);addSprinkles(g,crumb?.38:.44,crumb?11:26);return g}
function createDonut(){if(ammo<=0||won)return;let mesh=donutMesh((level+levels[level].ammo-ammo)%frosting.length);mesh.position.set(0,1.3,5.8);mesh.rotation.set(-.21,0,-.12);scene.add(mesh);donut={mesh,body:null,start:performance.now()};$('centerPrompt').style.opacity=1}
function makeTarget(x,type,yOverride,zOffset=0,index=0){let h=type==='domino'?1.55:type==='box'?1.2:1.1;let y=yOverride??(.5+h/2);let z=-7.6+zOffset;let mesh,shape,mass;
 if(type==='can'){mesh=new THREE.Group();let c=new THREE.Mesh(new THREE.CylinderGeometry(.37,.37,h,20),mat([0x75c0c1,0xf18aa3,0xf2bf73,0x9d89ce][index%4],.37,.09));c.castShadow=true;c.receiveShadow=true;mesh.add(c);const band=new THREE.Mesh(new THREE.CylinderGeometry(.375,.375,.24,20),mat(0xfff4df,.48));mesh.add(band);let lid=new THREE.Mesh(new THREE.CylinderGeometry(.375,.375,.06,20),mat(0xf7e3cc,.28,.3));lid.position.y=h/2;mesh.add(lid);shape=cylinderShape(.37,.37,h);mass=1.05}
 else {let w=type==='box'?.97:.39,d=type==='box'?.76:.72;mesh=new THREE.Group();let body=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(type==='box'?0xf3a47c:0xe7c073));body.castShadow=true;body.receiveShadow=true;mesh.add(body);let label=new THREE.Mesh(new THREE.BoxGeometry(w*.72,h*.24,d+.012),mat(type==='box'?0xffe5ba:0xd36e7c));mesh.add(label);shape=new CANNON.Box(new CANNON.Vec3(w/2,h/2,d/2));mass=type==='box'?1.65:.68}
 mesh.position.set(x,y,z);scene.add(mesh);let b=makeBody(mesh,shape,mass,x,y,z,'target',{origin:new THREE.Vector3(x,y,z),type,fallen:false});b.addEventListener('collide',e=>{let other=e.body;if(other===donut?.body&&performance.now()-lastCall>100){lastCall=performance.now();sound('hit');message(['BONK!','CRUNCH!','KAPOW!'][Math.floor(Math.random()*3)]);if(!broken)shatterDonut(false)}});targets.push(entities.at(-1));return b}
function createMilk(){const x=0,y=.5,z=-5.7;const wall=new THREE.Mesh(new THREE.CylinderGeometry(.92,.72,2.1,32,1,true),new THREE.MeshPhysicalMaterial({color:0xd8f8ff,transparent:true,opacity:.3,side:THREE.DoubleSide,roughness:.1,metalness:.1,depthWrite:false}));wall.position.set(x,y+1.05,z);scene.add(wall);decor.push(wall);addMesh(new THREE.CylinderGeometry(.82,.76,1.5,32),mat(0xfffcf1,.17,0,{transparent:true,opacity:.84}),x,y+.75,z);const lip=addMesh(new THREE.TorusGeometry(.92,.045,8,32),mat(0xe9f8ff,.2,.1),x,y+2.1,z);lip.rotation.x=Math.PI/2;milk={x,z,y:.5,r:.81,top:2.6,used:false}}
function clearLevel(){if(flightTimeout)clearTimeout(flightTimeout);for(const e of entities){scene.remove(e.mesh);world.removeBody(e.body)}entities.length=0;targets.length=0;for(const m of decor.splice(permanentDecorCount)){scene.remove(m)}crumbs.length=0;if(donut&&!donut.body)scene.remove(donut.mesh);donut=null;milk=null;down=0;shot=false;won=false;broken=false;aiming=false;$('nextBtn').hidden=true;$('flightMessage').classList.remove('show');$('aim').hidden=true}
function loadLevel(n){clearLevel();level=n%levels.length;const l=levels[level];ammo=l.ammo;$('levelNo').textContent=String(level+1).padStart(2,'0');$('levelLabel').textContent=l.label;$('levelTitle').textContent=l.title;$('levelDesc').textContent=l.desc;$('mission').textContent=l.mission;$('progress').textContent=`0 / ${l.goal}`;$('progressBar').style.width='0%';for(let i=0;i<l.objects.length;i++){let [x,type,y]=l.objects[i];makeTarget(x,type,y,((i%3)-1)*.28,i)}if(l.milk)createMilk();updateAmmo();createDonut()}
function updateAmmo(){$('ammoIcons').innerHTML=Array.from({length:levels[level].ammo},(_,i)=>`<i class="${i>=ammo?'spent':''}"></i>`).join('')}
function message(t){const e=$('flightMessage');e.textContent=t;e.classList.remove('show');void e.offsetWidth;e.classList.add('show')}
function sound(type){if(muted)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();let o=audio.createOscillator(),gain=audio.createGain(),now=audio.currentTime;o.type=type==='launch'?'sine':type==='win'?'triangle':'square';o.frequency.setValueAtTime(type==='launch'?250:type==='win'?420:110,now);o.frequency.exponentialRampToValueAtTime(type==='launch'?95:type==='win'?860:45,now+.2);gain.gain.setValueAtTime(.12,now);gain.gain.exponentialRampToValueAtTime(.001,now+.24);o.connect(gain).connect(audio.destination);o.start();o.stop(now+.25)}catch{}}
function shatterDonut(soggy){if(broken||!donut)return;broken=true;let p=donut.body?.position||donut.mesh.position;let vel=donut.body?.velocity;let x=p.x,y=p.y,z=p.z;scene.remove(donut.mesh);if(donut.body){world.removeBody(donut.body);const i=entities.findIndex(e=>e.body===donut.body);if(i>=0)entities.splice(i,1)}for(let i=0;i<16;i++){let a=Math.random()*Math.PI*2,r=.045+Math.random()*.085;let piece=new THREE.Mesh(new THREE.IcosahedronGeometry(r,0),mat(i%4===0?frosting[level%frosting.length]:0xc98954));piece.castShadow=true;scene.add(piece);let b=makeBody(piece,new CANNON.Sphere(r),.025,x+(Math.random()-.5)*.45,y+(Math.random()-.5)*.3,z+(Math.random()-.5)*.3,'crumb',{lifetime:performance.now()+3600});b.velocity.set((vel?.x??0)*.25+Math.cos(a)*(soggy?1:3)*Math.random(),(vel?.y??0)*.1+Math.random()*(soggy?1:3),(vel?.z??0)*.25+Math.sin(a)*3*Math.random());crumbs.push(b)}donut=null;sound(soggy?'sog':'hit');if(soggy)message('SOGGY!')}
function fire(dx,dy){if(!donut||shot||won||ammo<1)return;let pull=Math.min(180,Math.hypot(dx,dy));if(pull<9)return;shot=true;broken=false;ammo--;updateAmmo();let xPower=THREE.MathUtils.clamp(-dx/75,-2.1,2.1);let lift=THREE.MathUtils.clamp(-dy/100,0,1.5);let speed=19+pull/25;let b=makeBody(donut.mesh,ballShape,1.2,0,1.3,5.8,'donut');donut.body=b;b.velocity.set(xPower*2.9,6.7+lift,-speed);b.angularVelocity.set(8+pull/30,3,-xPower*3);shotAt=performance.now();sound('launch');$('centerPrompt').style.opacity=0;flightTimeout=setTimeout(()=>{if(donut&&!broken)shatterDonut(false);if(!won){if(ammo>0){shot=false;createDonut()}else if(down<levels[level].goal){message('TRY AGAIN!');setTimeout(()=>{$('centerPrompt').textContent='TAP RETRY TO GO AGAIN';$('centerPrompt').style.opacity=1},800)}}},3000)}
function checkTargets(){for(const t of targets){if(t.fallen)continue;let b=t.body;let ang=2*Math.acos(Math.min(1,Math.abs(b.quaternion.w)));let lateral=Math.hypot(b.position.x-t.origin.x,b.position.z-t.origin.z);let height=b.position.y;if((ang>.83&&lateral>.15)||(lateral>.88)||(height<t.origin.y-.65)){t.fallen=true;down++;let bonus=t.type==='domino'?150:t.type==='box'?200:100;score+=bonus;$('score').textContent=String(score).padStart(5,'0');$('progress').textContent=`${Math.min(down,levels[level].goal)} / ${levels[level].goal}`;$('progressBar').style.width=`${Math.min(100,down/levels[level].goal*100)}%`;sound('hit');if(down>=levels[level].goal&&!won){won=true;score+=Math.max(0,ammo)*75;$('score').textContent=String(score).padStart(5,'0');message(level===levels.length-1?'SWEET VICTORY!':'SWEET CLEAR!');sound('win');$('nextBtn').hidden=false;$('nextBtn').textContent=level===levels.length-1?'PLAY AGAIN →':'NEXT LEVEL →';$('centerPrompt').style.opacity=0}}}}
function frame(t){requestAnimationFrame(frame);let dt=Math.min(.05,(t-(frame.last||t))/1000);frame.last=t;if(!loading){world.step(1/60,dt,3);for(const e of entities){e.mesh.position.set(e.body.position.x,e.body.position.y,e.body.position.z);e.mesh.quaternion.set(e.body.quaternion.x,e.body.quaternion.y,e.body.quaternion.z,e.body.quaternion.w);if(e.lifetime&&t>e.lifetime){scene.remove(e.mesh);world.removeBody(e.body);e.expired=true}}for(let i=entities.length-1;i>=0;i--)if(entities[i].expired)entities.splice(i,1);if(donut&&!donut.body){donut.mesh.rotation.z=-.12+Math.sin(t*.004)*.055;donut.mesh.position.y=1.3+Math.sin(t*.004)*.04}if(milk&&donut?.body&&!milk.used){let p=donut.body.position;if(Math.hypot(p.x-milk.x,p.z-milk.z)<milk.r&&p.y<milk.top&&p.y>.4){milk.used=true;donut.body.velocity.scale(.1,donut.body.velocity);setTimeout(()=>shatterDonut(true),220)}}checkTargets()}renderer.render(scene,camera)}requestAnimationFrame(frame);
function resize(){let w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.fov=w<600?57:45;camera.position.set(0,w<600?8.4:6.7,w<600?18.5:17.3);camera.lookAt(0,1.25,-4.7);camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(stage);resize();
stage.addEventListener('pointerdown',e=>{if($('intro').hidden&&!shot&&donut&&!won){stage.setPointerCapture(e.pointerId);aiming=true;dragStart={x:e.clientX,y:e.clientY};$('aim').hidden=false;drawAim(e)}});
stage.addEventListener('pointermove',e=>{if(aiming)drawAim(e)});
function drawAim(e){let dx=e.clientX-dragStart.x,dy=e.clientY-dragStart.y;let l=Math.min(180,Math.hypot(dx,dy));let line=$('aim').firstElementChild;line.style.left=dragStart.x-stage.getBoundingClientRect().left+'px';line.style.top=dragStart.y-stage.getBoundingClientRect().top+'px';line.style.height=l+'px';line.style.transform=`rotate(${-Math.atan2(dx,dy)}rad)`;let c=$('aim').lastElementChild;c.style.left=e.clientX-stage.getBoundingClientRect().left+'px';c.style.top=e.clientY-stage.getBoundingClientRect().top+'px'}
stage.addEventListener('pointerup',e=>{if(!aiming)return;aiming=false;$('aim').hidden=true;fire(e.clientX-dragStart.x,e.clientY-dragStart.y)});
stage.addEventListener('pointercancel',()=>{aiming=false;$('aim').hidden=true});
$('playBtn').onclick=()=>{$('intro').hidden=true;loadLevel(0)};
$('restartBtn').onclick=()=>{$('centerPrompt').textContent='DRAG BACK · RELEASE TO FLING';loadLevel(level)};
$('nextBtn').onclick=()=>{$('centerPrompt').textContent='DRAG BACK · RELEASE TO FLING';loadLevel((level+1)%levels.length)};
$('soundBtn').onclick=()=>{muted=!muted;$('soundBtn').textContent=muted?'♪̸':'♫';$('soundBtn').setAttribute('aria-label',muted?'Turn sound on':'Mute sound')};
window.addEventListener('keydown',e=>{if(e.key==='r'||e.key==='R')loadLevel(level);if(e.key===' '){e.preventDefault();if(!$('intro').hidden)$('playBtn').click();else if(!shot)fire((Math.random()-.5)*30,-100)}});
