import test from 'node:test';
import assert from 'node:assert/strict';
import {Game,LEVELS,TYPES,cleanSave} from '../engine.mjs';
const advance=(g,seconds)=>{for(let i=0;i<Math.ceil(seconds/.05);i++)g.step(.05)};
const fixture=type=>{const g=new Game({},()=>.5);g.start(0);g.enemies=[];g.spawnClock=-999;g.invulnerable=0;const e=g.spawn(type);e.x=.5;e.y=.4;e.vx=0;e.vy=0;return {g,e};};
function seeded(seed){return ()=>{seed=(Math.imul(1664525,seed)+1013904223)>>>0;return seed/4294967296}}
test('15 levels, five genuinely new types, three distinct bosses',()=>{assert.equal(LEVELS.length,15);assert.equal(Object.values(TYPES).filter(t=>t.new).length,5);assert.deepEqual(LEVELS.filter(l=>l.boss).map(l=>l.boss),['king','goliath','moon']);for(const l of LEVELS){assert.ok(l.goal>0);for(const t of l.pool)assert.ok(TYPES[t]);}});
test('save data is finite, bounded, and cannot overdraw perks',()=>{const s=cleanSave({unlocked:Infinity,stars:[99,-1,'3',NaN],upgrades:{heart:3,tongue:3,bloom:3}});assert.equal(s.unlocked,0);assert.deepEqual(s.stars.slice(0,4),[3,0,0,0]);assert.deepEqual(s.upgrades,{heart:1,tongue:0,bloom:0});assert.equal(cleanSave(null).won,false);assert.equal(cleanSave({unlocked:100}).unlocked,14);});
test('locked and invalid stages cannot start',()=>{const g=new Game();for(const i of [-1,1,15,1.5,NaN])assert.equal(g.start(i),false);assert.equal(g.start(0),true);});
test('tap at rendered target uses aspect-correct portrait coordinates',()=>{const {g,e}=fixture('fly');g.shoot(e.x+.025,e.y+.01,1.6);assert.equal(g.progress,1);assert.equal(g.enemies.length,0);});
test('rapid taps respect cooldown and guarded hits do not damage',()=>{const {g,e}=fixture('beetle');assert.equal(g.shoot(e.x,e.y),true);assert.equal(e.hp,1);assert.equal(g.shoot(e.x,e.y),false);advance(g,.2);g.shoot(e.x,e.y);assert.equal(g.progress,2);});
test('misses do not grant snacks or Blooms',()=>{const {g}=fixture('fly');g.shoot(.01,.95);assert.equal(g.progress,0);assert.equal(g.blooms,2);assert.equal(g.misses,1);});
test('hazards hurt once during invulnerability, and zero hearts stops play',()=>{const {g,e}=fixture('bee');g.shoot(e.x,e.y);assert.equal(g.hp,4);advance(g,.2);g.shoot(e.x,e.y);assert.equal(g.hp,4);for(let i=0;i<4;i++){advance(g,1.2);g.shoot(e.x,e.y);}assert.equal(g.mode,'dead');assert.equal(g.hp,0);assert.equal(g.hop(),false);assert.equal(g.bloom(),false);});
test('hop dodges attacks and cannot be spammed',()=>{const {g}=fixture('wasp');assert.equal(g.hop(),true);assert.equal(g.hurt('attack'),false);assert.equal(g.hop(),false);advance(g,1);assert.equal(g.hurt('attack'),true);advance(g,1.3);assert.equal(g.hop(),true);});
test('paused timers, enemies, flowers and attacks remain frozen',()=>{const {g}=fixture('wasp');g.bloom();g.hop();g.pause();const snapshot=JSON.stringify({enemies:g.enemies,flowers:g.flowers,time:g.time,hop:g.hopCooldown});advance(g,10);assert.equal(JSON.stringify({enemies:g.enemies,flowers:g.flowers,time:g.time,hop:g.hopCooldown}),snapshot);assert.equal(g.shoot(.5,.4),false);g.resume();g.step(.05);assert.ok(g.time>0);});
test('Bloom lures hazards and BOOM consumes flowers exactly once',()=>{const {g,e}=fixture('bee');g.bloom();e.x=.23;e.y=.63;assert.equal(g.blooms,1);assert.equal(g.boom(),true);assert.equal(g.enemies.length,0);assert.equal(g.flowers.length,0);assert.equal(g.boom(),false);});
test('expired flowers cannot be detonated',()=>{const {g}=fixture('fly');g.bloom();advance(g,8.1);assert.equal(g.flowers.length,0);assert.equal(g.boom(),false);});
test('five noms recharge one Bloom',()=>{const {g}=fixture('fly');g.enemies=[];g.progress=-100;for(let i=0;i<5;i++){const e=g.spawn('fly');g.damage(e,1);}assert.equal(g.blooms,3);});
for(const type of ['mantis','snail','mimic'])test(`${type} has guard and vulnerable windows`,()=>{const {g,e}=fixture(type);e.offset=0;g.step(.05);assert.equal(e.open,false);g.shoot(e.x,e.y);assert.equal(e.hp,e.maxHp);advance(g,2.8);assert.equal(e.open,true);g.shoot(e.x,e.y);assert.equal(e.hp,e.maxHp-1);});
test('Bloom exposes mantis and snail early',()=>{for(const type of ['mantis','snail']){const {g,e}=fixture(type);e.offset=0;g.step(.05);assert.equal(e.open,false);g.bloom();g.step(.05);assert.equal(e.open,true);}});
test('dive wasp telegraphs then damages, a timed hop prevents damage',()=>{let {g,e}=fixture('wasp');advance(g,3.8);assert.equal(e.phase,'warning');assert.equal(g.hp,5);g.hop();advance(g,1.1);assert.equal(g.hp,4,'hopping too early is not permanent immunity');({g,e}=fixture('wasp'));advance(g,4.3);g.hop();advance(g,.6);assert.equal(g.hp,5);});
test('spore projectiles can be intercepted and otherwise deal damage',()=>{const {g,e}=fixture('spore');advance(g,4.3);assert.ok(g.projectiles.length>0);const p=g.projectiles[0];g.shoot(p.x,p.y);assert.equal(g.projectiles.length,0);g.projectile(e);advance(g,3);assert.equal(g.hp,4);});
for(const type of ['king','goliath','moon'])test(`${type} boss blocks guard hits and has damaging attack / vulnerable phase`,()=>{const {g,e}=fixture(type);g.bossSpawned=true;g.step(.05);assert.equal(e.open,false);g.shoot(e.x,e.y);assert.equal(e.hp,e.maxHp);advance(g,2.75);assert.equal(e.phase,'attack');if(type==='moon')assert.equal(g.projectiles.length,3);else assert.equal(g.hp,4);advance(g,.4);assert.equal(e.open,true);g.shoot(e.x,e.y);assert.equal(e.hp,e.maxHp-1);});
test('replaying a stage cannot farm perk currency; upgrades apply next start',()=>{const g=new Game();g.start(0);g.complete();assert.equal(g.tokens,1);assert.equal(g.upgrade('heart'),true);assert.equal(g.tokens,0);g.start(0);assert.equal(g.maxHp,6);g.complete();assert.equal(g.tokens,0);assert.equal(g.upgrade('tongue'),false);});
test('retry resets score, health, attacks, flowers and cooldowns',()=>{const {g}=fixture('spore');g.score=10;g.hp=1;g.bloom();g.hop();g.projectile(g.enemies[0]);g.start(0);assert.equal(g.score,0);assert.equal(g.hp,5);assert.equal(g.projectiles.length,0);assert.equal(g.flowers.length,0);assert.equal(g.hopCooldown,0);});
test('progress save survives serialization and final victory is retained',()=>{const g=new Game({unlocked:14});g.start(14);g.complete();const restored=new Game(JSON.parse(JSON.stringify(g.save)));assert.equal(restored.save.won,true);assert.equal(restored.save.unlocked,14);assert.equal(restored.save.stars[14],3);});
test('hostile cap always leaves edible prey and bounded entity counts',()=>{const g=new Game({unlocked:14},seeded(7));g.start(14);advance(g,120);assert.ok(g.enemies.length<=9);assert.ok(g.enemies.some(e=>!TYPES[e.type].hazard));assert.ok(g.projectiles.length<20);for(const e of g.enemies)assert.ok(Number.isFinite(e.x)&&Number.isFinite(e.y));});
for(const seed of [7,31,99])test(`full 15-stage campaign can be won through shoot/hop inputs, seed ${seed}`,()=>{const g=new Game({},seeded(seed));for(let stage=0;stage<15;stage++){assert.equal(g.start(stage),true);let frames=0;while(g.mode==='playing'&&frames++<4000){
 const danger=g.enemies.find(e=>(TYPES[e.type].boss&&e.type!=='moon'&&e.phase==='warning'&&e.phaseTime>.6)||(e.type==='wasp'&&e.attackClock>4.25));if(danger)g.hop();
 if(g.cooldown<=0){const p=g.projectiles.find(p=>p.y>.55);const target=p||g.enemies.find(e=>e.type==='wasp')||g.enemies.find(e=>e.open&&!TYPES[e.type].hazard);if(target)g.shoot(target.x,target.y,1.4);}
 g.step(.05);g.drain();}
 assert.ok(g.mode==='clear'||g.mode==='victory',`stage ${stage+1}: ${g.mode}, HP ${g.hp}, progress ${g.progress}, frames ${frames}`);
 }assert.equal(g.save.won,true);assert.equal(g.save.stars.filter(Boolean).length,15);});
