import { LOCATION_BY_ID, PRODUCT_BY_ID, WEAPON_BY_ID, enabledProducts } from './config.js?v=8';
import { freeCapacity, totalCapacity } from './state.js';
import { finalScore } from './scoring.js';
import { formatMoney } from './utils.js';

const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const icon = (name,label='') => `<img src="assets/ui/${name}.svg" alt="${escapeHtml(label)}">`;

export class Renderer {
  constructor({main,header,status,actions}) { this.main=main; this.header=header; this.status=status; this.actions=actions; this.quantities=new Map(); }
  showChrome(show) { this.header.hidden=!show; this.status.hidden=!show; this.actions.hidden=!show; }
  renderTitle({classicSave=null,extendedSave=null,settings={},notice=''}) {
    this.showChrome(false);
    const resume=classicSave?`<button class="button dos-wide" type="button" data-action="resume" data-mode="classic">CONTINUE — DAY ${classicSave.day}, ${escapeHtml(LOCATION_BY_ID[classicSave.location]?.name).toUpperCase()}</button>`:'';
    this.main.innerHTML=`<section class="title-screen dos-title" aria-labelledby="game-title"><div class="dos-title-box"><p class="dos-kicker">A THIRTY DAY NEW YORK MARKET GAME</p><h1 id="game-title">MANGOWARZ<br>CLASSIC</h1><p class="dos-rule">BUY LOW. SELL HIGH. PAY THE SHARK. STAY ALIVE.</p>${notice?`<p class="dos-alert" role="alert">${escapeHtml(notice)}</p>`:''}<form id="new-game-form" class="form-stack dos-menu"><input type="hidden" name="mode" value="classic"><button class="button primary dos-wide" type="submit">NEW GAME</button>${resume}<details class="dos-options"><summary>OPTIONS</summary><div class="form-stack"><label class="check-row"><input type="checkbox" name="sixProductVariant"><span><b>SIX-PRODUCT VARIANT</b><small>Use the smaller historical market.</small></span></label><div class="field"><label for="seed-input">DEBUG SEED</label><input id="seed-input" name="seed" autocomplete="off" spellcheck="false" placeholder="Leave blank for random"></div><div class="two-col"><label class="check-row"><input type="checkbox" name="audio" ${settings.audio!==false?'checked':''}><span><b>SOUND</b></span></label><label class="check-row"><input type="checkbox" name="haptics" ${settings.haptics!==false?'checked':''}><span><b>HAPTICS</b></span></label></div></div></details></form><button id="install-button" class="button ghost dos-wide" type="button" hidden>INSTALL</button><p class="dos-foot">$2,000 CASH • $5,500 DEBT • 100 COAT SPACES • 30 DAYS</p></div></section>`;
  }
  renderStatus(state) {
    const free=freeCapacity(state), total=totalCapacity(state), healthClass=state.health<=25?'critical':'';
    this.status.innerHTML=`<div class="status-item"><span>Cash</span><strong>${formatMoney(state.cash)}</strong></div><div class="status-item"><span>Guns</span><strong>${state.weapons.length}</strong></div><div class="status-item ${healthClass?'bad':''}"><span>Health</span><strong>${state.health}%</strong></div><div class="status-item"><span>Bank</span><strong>${formatMoney(state.bank)}</strong></div><div class="status-item bad"><span>Debt</span><strong>${formatMoney(state.debt)}</strong></div><div class="status-item"><span>Coat</span><strong>${free}/${total}</strong></div>`;
    this.header.querySelector('#day-location');
    document.getElementById('day-location').innerHTML=`<span>Day ${state.day} of ${state.maxDay}</span><strong>${escapeHtml(LOCATION_BY_ID[state.location].name)}</strong>`;
  }
  renderGame(state) {
    this.showChrome(true); this.renderStatus(state);
    const loc=LOCATION_BY_ID[state.location];
    const visibleProducts=enabledProducts(state.settings).filter(product=>state.market?.rows?.[product.id]?.available||(state.inventory[product.id]??0)>0);
    const rows=visibleProducts.map((product,index)=>this.marketRow(state,product,index)).join('');
    this.main.innerHTML=`<section class="game-screen dos-game"><div class="dos-location"><span>DAY ${state.day}/${state.maxDay}</span><strong>${escapeHtml(loc.name).toUpperCase()}</strong></div><div class="ticker dos-ticker" role="status"><p>${escapeHtml(state.ticker)}</p></div><div class="dos-market" aria-label="${escapeHtml(loc.name)} market"><div class="market-line market-heading" aria-hidden="true"><span>#</span><span>DRUG</span><span>PRICE</span><span>HAVE</span></div><div class="market-list">${rows}</div></div><p class="dos-prompt">SELECT A LISTED DRUG TO BUY OR SELL.</p>${state.day===state.maxDay?`<button class="button primary dos-wide" data-action="finish-run">FINISH DAY 30</button>`:''}</section>`;
    this.actions.innerHTML=`<button class="nav-button primary-nav" data-action="travel" ${state.day>=state.maxDay||state.ended?'disabled':''}><span><b>[J]</b>ET</span></button><button class="nav-button" data-action="services"><span><b>[V]</b>ISIT</span></button><button class="nav-button" data-action="inventory"><span><b>[I]</b>NV</span></button><button class="nav-button" data-action="history"><span><b>[L]</b>OG</span></button><button class="nav-button" data-action="settings"><span><b>[O]</b>PT</span></button>`;
  }
  marketRow(state,product,index=0) {
    const row=state.market?.rows?.[product.id]; const available=Boolean(row?.available); const owned=state.inventory[product.id]??0;
    const event=row?.event??'ordinary'; const eventText=event==='cheap'?'LOW!':event==='expensive'?'HIGH!':'';
    return `<button type="button" class="market-line ${available?'':'unavailable'}" data-event="${event}" data-action="trade-product" data-product="${product.id}" ${available?'':'disabled'} aria-label="${escapeHtml(product.name)}, ${available?`${formatMoney(row.price)}, ${owned} owned, open trade`:'not for sale'}, ${eventText}"><span class="market-number">${index+1}</span><span class="market-name">${escapeHtml(product.name)} ${eventText?`<small>${eventText}</small>`:''}</span><span class="market-price">${available?formatMoney(row.price):'--------'}</span><span class="market-owned">${owned}</span></button>`;
  }
  renderFinal(state,isBest=false) {
    this.showChrome(false); const score=state.stats.finalScore??finalScore(state); const remaining=Object.entries(state.inventory).filter(([,q])=>q>0).map(([id,q])=>`${PRODUCT_BY_ID[id].name} ×${q}`).join(', ')||'None'; const weapons=state.weapons.map(id=>WEAPON_BY_ID[id]?.name).filter(Boolean).join(', ')||'None';
    this.main.innerHTML=`<section class="final-screen dos-final"><div class="score-hero"><p class="dos-kicker">${state.mode==='classic'?'CLASSIC':'EXTENDED'} RUN COMPLETE</p><h1>${state.health===0?'GAME OVER':'DAY 30 COMPLETE'}</h1><p>FINAL SCORE</p><div class="score-number">${formatMoney(score)}</div>${isBest?'<p class="dos-alert">NEW PERSONAL BEST</p>':''}<p>SEED: <code>${escapeHtml(state.seed)}</code></p></div><div class="score-grid"><div class="score-cell"><span>Cash</span><strong>${formatMoney(state.cash)}</strong></div><div class="score-cell"><span>Bank</span><strong>${formatMoney(state.bank)}</strong></div><div class="score-cell"><span>Debt</span><strong>${formatMoney(state.debt)}</strong></div><div class="score-cell"><span>Health</span><strong>${state.health}/100</strong></div><div class="score-cell"><span>Capacity</span><strong>${freeCapacity(state)} free / ${totalCapacity(state)}</strong></div><div class="score-cell"><span>Trips</span><strong>${state.trips}</strong></div><div class="score-cell"><span>Bought / sold</span><strong>${state.stats.unitsBought} / ${state.stats.unitsSold}</strong></div><div class="score-cell"><span>Police</span><strong>${state.stats.policeEncounters}</strong></div><div class="score-cell"><span>Escapes</span><strong>${state.stats.successfulEscapes}</strong></div><div class="score-cell"><span>Victories</span><strong>${state.stats.combatVictories}</strong></div><div class="score-cell"><span>Best trade</span><strong>${state.stats.bestTrade?`${state.stats.bestTrade.productName} ${formatMoney(state.stats.bestTrade.estimatedProfit)}`:'None'}</strong></div><div class="score-cell"><span>Worst trade</span><strong>${state.stats.worstTrade?`${state.stats.worstTrade.productName} ${formatMoney(state.stats.worstTrade.estimatedProfit)}`:'None'}</strong></div></div><div class="panel-card"><h2>WHAT REMAINS</h2><p><b>Inventory:</b> ${escapeHtml(remaining)}</p><p><b>Weapons:</b> ${escapeHtml(weapons)}</p></div><div class="two-col"><button class="button primary" data-action="play-again">PLAY AGAIN</button><button class="button sell" data-action="share-summary">COPY SCORE</button></div></section>`;
  }
}

export { escapeHtml, icon };
