import { CLASSIC_PRODUCTS, EXTENDED_ASSETS, LOCATION_BY_ID, LOCATIONS, PRODUCT_BY_ID, WEAPON_BY_ID, enabledProducts } from './config.js';
import { netWorth } from './encounters.js';
import { freeCapacity, totalCapacity, usedCapacity } from './state.js';
import { finalScore } from './scoring.js';
import { formatMoney } from './utils.js';

const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const icon = (name,label='') => `<img src="assets/ui/${name}.svg" alt="${escapeHtml(label)}">`;
const productArt = id => `assets/products/${id}.svg`;

export class Renderer {
  constructor({main,header,status,actions}) { this.main=main; this.header=header; this.status=status; this.actions=actions; this.quantities=new Map(); }
  showChrome(show) { this.header.hidden=!show; this.status.hidden=!show; this.actions.hidden=!show; }
  renderTitle({classicSave=null,extendedSave=null,settings={},notice=''}) {
    this.showChrome(false);
    const resumes=[classicSave,extendedSave].filter(Boolean).map(save=>`<button class="resume-card" data-action="resume" data-mode="${save.mode}"><img src="assets/branding/compact-logo.svg" alt=""><span><strong>Resume ${save.mode==='classic'?'Classic':'Extended'}</strong><small>Day ${save.day} • ${LOCATION_BY_ID[save.location]?.name} • ${formatMoney(save.cash)}</small></span><span>Continue</span></button>`).join('');
    this.main.innerHTML=`<section class="title-screen" aria-labelledby="game-title"><div class="title-grid"><figure class="title-art"><img src="assets/branding/splash.webp" alt="Neo-retro city skyline glowing in mango orange and electric blue"><figcaption class="title-copy"><span class="eyebrow">Thirty days. One coat. Bad interest.</span><h1 id="game-title">MangoWarz<br><span class="positive-text">Classic</span></h1><p>Travel. Trade. Survive. Settle up.</p></figcaption></figure><div class="title-panel"><form id="new-game-form" class="form-stack"><div><span class="eyebrow">New run</span><h2>Choose your rules</h2></div>${notice?`<p class="warning-text" role="alert">${escapeHtml(notice)}</p>`:''}<div class="two-col"><div class="mode-card"><label><input type="radio" name="mode" value="classic" checked> Classic Mode</label><small>Exact 30-day core. Inventory is not auto-liquidated.</small></div><div class="mode-card"><label><input type="radio" name="mode" value="extended"> Mango Extended</label><small>Separate save, assets, portfolio score, and absurd progression.</small></div></div><label class="check-row"><input type="checkbox" name="sixProductVariant"><span><b>Six-product historical variant</b><small>Optional simplified market; disabled by default.</small></span></label><div class="field"><label for="seed-input">Debug seed <span class="muted">(blank = secure generated seed)</span></label><input id="seed-input" name="seed" autocomplete="off" spellcheck="false" placeholder="Example: mango-30-day-test"></div><div class="two-col"><label class="check-row"><input type="checkbox" name="audio" ${settings.audio!==false?'checked':''}><span><b>Sound</b><small>Original synthesized effects</small></span></label><label class="check-row"><input type="checkbox" name="haptics" ${settings.haptics!==false?'checked':''}><span><b>Haptics</b><small>Meaningful vibration only</small></span></label></div><button class="button primary" type="submit">Start new run</button></form>${resumes?`<div class="form-stack" style="margin-top:14px"><span class="eyebrow">Saved runs</span>${resumes}</div>`:''}<button id="install-button" class="button ghost" type="button" hidden>Install MangoWarz Classic</button><p class="small" style="margin-top:12px">No analytics. No network at play time. Saves stay on this device.</p></div></div></section>`;
  }
  renderStatus(state) {
    const free=freeCapacity(state), total=totalCapacity(state), healthClass=state.health<=25?'critical':'';
    this.status.innerHTML=`<div class="status-item good"><span>Cash</span><strong>${formatMoney(state.cash)}</strong></div><div class="status-item bad"><span>Debt</span><strong>${formatMoney(state.debt)}</strong></div><div class="status-item"><span>Bank</span><strong>${formatMoney(state.bank)}</strong></div><div class="status-item ${healthClass?'bad':''}"><span>Health</span><strong>${state.health}/100</strong><div class="health-meter ${healthClass}" style="--meter:${state.health}%"><i></i></div></div><div class="status-item"><span>Free coat</span><strong>${free}/${total}</strong><div class="capacity-meter" style="--meter:${Math.round(usedCapacity(state)/Math.max(1,total)*100)}%"><i></i></div></div><div class="status-item"><span>Net worth</span><strong>${formatMoney(netWorth(state))}</strong></div>`;
    this.header.querySelector('#day-location');
    document.getElementById('day-location').innerHTML=`<span>Day ${state.day} of ${state.maxDay}</span><strong>${escapeHtml(LOCATION_BY_ID[state.location].name)}</strong>`;
  }
  renderGame(state) {
    this.showChrome(true); this.renderStatus(state);
    const loc=LOCATION_BY_ID[state.location];
    const alert=state.pendingEncounter?.type==='police'&&!state.pendingEncounter.resolved;
    const hero=state.location==='bronx'&&!alert?'assets/locations/bronx-night.webp':`assets/locations/${state.location}-${alert?'alert':'day'}.svg`;
    const rows=enabledProducts(state.settings).map(product=>this.marketRow(state,product)).join('');
    const marketEvents=state.market?.events?.length ?? 0;
    const pedestrians=Array.from({length:8},(_,i)=>`<img src="assets/civilians/pedestrian-${i+1}.svg" alt="">`).join('');
    this.main.innerHTML=`<section class="game-screen"><div class="hero-grid"><article class="location-card"><img src="${hero}" alt="${escapeHtml(loc.name)} neighborhood establishing scene${alert?', under police alert':''}"><div class="street-crowd" aria-hidden="true">${pedestrians}</div><div class="location-overlay"><span class="eyebrow">Current neighborhood</span><h2>${escapeHtml(loc.name)}</h2><div class="location-meta"><span class="tag">Police ${loc.police}</span><span class="tag">${state.market?.listedCount??0} listings</span>${marketEvents?`<span class="tag expensive">${marketEvents} market shock${marketEvents===1?'':'s'}</span>`:''}</div></div></article><aside class="side-panel"><div class="ticker" role="status">${icon('ticker')}<p>${escapeHtml(state.ticker)}</p></div><div class="panel-card"><span class="eyebrow">Run</span><p><strong>${state.trips}</strong> trips • <strong>${state.stats.transactions}</strong> trades</p></div>${state.day===state.maxDay?`<button class="button primary" data-action="finish-run">Finish Day 30</button>`:''}</aside></div><div class="market-list" aria-label="${escapeHtml(loc.name)} market">${rows}</div></section>`;
    this.actions.innerHTML=`<button class="nav-button primary-nav" data-action="travel" ${state.day>=state.maxDay||state.ended?'disabled':''}>${icon('travel')}<span>Travel</span></button><button class="nav-button" data-action="services">${icon('services')}<span>Services</span></button><button class="nav-button" data-action="inventory">${icon('inventory')}<span>Inventory</span></button><button class="nav-button" data-action="history">${icon('history')}<span>History</span></button><button class="nav-button" data-action="settings">${icon('settings')}<span>More</span></button>`;
  }
  marketRow(state,product) {
    const row=state.market?.rows?.[product.id]; const available=Boolean(row?.available); const owned=state.inventory[product.id]??0;
    const maxBuy=available?Math.min(Math.floor(state.cash/row.price),freeCapacity(state)):0; const maxSell=available?owned:0;
    const quantity=this.quantities.get(product.id)??1; const event=row?.event??'ordinary';
    return `<article class="market-card ${available?'':'unavailable'}" data-event="${event}" data-product="${product.id}"><div class="product-art"><img src="${productArt(product.id)}" alt="Stylized ${escapeHtml(product.name)} product icon">${owned?`<span class="owned-dot" aria-label="${owned} owned">${owned}</span>`:''}</div><div><div class="market-head"><div class="market-name"><h3>${escapeHtml(product.name)} ${event!=='ordinary'?`<span class="tag ${event}">${event==='cheap'?'Flood':'Shortage'}</span>`:available?'':'<span class="tag unavailable">Unavailable</span>'}</h3></div><div class="market-price">${available?formatMoney(row.price):'—'}</div></div><div class="market-meta"><span>Owned ${owned}</span><span>Max buy ${maxBuy}</span><span>Max sell ${maxSell}</span></div><div class="trade-controls"><button class="qty-button" data-action="qty-minus" data-product="${product.id}" aria-label="Decrease ${product.name} quantity">−</button><input class="qty-input" data-quantity="${product.id}" inputmode="numeric" pattern="[0-9]*" value="${quantity}" aria-label="${product.name} quantity"><button class="qty-button" data-action="qty-plus" data-product="${product.id}" aria-label="Increase ${product.name} quantity">+</button><div class="max-buttons"><button class="qty-button" data-action="qty-buy-max" data-product="${product.id}" ${maxBuy===0?'disabled':''}>Buy max</button><button class="qty-button" data-action="qty-sell-max" data-product="${product.id}" ${maxSell===0?'disabled':''}>Sell max</button></div><div class="trade-buttons"><button class="button buy" data-action="buy" data-product="${product.id}" ${!available||maxBuy===0?'disabled':''}>Buy <span aria-hidden="true">＋</span></button><button class="button sell" data-action="sell" data-product="${product.id}" ${!available||maxSell===0?'disabled':''}>Sell <span aria-hidden="true">−</span></button></div></div>${row?.announcement?`<p class="event-note">${escapeHtml(row.announcement)}</p>`:''}</div></article>`;
  }
  renderFinal(state,isBest=false) {
    this.showChrome(false); const score=state.stats.finalScore??finalScore(state); const remaining=Object.entries(state.inventory).filter(([,q])=>q>0).map(([id,q])=>`${PRODUCT_BY_ID[id].name} ×${q}`).join(', ')||'None'; const weapons=state.weapons.map(id=>WEAPON_BY_ID[id]?.name).filter(Boolean).join(', ')||'None';
    const achievements=(state.achievements??[]).map(item=>`<span class="tag cheap">${escapeHtml(item.name)}</span>`).join(' ')||'<span class="small">No achievements this run.</span>';
    this.main.innerHTML=`<section class="final-screen"><div class="score-hero"><img src="assets/branding/${state.health===0?'game-over':'victory'}.svg" alt="${state.health===0?'Defeat':'Final victory'} illustration" style="width:150px;margin:auto"><span class="eyebrow">${state.mode==='classic'?'Classic':'Mango Extended'} run complete</span><h1>${state.health===0?'Run Over':'Day 30 Closed'}</h1><div class="score-number">${formatMoney(score)}</div>${isBest?'<span class="tag cheap">New personal best</span>':''}<p>Seed: <code>${escapeHtml(state.seed)}</code></p></div><div class="score-grid"><div class="score-cell"><span>Cash</span><strong>${formatMoney(state.cash)}</strong></div><div class="score-cell"><span>Bank</span><strong>${formatMoney(state.bank)}</strong></div><div class="score-cell"><span>Debt</span><strong>${formatMoney(state.debt)}</strong></div><div class="score-cell"><span>Health</span><strong>${state.health}/100</strong></div><div class="score-cell"><span>Capacity</span><strong>${freeCapacity(state)} free / ${totalCapacity(state)}</strong></div><div class="score-cell"><span>Trips</span><strong>${state.trips}</strong></div><div class="score-cell"><span>Bought / sold</span><strong>${state.stats.unitsBought} / ${state.stats.unitsSold}</strong></div><div class="score-cell"><span>Police encounters</span><strong>${state.stats.policeEncounters}</strong></div><div class="score-cell"><span>Escapes</span><strong>${state.stats.successfulEscapes}</strong></div><div class="score-cell"><span>Combat victories</span><strong>${state.stats.combatVictories}</strong></div><div class="score-cell"><span>Best trade</span><strong>${state.stats.bestTrade?`${state.stats.bestTrade.productName} ${formatMoney(state.stats.bestTrade.estimatedProfit)}`:'None'}</strong></div><div class="score-cell"><span>Worst trade</span><strong>${state.stats.worstTrade?`${state.stats.worstTrade.productName} ${formatMoney(state.stats.worstTrade.estimatedProfit)}`:'None'}</strong></div></div><div class="panel-card"><h2>${state.mode==='classic'?'Classic':'Extended'} achievements</h2><div class="location-meta">${achievements}</div></div><div class="panel-card"><h2>What remains</h2><p><b>Inventory:</b> ${escapeHtml(remaining)}</p><p><b>Weapons:</b> ${escapeHtml(weapons)}</p>${state.mode==='classic'?'<p class="small">Classic inventory is intentionally not auto-liquidated.</p>':''}</div><div class="two-col"><button class="button primary" data-action="play-again">Play again</button><button class="button sell" data-action="share-summary">Copy/share summary</button></div></section>`;
  }
}

export { escapeHtml, icon };
