import {Game,LEVELS,TYPES,BIOMES,UPGRADES} from './engine.mjs';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d');
const SAVE_KEY='frogNom3.v1';let raw={};try{raw=JSON.parse(localStorage.getItem(SAVE_KEY)||'{}')}catch{}
const game=new Game(raw),pond=new Image();pond.src=new URL('./pond.png',import.meta.url).href;
let W=1,H=1,last=0,visualTime=0,particles=[],ripples=[],toastUntil=0,shake=0,hopTime=0,aim={x:.5,y:.4},keyboardAim=false,audioContext=null,resumeAfterDialog=false,lastHUD='',mapSelection=0;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function persist(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(game.save));$('saveWarning').hidden=true}catch{$('saveWarning').hidden=false}}
function resize(){const r=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);W=r.width;H=r.height;canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}
new ResizeObserver(resize).observe(canvas);
function sound(type){if(!game.save.sound)return;try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume();const osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.connect(gain);gain.connect(audioContext.destination);const t=audioContext.currentTime;osc.type=type==='hurt'?'sawtooth':'sine';const freq={nom:620,hit:360,hop:260,bloom:750,boom:90,hurt:130,clear:880,block:180,pop:1000}[type]||440;osc.frequency.setValueAtTime(freq,t);osc.frequency.exponentialRampToValueAtTime(type==='hurt'?70:freq*1.6,t+.13);gain.gain.setValueAtTime(.035,t);gain.gain.exponentialRampToValueAtTime(.001,t+.18);osc.start(t);osc.stop(t+.2)}catch{}}
function toast(text,time=2){$('toast').textContent=text;$('toast').classList.add('show');toastUntil=visualTime+time;}
function burst(x,y,color,count=12,text=''){for(let i=0;i<(reduced?3:count);i++)particles.push({x:x*W,y:y*H,vx:(Math.random()-.5)*180,vy:-Math.random()*140,life:.65,color});if(text)particles.push({x:x*W,y:y*H-25,vx:0,vy:-30,life:.8,color:'#fff5bb',text});}
function drain(){for(const e of game.drain()){
 if(['nom','hit','bloom','boom','hurt','hop','block','pop'].includes(e.type))sound(e.type);
 if(['nom','hit','pop'].includes(e.type))burst(e.x,e.y,e.color,e.type==='nom'?16:5,e.text);
 if(e.type==='block'){burst(e.x,e.y,'#f4d5ba',3);toast(e.text,.6)}
 if(e.type==='hurt'){shake=reduced?0:.24;toast(e.text,2)}
 if(e.type==='hop')hopTime=.75;
 if(e.type==='bloom')toast('LURE PLANTED · BLOOM EXPOSES ARMOR',1.7);
 if(e.type==='boom'){shake=reduced?0:.17;for(const f of e.flowers)ripples.push({x:f.x*W,y:f.y*H,life:.6});}
 if(e.type==='charge')toast('+1 BLOOM · FIVE SAFE NOMS',1.2);
 if(e.type==='boss'){toast('BOSS APPROACHING',2);sound('hurt')}
 if(e.type==='warning')toast(e.text,1);
 if(e.type==='save'){persist();renderMap()}
 if(e.type==='clear'){sound('clear');showResult(e);renderMap()}
 if(e.type==='dead')showDead();
 if(e.type==='pause')showPause();
 }updateHUD();}
function updateHUD(){const cfg=LEVELS[game.level],boss=game.enemies.find(e=>TYPES[e.type].boss);const key=[game.mode,game.level,game.score,game.hp,game.progress,game.blooms,game.flowers.length,Math.ceil(game.hopCooldown*10),boss?.hp,boss?.phase,game.combo].join('|');if(key===lastHUD)return;lastHUD=key;
 $('region').textContent=`${String(game.level+1).padStart(2,'0')} / ${BIOMES[cfg.biome].toUpperCase()}`;$('stageName').textContent=cfg.name;$('score').textContent=String(game.score).padStart(3,'0');$('hearts').textContent='♥'.repeat(game.hp)+'♡'.repeat(Math.max(0,game.maxHp-game.hp));$('hearts').setAttribute('aria-label',`${game.hp} of ${game.maxHp} hearts`);$('progress').style.width=`${game.progress/cfg.goal*100}%`;$('goalText').textContent=`${game.progress} / ${cfg.goal} snacks`;$('ammo').textContent=game.blooms;
 const active=game.mode==='playing';$('bloomBtn').disabled=!active||game.blooms<=0;$('boomBtn').disabled=!active||game.flowers.length===0;$('hopBtn').disabled=!active||game.hopCooldown>0;$('hopLabel').innerHTML=game.hopCooldown>0?`${game.hopCooldown.toFixed(1)}s<small>Recharging</small>`:'HOP<small>Dodge · Space</small>';$('pauseBtn').disabled=!['playing','paused'].includes(game.mode);$('pauseBtn').textContent=game.mode==='paused'?'▶':'Ⅱ';$('pauseBtn').setAttribute('aria-label',game.mode==='paused'?'Resume game':'Pause game');
 $('combo').textContent=game.combo>=3?`${game.combo} NOM STREAK!`:'';$('bossHud').hidden=!boss;if(boss){$('bossName').textContent=TYPES[boss.type].name;$('bossHealth').style.width=`${boss.hp/boss.maxHp*100}%`;$('bossPhase').textContent=boss.phase==='open'?'OPEN · NOM NOW':boss.phase==='warning'?'INCOMING · WAIT…':boss.phase==='attack'?'HOP!':`GUARDED · ${boss.hp} / ${boss.maxHp}`;}
 $('nextTease').innerHTML=game.level===14?'THE MOON CROWN AWAITS':`UP NEXT <b>${LEVELS[game.level+1].name}</b>`;$('pondLabel').textContent=active?(game.level===0?'TAP THE BUGS · FIVE NOMS = ONE BLOOM':'BLOOM TO LURE · BOOM TO CLEAR · HOP TO DODGE'):'TAP A BUG. MAKE ITS DAY WORSE.';
}
function overlay(html){$('overlayContent').innerHTML=html;$('overlay').hidden=false;requestAnimationFrame(()=>$('overlayContent').querySelector('button')?.focus({preventScroll:true}));}
function title(){overlay(`<span class="eyebrow">A LITTLE FROG. A BIG APPETITE.</span><div class="big-title">FROG<br>NOM <b>3</b></div><p>New pond. New predators.<br>Eat your way to the Moon Crown.</p><button class="primary" data-action="continue">${game.save.unlocked||game.save.stars[0]?'Continue adventure →':'Hop in →'}</button><button class="secondary" data-action="map">Explore the map</button><div class="tiny">15 PONDS &nbsp;·&nbsp; 3 BOSSES &nbsp;·&nbsp; ONE HUNGRY FROG</div>`);}
function start(index){if(!game.start(index))return;$('overlay').hidden=true;$('mapPanel').classList.remove('open');particles=[];ripples=[];hopTime=0;shake=0;mapSelection=index;last=performance.now();canvas.focus({preventScroll:true});renderMap();drain();const n=LEVELS[index].pool.find(x=>TYPES[x].new);toast(index===0?'TAP THE FLIES · YOUR TONGUE DOES THE REST':n?TYPES[n].tip:LEVELS[index].tease,3);}
function showPause(){overlay(`<span class="eyebrow">TAKE A BREATHER</span><h2>Pond on pause.</h2><p>Your snacks can wait.</p><button class="primary" data-action="resume">Back to the pond →</button><button class="secondary" data-action="map">View progression map</button><button class="secondary" data-action="retry-confirm">Restart this pond</button>`);}
function showDead(){overlay(`<span class="eyebrow">A MINOR FROG SETBACK</span><h2>You croaked.</h2><p>${game.progress} / ${LEVELS[game.level].goal} snacks collected.<br>${LEVELS[game.level].boss&&game.bossSpawned?'HOP as the warning ends. Hit the boss while OPEN.':'Use Bloom to lure hazards, then BOOM. Hop dodges incoming attacks.'}</p><button class="primary" data-action="retry">One more hop →</button><button class="secondary" data-action="upgrades">Spend perk points (${game.tokens})</button><button class="secondary" data-action="map">Back to the map</button>`);}
function showResult(e){overlay(`<span class="eyebrow">${game.mode==='victory'?'ALL HAIL THE HUNGRY ONE':'POND '+(game.level+1)+' COMPLETE'}</span><div class="star-award">${'★'.repeat(e.stars)}${'☆'.repeat(3-e.stars)}</div><h2>${game.mode==='victory'?'The crown is yours.':'Nicely nommed.'}</h2><p>${game.mode==='victory'?'Fifteen ponds. Three fallen bosses. One extremely full frog.':LEVELS[game.level].tease}${e.first?'<br>+1 perk point earned.':''}</p><button class="primary" data-action="${game.mode==='victory'?'map':'next'}">${game.mode==='victory'?'Explore your kingdom →':'Enter '+LEVELS[game.level+1].name+' →'}</button><button class="secondary" data-action="upgrades">Pond perks · ${game.tokens} available</button>${game.mode==='victory'?'':'<button class="secondary" data-action="map">View the map</button>'}`);}
function renderMap(){let html='';for(let i=0;i<15;i++){if(i%5===0)html+=`<div class="biome-label"><span>0${i/5+1} / ${BIOMES[i/5].toUpperCase()}</span><span>${i===0?'☀':i===5?'✿':'☾'}</span></div>`;const lv=LEVELS[i],done=game.save.stars[i]>0,locked=i>game.save.unlocked,current=i===mapSelection;html+=`<div class="node-row${done?' done':''}${locked?' locked':''}${current?' current':''}${lv.boss?' boss':''}"><button class="node" data-level="${i}" ${locked?'disabled':''} ${current?'aria-current="step"':''} aria-label="${locked?'Locked: ':''}Pond ${i+1}, ${lv.name}">${done?'✓':lv.boss?'♛':String(i+1).padStart(2,'0')}</button><div class="node-copy"><div class="node-name">${lv.name}</div><div class="node-detail">${done?'★'.repeat(game.save.stars[i])+'☆'.repeat(3-game.save.stars[i]):lv.boss?'BOSS FIGHT':locked?'UNDISCOVERED':current?'YOU ARE HERE':'READY TO EXPLORE'}</div></div></div>`;}
 $('mapNodes').innerHTML=html;$('mapProgress').textContent=`${game.save.stars.filter(Boolean).length} / 15 ponds cleared`;$('starTotal').textContent=`★ ${game.save.stars.reduce((a,b)=>a+b,0)}`;$('tokenCount').textContent=game.tokens;
}
function openMap(){if(game.mode==='playing')game.pause();drain();$('mapPanel').classList.add('open');if(innerWidth>=900){$('mapPanel').scrollIntoView({block:'nearest',behavior:'smooth'});$('mapNodes').querySelector(`[data-level="${mapSelection}"]`)?.focus({preventScroll:true});}else $('closeMap').focus();}
function selectLevel(i){mapSelection=i;renderMap();if(game.mode==='playing')game.pause();drain();$('mapPanel').classList.remove('open');const lv=LEVELS[i],n=lv.pool.find(x=>TYPES[x].new);overlay(`<span class="eyebrow">POND ${i+1} · ${BIOMES[lv.biome].toUpperCase()}</span><h2>${lv.name}</h2><p>Collect ${lv.goal} snacks${lv.boss?', then defeat '+TYPES[lv.boss].name:'.'}<br>${n?TYPES[n].tip:lv.boss?TYPES[lv.boss].tip:'Nom flies. Avoid stingers. Bloom + BOOM clears hazards.'}</p><button class="primary" data-action="selected">${game.mode==='paused'?'Start pond from the beginning':'Enter the pond'} →</button><button class="secondary" data-action="${game.mode==='paused'?'resume':'map'}">${game.mode==='paused'?'Resume current pond':'Back to map'}</button>`);}
function openDialog(id){resumeAfterDialog=game.mode==='playing';if(resumeAfterDialog)game.pause();drain();if(id==='upgradesDialog')renderUpgrades();$(id).showModal();}
function renderUpgrades(){$('upgradeBalance').textContent=`${game.tokens} perk point${game.tokens===1?'':'s'} available`;$('upgradeGrid').innerHTML=Object.entries(UPGRADES).map(([key,u])=>`<div class="upgrade-card"><div><h3>${u.name} <span class="new-tag">${game.save.upgrades[key]} / 3</span></h3><p>${u.description}</p></div><button data-upgrade="${key}" ${game.tokens<=0||game.save.upgrades[key]>=3?'disabled':''}>${game.save.upgrades[key]>=3?'Maxed':'Get · 1'}</button></div>`).join('');}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const act=b.dataset.action;if(act==='continue')start(game.save.unlocked);if(act==='selected')start(mapSelection);if(act==='next')start(game.level+1);if(act==='retry')start(game.level);if(act==='resume'){game.resume();$('overlay').hidden=true;mapSelection=game.level;renderMap();canvas.focus();}if(act==='map')openMap();if(act==='upgrades')openDialog('upgradesDialog');if(act==='retry-confirm')overlay('<h2>Fresh start?</h2><p>This pond restarts with full hearts. Your unlocked ponds and perks are kept.</p><button class="primary" data-action="retry">Restart pond</button><button class="secondary" data-action="resume">Keep playing</button>');if(b.dataset.level!==undefined)selectLevel(Number(b.dataset.level));if(b.dataset.close)$(b.dataset.close).close();if(b.dataset.upgrade){game.upgrade(b.dataset.upgrade);drain();renderUpgrades();}updateHUD();});
for(const id of ['guideDialog','upgradesDialog'])$(id).addEventListener('close',()=>{if(resumeAfterDialog&&game.mode==='paused'){game.resume();$('overlay').hidden=true;canvas.focus({preventScroll:true});}resumeAfterDialog=false;updateHUD();});
$('guideBtn').onclick=()=>openDialog('guideDialog');$('upgradesBtn').onclick=()=>openDialog('upgradesDialog');$('mobileMap').onclick=openMap;$('closeMap').onclick=()=>{$('mapPanel').classList.remove('open');if(game.mode==='paused')showPause();};$('pauseBtn').onclick=()=>{if(game.mode==='paused'){game.resume();$('overlay').hidden=true;canvas.focus();}else game.pause();drain();};$('bloomBtn').onclick=()=>{game.bloom();drain();canvas.focus({preventScroll:true})};$('boomBtn').onclick=()=>{game.boom();drain();canvas.focus({preventScroll:true})};$('hopBtn').onclick=()=>{game.hop();drain();canvas.focus({preventScroll:true})};
function updateSound(){$('soundBtn').textContent=game.save.sound?'♪':'♪̸';$('soundBtn').setAttribute('aria-pressed',String(!game.save.sound));$('soundBtn').setAttribute('aria-label',game.save.sound?'Mute sound':'Enable sound');}$('soundBtn').onclick=()=>{game.save.sound=!game.save.sound;updateSound();persist();if(game.save.sound)sound('nom')};
canvas.addEventListener('pointerdown',e=>{e.preventDefault();canvas.focus({preventScroll:true});const r=canvas.getBoundingClientRect();keyboardAim=false;game.shoot((e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height,r.height/r.width);drain();},{passive:false});
document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]'))return;if(e.code==='Escape'){if($('mapPanel').classList.contains('open')){$('mapPanel').classList.remove('open');return;}if(game.mode==='playing')game.pause();else if(game.mode==='paused'){game.resume();$('overlay').hidden=true;}drain();return;}if(e.repeat&& !e.key.startsWith('Arrow'))return;
 if(e.code==='KeyP'){if(game.mode==='playing')game.pause();else if(game.mode==='paused'){game.resume();$('overlay').hidden=true;}drain();return;}if(game.mode!=='playing')return;
 if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();keyboardAim=true;aim.x=Math.max(.04,Math.min(.96,aim.x+(e.key==='ArrowRight'?.04:e.key==='ArrowLeft'?-.04:0)));aim.y=Math.max(.08,Math.min(.78,aim.y+(e.key==='ArrowDown'?.04:e.key==='ArrowUp'?-.04:0)));canvas.focus();}
 if(e.code==='Enter'&&document.activeElement===canvas){e.preventDefault();game.shoot(aim.x,aim.y,H/W)}if(e.code==='Space'&&!['BUTTON','A'].includes(document.activeElement.tagName)){e.preventDefault();game.hop()}if(e.code==='KeyB')game.bloom();if(e.code==='KeyX')game.boom();drain();});
document.addEventListener('visibilitychange',()=>{if(document.hidden){game.pause();drain();}last=performance.now();});window.addEventListener('pagehide',persist);

// Canvas-native animated characters retain the original game's lightweight renderer.
function ellipse(c,x,y,rx,ry,fill,stroke='#103d3c',line=3,rotation=0){c.beginPath();c.ellipse(x,y,rx,ry,rotation,0,Math.PI*2);c.fillStyle=fill;c.fill();if(stroke){c.strokeStyle=stroke;c.lineWidth=line;c.stroke();}}
function line(c,points,color,width=3){c.beginPath();c.moveTo(...points[0]);for(let i=1;i<points.length;i++)c.lineTo(...points[i]);c.strokeStyle=color;c.lineWidth=width;c.lineCap='round';c.lineJoin='round';c.stroke();}
function eyes(c,x,y,separation=10,r=7,pupil=3){for(const s of [-1,1]){ellipse(c,x+s*separation,y,r,r+1,'#fffadc','#133e38',2);ellipse(c,x+s*separation+1,y+1,pupil,pupil+1,'#163c38',null);}}
function bug(c,type,x,y,size,time=0,open=true,flash=0){const t=TYPES[type];c.save();c.translate(x,y);c.scale(size/30,size/30);c.lineJoin='round';const col=flash?'#fffad6':t.color;
 if(type==='spider'){for(const s of [-1,1])for(let i=0;i<4;i++)line(c,[[s*10,0],[s*(23+i*2),-18+i*10],[s*(33+i*2),-9+i*7]],'#704d99',3);ellipse(c,0,4,18,20,col);eyes(c,0,0,7,6);}
 else if(type==='snail'){ellipse(c,1,10,29,11,'#93c6ae');ellipse(c,-8,-3,23,23,col);c.beginPath();for(let a=0;a<Math.PI*4;a+=.1){const r=a*1.35;c.lineTo(-8+Math.cos(a)*r,-3+Math.sin(a)*r)}c.strokeStyle='#5f599a';c.lineWidth=3;c.stroke();if(open){line(c,[[17,6],[21,-15]],'#88c9b1',6);line(c,[[24,7],[32,-12]],'#88c9b1',6);eyes(c,26,-15,6,5,2);}else{line(c,[[-22,-6],[7,-13]],'#ded6ff',4);}}
 else if(type==='spore'){ellipse(c,0,10,11,20,'#fff1c2');c.beginPath();c.moveTo(-32,0);c.bezierCurveTo(-30,-40,30,-40,32,0);c.quadraticCurveTo(0,10,-32,0);c.fillStyle=col;c.fill();c.strokeStyle='#61394d';c.lineWidth=3;c.stroke();ellipse(c,-12,-15,6,5,'#fff1d9',null);ellipse(c,15,-12,5,7,'#fff1d9',null);eyes(c,0,11,5,4,2);}
 else if(type==='mantis'){ellipse(c,0,6,12,24,col);for(const s of [-1,1])line(c,[[s*9,3],[s*26,open?-3:18],[open?s*26:-s*15,open?-25:-6]],'#366849',5);c.beginPath();c.moveTo(-21,-18);c.lineTo(21,-18);c.lineTo(0,4);c.closePath();c.fillStyle=col;c.fill();c.strokeStyle='#224e36';c.lineWidth=3;c.stroke();eyes(c,0,-17,14,7);line(c,[[-9,-23],[-12,-34]],'#224e36',2);line(c,[[9,-23],[14,-33]],'#224e36',2);}
 else if(type==='beetle'||type==='goliath'){for(const s of [-1,1])for(let i=0;i<3;i++)line(c,[[s*12,-5+i*9],[s*28,0+i*9],[s*31,-5+i*10]],'#295443',3);ellipse(c,0,3,23,28,col);line(c,[[0,-22],[0,29]],'#365552',3);ellipse(c,0,-17,17,13,'#6a9b76');eyes(c,0,-19,8,5,2);if(type==='goliath'){line(c,[[0,-26],[0,-44],[-8,-37]],'#dfc8fa',6);if(open){c.fillStyle='#ffe5b8';c.fillRect(-5,-7,10,27);}}}
 else if(type==='moon'){for(const s of [-1,1]){ellipse(c,s*20,-6,24,33,col,'#573c72',2,s*(.2+Math.sin(time*7)*.08));ellipse(c,s*24,-12,11,16,'#977bc2','#e6c4f5',2,s*.4);ellipse(c,s*25,-13,4,6,'#e8f495',null);ellipse(c,s*18,21,17,17,'#b6cee9','#573c72',2);}ellipse(c,0,0,8,25,'#f8ebbd');eyes(c,0,-17,5,5,2);line(c,[[-4,-23],[-13,-34]],'#ffe4c5',2);line(c,[[4,-23],[13,-34]],'#ffe4c5',2);}
 else {const wing=type==='dragonfly'?30:20;const wig=Math.sin(time*28)*3;ellipse(c,-16,-12,wing,11+wig,'#e0fcf0b8','#54898a',2,-.5);ellipse(c,16,-12,wing,11-wig,'#e0fcf0b8','#54898a',2,.5);if(type==='dragonfly'){ellipse(c,-13,9,25,7,'#d2faf0b8','#54898a',2,-.4);ellipse(c,13,9,25,7,'#d2faf0b8','#54898a',2,.4);ellipse(c,0,9,6,27,col);}
  else{ellipse(c,0,5,17,21,col);if(['bee','hornet','wasp'].includes(type)){for(const yy of [-2,8,17])line(c,[[-12,yy],[12,yy]],'#4d4932',5);c.beginPath();c.moveTo(-5,24);c.lineTo(0,34);c.lineTo(5,24);c.fillStyle='#543329';c.fill();}}
  eyes(c,0,-8,8,7,3);if(type==='mimic'&&!open){for(let i=0;i<6;i++){const a=i*Math.PI/3;c.beginPath();c.moveTo(Math.cos(a)*20,Math.sin(a)*22);c.lineTo(Math.cos(a+.15)*32,Math.sin(a+.15)*32);c.lineTo(Math.cos(a+.35)*20,Math.sin(a+.35)*22);c.fillStyle='#527991';c.fill();}}
  if(type==='toxic'){ellipse(c,0,9,7,8,'#567735',null);eyes(c,0,-8,8,7,2);}
  if(type==='king'){c.beginPath();c.moveTo(-20,-24);c.lineTo(-23,-44);c.lineTo(-9,-35);c.lineTo(0,-48);c.lineTo(9,-35);c.lineTo(23,-44);c.lineTo(20,-24);c.closePath();c.fillStyle='#ffe58a';c.fill();c.strokeStyle='#675128';c.lineWidth=3;c.stroke();}
 }
 c.restore();}
function frog(c,x,y,size,time){c.save();c.translate(x,y);const jump=hopTime>0&&!reduced?Math.sin(hopTime/.75*Math.PI)*24:0;c.translate(0,-jump);c.scale(size/60,size/60);
 ellipse(c,-31,23,22,12,'#83b84d','#1c5945',3,-.2);ellipse(c,31,23,22,12,'#83b84d','#1c5945',3,.2);ellipse(c,0,11,36,29,'#95ca53','#185846',3);ellipse(c,0,20,24,17,'#dbeb8a',null);
 ellipse(c,0,-8,43,29,'#abe060','#174f3c',3);ellipse(c,-24,-30,17,18,'#b8ea77','#174f3c',3);ellipse(c,24,-30,17,18,'#b8ea77','#174f3c',3);const blink=Math.sin(time*.73)> .998;for(const s of [-1,1]){ellipse(c,s*24,-30,11,blink?2:12,'#fff6d7',null);if(!blink){ellipse(c,s*24+2,-29,5,7,'#163e34',null);ellipse(c,s*24+4,-32,2,2,'#fff',null);}}
 ellipse(c,-31,-5,8,4,'#eea488',null);ellipse(c,31,-5,8,4,'#eea488',null);if(game.shots.length){ellipse(c,0,3,13,10,'#733b45','#174f3c',2);}else{c.beginPath();c.moveTo(-21,-1);c.quadraticCurveTo(0,20,21,-1);c.strokeStyle='#215340';c.lineWidth=3;c.stroke();}
 if(game.save.won){c.beginPath();c.moveTo(-13,-48);c.lineTo(-17,-62);c.lineTo(-6,-57);c.lineTo(0,-69);c.lineTo(7,-57);c.lineTo(17,-62);c.lineTo(13,-48);c.fillStyle='#ffe18a';c.fill();c.strokeStyle='#755e32';c.stroke();}c.restore();}
function draw(dt){ctx.save();if(shake>0){ctx.translate(Math.sin(visualTime*90)*4,Math.cos(visualTime*72)*3);shake-=dt;}ctx.clearRect(-5,-5,W+10,H+10);
 if(pond.complete&&pond.naturalWidth){const scale=Math.max(W/pond.width,H/pond.height);ctx.drawImage(pond,(W-pond.width*scale)/2,(H-pond.height*scale)/2,pond.width*scale,pond.height*scale);}else{ctx.fillStyle='#4caf9f';ctx.fillRect(0,0,W,H)}
 const biome=LEVELS[game.level].biome;if(biome){ctx.fillStyle=biome===1?'#596fae24':'#0b164c77';ctx.fillRect(0,0,W,H);}ctx.fillStyle='#07494612';ctx.fillRect(0,0,W,H);
 for(let i=0;i<14;i++){const x=(i*87.7+29)%W,y=(i*53+27)%H;ctx.globalAlpha=.25+.2*Math.sin(visualTime*2+i);ellipse(ctx,x,y,1.4,1.4,'#f4ffb3',null)}ctx.globalAlpha=1;
 for(const f of game.flowers){const x=f.x*W,y=f.y*H;ctx.globalAlpha=Math.min(1,f.life);ctx.strokeStyle='#ffc6e67a';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,40+Math.sin(visualTime*3)*8,0,Math.PI*2);ctx.stroke();for(let i=0;i<6;i++){const a=i*Math.PI/3;ellipse(ctx,x+Math.cos(a)*11,y+Math.sin(a)*11,10,8,'#ffafd7','#9b598d',2,a)}ellipse(ctx,x,y,8,8,'#ffe4a0','#9b598d',2);ctx.globalAlpha=1;}
 const scale=Math.max(.7,Math.min(1,W/620));
 for(const e of game.enemies){const t=TYPES[e.type],x=e.x*W,y=e.y*H,s=t.r*scale;
  if(e.type==='spider'){line(ctx,[[x,0],[x,y]],'#d2e9d877',1)}
  if(e.phase==='warning'&&(t.boss||e.type==='wasp')){ctx.setLineDash([8,7]);line(ctx,[[x,y+30],[W/2,H*.89]],'#ff8cbd',3);ctx.setLineDash([]);const radius=26+Math.sin(visualTime*16)*3;ctx.beginPath();ctx.arc(W/2,H*.89,radius,0,Math.PI*2);ctx.strokeStyle='#ffb4c8';ctx.lineWidth=3;ctx.stroke();}
  if(e.type==='firefly'){ctx.globalAlpha=e.open?1:.25;if(e.open){ctx.shadowColor='#eaff87';ctx.shadowBlur=18;}}
  ellipse(ctx,x,y+s*.95,s*.75,s*.19,'#053b3929',null);bug(ctx,e.type,x,y,s,reduced?0:visualTime,e.open,e.flash);ctx.shadowBlur=0;ctx.globalAlpha=1;
  if(t.hazard){ctx.fillStyle='#7f3544';ctx.beginPath();ctx.arc(x+s*.9,y-s*.65,8,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff4de';ctx.font='900 11px system-ui';ctx.textAlign='center';ctx.fillText('!',x+s*.9,y-s*.65+4);}
  if(t.new||t.boss){const text=e.type==='wasp'?(e.phase==='warning'?'HOP!':'NOM'):e.type==='spore'?'NOM':e.open?'OPEN':'GUARD';ctx.font=`900 ${t.boss?11:9}px system-ui`;ctx.textAlign='center';const width=ctx.measureText(text).width+12;ctx.fillStyle=e.open?'#173f36e8':'#3d4353e8';ctx.beginPath();ctx.roundRect(x-width/2,y+s+9,width,16,5);ctx.fill();ctx.fillStyle=e.open?'#ddff96':'#eee0ed';ctx.fillText(text,x,y+s+20);}
  if(e.maxHp>1&&!t.boss){for(let i=0;i<e.maxHp;i++)ellipse(ctx,x+(i-(e.maxHp-1)/2)*8,y-s-8,2.6,2.6,i<e.hp?'#ffffc2':'#365f60',null);}
 }
 for(const p of game.projectiles){const x=p.x*W,y=p.y*H;ellipse(ctx,x,y,11,11,'#ffd0ec','#9e5285',2);ellipse(ctx,x-3,y-3,3,3,'#fff6d4',null);ctx.strokeStyle='#ffe3dc55';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,17+Math.sin(visualTime*8)*2,0,Math.PI*2);ctx.stroke();}
 const fx=W/2,fy=H*.87;ellipse(ctx,fx,fy+27*scale,58*scale,19*scale,'#326e48','#b6d789',2);line(ctx,[[fx,fy+27*scale],[fx+44*scale,fy+37*scale]],'#1e5c42',2);
 for(const s of game.shots){const p=1-s.life/.17,ext=Math.sin(Math.min(1,p)*Math.PI);line(ctx,[[fx,fy-5], [fx+(s.x*W-fx)*ext,fy-5+(s.y*H-fy+5)*ext]],'#713e50',9*scale);line(ctx,[[fx,fy-5], [fx+(s.x*W-fx)*ext,fy-5+(s.y*H-fy+5)*ext]],'#ff8eac',5*scale);}
 if(game.invulnerable>0&&game.mode==='playing'){ctx.strokeStyle='#e5ffd590';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(fx,fy,49*scale,42*scale,0,0,Math.PI*2);ctx.stroke();}
 frog(ctx,fx,fy,57*scale,reduced?0:visualTime);hopTime=Math.max(0,hopTime-dt);
 for(const p of particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;if(!p.text)p.vy+=200*dt;ctx.globalAlpha=Math.min(1,p.life*2);ctx.fillStyle=p.color;if(p.text){ctx.font='900 20px Trebuchet MS';ctx.textAlign='center';ctx.strokeStyle='#16493b';ctx.lineWidth=3;ctx.strokeText(p.text,p.x,p.y);ctx.fillText(p.text,p.x,p.y);}else{ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.life*6);ctx.fillRect(-2,-2,5,5);ctx.restore();}}
 particles=particles.filter(p=>p.life>0).slice(-180);ctx.globalAlpha=1;
 for(const r of ripples){r.life-=dt;ctx.globalAlpha=Math.max(0,r.life);ctx.beginPath();ctx.arc(r.x,r.y,(1-r.life/.6)*W*.45,0,Math.PI*2);ctx.strokeStyle='#fff0be';ctx.lineWidth=10;ctx.stroke();}ripples=ripples.filter(r=>r.life>0);ctx.globalAlpha=1;
 if(keyboardAim&&game.mode==='playing'){const x=aim.x*W,y=aim.y*H;ctx.strokeStyle='#f7ffc5';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,16,0,Math.PI*2);ctx.stroke();line(ctx,[[x-23,y],[x+23,y]],'#fffad7',1);line(ctx,[[x,y-23],[x,y+23]],'#fffad7',1)}ctx.restore();
}
function frame(now){const dt=Math.min(.05,Math.max(0,(now-last)/1000||0));last=now;visualTime+=dt;game.step(dt);drain();draw(dt);if(visualTime>toastUntil)$('toast').classList.remove('show');requestAnimationFrame(frame);}
function guide(){$('guideGrid').innerHTML=Object.entries(TYPES).map(([key,t])=>`<article class="guide-card"><canvas data-bug="${key}" width="160" height="130" aria-label="${t.name} illustration"></canvas>${t.new?'<span class="new-tag">NEW SPECIES</span>':t.boss?'<span class="new-tag">BOSS</span>':''}<h3>${t.name}</h3><p>${t.tip}</p></article>`).join('');for(const c of $('guideGrid').querySelectorAll('canvas')){const cc=c.getContext('2d');cc.scale(2,2);bug(cc,c.dataset.bug,40,33,21,0,true,0);}}
updateSound();guide();renderMap();updateHUD();title();requestAnimationFrame(frame);
