import assert from 'node:assert/strict';
import {bootGame} from './helpers/game.mjs';
const {app,context,frame,get,setPads,window}=await bootGame(),t=app.test,life=t.streetLife,C=context.C;
t.loadLevel(24);app.start();const rideable=t.secretView.rideables[0];assert(rideable&&rideable.asset.config.bike);assert.equal(t.world.bodies.filter(b=>b.userData?.kind==='racer bike').length,1);assert.equal(t.traffic.active.length,20);
// The detailed parked model is reused: it gains a rider only when mounted.
assert(!rideable.mesh.getObjectByName('rider').visible);const geometry=new Set();rideable.mesh.traverse(n=>{if(n.geometry)geometry.add(n.geometry);});const truck=t.car,truckP=t.chassis.position.clone();t.teleport(0,190);assert(life.exitVehicle());const beforeBodies=t.world.bodies.length;life.body.position.set(rideable.body.position.x+2,1.05,rideable.body.position.z);assert(life.interact());frame();assert.equal(t.car.config.id,'racer-bike');assert.equal(t.vehicle.wheelInfos.length,2);assert(t.car.root.getObjectByName('rider').visible);assert(!t.world.bodies.includes(rideable.body));assert(rideable.occupied);t.car.root.traverse(n=>{if(n.geometry)assert(geometry.has(n.geometry));});
// Real physics acceleration / steering, front steering only and rear drive only.
t.teleport(0,170);t.input.KeyW=true;for(let i=0;i<120;i++)t.step(1/60);assert(t.chassis.velocity.length()>8);assert(t.chassis.position.z<163);assert.equal(t.vehicle.wheelInfos[0].engineForce,0);assert.equal(t.vehicle.wheelInfos[1].engineForce,1800);t.input.KeyD=true;for(let i=0;i<90;i++)t.step(1/60);assert(Math.abs(t.chassis.position.x-6000)>1);assert.equal(t.vehicle.wheelInfos[1].steering,0);assert(t.chassis.quaternion.vmult(new C.Vec3(0,1,0)).y>.85);delete t.input.KeyW;delete t.input.KeyD;
t.togglePerspective();frame();assert(app.getState().firstPerson);assert(!t.car.root.getObjectByName('rider').visible);assert(app.camera.position.distanceTo(t.car.root.position)<2);t.togglePerspective();frame();assert(t.car.root.getObjectByName('rider').visible);
// The two-wheel bike also launches from a real deck without stopping or wrecking.
t.teleport(0,135,0,24);t.input.KeyW=true;let bikeLaunch=false,bikeMin=24,bikeHeight=0;for(let i=0;i<200;i++){t.step(1/60);bikeHeight=Math.max(bikeHeight,t.chassis.position.y);if(t.chassis.position.z<114&&t.chassis.position.z>92)bikeMin=Math.min(bikeMin,-t.chassis.velocity.z);if(t.chassis.position.z<90){bikeLaunch=true;break;}}delete t.input.KeyW;assert(bikeLaunch);assert(bikeMin>12);assert(bikeHeight>2.5);
// Simulated Xbox analog throttle remains proportional on the bike.
t.teleport(0,170);let pad={index:0,id:'Xbox Wireless Controller',mapping:'standard',connected:true,axes:[0,0,0,0],buttons:Array.from({length:17},()=>({value:0,pressed:false}))};setPads([pad]);frame();pad.buttons[7]={value:.5,pressed:true};for(let i=0;i<5;i++)frame();assert(Math.abs(t.vehicle.wheelInfos[1].engineForce-900)<1);pad.buttons[7]={value:1,pressed:true};frame();assert.equal(t.vehicle.wheelInfos[1].engineForce,1800);setPads([]);frame();if(app.getState().state==='paused')get('resume').click();
t.chassis.velocity.setZero();t.chassis.angularVelocity.setZero();assert(life.exitVehicle());assert.equal(t.car.config.id,'monster-gold');assert.equal(t.vehicle.wheelInfos.length,4);assert.equal(t.world.bodies.length,beforeBodies);assert(!rideable.occupied);assert(!rideable.mesh.getObjectByName('rider').visible);assert(t.world.bodies.includes(rideable.body));assert(truck.root.parent);
for(let i=0;i<20;i++){life.body.position.set(rideable.body.position.x+2,1.05,rideable.body.position.z);assert(life.enterVehicle(rideable));assert.equal(t.vehicle.wheelInfos.length,2);assert(life.exitVehicle());assert.equal(t.world.bodies.length,beforeBodies);assert.equal(t.vehicle.wheelInfos.length,4);}life.body.position.set(rideable.body.position.x+2,1.05,rideable.body.position.z);assert(life.enterVehicle(rideable));app.start();assert.equal(t.car.config.id,'monster-gold');assert(t.car.root.parent);assert(!rideable.occupied);assert.equal(t.vehicle.wheelInfos.length,4);assert.equal(t.world.bodies.filter(b=>b.userData?.kind==='racer bike').length,1);
// Isolate the actual launch decks and terrain to measure ramp physics, not incidental city collisions.
const ramps=t.world.bodies.filter(b=>b.userData?.kind==='ramp'),ground=t.world.bodies.find(b=>b.shapes[0]?.type===C.Shape.types.HEIGHTFIELD),report=[];assert.equal(ramps.length,4);
for(const ramp of ramps)for(const velocity of [20,32,50,80]){t.recover(true);t.setState('running');for(const b of [...t.world.bodies])if(!ramps.includes(b)&&b!==ground&&b!==t.chassis)t.world.removeBody(b);const forward=ramp.quaternion.vmult(new C.Vec3(0,0,-1)),start=ramp.position.vadd(ramp.quaternion.vmult(new C.Vec3(0,0,30))),yaw=Math.atan2(-forward.x,-forward.z);t.teleport(start.x-6000,start.z,yaw);for(let i=0;i<90;i++)t.step(1/60);t.teleport(start.x-6000,start.z,yaw,velocity);t.input.KeyW=true;let minSpeed=velocity,maxY=0,cleared=false,launchVy=0;for(let i=0;i<200;i++){t.step(1/60);const local=ramp.pointToLocalFrame(t.chassis.position);maxY=Math.max(maxY,t.chassis.position.y);if(local.z<9&&local.z>-14)minSpeed=Math.min(minSpeed,t.chassis.velocity.dot(forward));if(local.z<-14){launchVy=t.chassis.velocity.y;cleared=true;break;}}delete t.input.KeyW;assert(cleared,'Ramp blocked at '+velocity);assert(minSpeed>velocity*.65,'Excess speed loss '+minSpeed+' at '+velocity);assert(maxY>3.2);report.push({speed:velocity,retained:+minSpeed.toFixed(1),launchY:+maxY.toFixed(1),verticalVelocity:+launchVy.toFixed(1)});}
console.log(JSON.stringify({bike:'Two-wheel acceleration, steering, first-person rider visibility, analog Xbox input, 20 stable handoffs and restarting while mounted pass.',ramps:report},null,2));
