import assert from 'node:assert/strict';
import {bootGame} from './helpers/game.mjs';
const {app,window,document,get,frame}=await bootGame(),t=app.test,life=t.streetLife;
globalThis.Element=window.Element;
t.loadLevel(24);app.start();t.setState('running');t.teleport(0,190);assert(life.exitVehicle());life.refreshDoors();const mart=t.secretView.buildings.find(b=>b.type==='convenience');life.body.position.set(mart.door.x+mart.door.nx*.6,1.05,mart.door.z+mart.door.nz*.6);assert(life.enterBuilding(mart));assert(life.openShop());assert(document.body.classList.contains('menu-open'));
function touch(target,type,x=12,y=12){const e=new window.Event(type,{bubbles:true,cancelable:true});Object.assign(e,{touches:type==='touchend'?[]:[{clientX:x,clientY:y}],changedTouches:[{clientX:x,clientY:y}]});target.dispatchEvent(e);return e;}
for(const id of ['shopContent','scratchGame-numbers','shopClose']){touch(get(id),'touchstart');assert(!touch(get(id),'touchmove',12,70).defaultPrevented,id+' must permit scrolling');touch(get(id),'touchend');}
let clicks=0;get('scratchGame-numbers').addEventListener('click',()=>clicks++);for(let i=0;i<3;i++){touch(get('scratchGame-numbers'),'touchstart');assert(!touch(get('scratchGame-numbers'),'touchend').defaultPrevented);}assert.equal(clicks,0,'touch guard must not synthesize duplicate menu clicks');
get('scratchGame-numbers').click();get('buyScratch').click();assert(life.economy.info().ticket);assert(get('shopStock').querySelector('.scratch-rack').hidden);assert(get('buyScratch').hidden);assert(!get('revealScratch').hidden);assert.equal(get('revealScratch').closest('.modal-footer').parentNode,get('shopPanel').firstElementChild);assert(touch(get('scratchCanvas'),'touchmove').defaultPrevented,'ticket rub owns its touch gesture');
const ticket=life.economy.info().ticket;get('shopClose').click();assert(!life.shopOpen);assert(!document.body.classList.contains('menu-open'));assert.deepEqual(life.economy.info().ticket,ticket);life.openShop();get('revealScratch').click();assert.equal(life.economy.info().ticket,null);get('shopClose').click();life.leaveBuilding();
const room=t.secretView.buildings.find(b=>b.type==='casino');life.body.position.set(room.door.x+room.door.nx*.6,1.05,room.door.z+room.door.nz*.6);assert(life.enterBuilding(room));life.body.position.set(-5997.9,.83,1.6);get('interactButton').click();assert(life.shopOpen);assert(life.getInfo().seated);assert.equal(life.getInfo().seatGame,'roulette');assert(document.body.classList.contains('menu-open'));assert(!touch(get('casinoContent'),'touchmove').defaultPrevented);assert.equal(get('casinoPlay').closest('.modal-footer').parentNode,get('casinoPanel').firstElementChild);
const before=life.economy.info().cash;get('roulette-red').click();get('casinoPlay').click();assert.equal(life.economy.info().cash,before-10+life.casinoUI.games.info().result.payout);life.casinoUI.finishReveal();
for(const code of ['Space','KeyR']){const key=new window.Event('keydown',{bubbles:true,cancelable:true});key.code=code;window.dispatchEvent(key);assert(!key.defaultPrevented);assert.equal(life.mode,'foot');assert(life.shopOpen);}get('casinoClose').click();assert(!life.shopOpen);assert(!document.body.classList.contains('menu-open'));
assert(touch(get('view'),'touchmove').defaultPrevented,'camera still owns swipes');
console.log('Mobile menu swipes are not cancelled; scratch gestures remain captured; rapid taps do not duplicate actions; ticket rack yields to active ticket; footer actions and both close buttons work; wallet and keyboard isolation pass.');
