import assert from 'node:assert/strict';
import {bootGame} from './helpers/game.mjs';
const {app,context,get,frame,setPads,storage}=await bootGame(),t=app.test,life=t.streetLife,crowd=t.crowd,C=context.C;
t.loadLevel(24);app.start();t.setState('running');t.teleport(0,190);assert(life.exitVehicle());
const route={x0:0,x1:8,z0:174,z1:182};
function resetPeople(count=1){crowd.reset(24,6000,{count,routes:[route]});return crowd.people[0];}
function standAt(p,d=1){life.body.position.set(p.pose[0].p.x,1.05,p.pose[0].p.z+d);life.body.velocity.setZero();life.body.aabbNeedsUpdate=true;}
let p=resetPeople();standAt(p);life.ui();assert(get('interactButton').textContent.includes('Rob pedestrian'));const cash=life.economy.info().cash;get('interactButton').click();assert(p.robbed);assert.equal(life.economy.info().cash,cash+p.cash);assert(!life.rob(p));assert.equal(JSON.parse(storage.get('parkside-street-life-v1')).cash,cash+p.cash);assert(p.robPose>0&&p.flee>0);
// A solid obstruction blocks the interaction, and pause blocks wallet mutation.
p=resetPeople();standAt(p,2);const wall=new C.Body({mass:0,shape:new C.Box(new C.Vec3(1,1,.15)),position:new C.Vec3(6000,1,175)});t.world.addBody(wall);assert(!life.rob(p));t.world.removeBody(wall);t.setState('paused');assert(!life.rob(p));t.setState('running');
// Xbox X takes the same one-time action, including a held button across frames.
const pad={index:0,id:'Xbox Wireless Controller',mapping:'standard',connected:true,axes:[0,0,0,0],buttons:Array.from({length:17},()=>({value:0,pressed:false}))};setPads([pad]);frame();const beforePad=life.economy.info().cash;pad.buttons[2]={value:1,pressed:true};frame();assert(p.robbed);for(let i=0;i<8;i++)frame();assert.equal(life.economy.info().cash,beforePad+p.cash);pad.buttons[2]={value:0,pressed:false};frame();
// Knocked-down pedestrians retain a single pocket payout.
p=resetPeople();crowd.strike(p.sensor,p.pose[0].p,10,'hammer');standAt(p);life.ui();assert(get('interactButton').textContent.includes('Search pockets'));assert(life.rob(p));assert(!life.rob(p));
life.economy.earn(3000);for(const id of ['pistol','machine','hammer','grenade'])assert(life.economy.buy(id));
function aimAt(p,d=6){standAt(p,d);app.camera.position.set(life.body.position.x,2,life.body.position.z+1);app.camera.lookAt(p.pose[0].p.x,life.economy.info().equipped==='pistol'?1.53*p.scale:1.08,p.pose[0].p.z);app.camera.updateMatrixWorld(true);life.beforeStep(.8,{},{});}
const weapons=[];
for(const id of ['pistol','machine','hammer']){p=resetPeople();life.economy.equip(id);aimAt(p,id==='hammer'?2:6);const ammo=life.economy.info().ammo[id],hits=crowd.getInfo().hits;assert(life.fire());assert(p.health<100,id+' missed pedestrian');assert.equal(life.economy.info().ammo[id],ammo-(id==='hammer'?0:1));if(!p.down){assert(p.health>0);life.beforeStep(.5,{},{});assert(life.fire());}assert(p.down);assert.equal(crowd.getInfo().hits,hits+1);assert.equal(p.bodies.length,7);const score=t.scoring.snapshot(0).pending;crowd.strike(p.bodies[0],p.pose[0].p,10,id);assert.equal(crowd.getInfo().hits,hits+1);assert.equal(t.scoring.snapshot(0).pending,score);weapons.push(id);}
// Weapon rays obey occlusion and finite hammer reach.
p=resetPeople();life.economy.equip('pistol');aimAt(p);t.world.addBody(wall);assert(life.fire());assert.equal(p.health,100);t.world.removeBody(wall);life.economy.equip('hammer');aimAt(p,6);assert(life.fire());assert.equal(p.health,100);
// The actual ballistic grenade detects the soft hitbox and applies its blast.
p=resetPeople();life.economy.equip('grenade');aimAt(p);const grenadeAmmo=life.economy.info().ammo.grenade;assert(life.fire());for(let i=0;i<120;i++)life.beforeStep(1/60,{},{});assert(p.down);assert.equal(life.economy.info().ammo.grenade,grenadeAmmo-1);assert.equal(life.getInfo().grenades,0);assert(life.getInfo().grenadePool<=12);weapons.push('grenade');
// Stress the existing ragdoll limit and check that reset retires every body/constraint.
resetPeople(40);const baseline=t.world.bodies.length;for(const person of crowd.people)crowd.strike(person.sensor,person.pose[0].p,100,'machine');assert.equal(crowd.getInfo().activeRagdolls,16);assert.equal(t.world.constraints.filter(c=>c.bodyA.userData?.kind==='pedestrian').length,96);for(let i=0;i<600;i++){t.world.step(1/60);crowd.beforeStep(1/60,false);crowd.afterStep(1/60,true);}assert.equal(crowd.getInfo().activeRagdolls,0);assert.equal(t.world.constraints.filter(c=>c.bodyA.userData?.kind==='pedestrian').length,0);resetPeople(40);assert.equal(t.world.bodies.length,baseline);assert(crowd.people.every(p=>p.health===100&&!p.robbed));
// Drive into a real sensor: first-person frontal hits sometimes lift the existing ragdoll.
setPads([]);frame();t.loadLevel(24);t.setState('running');t.setCamera('first');const originalRandom=Math.random;Math.random=()=>0;
function impact(first=true,speed=18,yaw=0){t.setCamera(first?'first':'follow');crowd.reset(24,6000,{count:1,routes:[{x0:0,x1:8,z0:0,z1:8}]});t.teleport(0,0,yaw,speed);const person=crowd.people[0],local=new C.Vec3(0,0,-2.9),pos=new C.Vec3();t.chassis.pointToWorldFrame(local,pos);person.route={x0:pos.x-6000,x1:pos.x-6000+8,z0:pos.z,z1:pos.z+8};person.distance=0;crowd.beforeStep(0,false);person.sensor.dispatchEvent({type:'collide',body:t.chassis});crowd.afterStep(1/60,true);return person;}
try{p=impact();assert(p.down);assert.equal(crowd.getInfo().windshieldHits,1);assert(p.windshield>0);assert(p.bodies[0].velocity.y>5);const targetY=t.chassis.position.y+3.55-1.23-.12;let closest=Infinity,height=0;const forward=t.chassis.quaternion.vmult(new C.Vec3(0,0,-1));for(let i=0;i<35;i++){t.step(1/60);const rel=new C.Vec3();t.chassis.pointToLocalFrame(p.bodies[0].position,rel);const d=Math.abs(rel.z+.85);if(d<closest){closest=d;height=p.bodies[0].position.y;}}assert(height>targetY-.65,JSON.stringify({height,targetY,closest}));assert.equal(p.windshield,0);assert(p.bodies.every(b=>b.collisionFilterMask===3));const snap=crowd.snapshot();crowd.apply(snap,snap,0);assert.equal(snap.length,49);
 p=impact(false);assert.equal(crowd.getInfo().windshieldHits,0);p=impact(true,3);assert.equal(crowd.getInfo().windshieldHits,0);Math.random=()=>.99;p=impact();assert.equal(crowd.getInfo().windshieldHits,0);
 Math.random=()=>0;
 crowd.reset(24,6000,{count:2,routes:[{x0:0,x1:8,z0:-2.9,z1:5.1}]});t.setCamera('first');t.teleport(0,0,0,18);for(const person of crowd.people)person.distance=0;crowd.beforeStep(0,false);for(const person of crowd.people)person.sensor.dispatchEvent({type:'collide',body:t.chassis});crowd.afterStep(1/60,true);assert.equal(crowd.getInfo().down,2);assert.equal(crowd.getInfo().windshieldHits,1);assert.equal(crowd.people.filter(p=>p.windshield>0).length,1);
 // Actual moving-car collisions, then project the animated torso through the driver's camera.
 for(const level of [24,0]){t.loadLevel(level);if(level===0){t.setState('menu');t.selectVehicle(0);}t.setState('running');t.setCamera('first');const z=level===24?174:70,ox=level===24?6000:0;crowd.reset(level,ox,{count:1,routes:[{x0:0,x1:8,z0:z,z1:z+8}]});t.teleport(0,z+10,0,18);t.input.KeyW=true;const person=crowd.people[0];let visible=0;for(let i=0;i<100;i++){frame();if(person.down&&person.bodies){const projected=person.pose[0].p.clone().project(app.camera);if(Math.abs(projected.x)<1&&Math.abs(projected.y)<1&&projected.z>0&&projected.z<1)visible++;}}delete t.input.KeyW;assert(person.down,JSON.stringify({level,state:app.getState().state,car:t.chassis.position,ped:person.pose[0].p,velocity:t.chassis.velocity}));assert.equal(crowd.getInfo().windshieldHits,1);assert(visible>=4,'Windshield tumble missed the first-person camera');}
 t.teleport(0,90);assert(life.exitVehicle());crowd.reset(0,0,{count:1,routes:[{x0:0,x1:8,z0:70,z1:78}]});p=crowd.people[0];standAt(p);assert(life.rob(p));
}finally{Math.random=originalRandom;}
console.log(JSON.stringify({robbery:'Touch and Xbox X, once-only saved cash, nearby/downed pedestrians, obstruction and pause guards pass.',weapons,damage:'Finite range, solid-wall occlusion, ammo, health, once-only knockdown scoring and grenade hitbox/blast pass.',windshield:'First-person frontal lift crosses windshield height, releases collision protection, survives snapshot round-trip, is visible to the driver camera in actual truck/car collisions, and obeys speed/chance/view gates.',resources:'40 knockdowns stay within 16 seven-body ragdolls; settling and reset remove constraints and restore exact body counts.'},null,2));
