import assert from 'node:assert/strict';
import {bootGame} from './helpers/game.mjs';
import {createCityBroadphase} from '../city-broadphase.js';
import {createAdaptiveQuality} from '../adaptive-quality.js';
const {app,context}=await bootGame(),t=app.test,C=context.C;
// Compare exact candidate sets against Cannon's exhaustive AABB broadphase,
// including rotations, sleeping, masks, sensor bodies, teleports and all axes.
const world=new C.World(),sweep=createCityBroadphase(C,world),naive=new C.NaiveBroadphase();naive.useBoundingBoxes=true;let seed=7931;const random=()=>((seed=Math.imul(seed,1664525)+1013904223>>>0)/4294967296);
for(let i=0;i<220;i++){const body=new C.Body({mass:i%4===0?20:0,type:i%11===0?C.Body.KINEMATIC:undefined,shape:i%3?new C.Box(new C.Vec3(.3+random()*5,.3+random()*3,.3+random()*5)):new C.Sphere(.3+random()*3),position:new C.Vec3(random()*120-60,random()*8,random()*120-60),collisionFilterGroup:i%5===0?4:1,collisionFilterMask:i%5===0?33:-1});body.quaternion.setFromEuler(random(),random(),random());world.addBody(body);}world.addBody(new C.Body({shape:new C.Plane()}));
function pairs(broadphase){const a=[],b=[];broadphase.collisionPairs(world,a,b);return new Set(a.map((v,i)=>[v.id,b[i].id].sort((a,b)=>a-b).join(':')));}
for(let round=0;round<24;round++){for(let i=0;i<world.bodies.length;i++){const b=world.bodies[i];if(i%7===round%7){b.position.x+=random()*10-5;b.position.z+=random()*10-5;b.quaternion.setFromEuler(random(),random(),random());b.aabbNeedsUpdate=true;}if(i%13===0)round%2?b.sleep():b.wakeUp();if(b.aabbNeedsUpdate)b.updateAABB();}sweep.axisIndex=round%3;sweep.dirty=true;assert.deepEqual(pairs(sweep),pairs(naive),'no missing or extra AABB candidate pair');}
const removed=world.bodies[10];world.removeBody(removed);sweep.dirty=true;assert.deepEqual(pairs(sweep),pairs(naive));world.addBody(removed);sweep.dirty=true;assert.deepEqual(pairs(sweep),pairs(naive));assert(sweep.stats.scanned<world.bodies.length**2/3);
// Resolution responds to sustained load, not individual frames or paused menus.
const ratios=[],renderer={setPixelRatio:r=>ratios.push(r)},quality=createAdaptiveQuality(renderer,{pixelRatio:3,mobile:true});assert.equal(quality.getInfo().pixelRatio,1);for(let i=0;i<200;i++)quality.sample(.05);assert.equal(quality.getInfo().pixelRatio,.65);const count=ratios.length;for(let i=0;i<200;i++)quality.sample(.5);for(let i=0;i<1000;i++)quality.sample(.016,false);assert.equal(ratios.length,count);for(let i=0;i<4000;i++)quality.sample(1/60);assert.equal(quality.getInfo().pixelRatio,1);assert(ratios.every(r=>r>=.65&&r<=1));
// Count actual camera-layer submissions instead of the renderer stub's traversal.
t.loadLevel(24);app.start();const view=t.secretView,baseline=t.world.bodies.length;assert.equal(baseline,1070);assert.equal(app.renderer.shadowMap.enabled,false);assert.equal(app.getState().performance.mobile,true);
function draws(){let count=0;app.scene.traverseVisible(m=>{if(m.isMesh&&m.layers.test(app.camera.layers)&&m.material.visible!==false&&(!m.isInstancedMesh||m.count))count++;});return count;}
t.cityShells.originals();for(const item of t.traffic.active)item.mesh.visible=true;const unbatched=draws();t.cityShells.update();t.trafficLOD.update(0,210);const batched=draws();assert(batched<unbatched*.4,JSON.stringify({unbatched,batched}));const capacity=t.cityShells.getInfo().capacity,batches=t.cityShells.getInfo().batches;
const building=view.buildings.find(b=>b.h===16),wall=building.target.entries.find(e=>e.foundation);view.detail.update(0,wall.home.x-view.ox,wall.home.z,true);assert(!wall.mesh.layers.test(app.camera.layers));t.environment.strike(wall.body,wall.body.position,30);t.environment.update(1/60);t.cityShells.update();assert(wall.mesh.layers.test(app.camera.layers));assert(wall.broken);assert(t.world.bodies.includes(wall.body));
const car=t.traffic.active[0];car.body.position.set(view.ox,car.body.position.y,210);t.trafficLOD.update(0,210);assert(car.mesh.visible,'near cars retain the full detailed vehicle');car.occupied=true;t.trafficLOD.update(0,210);assert(!car.mesh.visible);car.occupied=false;
t.trafficLOD.update(-1000,210);assert(!car.mesh.visible);t.trafficLOD.originals();assert(car.mesh.visible,'replay renders original vehicles at snapshot transforms');assert(view.group.children.filter(m=>m.name==='Distant street cars').every(m=>m.count===0));
for(let i=0;i<12;i++){t.environment.reset(24);t.traffic.reset(24);t.cityShells.update();t.trafficLOD.update(0,210);assert.equal(t.cityShells.getInfo().capacity,capacity);assert.equal(t.cityShells.getInfo().batches,batches);assert.equal(t.world.bodies.length,baseline);assert(!wall.mesh.layers.test(app.camera.layers));assert(t.cityShells.getInfo().intactMeshes===capacity);}
const sensor=t.crowd.people[0].sensor;assert.equal(sensor.collisionFilterMask,32);assert(sensor.collisionFilterMask&t.chassis.collisionFilterGroup);assert(!(sensor.collisionFilterMask&wall.body.collisionFilterGroup));
console.log(JSON.stringify({unbatched,batched,submissionReduction:Math.round((1-batched/unbatched)*100)+'%',cityBatches:batches,cityCapacity:capacity,trafficBatches:3,permanentBodies:baseline,physics:'24 exhaustive broadphase comparisons match, including all axes and add/remove',quality:'Mobile ratio 1→0.65→1; ignores pause/background stalls',rebuilds:12},null,2));
