import assert from 'node:assert/strict';
import {createShopEconomy} from '../shop-economy.js';
import {SCRATCH_GAMES,createScratchBoard,evaluateScratchBoard,ticketProgress,CELLS_PER_ZONE} from '../scratch-tickets.js';
function wallet(random){const data=new Map(),storage={getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)},economy=createShopEconomy(storage,random);economy.earn(100000);return {economy,storage};}
assert.equal(SCRATCH_GAMES.length,10);assert.equal(new Set(SCRATCH_GAMES.map(g=>g.id)).size,10);
for(const g of SCRATCH_GAMES)for(const payout of [0,10,25,100,500])for(let id=1;id<=200;id++){const ticket={id,payout,design:g.id,seed:Math.imul(id,7919)>>>0,scratched:[]},board=createScratchBoard(ticket);assert.equal(evaluateScratchBoard(board),payout,g.name+' seed '+id);assert.equal(board.plays.length,9);assert.deepEqual(createScratchBoard(ticket),board);}
// Exactly the old distribution for every design; selecting a game never draws another odds roll.
for(const g of SCRATCH_GAMES){let sample=0,calls=0;const {economy}=wallet(()=>{calls++;return (sample+.5)/1000;});const counts={0:0,10:0,25:0,100:0,500:0};for(sample=0;sample<1000;sample++){const cash=economy.info().cash;assert(economy.buyTicket(g.id));const ticket=economy.info().ticket;assert.equal(economy.info().cash,cash-10);counts[ticket.payout]++;assert.equal(evaluateScratchBoard(createScratchBoard(ticket)),ticket.payout);assert.equal(economy.claimTicket(),ticket.payout);assert.equal(economy.claimTicket(),null);}assert.deepEqual(counts,{0:600,10:200,25:120,100:60,500:20});assert.equal(calls,1000);}
const {economy,storage}=wallet(()=>.99);assert(economy.buyTicket('numbers'));const t=economy.info().ticket,board=createScratchBoard(t);const mask=Array.from({length:70},(_,i)=>i);assert(economy.scratchTicket(t.id,mask));assert(!economy.scratchTicket(t.id+1,mask));let saved=economy.info().ticket;assert.equal(ticketProgress(saved).revealed,1);saved.scratched.length=0;assert.equal(economy.info().ticket.scratched.length,70);const restored=createShopEconomy(storage,()=>0);assert.deepEqual(restored.info().ticket,economy.info().ticket);assert.equal(evaluateScratchBoard(createScratchBoard(restored.info().ticket)),500);assert(!restored.buyTicket('dice'));const balance=restored.info().cash;assert.equal(restored.claimTicket(),500);assert.equal(restored.info().cash,balance+500);assert.equal(restored.claimTicket(),null);assert.equal(restored.info().lastTicket.id,t.id);assert.equal(restored.info().ticket,null);
// Old saved tickets retain their predetermined payout and become a playable numbered ticket.
const legacy=createShopEconomy({getItem:()=>JSON.stringify({cash:90,owned:[],serial:2,ticket:{id:2,payout:25}}),setItem:()=>{}},()=>0);assert.equal(legacy.info().ticket.design,'numbers');assert.equal(evaluateScratchBoard(createScratchBoard(legacy.info().ticket)),25);assert.equal(legacy.claimTicket(),25);
console.log('10,000 ticket purchases preserve exactly 40% wins and the existing 60/20/12/6/2 payout distribution. All 10 game rules agree with 10,000 generated boards; partial scratches, legacy migration, fixed outcomes and exactly-once payout pass.');
