import * as C from './cannon-es.js';
import {buildRoadster} from './roadster-model.js';
const T=window.THREE,$=id=>document.getElementById(id),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
try{boot()}catch(e){console.error(e);$('fatal').hidden=false;$('errorText').textContent=e.message;}
function boot(){
const scene=new T.Scene();scene.background=new T.Color(0xb9c9bc);scene.fog=new T.Fog(0xb9c9bc,85,310);
const renderer=new T.WebGLRenderer({canvas:$('view'),antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
const camera=new T.PerspectiveCamera(54,1,.15,520);scene.add(new T.HemisphereLight(0xfff3d9,0x667d50,1.5));
const sun=new T.DirectionalLight(0xffdfaa,2.5);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-23,right:23,top:23,bottom:-23,near:1,far:120});sun.shadow.bias=-.0007;sun.shadow.normalBias=.035;scene.add(sun,sun.target);
const world=new C.World({gravity:new C.Vec3(0,-9.82,0),allowSleep:true});world.broadphase=new C.SAPBroadphase(world);world.solver.iterations=8;world.defaultContactMaterial.friction=.45;world.defaultContactMaterial.restitution=.12;
const groundMat=new C.Material('ground'),carMat=new C.Material('car');world.addContactMaterial(new C.ContactMaterial(carMat,groundMat,{friction:.35,restitution:.1}));
const ground=new C.Body({mass:0,material:groundMat,shape:new C.Plane()});ground.quaternion.setFromEuler(-Math.PI/2,0,0);world.addBody(ground);
const palette={road:0x535956,grass:0x84986a,dirt:0xb5a27c,wood:0x776346,hay:0xc2a258,red:0x9d4638,stone:0x89908a,white:0xede5cf};
const mat=(c,r=.9)=>new T.MeshStandardMaterial({color:c,roughness:r});const mats=Object.fromEntries(Object.entries(palette).map(([k,c])=>[k,mat(c)]));
const unitBox=new T.BoxGeometry(1,1,1),unitSphere=new T.IcosahedronGeometry(1,1);
function visualBox(w,h,d,material,x=0,y=0,z=0){const m=new T.Mesh(unitBox,material);m.scale.set(w,h,d);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;return m;}
function boxBody(w,h,d,mass,x,y,z,quaternion=null){const b=new C.Body({mass,material:mass?carMat:groundMat,shape:new C.Box(new C.Vec3(w/2,h/2,d/2)),position:new C.Vec3(x,y,z)});if(quaternion)b.quaternion.copy(quaternion);world.addBody(b);return b;}
const LENGTH=2400,roadX=s=>12*Math.sin(s/145)+7*Math.sin(s/67),roadSlope=s=>12/145*Math.cos(s/145)+7/67*Math.cos(s/67),heading=s=>-Math.atan(roadSlope(s));
function strip(width,offset,y,material){const vertices=[],indices=[];for(let s=-80,i=0;s<=LENGTH+200;s+=4,i++){const x=roadX(s);vertices.push(x+offset-width/2,y,-s,x+offset+width/2,y,-s);if(i){let a=i*2;indices.push(a-2,a-1,a,a-1,a+1,a)}}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(vertices,3));g.setIndex(indices);g.computeVertexNormals();const m=new T.Mesh(g,material);m.receiveShadow=true;scene.add(m);}
const land=new T.Mesh(new T.PlaneGeometry(2500,6000),mats.grass);land.rotation.x=-Math.PI/2;land.position.set(0,-.025,-1000);land.receiveShadow=true;scene.add(land);strip(11.4,0,.005,mats.dirt);strip(8.4,0,.018,mats.road);strip(.11,-3.95,.022,mats.white);strip(.11,3.95,.022,mats.white);
const dummy=new T.Object3D();function instanced(g,m,transforms){const batch=new T.InstancedMesh(g,m,transforms.length);transforms.forEach((a,i)=>{dummy.position.set(...a.p);dummy.rotation.set(0,a.r||0,0);dummy.scale.set(...a.s);dummy.updateMatrix();batch.setMatrixAt(i,dummy.matrix)});batch.receiveShadow=true;scene.add(batch);return batch;}
let seed=842;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}const dashes=[],trunks=[],crowns=[],hills=[],posts=[],rails=[];
for(let s=-40;s<LENGTH+120;s+=9)dashes.push({p:[roadX(s),.026,-s],s:[.11,.01,4],r:heading(s)});instanced(unitBox,mats.white,dashes);
for(let s=-30;s<LENGTH+170;s+=10){for(const side of [-1,1]){const off=13+rand()*38,x=roadX(s)+off*side,sz=3+rand()*4;trunks.push({p:[x,1.8,-s],s:[.35,3.6,.35]});crowns.push({p:[x,4.6,-s],s:[sz*.7,sz,sz*.7]});if(off<22){const b=new C.Body({mass:0,shape:new C.Sphere(.55),position:new C.Vec3(x,1,-s)});b.userData={kind:'tree'};world.addBody(b);}if(s%30===0)hills.push({p:[roadX(s)+(145+rand()*100)*side,-3,-s],s:[40+rand()*45,14+rand()*25,50+rand()*40]});}}
instanced(new T.CylinderGeometry(.5,.65,1,6),mats.wood,trunks);instanced(new T.IcosahedronGeometry(1,0),mat(0x557b50),crowns);instanced(unitSphere,mat(0x799068),hills);
for(let s=-20;s<LENGTH+80;s+=8)for(const side of [-1,1]){if(Math.floor(s/180)%3===2)continue;let x=roadX(s)+side*9;posts.push({p:[x,.6,-s],s:[.14,1.2,.14]});rails.push({p:[x,.85,-s+4],s:[.09,.13,8.3],r:heading(s)});rails.push({p:[x,.42,-s+4],s:[.09,.13,8.3],r:heading(s)});}
instanced(unitBox,mats.wood,posts);instanced(unitBox,mats.wood,rails);
// Fence posts have individual collision proxies; open pasture stretches remain drivable.
for(let i=0;i<posts.length;i++){const p=posts[i].p;const b=boxBody(.22,1.2,.22,0,p[0],p[1],p[2]);b.userData={kind:'fence'};}
function label(text,color='#173b2e'){const cv=document.createElement('canvas');cv.width=512;cv.height=128;const ctx=cv.getContext('2d');ctx.fillStyle=color;ctx.fillRect(0,0,512,128);ctx.strokeStyle='#ecebd1';ctx.lineWidth=5;ctx.strokeRect(7,7,498,114);ctx.fillStyle='#fff4db';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='bold 40px system-ui';ctx.fillText(text,256,67);const tx=new T.CanvasTexture(cv);tx.colorSpace=T.SRGBColorSpace;return new T.Mesh(new T.PlaneGeometry(6,1.5),new T.MeshBasicMaterial({map:tx,side:T.DoubleSide}));}
const checkpoints=[600,1200,1800,2400],gates=[];for(const s of [0,...checkpoints]){let x=roadX(s);const sign=label(s===0?'COUNTRY RUN':s===2400?'FINISH':'SERVICE • '+s/1000+' KM');sign.position.set(x,4.9,-s);scene.add(sign);for(const side of [-1,1]){scene.add(visualBox(.16,5,.16,mats.wood,x+side*4.8,2.5,-s));}const line=visualBox(8.3,.025,2,mat(s===2400?0xe8bf68:0x73bb96),x,.04,-s);scene.add(line);gates.push({s,line});}
// Farms, telegraph poles and fields establish distance without texture downloads.
for(let s=120;s<LENGTH;s+=370){const side=s%740<370?1:-1,x=roadX(s)+side*34;scene.add(visualBox(12,5,16,mats.red,x,2.5,-s));const roof=new T.Mesh(new T.ConeGeometry(10,3,4),mats.wood);roof.rotation.y=Math.PI/4;roof.scale.set(1,1,1.2);roof.position.set(x,6.2,-s);scene.add(roof);scene.add(visualBox(4,3,.1,mats.wood,x,1.5,-s+8.05));}
const obstacles=[],loose=[],sparks=[];let totalLost=0;function obstacle(kind,s,lane){const x=roadX(s)+lane,z=-s;let w,h,d,mass,material;switch(kind){case'hay':w=1.7;h=1.3;d=1.3;mass=48;material=mats.hay;break;case'barrel':w=.8;h=1.15;d=.8;mass=35;material=mats.red;break;case'log':w=3.6;h=.65;d=.65;mass=180;material=mats.wood;break;case'stone':w=1.4;h=1.15;d=1.4;mass=0;material=mats.stone;break;default:w=1.2;h=1.2;d=1.2;mass=60;material=mats.wood;}
 const mesh=new T.Group();mesh.add(visualBox(w,h,d,material));if(kind==='hay'||kind==='crate'){for(const a of [-.35,.35])mesh.add(visualBox(.07,h+.03,d+.035,mats.wood,w*a,0,0));}if(kind==='barrel'){mesh.clear();const barrel=new T.Mesh(new T.CylinderGeometry(.4,.4,h,12),material);barrel.castShadow=true;mesh.add(barrel);for(let yy of [-.32,.32]){const band=new T.Mesh(new T.TorusGeometry(.405,.035,5,12),mats.stone);band.rotation.x=Math.PI/2;band.position.y=yy;mesh.add(band);}}
 mesh.position.set(x,h/2,z);scene.add(mesh);const body=boxBody(w,h,d,mass,x,h/2,z);body.userData={kind};body.sleepSpeedLimit=.4;body.sleepTimeLimit=1;obstacles.push({mesh,body,home:body.position.clone(),q:body.quaternion.clone()});}
for(let s=105,n=0;s<LENGTH-80;s+=65,n++){if(checkpoints.some(c=>Math.abs(s-c)<38))continue;const lane=[-2.4,2.2,0,-1.8,2.6][n%5],kind=['hay','crate','barrel','log','stone'][n%5];obstacle(kind,s,lane);if(n%3===1)obstacle('barrel',s+4,lane+.9);}
for(let s of [330,940,1570,2100]){const x=roadX(s)+2.1,q=new C.Quaternion();q.setFromEuler(.18,0,0);const body=boxBody(2.7,.22,6,0,x,.48,-s,q);body.userData={kind:'ramp'};const mesh=visualBox(2.7,.22,6,mats.wood,x,.48,-s);mesh.quaternion.copy(q);scene.add(mesh);const sign=label('RAMP →','#815f31');sign.scale.setScalar(.32);sign.position.set(x+3,1.9,-s+9);scene.add(sign);}
const car=buildRoadster(T);scene.add(car.root);
const chassis=new C.Body({mass:950,material:carMat,position:new C.Vec3(0,1.2,0),linearDamping:.025,angularDamping:.48});chassis.addShape(new C.Box(new C.Vec3(.72,.26,1.85)),new C.Vec3(0,.05,0));world.addBody(chassis);
const vehicle=new C.RaycastVehicle({chassisBody:chassis,indexRightAxis:0,indexUpAxis:1,indexForwardAxis:2});
for(const z of [-1.48,1.45])for(const x of [-1.04,1.04])vehicle.addWheel({radius:.525,directionLocal:new C.Vec3(0,-1,0),axleLocal:new C.Vec3(-1,0,0),chassisConnectionPointLocal:new C.Vec3(x,-.04,z),suspensionStiffness:32,suspensionRestLength:.29,maxSuspensionTravel:.22,frictionSlip:3.4,dampingRelaxation:2.3,dampingCompression:4.4,maxSuspensionForce:90000,rollInfluence:.07,customSlidingRotationalSpeed:-25,useCustomSlidingRotationalSpeed:true});vehicle.addToWorld(world);
const wheelParts=vehicle.wheelInfos.map((w,i)=>car.assemblies.find(p=>p.name==='wheel-'+(i<2?'front':'rear')+'-'+(i%2?'left':'right')));
let mode='run',state='menu',health=100,time=0,distance=0,passed=0,speed=0,forwardSpeed=0,steer=0,cameraMode=0,clock=0,physicsTime=0,lastImpact=-10,flash=0,noticeUntil=0,countdown=0,deadTime=0,penalty=0,slow=false;const keys={},touch={};let input={};
const camGoal=new T.Vector3(),camLook=new T.Vector3(),look=new T.Vector3(),carPos=new T.Vector3();let camInit=false;
function notify(message,seconds=2){$('notice').textContent=message;noticeUntil=clock+seconds;$('notice').style.opacity='1';}
function syncCar(){car.root.position.copy(chassis.position);car.root.quaternion.copy(chassis.quaternion);car.root.position.add(new T.Vector3(0,-.85,0).applyQuaternion(car.root.quaternion));car.root.updateMatrixWorld(true);for(let i=0;i<4;i++){const p=wheelParts[i];if(!p.userData.attached)continue;vehicle.updateWheelTransform(i);const t=vehicle.wheelInfos[i].worldTransform;const local=new T.Vector3().copy(t.position);car.root.worldToLocal(local);p.position.copy(local);p.quaternion.copy(car.root.quaternion).invert().multiply(new T.Quaternion().copy(t.quaternion));}}
function restore(){for(const d of loose){world.removeBody(d.body);scene.remove(d.mesh)}loose.length=0;for(const p of car.assemblies){car.root.add(p);p.position.copy(p.userData.home);p.quaternion.identity();p.scale.set(1,1,1);p.userData.attached=true;p.visible=true;}for(const w of vehicle.wheelInfos){w.radius=.525;w.suspensionStiffness=32;w.frictionSlip=3.4;}health=100;}
function detach(part,kick=0){if(!part||!part.userData.attached||part.name==='chassis'||part.name==='tub')return;part.userData.attached=false;totalLost++;scene.attach(part);const sz=part.userData.size;const body=boxBody(clamp(sz.x,.12,2.3),clamp(sz.y,.12,1.4),clamp(sz.z,.12,2.6),part.name.startsWith('wheel')?25:12,part.position.x,part.position.y,part.position.z);body.quaternion.copy(part.quaternion);body.velocity.copy(chassis.velocity);body.velocity.x+=(rand()-.5)*(4+kick);body.velocity.y+=2+rand()*3+kick*.5;body.velocity.z+=(rand()-.5)*(4+kick);body.angularVelocity.set((rand()-.5)*8,(rand()-.5)*8,(rand()-.5)*8);body.collisionFilterGroup=2;body.collisionFilterMask=1;body.sleepSpeedLimit=.35;loose.push({mesh:part,body,age:0});let i=wheelParts.indexOf(part);if(i>=0){vehicle.wheelInfos[i].radius=.14;vehicle.wheelInfos[i].suspensionStiffness=8;vehicle.wheelInfos[i].frictionSlip=.4;}while(loose.length>32){const d=loose.shift();world.removeBody(d.body);scene.remove(d.mesh);}}
function burst(point,strength){for(let i=0;i<Math.min(18,5+strength);i++){const mesh=new T.Mesh(unitBox,new T.MeshBasicMaterial({color:i%2?0xffba56:0xfff4c5}));mesh.scale.set(.035,.035,.16);mesh.position.copy(point);scene.add(mesh);sparks.push({mesh,v:new T.Vector3((rand()-.5)*9,rand()*6,(rand()-.5)*9),life:.5+rand()*.5});}flash=Math.min(.65,strength/35);}
chassis.addEventListener('collide',event=>{if(state!=='running'||physicsTime-lastImpact<.3)return;const impact=Math.abs(event.contact.getImpactVelocityAlongNormal());if(impact<3.4)return;const other=event.body,kind=other.userData?.kind;if(other===ground&&impact<6.5)return;lastImpact=physicsTime;const damage=clamp((impact-2.7)*(kind==='hay'?1.35:2.4),1,65);health=Math.max(0,health-damage);const cp=event.contact.bi===chassis?event.contact.ri:event.contact.rj;const point=new T.Vector3(chassis.position.x+cp.x,chassis.position.y+cp.y,chassis.position.z+cp.z);burst(point,impact);crashSound(impact);syncCar();const candidates=car.assemblies.filter(p=>p.userData.attached&&!['chassis','tub','cabin','drive'].includes(p.name));candidates.sort((a,b)=>a.getWorldPosition(new T.Vector3()).distanceToSquared(point)-b.getWorldPosition(new T.Vector3()).distanceToSquared(point));const n=impact>18?4:impact>10?2:impact>5?1:0;for(let i=0;i<n;i++)detach(candidates[i],impact*.2);notify(impact>14?'Heavy impact!':n?'Parts lost — keep it together':'Body damage',1.4);});
function explode(){syncCar();for(const p of car.assemblies)detach(p,14);chassis.velocity.y=7;chassis.angularVelocity.set(1,2,1);burst(new T.Vector3().copy(chassis.position),30);crashSound(25);health=0;}
function recover(initial=false){const s=initial?8:clamp(-chassis.position.z,8,LENGTH-8);chassis.position.set(roadX(s),1.18,-s);chassis.quaternion.setFromEuler(0,heading(s),0);chassis.velocity.setZero();chassis.angularVelocity.setZero();chassis.force.setZero();chassis.torque.setZero();chassis.wakeUp();for(const w of vehicle.wheelInfos){w.rotation=0;w.deltaRotation=0;w.suspensionLength=.29;}steer=0;lastImpact=physicsTime+.35;camInit=false;if(!initial){penalty+=10;notify(mode==='run'?'Recovered · +10 seconds':'Recovered');if(mode==='sandbox')restore();}syncCar();}
function resetObstacles(){for(const o of obstacles){o.body.position.copy(o.home);o.body.quaternion.copy(o.q);o.body.velocity.setZero();o.body.angularVelocity.setZero();o.body.wakeUp();}}
function start(){restore();resetObstacles();time=0;distance=8;passed=0;totalLost=0;penalty=0;deadTime=0;clearInput();recover(true);state='countdown';countdown=1.5;$('intro').hidden=true;$('finish').hidden=true;$('pausePanel').hidden=true;$('hud').hidden=false;$('touch').hidden=false;$('explodeButton').hidden=mode!=='sandbox';notify('Ready',.7);resumeAudio();}
function finish(won){state='ended';clearInput();$('touch').hidden=true;$('finish').hidden=false;$('finishTag').textContent=won?'COUNTRY RUN COMPLETE':time+penalty>=240?'OUT OF TIME':'ROADSIDE RETIREMENT';$('finishTitle').textContent=won?'Home in one piece. Mostly.':'That’ll need a tow.';$('resultDistance').textContent=Math.round(distance);$('resultTime').textContent=Math.round(time+penalty);$('resultParts').textContent=totalLost;let best;try{best=Number(localStorage.getItem('roadster-country-best')||0);if(won&&(!best||time+penalty<best)){best=Math.round(time+penalty);localStorage.setItem('roadster-country-best',best);}}catch{}$('best').textContent=won?`Car condition: ${Math.round(health)}%${best?' · Best run: '+best+'s':''}`:'Ease off before bends. Service gates repair damage.';}
function pause(){if(state==='running'||state==='countdown'){state='paused';clearInput();$('pausePanel').hidden=false;$('touch').hidden=true;}else if(state==='paused'){state='running';$('pausePanel').hidden=true;$('touch').hidden=false;}}
function clearInput(){for(const k in keys)delete keys[k];for(const k in touch)delete touch[k];document.querySelectorAll('.pressed').forEach(b=>b.classList.remove('pressed'));}
$('start').onclick=start;$('again').onclick=start;$('restart').onclick=start;$('resume').onclick=pause;$('pauseButton').onclick=pause;$('cameraButton').onclick=()=>cameraMode=(cameraMode+1)%3;$('recover').onclick=()=>{if(state==='running')recover()};$('menu').onclick=()=>{state='menu';$('finish').hidden=true;$('intro').hidden=false;$('hud').hidden=true;restore();recover(true);};$('explodeButton').onclick=()=>{pause();explode()};
$('runMode').onclick=()=>{mode='run';$('runMode').classList.add('active');$('sandboxMode').classList.remove('active')};$('sandboxMode').onclick=()=>{mode='sandbox';$('sandboxMode').classList.add('active');$('runMode').classList.remove('active')};
window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();keys[e.code]=true;if(e.repeat)return;if(e.code==='KeyP'||e.code==='Escape')pause();if(e.code==='KeyC')cameraMode=(cameraMode+1)%3;if(e.code==='KeyR'&&state==='running')recover();if(e.code==='KeyE'&&mode==='sandbox'&&state==='running')explode();});window.addEventListener('keyup',e=>delete keys[e.code]);
for(const b of document.querySelectorAll('[data-input]')){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);touch[b.dataset.input]=true;b.classList.add('pressed');resumeAudio()});const release=()=>{touch[b.dataset.input]=false;b.classList.remove('pressed')};b.addEventListener('pointerup',release);b.addEventListener('pointercancel',release);b.addEventListener('lostpointercapture',release);}
window.addEventListener('blur',()=>{clearInput();if(state==='running'||state==='countdown')pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();if(state==='running'||state==='countdown')pause()}});
let audioCtx,engineOsc,gain,sound=false;function resumeAudio(){if(sound){if(!audioCtx){audioCtx=new(window.AudioContext||window.webkitAudioContext)();engineOsc=audioCtx.createOscillator();engineOsc.type='sawtooth';gain=audioCtx.createGain();gain.gain.value=0;const filter=audioCtx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=480;engineOsc.connect(filter).connect(gain).connect(audioCtx.destination);engineOsc.start();}audioCtx.resume().catch(()=>{});}}
$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'Sound on':'Sound off';resumeAudio();};function crashSound(n){if(!sound||!audioCtx)return;const count=audioCtx.sampleRate*.22,buffer=audioCtx.createBuffer(1,count,audioCtx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<count;i++)data[i]=(Math.random()*2-1)*(1-i/count);const src=audioCtx.createBufferSource(),g=audioCtx.createGain();g.gain.value=Math.min(.35,n*.012);src.buffer=buffer;src.connect(g).connect(audioCtx.destination);src.start();}
function physics(dt){physicsTime+=dt;input={gas:keys.KeyW||keys.ArrowUp||touch.gas,brake:keys.KeyS||keys.ArrowDown||touch.brake,left:keys.KeyA||keys.ArrowLeft||touch.left,right:keys.KeyD||keys.ArrowRight||touch.right,handbrake:keys.Space||touch.handbrake};const active=state==='running';const fwd=chassis.quaternion.vmult(new C.Vec3(0,0,-1));forwardSpeed=chassis.velocity.dot(fwd);speed=chassis.velocity.length();const off=Math.abs(chassis.position.x-roadX(-chassis.position.z))>4.2;const desired=active?((input.left?1:0)-(input.right?1:0))*(.43/(1+speed*.025)):0;steer+=(desired-steer)*Math.min(1,dt*8);vehicle.setSteeringValue(steer,0);vehicle.setSteeringValue(steer,1);
 let engine=0,brake=active?0:45;const motor=car.assemblies.find(p=>p.name==='engine').userData.attached;if(active&&health>0&&motor){const force=3400*(.45+.55*health/100);if(input.gas)engine=forwardSpeed<35?force:0;if(input.brake){if(forwardSpeed>1)brake=42;else engine=forwardSpeed>-8?-force*.6:0;}}else if(active){engine=0;}
 for(let i=0;i<4;i++){const attached=wheelParts[i].userData.attached;vehicle.applyEngineForce(i>=2&&attached?engine:0,i);vehicle.setBrake(input.handbrake&&active&&i>=2?70:brake,i);vehicle.wheelInfos[i].frictionSlip=attached?(off?1.7:input.handbrake&&i>=2?1.3:3.4):.4;}
 if(off&&speed>0){chassis.applyForce(chassis.velocity.scale(-40),new C.Vec3());}else if(speed>0){chassis.applyForce(chassis.velocity.scale(-8-speed*.6),new C.Vec3());}
 world.step(1/60,dt,5);syncCar();
 if(active){time+=dt;const oldDistance=distance;distance=Math.max(distance,clamp(-chassis.position.z,0,LENGTH));if(passed<checkpoints.length&&-chassis.position.z>=checkpoints[passed]&&Math.abs(chassis.position.x-roadX(checkpoints[passed]))<4.4){const cp=checkpoints[passed];passed++;if(cp<LENGTH){restore();notify('Service checkpoint · car repaired',2.2);}else if(mode==='run')finish(true);else{notify('End of the road · new run');start();}}
 // A missed gate stays required: go back through it or recover before it.
 if(passed<checkpoints.length&&distance>checkpoints[passed]+30&&oldDistance<=checkpoints[passed]+30)notify('Missed service gate — turn back',4);
 const missingWheels=wheelParts.filter(p=>!p.userData.attached).length;if(health<=0||(!motor&&speed<1)||missingWheels>=3)deadTime+=dt;else deadTime=0;if(mode==='run'&&(deadTime>3.5||time+penalty>=240))finish(false);if(mode==='sandbox'&&deadTime>5){restore();recover();deadTime=0;}if(chassis.position.y<-10||Math.abs(chassis.position.x)>350)recover();}
 for(const o of obstacles){o.mesh.position.copy(o.body.position);o.mesh.quaternion.copy(o.body.quaternion);}for(const d of loose){d.age+=dt;d.mesh.position.copy(d.body.position);d.mesh.quaternion.copy(d.body.quaternion);}for(let i=sparks.length-1;i>=0;i--){const p=sparks[i];p.life-=dt;p.v.y-=9.8*dt;p.mesh.position.addScaledVector(p.v,dt);if(p.life<0){scene.remove(p.mesh);p.mesh.material.dispose();sparks.splice(i,1);}}
}
const mapCtx=$('map').getContext('2d');function hud(){const mph=Math.round(Math.abs(forwardSpeed)*2.237);$('speed').textContent=mph;$('distance').textContent=(distance/1000).toFixed(2)+' / 2.4 KM';const t=Math.max(0,Math.ceil(240-time-penalty));$('timer').textContent=mode==='sandbox'?'FREE DRIVE':Math.floor(t/60)+':'+String(t%60).padStart(2,'0');$('progress').style.width=distance/LENGTH*100+'%';$('healthBar').style.width=health+'%';$('healthBar').style.background=health<35?'#ff986b':'#bee794';$('condition').textContent=Math.round(health)+'% · '+car.assemblies.filter(p=>!p.userData.attached).length+' parts lost';const off=Math.abs(chassis.position.x-roadX(-chassis.position.z))>4.2;$('gear').textContent=(forwardSpeed<-1?'R':mph<2?'N':Math.min(5,1+Math.floor(mph/19)))+' · '+(off?'GRASS':input.handbrake?'HANDBRAKE':'TARMAC');
 const c=mapCtx;c.clearRect(0,0,168,230);const s=-chassis.position.z;const xy=q=>[84+(roadX(q)-roadX(s))*2,195-(q-s)*.85];c.strokeStyle='#eff1d666';c.lineWidth=9;c.lineCap='round';c.beginPath();for(let q=s-30;q<s+230;q+=3){let[x,y]=xy(q);q===s-30?c.moveTo(x,y):c.lineTo(x,y);}c.stroke();for(const o of obstacles){let q=-o.body.position.z;if(q<s||q>s+210)continue;let [x,y]=xy(q);c.fillStyle='#efb065';c.fillRect(x+(o.body.position.x-roadX(q))*2-2,y-2,4,4);}c.fillStyle='#fff3d0';c.beginPath();const x=84+(chassis.position.x-roadX(s))*2;c.moveTo(x,187);c.lineTo(x-6,202);c.lineTo(x+6,202);c.closePath();c.fill();}
function updateCamera(dt){carPos.copy(chassis.position);const s=-chassis.position.z;const q=new T.Quaternion().setFromAxisAngle(new T.Vector3(0,1,0),heading(s));if(state==='menu'){camGoal.set(roadX(8)+6.6,3.3,1.5);look.set(roadX(8),.9,-8);}else if(cameraMode===2){camGoal.copy(carPos).add(new T.Vector3(0,21,7));look.copy(carPos).add(new T.Vector3(0,0,-9));}else{const yawQ=new T.Quaternion().copy(chassis.quaternion);const forward=new T.Vector3(0,0,-1).applyQuaternion(yawQ);forward.y=0;if(forward.length()<.1)forward.set(0,0,-1);forward.normalize();if(cameraMode===1){camGoal.copy(carPos).addScaledVector(forward,1.6);camGoal.y+=1.6;look.copy(carPos).addScaledVector(forward,22);look.y+=1;}else{camGoal.copy(carPos).addScaledVector(forward,-(camera.aspect<.8?10.5:8));camGoal.y+=4.1+speed*.018;look.copy(carPos).addScaledVector(forward,6);look.y+=.75;}}
 if(!camInit){camera.position.copy(camGoal);camLook.copy(look);camInit=true;}else{camera.position.lerp(camGoal,1-Math.exp(-dt*5));camLook.lerp(look,1-Math.exp(-dt*7));}camera.position.y=Math.max(camera.position.y,1.1);camera.lookAt(camLook);sun.position.set(chassis.position.x-20,45,chassis.position.z+15);sun.target.position.copy(chassis.position);}
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();camInit=false;}window.addEventListener('resize',resize);resize();recover(true);$('start').disabled=false;$('start').textContent='Start driving →';
$('view').addEventListener('webglcontextlost',e=>{e.preventDefault();if(state==='running')pause();$('fatal').hidden=false;$('errorText').textContent='The graphics context was interrupted. Reload to resume.';});
let last=performance.now(),hudClock=0;function frame(now){requestAnimationFrame(frame);const realDt=Math.min(.06,(now-last)/1000);last=now;if(document.hidden)return;clock+=realDt;slow=state==='running'&&(keys.ShiftLeft||keys.ShiftRight||touch.slow);$('slowBadge').hidden=!slow;const dt=realDt*(slow?.24:1);if(state==='countdown'){countdown-=realDt;if(countdown<=0){state='running';notify('Go!',1);}}
 if(state==='running'||state==='countdown'||state==='menu')physics(dt);else syncCar();updateCamera(realDt);if(clock>noticeUntil)$('notice').style.opacity='0';flash*=Math.exp(-realDt*6);$('crashFlash').style.opacity=flash;hudClock+=realDt;if(hudClock>.1){hud();hudClock=0;}if(gain){gain.gain.setTargetAtTime(sound&&state==='running'&&health>0?.024+(input.gas?.026:0):0,audioCtx.currentTime,.12);engineOsc.frequency.setTargetAtTime(30+Math.abs(forwardSpeed)*3+(input.gas?12:0),audioCtx.currentTime,.1);}renderer.render(scene,camera);}
requestAnimationFrame(frame);
// Read-only state inspection plus deterministic integration hooks for local development.
window.roadster={getState:()=>({state,health,distance,time,speed,forwardSpeed,position:{...chassis.position},partsLost:totalLost,attached:car.assemblies.filter(p=>p.userData.attached).map(p=>p.name),drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,checkpoint:passed,mode}),start,renderer,scene,camera};
if(location.hostname==='localhost'||location.hostname==='127.0.0.1')window.roadster.test={chassis,world,vehicle,obstacles,car,detach,explode,restore,recover,step:physics,setMode:v=>mode=v,setState:v=>state=v,teleport:(s,lane=0,v=0)=>{chassis.position.set(roadX(s)+lane,1,-s);chassis.quaternion.setFromEuler(0,heading(s),0);chassis.velocity.set(roadSlope(s)*v,0,-v);chassis.angularVelocity.setZero();chassis.wakeUp();syncCar();},input:keys};
}
