import * as C from './cannon-es.js';
import {buildNovelty} from './novelty-models.js?v=chaos-1';
import {installTouchGuard} from './touch-guard.js?v=chaos-1';
import {buildRoadster} from './roadster-model.js';
import {VEHICLES,buildSUV} from './garage-models.js?v=chaos-1';
import {createCrashDirector} from './crash-replay.js?v=chaos-1';
import {LOTS,buildLots,assessParking} from './parking-lots.js?v=chaos-1';
const T=window.THREE,$=id=>document.getElementById(id),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
installTouchGuard();
try{boot()}catch(e){console.error(e);$('fatal').hidden=false;$('errorText').textContent=e.message;}
function boot(){
const scene=new T.Scene();scene.background=new T.Color(0xb9c9bc);scene.fog=new T.Fog(0xb9c9bc,75,150);
const renderer=new T.WebGLRenderer({canvas:$('view'),antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
const camera=new T.PerspectiveCamera(54,1,.15,520);scene.add(new T.HemisphereLight(0xfff3d9,0x667d50,1.5));
const sun=new T.DirectionalLight(0xffdfaa,2.5);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-23,right:23,top:23,bottom:-23,near:1,far:120});sun.shadow.bias=-.0007;sun.shadow.normalBias=.035;scene.add(sun,sun.target);
const world=new C.World({gravity:new C.Vec3(0,-9.82,0),allowSleep:true});world.broadphase=new C.SAPBroadphase(world);world.solver.iterations=8;world.defaultContactMaterial.friction=.45;world.defaultContactMaterial.restitution=.12;
const groundMat=new C.Material('ground'),carMat=new C.Material('car');world.addContactMaterial(new C.ContactMaterial(carMat,groundMat,{friction:.35,restitution:.1}));
const ground=new C.Body({mass:0,material:groundMat,shape:new C.Plane()});ground.quaternion.setFromEuler(-Math.PI/2,0,0);ground.updateAABB();world.addBody(ground);
const palette={road:0x535956,grass:0x84986a,dirt:0xb5a27c,wood:0x776346,hay:0xc2a258,red:0x9d4638,stone:0x89908a,white:0xede5cf};
const mat=(c,r=.9)=>new T.MeshStandardMaterial({color:c,roughness:r});const mats=Object.fromEntries(Object.entries(palette).map(([k,c])=>[k,mat(c)]));
const unitBox=new T.BoxGeometry(1,1,1),unitSphere=new T.IcosahedronGeometry(1,1);
function visualBox(w,h,d,material,x=0,y=0,z=0){const m=new T.Mesh(unitBox,material);m.scale.set(w,h,d);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;return m;}
function boxBody(w,h,d,mass,x,y,z,quaternion=null){const b=new C.Body({mass,material:mass?carMat:groundMat,shape:new C.Box(new C.Vec3(w/2,h/2,d/2)),position:new C.Vec3(x,y,z)});if(quaternion)b.quaternion.copy(quaternion);world.addBody(b);return b;}
const lots=buildLots({T,C,scene,world,groundMat}),obstacles=lots.obstacles,loose=[],sparks=[];
let seed=842,totalLost=0,levelIndex=0,parkingHold=0,parkingState=null,bumps=0,lastDirection=0,reverseTravel=0,selectedGear=1;
let saves=[];try{saves=JSON.parse(localStorage.getItem('parkside-chaos-saves-v1')||'[]');if(!Array.isArray(saves))saves=[];}catch{}
function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
const baseComplete=()=>Array.from({length:8},(_,i)=>saves[i]?.stars>=1).every(Boolean),unlocked=i=>i<8||baseComplete();
const lot=()=>LOTS[levelIndex],view=()=>lots.views[levelIndex];
const garage=VEHICLES.map(config=>({config,...(config.id==='roadster'?buildRoadster(T):config.id==='santafe'?buildSUV(T,config.id):buildNovelty(T,config.id))}));
let vehicleIndex=0;try{vehicleIndex=Math.max(0,VEHICLES.findIndex(v=>v.id===localStorage.getItem('parkside-chaos-car')));}catch{}
let car=garage[vehicleIndex],spec=car.config;for(const item of garage){scene.add(item.root);item.root.visible=item===car;}
const chassis=new C.Body({mass:950,allowSleep:false,material:carMat,position:new C.Vec3(0,1.2,0),linearDamping:.025,angularDamping:.48});chassis.addShape(new C.Box(new C.Vec3(1.16,.26,2.28)),new C.Vec3(0,.05,0));world.addBody(chassis);
const vehicle=new C.RaycastVehicle({chassisBody:chassis,indexRightAxis:0,indexUpAxis:1,indexForwardAxis:2});
for(const z of [-1.48,1.45])for(const x of [-1.04,1.04])vehicle.addWheel({radius:.525,directionLocal:new C.Vec3(0,-1,0),axleLocal:new C.Vec3(-1,0,0),chassisConnectionPointLocal:new C.Vec3(x,-.04,z),suspensionStiffness:32,suspensionRestLength:.29,maxSuspensionTravel:.22,frictionSlip:3.4,dampingRelaxation:2.3,dampingCompression:4.4,maxSuspensionForce:90000,rollInfluence:.07,customSlidingRotationalSpeed:-25,useCustomSlidingRotationalSpeed:true});vehicle.addToWorld(world);
let wheelParts=vehicle.wheelInfos.map((w,i)=>car.assemblies.find(p=>p.name==='wheel-'+(i<2?'front':'rear')+'-'+(i%2?'left':'right')));
let mode='run',state='menu',health=100,time=0,distance=0,passed=0,speed=0,forwardSpeed=0,steer=0,cameraMode=0,clock=0,physicsTime=0,lastImpact=-10,flash=0,noticeUntil=0,countdown=0,deadTime=0,penalty=0,slow=false,wreckTime=0,pendingHit=null,pausedFrom='running';const keys={},touch={};let input={};
const camGoal=new T.Vector3(),camLook=new T.Vector3(),look=new T.Vector3(),carPos=new T.Vector3();let camInit=false;
const wheel=$('steeringWheel');let wheelAngle=0,wheelPointer=null,wheelLast=0;
const director=createCrashDirector({T,scene,camera,parts:car.assemblies,obstacles,onComplete:showWreck});
function wheelPolar(e){const r=wheel.getBoundingClientRect();return Math.atan2(e.clientX-r.left-r.width/2,-(e.clientY-r.top-r.height/2));}
wheel.addEventListener('pointerdown',e=>{if(state!=='running'&&state!=='countdown')return;if(wheelPointer!==null)return;e.preventDefault();wheelPointer=e.pointerId;wheelLast=wheelPolar(e);wheel.setPointerCapture(e.pointerId);resumeAudio();});
wheel.addEventListener('pointermove',e=>{if(e.pointerId!==wheelPointer)return;e.preventDefault();const a=wheelPolar(e);let delta=a-wheelLast;if(delta>Math.PI)delta-=Math.PI*2;if(delta<-Math.PI)delta+=Math.PI*2;wheelAngle=clamp(wheelAngle+delta*180/Math.PI,-135,135);wheelLast=a;paintWheel();});
function releaseWheel(e){if(e.pointerId===wheelPointer)wheelPointer=null;}
wheel.addEventListener('pointerup',releaseWheel);wheel.addEventListener('pointercancel',releaseWheel);wheel.addEventListener('lostpointercapture',releaseWheel);
function paintWheel(){const keyboard=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0);$('wheelArt').style.transform='rotate('+(keyboard?keyboard*95:wheelAngle)+'deg)';wheel.setAttribute('aria-valuenow',String(Math.round(wheelAngle)));}
function updateWheel(dt){if(wheelPointer===null)wheelAngle*=Math.exp(-dt*7);if(Math.abs(wheelAngle)<.05)wheelAngle=0;paintWheel();}
function notify(message,seconds=2){$('notice').textContent=message;noticeUntil=clock+seconds;$('notice').style.opacity='1';}
function syncCar(){car.root.position.copy(chassis.position);car.root.quaternion.copy(chassis.quaternion);car.root.position.add(new T.Vector3(0,-spec.offset,0).applyQuaternion(car.root.quaternion));car.root.updateMatrixWorld(true);for(let i=0;i<4;i++){const p=wheelParts[i];if(!p.userData.attached)continue;vehicle.updateWheelTransform(i);const t=vehicle.wheelInfos[i].worldTransform;const local=new T.Vector3().copy(t.position);car.root.worldToLocal(local);p.position.copy(local);p.quaternion.copy(car.root.quaternion).invert().multiply(new T.Quaternion().copy(t.quaternion));}}
function restore(){chassis.collisionResponse=true;chassis.collisionFilterMask=-1;for(const d of loose){world.removeBody(d.body);scene.remove(d.mesh)}loose.length=0;for(const p of car.assemblies){car.root.add(p);p.position.copy(p.userData.home);p.quaternion.identity();p.scale.set(1,1,1);p.userData.attached=true;p.visible=true;}for(const w of vehicle.wheelInfos){w.radius=spec.radius;w.suspensionStiffness=32;w.frictionSlip=3.4;}health=100;}
function detach(part,kick=0,all=false){if(!part||!part.userData.attached||(!all&&(part.name==='chassis'||part.name==='tub')))return;part.userData.attached=false;totalLost++;scene.attach(part);const sz=part.userData.size;const body=boxBody(clamp(sz.x,.12,2.3),clamp(sz.y,.12,1.4),clamp(sz.z,.12,2.6),part.name==='engine'?65:part.name==='chassis'?90:part.name==='tub'?45:part.name.startsWith('wheel')?25:12,part.position.x,part.position.y,part.position.z);body.quaternion.copy(part.quaternion);body.velocity.copy(chassis.velocity);const outward=new T.Vector3(part.position.x-chassis.position.x,0,part.position.z-chassis.position.z).normalize();body.velocity.x+=outward.x*kick*.7+(rand()-.5)*4;body.velocity.y+=1+rand()*3+kick*.27;body.velocity.z+=outward.z*kick*.7+(rand()-.5)*4;body.angularVelocity.set((rand()-.5)*8,(rand()-.5)*8,(rand()-.5)*8);body.collisionFilterGroup=2;body.collisionFilterMask=1;body.sleepSpeedLimit=.35;loose.push({mesh:part,body,age:0});let i=wheelParts.indexOf(part);if(i>=0){vehicle.wheelInfos[i].radius=.14;vehicle.wheelInfos[i].suspensionStiffness=8;vehicle.wheelInfos[i].frictionSlip=.4;}while(loose.length>64){const d=loose.shift();world.removeBody(d.body);scene.remove(d.mesh);}}
function burst(point,strength){for(let i=0;i<Math.min(18,5+strength);i++){const mesh=new T.Mesh(unitBox,new T.MeshBasicMaterial({color:i%2?0xffba56:0xfff4c5}));mesh.scale.set(.035,.035,.16);mesh.position.copy(point);scene.add(mesh);sparks.push({mesh,v:new T.Vector3((rand()-.5)*9,rand()*6,(rand()-.5)*9),life:.5+rand()*.5});}flash=Math.min(.65,strength/35);}
// Defer all body mutations until after the physics solver finishes its step.
chassis.addEventListener('collide',event=>{if(state!=='running'||physicsTime-lastImpact<.7)return;const impact=Math.abs(event.contact.getImpactVelocityAlongNormal());if(impact<.8||event.body.collisionFilterGroup===2)return;const kind=event.body.userData?.kind;if(event.body===ground&&impact<8)return;const cp=event.contact.bi===chassis?event.contact.ri:event.contact.rj;const point=new T.Vector3(chassis.position.x+cp.x,chassis.position.y+cp.y,chassis.position.z+cp.z);if(!pendingHit||impact>pendingHit.impact)pendingHit={impact,kind,point,velocity:new T.Vector3().copy(chassis.velocity)};});
function handleHit(hit){lastImpact=physicsTime;bumps++;parkingHold=0;const damage=clamp((hit.impact-2.7)*(hit.kind==='hay'?1.1:1.8),1,60);health=Math.max(0,health-damage);if(hit.impact>=6.5||health<=20){beginWreck(hit);return;}burst(hit.point,hit.impact);crashSound(hit.impact);const candidates=car.assemblies.filter(p=>p.userData.attached&&(p.name.startsWith('fender')||p.name.startsWith('pipes')||p.name==='grille'||p.name==='rear-bumper'));candidates.sort((a,b)=>a.getWorldPosition(new T.Vector3()).distanceToSquared(hit.point)-b.getWorldPosition(new T.Vector3()).distanceToSquared(hit.point));if(hit.impact>5)detach(candidates[0],2);notify('Scraped it — keep going',1.3);}
function beginWreck(hit){if(state==='wreck'||state==='replay'||state==='wreckReview')return;syncCar();director.record(physicsTime,true);const forward=hit.velocity.clone();forward.y=0;if(forward.length()<1)forward.set(0,0,-1).applyQuaternion(car.root.quaternion);forward.normalize();director.mark({point:hit.point,forward,speed:Math.max(hit.impact,hit.velocity.length())},physicsTime);state='wreck';wreckTime=0;clearInput();health=0;const kick=clamp(hit.impact*.42,6,13);for(const part of car.assemblies)detach(part,kick,true);chassis.collisionResponse=false;chassis.collisionFilterMask=0;document.body.classList.add('cinematic');$('replayHUD').hidden=false;$('replayTitle').textContent='WRECKED';$('replayAngle').textContent='REPLAY INCOMING';$('replayProgress').style.width='0%';$('impactStats').textContent=Math.round(Math.max(hit.impact,hit.velocity.length())*2.237)+' MPH / '+car.assemblies.length+' PARTS SCATTERED';$('skipReplay').textContent='Skip →';flash=.85;crashSound(35);}
function explode(){if(state!=='running')return;beginWreck({impact:25,point:new T.Vector3().copy(chassis.position),velocity:new T.Vector3().copy(chassis.velocity)});}
function startReplay(){state='replay';clearInput();$('wreckPanel').hidden=true;$('replayHUD').hidden=false;$('replayTitle').textContent='INSTANT REPLAY';$('skipReplay').textContent='Skip replay →';document.body.classList.add('cinematic');if(!director.begin())showWreck();}
function showWreck(){state='wreckReview';$('replayHUD').hidden=true;$('wreckPanel').hidden=false;const info=director.getImpact();$('wreckSpeed').textContent=Math.round((info?.speed||0)*2.237);$('wreckParts').textContent=car.assemblies.filter(p=>!p.userData.attached).length;$('wreckPenalty').textContent='Retry this parking challenge';}
function continueWreck(){start();}
$('skipReplay').onclick=()=>{director.stop();showWreck();};$('continueWreck').onclick=continueWreck;$('watchAgain').onclick=startReplay;
function recover(initial=false){pendingHit=null;director.reset();restore();const [x,z,yaw]=lot().spawn;chassis.position.set(view().ox+x,Math.max(1.05,spec.offset+.2),z);chassis.quaternion.setFromEuler(0,yaw,0);chassis.velocity.setZero();chassis.angularVelocity.setZero();chassis.force.setZero();chassis.torque.setZero();chassis.aabbNeedsUpdate=true;chassis.wakeUp();for(let i=0;i<4;i++){const w=vehicle.wheelInfos[i];w.rotation=0;w.deltaRotation=0;w.suspensionLength=.29;vehicle.applyEngineForce(0,i);vehicle.setBrake(0,i);}steer=0;wheelAngle=0;parkingHold=0;lastDirection=0;reverseTravel=0;selectedGear=1;lastImpact=physicsTime+.4;camInit=false;orbitMode='follow';paintCamera();orbitPitch=.52;orbitDistance=13;clearInput();if(!initial){bumps++;penalty+=10;notify('Reset to the entrance · +10s');}syncCar();}
function loadLevel(i){i=clamp(i,0,LOTS.length-1);if(!unlocked(i))return false;levelIndex=i;lots.show(levelIndex);scene.background.setHex(lot().theme);scene.fog.color.setHex(lot().theme);recover(true);renderLots();return true;}
function start(){if(!unlocked(levelIndex))return;document.body.classList.add('playing');director.reset();document.body.classList.remove('cinematic');$('replayHUD').hidden=true;$('wreckPanel').hidden=true;time=0;totalLost=0;penalty=0;bumps=0;deadTime=0;recover(true);state='running';$('intro').hidden=true;$('finish').hidden=true;$('pausePanel').hidden=true;$('hud').hidden=false;$('touch').hidden=false;$('cameraTools').hidden=false;$('explodeButton').hidden=true;notify(spec.noBrakes?'NO BRAKES — coast or select the opposite gear + GAS to slow down.':lot().hint,spec.noBrakes?6:4);resumeAudio();}
function finish(){const bonusWasUnlocked=baseComplete();document.body.classList.remove('playing');state='ended';clearInput();$('touch').hidden=true;$('cameraTools').hidden=true;$('finish').hidden=false;const elapsed=time+penalty,stars=bumps===0&&elapsed<=lot().par?3:bumps<=2?2:1;const previous=saves[levelIndex];if(!previous||stars>previous.stars||(stars===previous.stars&&elapsed<previous.time))saves[levelIndex]={stars,time:Math.round(elapsed)};try{localStorage.setItem('parkside-chaos-saves-v1',JSON.stringify(saves))}catch{}$('finishTag').textContent='BAY '+lot().code+' / PARKED';$('finishTitle').textContent=stars===3?'Perfect parking.':'Nicely parked.';$('resultDistance').textContent='★'.repeat(stars)+'☆'.repeat(3-stars);$('resultTime').textContent=Math.round(elapsed);$('resultParts').textContent=bumps;$('best').textContent=stars===3?'Clean, accurate and on time.':'For three stars: no bumps, within '+lot().par+' seconds.';const bonusNow=baseComplete();if(!bonusWasUnlocked&&bonusNow){$('finishTag').textContent='BONUS 8 UNLOCKED';$('best').textContent='Lots 9–16 are open. The chaos chapter begins.';}const next=nextLevel();$('nextLot').textContent=next===null?'Choose a lot':!bonusWasUnlocked&&bonusNow?'Enter bonus lots →':'Next lot →';renderLots();}

function nextLevel(){if(levelIndex<8&&baseComplete())return 8;if(levelIndex===7)return Array.from({length:8},(_,i)=>i).find(i=>!saves[i]?.stars)??null;return levelIndex<LOTS.length-1?levelIndex+1:null;}

function paintGear(){document.querySelectorAll('[data-gear]').forEach(b=>{const active=Number(b.dataset.gear)===selectedGear;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});}
function configureVehicle(){
 chassis.mass=spec.mass;while(chassis.shapes.length)chassis.removeShape(chassis.shapes[0]);chassis.addShape(new C.Box(new C.Vec3(...spec.box)),new C.Vec3(0,spec.center,0));chassis.updateMassProperties();chassis.updateBoundingRadius();chassis.aabbNeedsUpdate=true;
 vehicle.wheelInfos.forEach((w,i)=>{w.radius=spec.radius;w.chassisConnectionPointLocal.set(i%2?spec.track:-spec.track,-.04,i<2?spec.front:spec.rear);});
 wheelParts=vehicle.wheelInfos.map((w,i)=>car.assemblies.find(p=>p.name==='wheel-'+(i<2?'front':'rear')+'-'+(i%2?'left':'right')));
 director.setParts(car.assemblies);
 const brakeButton=document.querySelector('[data-input=brake]'),holdButton=document.querySelector('[data-input=handbrake]');for(const b of [brakeButton,holdButton]){b.disabled=!!spec.noBrakes;b.classList.toggle('broken',!!spec.noBrakes);}brakeButton.querySelector('span').textContent=spec.noBrakes?'BROKEN':'BRAKE';holdButton.querySelector('span').textContent=spec.noBrakes?'Broken':'Hold';
}
function selectVehicle(i){
 if(state!=='menu'||!garage[i])return;director.reset();restore();car.root.visible=false;vehicleIndex=i;car=garage[i];spec=car.config;car.root.visible=true;configureVehicle();recover(true);
 try{localStorage.setItem('parkside-chaos-car',spec.id);}catch{}renderGarage();
}
function vehicleThumbnail(item){
 if(item.thumbnail)return item.thumbnail;
 const preview=new T.Scene();preview.background=new T.Color(0x243b3a);preview.add(new T.HemisphereLight(0xf7faf2,0x6e8d89,2.6));const light=new T.DirectionalLight(0xffebcd,3);light.position.set(-3,6,-4);preview.add(light);
 const model=item.root.clone(true);model.position.set(0,-.6,0);model.quaternion.identity();model.visible=true;preview.add(model);const cam=new T.PerspectiveCamera(36,1.8,.1,40);cam.position.set(-4.2,2.9,-5.5);cam.lookAt(0,.5,0);
 renderer.setSize(252,140,false);renderer.render(preview,cam);item.thumbnail=renderer.domElement.toDataURL('image/png');resize();return item.thumbnail;
}
function renderGarage(){const wrap=$('garage');wrap.replaceChildren();garage.forEach((item,i)=>{const b=document.createElement('button');b.className='car-card'+(i===vehicleIndex?' selected':'');b.setAttribute('aria-pressed',String(i===vehicleIndex));b.setAttribute('aria-label','Choose '+item.config.name);const img=document.createElement('img');img.src=vehicleThumbnail(item);img.alt='';b.append(img);const name=document.createElement('b');name.textContent=item.config.name;b.append(name);const label=document.createElement('small');label.textContent=item.config.detail;b.append(label);b.onclick=()=>selectVehicle(i);wrap.append(b);});}

function renderLots(){const wrap=$('lotList');wrap.replaceChildren();const bonus=baseComplete();LOTS.forEach((l,i)=>{if(i===8){const d=document.createElement('div');d.className='bonus-divider'+(bonus?' open':'');d.innerHTML='<b>'+(bonus?'BONUS 8 UNLOCKED':'BONUS 8 LOCKED')+'</b><span>'+(bonus?'Eight new parking nightmares await.':saves.slice(0,8).filter(x=>x?.stars).length+' / 8 original lots complete')+'</span>';wrap.append(d);}const locked=!unlocked(i),b=document.createElement('button');b.className='lot-card'+(i===levelIndex?' selected':'')+(locked?' locked':'');b.disabled=locked;b.innerHTML='<span class="lot-num">'+String(i+1).padStart(2,'0')+'</span><span><b>'+l.name+'</b><small>'+(locked?'Finish lots 1–8 to unlock':l.kind)+'</small></span><em>'+(locked?'🔒':('★'.repeat(saves[i]?.stars||0)||'—'))+'</em>';b.onclick=()=>loadLevel(i);wrap.append(b);});$('start').disabled=!unlocked(levelIndex);$('start').textContent=unlocked(levelIndex)?'Drive '+lot().name+' →':'Complete the original eight';}
function openMenu(){document.body.classList.remove('playing');state='menu';clearInput();$('finish').hidden=true;$('pausePanel').hidden=true;$('intro').hidden=false;$('hud').hidden=true;$('touch').hidden=true;$('cameraTools').hidden=true;recover(true);renderLots();}
function pause(){if(state==='running'||state==='countdown'){pausedFrom=state;state='paused';clearInput();$('pausePanel').hidden=false;$('touch').hidden=true;}else if(state==='paused'){state=pausedFrom;$('pausePanel').hidden=true;$('touch').hidden=false;}}
function clearInput(){if(typeof cameraPointers!=='undefined')cameraPointers.clear();wheelPointer=null;wheelAngle=0;paintWheel();for(const k in keys)delete keys[k];for(const k in touch)delete touch[k];document.querySelectorAll('.pressed').forEach(b=>b.classList.remove('pressed'));}
$('start').onclick=start;$('again').onclick=start;$('restart').onclick=start;$('resume').onclick=pause;$('pauseButton').onclick=pause;$('cameraButton').onclick=()=>setCamera(orbitMode==='follow'?'back':orbitMode==='back'?'top':'follow');$('recover').onclick=()=>{if(state==='paused')pause();if(state==='running')recover()};$('menu').onclick=openMenu;$('pauseMenu').onclick=openMenu;$('nextLot').onclick=()=>{const next=nextLevel();if(next===null)openMenu();else if(loadLevel(next))start();};for(const b of document.querySelectorAll('[data-gear]'))b.onclick=()=>{selectedGear=Number(b.dataset.gear);paintGear();};$('explodeButton').onclick=()=>{pause();explode()};
window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();keys[e.code]=true;if(e.repeat)return;if(e.code==='KeyP'||e.code==='Escape'){if(state==='replay'||state==='wreck'){director.stop();showWreck();}else pause();}if(e.code==='KeyC')setCamera(orbitMode==='follow'?'back':orbitMode==='back'?'top':'follow');if(e.code==='KeyX')selectedGear*=-1;if(e.code==='KeyR'&&state==='running')recover();if(e.code==='KeyE'&&mode==='sandbox'&&state==='running')explode();});window.addEventListener('keyup',e=>delete keys[e.code]);
for(const b of document.querySelectorAll('[data-input]')){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);touch[b.dataset.input]=true;b.classList.add('pressed');resumeAudio()});const release=()=>{touch[b.dataset.input]=false;b.classList.remove('pressed')};b.addEventListener('pointerup',release);b.addEventListener('pointercancel',release);b.addEventListener('lostpointercapture',release);}
window.addEventListener('blur',()=>{clearInput();if(state==='running'||state==='countdown')pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();if(state==='running'||state==='countdown')pause()}});
let audioCtx,engineOsc,gain,sound=false;function resumeAudio(){if(sound){if(!audioCtx){audioCtx=new(window.AudioContext||window.webkitAudioContext)();engineOsc=audioCtx.createOscillator();engineOsc.type='sawtooth';gain=audioCtx.createGain();gain.gain.value=0;const filter=audioCtx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=480;engineOsc.connect(filter).connect(gain).connect(audioCtx.destination);engineOsc.start();}audioCtx.resume().catch(()=>{});}}
$('sound').onclick=()=>{sound=!sound;$('sound').classList.toggle('active',sound);$('sound').setAttribute('aria-pressed',String(sound));$('sound').querySelector('span').textContent=sound?'Sound on':'Sound off';resumeAudio();};function crashSound(n){if(!sound||!audioCtx)return;const count=audioCtx.sampleRate*.22,buffer=audioCtx.createBuffer(1,count,audioCtx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<count;i++)data[i]=(Math.random()*2-1)*(1-i/count);const src=audioCtx.createBufferSource(),g=audioCtx.createGain();g.gain.value=Math.min(.35,n*.012);src.buffer=buffer;src.connect(g).connect(audioCtx.destination);src.start();if(n>=30){const bass=audioCtx.createOscillator(),boom=audioCtx.createGain();bass.type='triangle';bass.frequency.setValueAtTime(135,audioCtx.currentTime);bass.frequency.exponentialRampToValueAtTime(28,audioCtx.currentTime+.8);boom.gain.setValueAtTime(.45,audioCtx.currentTime);boom.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+1.1);bass.connect(boom).connect(audioCtx.destination);bass.start();bass.stop(audioCtx.currentTime+1.2);}}
function physics(dt){physicsTime+=dt;input={gas:keys.KeyW||keys.ArrowUp||touch.gas,brake:keys.KeyS||keys.ArrowDown||touch.brake,left:keys.KeyA||keys.ArrowLeft||touch.left,right:keys.KeyD||keys.ArrowRight||touch.right,handbrake:keys.Space||touch.handbrake};const active=state==='running';if(spec.noBrakes)input.handbrake=false;const fwd=chassis.quaternion.vmult(new C.Vec3(0,0,-1));forwardSpeed=chassis.velocity.dot(fwd);speed=chassis.velocity.length();const off=Math.abs(chassis.position.x-view().ox)>23||Math.abs(chassis.position.z)>23;const axis=(input.left?1:0)-(input.right?1:0)||-wheelAngle/135;const desired=active?axis*(.69/(1+speed*.025)):0;steer+=(desired-steer)*Math.min(1,dt*10);vehicle.setSteeringValue(steer,0);vehicle.setSteeringValue(steer,1);
 let engine=0,brake=spec.noBrakes?0:active?3:45;const motor=car.assemblies.find(p=>p.name==='engine').userData.attached;
 const desiredGear=keys.KeyW||keys.ArrowUp?1:keys.KeyS||keys.ArrowDown?-1:selectedGear;
 const throttle=keys.KeyW||keys.ArrowUp||keys.KeyS||keys.ArrowDown||touch.gas;
 if(active&&health>0&&motor){if(spec.noBrakes){if(throttle)engine=desiredGear*(forwardSpeed*desiredGear<0||Math.abs(forwardSpeed)<(desiredGear>0?(spec.maxSpeed||8):4)?spec.power:0);}else if(touch.brake||input.handbrake)brake=40;else if(throttle){if(forwardSpeed*desiredGear<-.3)brake=32;else{engine=desiredGear*(Math.abs(forwardSpeed)<(desiredGear>0?(spec.maxSpeed||8):4)?spec.power:0);brake=0;}}}
 for(let i=0;i<4;i++){const attached=wheelParts[i].userData.attached;vehicle.applyEngineForce(i>=2&&attached?engine:0,i);vehicle.setBrake(spec.noBrakes?0:(input.handbrake&&active&&i>=2?70:brake)*spec.mass/950,i);vehicle.wheelInfos[i].frictionSlip=attached?(off?1.8:input.handbrake&&i>=2?1.05:3.8):.4;}
 if(off&&speed>0){chassis.applyForce(chassis.velocity.scale(-40),new C.Vec3());}else if(speed>0){chassis.applyForce(chassis.velocity.scale(-8-speed*.6),new C.Vec3());}
 world.step(1/60,dt,5);syncCar();if(pendingHit){const hit=pendingHit;pendingHit=null;handleHit(hit);}
 if(active&&state==='running'){time+=dt;forwardSpeed=chassis.velocity.dot(chassis.quaternion.vmult(new C.Vec3(0,0,-1)));speed=chassis.velocity.length();if(Math.abs(forwardSpeed)>.3)lastDirection=forwardSpeed>0?1:-1;
 const bayDistance=Math.hypot(chassis.position.x-view().ox-lot().target.x,chassis.position.z-lot().target.z);if(bayDistance>8)reverseTravel=0;else if(forwardSpeed<-.4)reverseTravel+=-forwardSpeed*dt;
 const f=chassis.quaternion.vmult(new C.Vec3(0,0,-1)),up=chassis.quaternion.vmult(new C.Vec3(0,1,0));parkingState=assessParking({x:chassis.position.x-view().ox,z:chassis.position.z,yaw:Math.atan2(-f.x,-f.z),halfWidth:spec.halfWidth||1.27,halfLength:spec.halfLength||2.4,speed,up:up.y,lastDirection:lot().target.reverse?(reverseTravel>.35?-1:0):lastDirection},lot().target);
 if(parkingState.valid&&physicsTime-lastImpact>.8)parkingHold+=dt;else parkingHold=0;if(parkingHold>=1.35)finish();
 if(chassis.position.y<-8||Math.abs(chassis.position.x-view().ox)>50||Math.abs(chassis.position.z)>50)recover();}
 for(const o of obstacles){o.mesh.position.copy(o.body.position);o.mesh.quaternion.copy(o.body.quaternion);}for(const d of loose){d.age+=dt;if(d.age>.45)d.body.collisionFilterMask=3;d.mesh.position.copy(d.body.position);d.mesh.quaternion.copy(d.body.quaternion);}for(let i=sparks.length-1;i>=0;i--){const p=sparks[i];p.life-=dt;p.v.y-=9.8*dt;p.mesh.position.addScaledVector(p.v,dt);if(p.life<0){scene.remove(p.mesh);p.mesh.material.dispose();sparks.splice(i,1);}}
 if(state==='running'||state==='wreck')director.record(physicsTime);if(state==='wreck'){wreckTime+=dt;director.renderEffects(wreckTime);$('replayProgress').style.width=Math.min(100,wreckTime/2.4*100)+'%';if(wreckTime>=2.4)startReplay();}
}
const mapCtx=$('map').getContext('2d');function hud(){
 $('speed').textContent=Math.round(Math.abs(forwardSpeed)*2.237);$('distance').textContent=(levelIndex+1)+' / '+LOTS.length+' · '+lot().code;$('timer').textContent=Math.floor((time+penalty)/60)+':'+String(Math.floor((time+penalty)%60)).padStart(2,'0');$('progress').style.width=Math.min(100,parkingHold/1.35*100)+'%';$('healthBar').style.width=health+'%';$('condition').textContent=bumps+' bump'+(bumps===1?'':'s');$('gear').textContent=(forwardSpeed<-.3?'R':forwardSpeed>.3?'D':selectedGear===1?'D':'R')+' · '+lot().kind.toUpperCase();paintGear();
 const p=parkingState;let hint='Park in '+lot().code+' · '+lot().kind;if(p?.near){hint=!p.contained?'Get all four corners inside':!p.aligned?'Face the bay’s arrow':!p.approach?'Back into this space in R':!p.stopped?(spec.noBrakes?'Coast or use opposite gear to stop':'Brake to a complete stop'):'Hold still…';}if(state==='ended')hint='Parked!';$('parkingHelp').textContent=hint;
 view().marker.fill.material.opacity=.18+(Math.sin(clock*3)+1)*.05;view().marker.fill.material.color.setHex(parkingHold>0?0xd3f59f:0x74e6ab);view().beacon.quaternion.copy(camera.quaternion);
 const c=mapCtx;c.clearRect(0,0,168,230);c.fillStyle='#536660';c.fillRect(8,35,152,152);const scale=152/48,xy=(x,z)=>[84+x*scale,111+z*scale];for(const m of view().mini){const [x,y]=xy(m.x,m.z);c.save();c.translate(x,y);c.rotate(-m.yaw);c.fillStyle=m.color;c.fillRect(-m.w*scale/2,-m.d*scale/2,m.w*scale,m.d*scale);c.restore();}const t=lot().target,[tx,ty]=xy(t.x,t.z);c.save();c.translate(tx,ty);c.rotate(-t.yaw);c.fillStyle='#a4f3ad';c.fillRect(-t.w*scale/2,-t.d*scale/2,t.w*scale,t.d*scale);c.restore();const [x,y]=xy(chassis.position.x-view().ox,chassis.position.z),f=chassis.quaternion.vmult(new C.Vec3(0,0,-1));c.save();c.translate(x,y);c.rotate(-Math.atan2(-f.x,-f.z));c.fillStyle='#fff4d7';c.beginPath();c.moveTo(0,-7);c.lineTo(-4,5);c.lineTo(4,5);c.closePath();c.fill();c.restore();c.fillStyle='#fff4d7';c.font='bold 11px system-ui';c.textAlign='center';c.fillText(lot().name,84,19);
 updateGuides();}
let orbitYaw=0,orbitPitch=.52,orbitDistance=13,orbitMode='follow',pinchLast=0;const cameraPointers=new Map(),canvas=$('view');
function paintCamera(){document.querySelectorAll('[data-camera]').forEach(b=>{const active=b.dataset.camera===orbitMode;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});}
function setCamera(m){orbitMode=m;paintCamera();orbitPitch=m==='top'?1.43:.52;orbitDistance=m==='top'?18:13;camInit=false;}
for(const b of document.querySelectorAll('[data-camera]'))b.onclick=()=>setCamera(b.dataset.camera);
canvas.addEventListener('pointerdown',e=>{if(!['running','paused','menu'].includes(state))return;canvas.setPointerCapture(e.pointerId);cameraPointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(cameraPointers.size===2){const [a,b]=[...cameraPointers.values()];pinchLast=Math.hypot(a.x-b.x,a.y-b.y);}});
canvas.addEventListener('pointermove',e=>{const old=cameraPointers.get(e.pointerId);if(!old)return;const dx=e.clientX-old.x,dy=e.clientY-old.y;cameraPointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(cameraPointers.size===2){const [a,b]=[...cameraPointers.values()],d=Math.hypot(a.x-b.x,a.y-b.y);orbitDistance=clamp(orbitDistance*pinchLast/Math.max(1,d),6,29);pinchLast=d;}else{orbitMode='orbit';paintCamera();orbitYaw-=dx*.009;orbitPitch=clamp(orbitPitch+dy*.006,.25,1.48);}});
for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,e=>cameraPointers.delete(e.pointerId));
canvas.addEventListener('wheel',e=>{e.preventDefault();orbitDistance=clamp(orbitDistance+e.deltaY*.014,6,29);},{passive:false});
const guideGeometry=new T.BufferGeometry(),guidePositions=new Float32Array(2*19*2*3);guideGeometry.setAttribute('position',new T.BufferAttribute(guidePositions,3));const guides=new T.LineSegments(guideGeometry,new T.LineBasicMaterial({color:0xf4d686,transparent:true,opacity:.8,depthTest:false}));guides.frustumCulled=false;guides.renderOrder=3;scene.add(guides);
function updateGuides(){guides.visible=state==='running'&&(selectedGear===-1||forwardSpeed<-.2);if(!guides.visible)return;let k=0;const q=new T.Quaternion().copy(chassis.quaternion);for(const side of [-1,1])for(let i=0;i<19;i++)for(let j=0;j<2;j++){let d=2.5+(i+j)*.22;const p=new T.Vector3(side*1.25-Math.tan(steer)*d*d/5.86,0,d).applyQuaternion(q);guidePositions[k++]=chassis.position.x+p.x;guidePositions[k++]=.065;guidePositions[k++]=chassis.position.z+p.z;}guideGeometry.attributes.position.needsUpdate=true;}
function updateCamera(dt){if(state==='replay'||state==='wreckReview')return;carPos.copy(chassis.position);if(state==='wreck'){look.set(0,0,0);for(const p of car.assemblies)look.add(p.position);look.multiplyScalar(1/car.assemblies.length);camGoal.copy(look).add(new T.Vector3(11,8,11));}else{const forward=chassis.quaternion.vmult(new C.Vec3(0,0,-1));const yaw=Math.atan2(-forward.x,-forward.z);if(orbitMode!=='orbit')orbitYaw=yaw+(orbitMode==='back'?Math.PI:0);const d=orbitDistance*(camera.aspect<.8?1.18:1);look.copy(carPos);look.y+=.35;camGoal.set(look.x+Math.sin(orbitYaw)*Math.cos(orbitPitch)*d,look.y+Math.sin(orbitPitch)*d,look.z+Math.cos(orbitYaw)*Math.cos(orbitPitch)*d);}
 if(!camInit){camera.position.copy(camGoal);camLook.copy(look);camInit=true;}else{camera.position.lerp(camGoal,1-Math.exp(-dt*9));camLook.lerp(look,1-Math.exp(-dt*9));}camera.lookAt(camLook);camera.fov=54;camera.updateProjectionMatrix();sun.position.set(chassis.position.x-20,45,chassis.position.z+15);sun.target.position.copy(chassis.position);}
function resize(){if(wheelPointer!==null)clearInput();renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();camInit=false;}window.addEventListener('resize',resize);resize();configureVehicle();renderGarage();loadLevel(0);$('start').disabled=false;renderLots();
$('view').addEventListener('webglcontextlost',e=>{e.preventDefault();if(state==='running')pause();$('fatal').hidden=false;$('errorText').textContent='The graphics context was interrupted. Reload to resume.';});
let last=performance.now(),hudClock=0;function frame(now){requestAnimationFrame(frame);const realDt=Math.min(.06,(now-last)/1000);last=now;if(document.hidden)return;clock+=realDt;updateWheel(realDt);slow=state==='running'&&(keys.ShiftLeft||keys.ShiftRight||touch.slow);$('slowBadge').hidden=!slow;const dt=realDt*(slow?.24:1);if(state==='countdown'){countdown-=realDt;if(countdown<=0){state='running';notify('Go!',1);}}
 if(state==='running'||state==='countdown'||state==='menu'||state==='wreck')physics(dt);else if(state==='replay')director.update(realDt);else if(state!=='wreckReview')syncCar();updateCamera(realDt);if(clock>noticeUntil)$('notice').style.opacity='0';flash*=Math.exp(-realDt*6);$('crashFlash').style.opacity=flash;hudClock+=realDt;if(hudClock>.1){hud();hudClock=0;}if(gain){gain.gain.setTargetAtTime(sound&&state==='running'&&health>0?.024+(input.gas?.026:0):0,audioCtx.currentTime,.12);engineOsc.frequency.setTargetAtTime(30+Math.abs(forwardSpeed)*3+(input.gas?12:0),audioCtx.currentTime,.1);}renderer.render(scene,camera);}
requestAnimationFrame(frame);
// Read-only state inspection plus deterministic integration hooks for local development.
window.roadster={getState:()=>({state,health,distance,time,speed,forwardSpeed,position:{...chassis.position},vehicle:spec.id,partsLost:totalLost,attached:car.assemblies.filter(p=>p.userData.attached).map(p=>p.name),drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,level:levelIndex,bonusUnlocked:baseComplete(),noBrakes:!!spec.noBrakes,parking:parkingState,parkingHold,bumps,gear:selectedGear,orbitMode,orbitYaw,mode,steering:steer,wheelAngle,replay:director.getInfo()}),start,renderer,scene,camera};
if(location.hostname==='localhost'||location.hostname==='127.0.0.1')window.roadster.test={chassis,world,vehicle,obstacles,get car(){return car;},selectVehicle,detach,explode,restore,recover,step:physics,loadLevel,assessParking,setCamera,setGear:v=>selectedGear=v,director,continueWreck,startReplay,updateWheel,setMode:v=>mode=v,setState:v=>state=v,teleport:(x,z,yaw=0,v=0)=>{chassis.position.set(view().ox+x,1,z);chassis.quaternion.setFromEuler(0,yaw,0);const f=chassis.quaternion.vmult(new C.Vec3(0,0,-1));chassis.velocity.set(f.x*v,0,f.z*v);chassis.angularVelocity.setZero();chassis.aabbNeedsUpdate=true;chassis.wakeUp();syncCar();},input:keys};
}
