import assert from 'node:assert/strict';
import {bootGame} from './helpers/game.mjs';
const {app,context,get,frame,setPads}=await bootGame(),t=app.test,life=t.streetLife,h=life.hulk,crowd=t.crowd,C=context.C;
t.loadLevel(24);app.start();t.setState('running');t.teleport(0,190);assert(!h.toggle());assert(life.exitVehicle());t.setFootCamera(0,.28);
function target(x=0,z=174){crowd.reset(24,6000,{count:1,routes:[{x0:x,x1:x+8,z0:z,z1:z+8}]});life.body.position.set(6000+x,1.05,z+1.5);life.body.velocity.setZero();return crowd.people[0];}
let p=target();get('hulkButton').click();assert(h.active);life.beforeStep(.4,{},{});life.ui();assert.equal(get('fireButton').textContent,'GRAB');assert(get('weaponButton').hidden);assert(life.interact());assert.equal(crowd.held,p);assert(p.bodies.every(b=>b.type===C.Body.KINEMATIC&&!b.collisionResponse));const bodies=t.world.bodies.length,constraints=t.world.constraints.length;
const old=p.pose[0].p.clone();for(let i=0;i<90;i++){life.beforeStep(1/60,{KeyD:true},{});t.world.step(1/60);crowd.beforeStep(1/60,false);crowd.afterStep(1/60,true);life.afterStep();}assert(life.body.position.x>6001);assert(p.pose[0].p.distanceTo(old)>2);crowd.afterStep(12,true);assert.equal(crowd.held,p);assert(p.bodies);assert.equal(t.world.bodies.length,bodies);assert.equal(t.world.constraints.length,constraints);
t.setCamera('first');frame();const projected=p.pose[0].p.clone().project(app.camera);assert(Math.abs(projected.x)<1&&Math.abs(projected.y)<1&&projected.z<1&&projected.z>0);assert(life.cameraTarget().y>life.body.position.y+1);t.setFootCamera(0,.28);life.ui();assert.equal(get('fireButton').textContent,'THROW');assert(!get('ripButton').hidden);
// A single held RT/Space press cannot immediately grab then auto-throw.
h.pollUse(false);h.pollUse(true);assert(!crowd.held);life.beforeStep(.6,{},{});life.body.position.copy(p.pose[0].p);life.body.position.z+=1;assert(h.use());const held=p;for(let i=0;i<60;i++)h.pollUse(true);assert.equal(crowd.held,held);h.pollUse(false);h.drop();
// Throwing into an actual destructible facade damages it through real physics.
const wall=t.secretView.buildings.find(b=>b.type==='convenience').target.entries.find(e=>e.foundation&&e.size[2]<1&&e.size[0]>2);p=target(wall.home.x-6000,wall.home.z+2);t.setFootCamera(0,.28);life.beforeStep(.5,{},{});assert(h.use());life.beforeStep(.5,{},{});assert(h.use());assert(!crowd.held);assert(p.bodies.every(b=>b.type===C.Body.DYNAMIC&&b.collisionResponse));for(let i=0;i<120;i++)t.step(1/60);assert(wall.damage>0,'Thrown pedestrian failed to damage facade');assert(p.throwHit);
// Cartoon split disconnects only the waist: two closed, clothed articulated groups.
p=target();life.beforeStep(.5,{},{});assert(h.use());life.beforeStep(.5,{},{});const waist=p.constraints[0],beforeBodies=t.world.bodies.length;get('ripButton').click();assert(p.split&&!p.held);assert.equal(p.constraints.length,5);assert(!t.world.constraints.includes(waist));assert.equal(t.world.bodies.length,beforeBodies);assert(h.getInfo().puffVisible);assert(!crowd.grab(p));for(let i=0;i<120;i++)t.step(1/60);assert(p.pose[0].p.distanceTo(p.pose[1].p)>.6);const snapshot=crowd.snapshot();crowd.apply(snapshot,snapshot,0);assert(p.split);assert(!h.getInfo().puffVisible);
// Previously frozen pedestrians can be carried again without another score credit.
p=target();crowd.strike(p.sensor,p.pose[0].p,100,'hammer');crowd.afterStep(12,true);assert(!p.bodies);const hits=crowd.getInfo().hits;life.body.position.set(p.pose[0].p.x,1.05,p.pose[0].p.z+1);life.beforeStep(.5,{},{});assert(h.use());assert.equal(crowd.getInfo().hits,hits);h.drop();
// Pause preserves carry but cannot throw or split; entering a building drops and calms.
p=target();life.beforeStep(.5,{},{});assert(h.use());t.setState('paused');assert(!h.use());assert(!h.split());assert.equal(crowd.held,p);t.setState('running');h.drop();const store=t.secretView.buildings.find(b=>b.type==='convenience');life.body.position.set(store.door.x+store.door.nx*.6,1.05,store.door.z+store.door.nz*.6);assert(life.enterBuilding(store));assert(!h.active);assert(!h.toggle());assert(life.leaveBuilding());
// Real Xbox button edges: D-pad down toggles, RT grabs/throws, LT splits, X drops.
p=target();const pad={index:0,id:'Xbox Wireless Controller',mapping:'standard',connected:true,axes:[0,0,0,0],buttons:Array.from({length:17},()=>({value:0,pressed:false}))};setPads([pad]);frame();function press(i,value=1){pad.buttons[i]={value,pressed:value>.5};frame();}press(13);assert(h.active);press(13,0);for(let i=0;i<25;i++)frame();press(7);assert(crowd.held);for(let i=0;i<35;i++)frame();assert(crowd.held);press(7,0);press(6);assert(p.split);press(6,0);assert(!crowd.held);
p=target();for(let i=0;i<35;i++)frame();press(7);assert(crowd.held);press(7,0);press(2);assert(!crowd.held);press(2,0);setPads([]);frame();t.setState('running');
// Budget retirement never rejoins the split or leaves its halves floating.
crowd.reset(24,6000,{count:40,routes:[{x0:0,x1:8,z0:174,z1:182}]});const retired=crowd.people[0];assert(crowd.grab(retired));crowd.carry(new C.Vec3(6000,3,174),0);assert(crowd.releaseHeld(new C.Vec3(0,8,-7),true));for(const person of crowd.people.slice(1))crowd.strike(person.sensor,person.pose[0].p,100,'hammer');assert(!retired.bodies&&retired.split);assert(retired.pose[0].p.y<.85&&retired.pose[1].p.y<.85);assert(retired.pose[0].p.distanceTo(retired.pose[1].p)>.8);
// A thrown pedestrian can knock down a new target when the ragdoll pool is already full.
const stressRoute={x0:0,x1:8,z0:174,z1:182};crowd.reset(24,6000,{count:40,routes:[stressRoute]});const source=crowd.people[0],victim=crowd.people[16];assert(crowd.grab(source));for(const person of crowd.people.slice(1,16)){crowd.strike(person.sensor,person.pose[0].p,100,'hammer');for(const b of person.bodies){b.position.x+=100;b.position.z+=60;b.aabbNeedsUpdate=true;}}victim.route={x0:0,x1:8,z0:172,z1:180};victim.distance=0;crowd.beforeStep(0,false);crowd.carry(new C.Vec3(6000,1.15,175),0);assert(crowd.releaseHeld(new C.Vec3(0,0,-25)));for(let i=0;i<24&&!victim.down;i++)t.step(1/60);assert(victim.down);assert(source.bodies);assert.equal(crowd.getInfo().activeRagdolls,16);
// Stress includes one held ragdoll inside the same 16-actor limit.
crowd.reset(24,6000,{count:40,routes:[{x0:0,x1:8,z0:174,z1:182}]});p=crowd.people[0];assert(crowd.grab(p));for(const person of crowd.people.slice(1))crowd.strike(person.sensor,person.pose[0].p,100,'hammer');assert.equal(crowd.getInfo().activeRagdolls,16);assert.equal(crowd.held,p);assert.equal(h.getInfo().puffMeshes,8);life.reset();assert(!h.active&&!crowd.held);crowd.reset(24,6000,{count:40,routes:[{x0:0,x1:8,z0:174,z1:182}]});assert.equal(t.world.constraints.filter(c=>c.bodyA.userData?.kind==='pedestrian').length,0);assert(crowd.people.every(p=>!p.split&&!p.held));
console.log(JSON.stringify({carry:'Hulk touch/first-person, walking, held RT debounce, extended carry and frozen-pedestrian reuse pass.',throw:'Actual facade impact damages scenery; released bodies return to physical collision.',split:'One waist joint disconnects into two clothed groups; eight-mesh puff expires, replay poses stay separate and no bodies are added.',controls:'Xbox D-down/RT/LT/X, pause, indoors, reset and exact constraint cleanup pass.',budget:'Held pedestrian remains inside the existing 16-ragdoll limit.'},null,2));
