import assert from 'node:assert/strict';
import {bootGame} from './helpers/game.mjs';
import {SCRATCH_GAMES,createScratchBoard,ticketProgress} from '../scratch-tickets.js';
const {app,window,get}=await bootGame(),t=app.test,life=t.streetLife;
t.loadLevel(24);app.start();t.teleport(0,190);assert(life.exitVehicle());life.refreshDoors();const shop=t.secretView.buildings.find(b=>b.type==='convenience');life.body.position.set(shop.door.x+shop.door.nx*.6,1.05,shop.door.z+shop.door.nz*.6);assert(life.enterBuilding(shop));assert(life.openShop());life.economy.earn(10000);life.closeShop();life.openShop();assert.equal(get('shopStock').querySelectorAll('.scratch-choice').length,10);
function pointer(type,x,y){const e=new window.Event(type,{bubbles:true,cancelable:true});Object.assign(e,{pointerId:1,clientX:x/360*100,clientY:y/560*44,pressure:.5});get('scratchCanvas').dispatchEvent(e);}
function rubZone(z){pointer('pointerdown',z.x+8,z.y+8);for(let y=z.y+8;y<z.y+z.h;y+=8){pointer('pointermove',z.x+8,y);pointer('pointermove',z.x+z.w-8,y);}pointer('pointerup',z.x+z.w-8,z.y+z.h-8);}
for(const g of SCRATCH_GAMES){get('scratchGame-'+g.id).click();const cash=life.economy.info().cash;get('buyScratch').click();let ticket=life.economy.info().ticket;assert(ticket);assert.equal(ticket.design,g.id);assert.equal(life.economy.info().cash,cash-10);assert(get('buyScratch').disabled);assert([...get('shopStock').querySelectorAll('.scratch-choice')].every(b=>b.disabled));assert.equal(get('scratchCanvas').width,360);assert.equal(get('scratchCanvas').height,560);assert(!get('scratchResult').textContent.includes('Won $'));
 const board=createScratchBoard(ticket),zone=board.zones.find(z=>z.covered!==false);rubZone(zone);ticket=life.economy.info().ticket;assert(ticket.scratched.length>0);assert(ticketProgress(ticket).revealed>=1);const saved=life.economy.info().ticket;life.closeShop();assert(life.openShop());assert.deepEqual(life.economy.info().ticket,saved);assert.equal(life.scratchUI.getInfo().cells,saved.scratched.length);
 // Complete physical scratch strokes; automatic validation pays once and leaves a readable receipt.
 for(const zone of board.zones)if(zone.covered!==false&&life.economy.info().ticket)rubZone(zone);assert.equal(life.economy.info().ticket,null);assert.equal(life.economy.info().cash,cash-10+saved.payout);assert.equal(life.economy.info().lastTicket.id,saved.id);assert(!get('scratchTicket').hidden);assert(get('revealScratch').hidden);assert.equal(life.economy.claimTicket(),null);assert(!life.scratchUI.revealAll());}
// The existing explicit Xbox/keyboard Reveal & collect shortcut still validates exactly once.
get('scratchGame-numbers').click();get('buyScratch').click();const before=life.economy.info(),payout=before.ticket.payout;get('revealScratch').click();assert.equal(life.economy.info().cash,before.cash+payout);get('revealScratch').click();assert.equal(life.economy.info().cash,before.cash+payout);
console.log('All ten rack selections, touch strokes, per-panel exposure, saved partial scratches, purchase lockout, automatic once-only collection, printed receipts and Reveal shortcut pass.');
