import {UPGRADES,TOOL_PRICES,PAINTS,vehicleKey} from './garage-upgrades.js?v=street-27';
export function createGarageUI({economy,getCar,getFleet,getRepair,onTune,onRepair,getContracts,close}){
 const $=id=>document.getElementById(id);let tab='vehicle',selected=null;
 function button(id,text,disabled,action){const b=document.createElement('button');b.id=id;b.textContent=text;b.disabled=disabled;b.onclick=()=>{action();render();};return b;}
 function row(name,detail,b){const div=document.createElement('div');div.className='shop-row';const text=document.createElement('div');text.textContent=name;const small=document.createElement('small');small.textContent=detail;text.append(small);div.append(text,b);$('garageStock').append(div);}
 function render(){const car=selected||getCar(),id=vehicleKey(car),s=economy.info(),r=economy.upgradeInfo(id);$('garageCash').textContent='$'+s.cash.toLocaleString();$('garageVehicle').textContent=car.config.name;$('garageStock').replaceChildren();$('garageTabs').replaceChildren();for(const [key,title]of [['vehicle','Vehicle'],['tools','Tools'],['contracts','Contracts']]){const b=button('garageTab-'+key,title,false,()=>tab=key);b.classList.toggle('active',tab===key);b.setAttribute('aria-pressed',String(tab===key));$('garageTabs').append(b);}
  if(tab==='vehicle'){const fleet=document.createElement('div');fleet.className='garage-fleet';for(const item of getFleet()){const b=button('garageCar-'+vehicleKey(item),item.config.name,false,()=>selected=item);b.classList.toggle('active',item===car);fleet.append(b);}$('garageStock').append(fleet);const repair=getRepair(car);row('Repair',repair.needed?'Restore body, wheels and engine':'Vehicle in good condition',button('garageRepair',repair.needed?'Repair · $'+repair.price:'Repaired',!repair.needed||s.cash<repair.price,()=>{if(getRepair(car).needed&&economy.spend(repair.price))onRepair();}));for(const u of UPGRADES){const level=r[u.id]||0,price=u.prices[level];row(u.name+' · '+level+'/3',u.effect,button('upgrade-'+u.id,price?'Upgrade · $'+price:'Maxed',!price||s.cash<price,()=>{if(economy.buyUpgrade(id,u.id))onTune(car);}));}
   const wrap=document.createElement('div');wrap.className='garage-paints';for(const p of PAINTS){const b=button('paint-'+p.id,p.name+(p.id==='factory'?'':' · $75'),r.paint===p.id||p.id!=='factory'&&s.cash<75,()=>{if(economy.buyPaint(id,p.id))onTune(car);});b.style.borderColor=p.color===null?'#a2b9af':'#'+p.color.toString(16).padStart(6,'0');wrap.append(b);}$('garageStock').append(wrap);
  }else if(tab==='tools'){const level=s.garage.tools,price=TOOL_PRICES[level];row('Tool tuning · '+level+'/3','All owned tools: +20% damage and faster use per tier',button('upgrade-tools',price?'Upgrade · $'+price:'Maxed',!price||s.cash<price,()=>economy.buyToolUpgrade()));}
  else{const contracts=getContracts(),info=contracts?.getInfo();if(info?.active)row(info.title,info.step,button('cancelContract','Cancel',false,()=>contracts.cancel()));if(info?.last){const p=document.createElement('p');p.textContent=info.last.message;$('garageStock').append(p);}for(const c of contracts?.board()||[]){row(c.name+' · $'+c.reward,c.description,button('contract-'+c.id,!c.available?'Rebuild district':info.active?'Finish current job':'Accept',!c.available||info.active,()=>contracts.accept(c.id)));}}
  $('garageMessage').textContent=tab==='contracts'?'Gold = target · green = protect / marked car. Cash on completion.':'Purchases save automatically. Upgrades apply to this vehicle.';
 }
 $('garageClose').onclick=$('garageLeave').onclick=close;
 return {open(){tab='vehicle';selected=getCar();$('garagePanel').hidden=false;render();},hide(){$('garagePanel').hidden=true;},render,get menu(){return {menuRoot:$('garagePanel'),defaultButton:'garageTab-'+tab};}};
}
