export function createMultiplayerUI({duel,onOpen=()=>{},onClose=()=>{}}){
 const panel=document.createElement('section');panel.id='duelPanel';panel.hidden=true;panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');panel.setAttribute('aria-labelledby','duelTitle');panel.innerHTML=`<div class="duel-card"><div class="duel-heading"><h2 id="duelTitle">Secret City duel</h2><button id="duelClose" aria-label="Close multiplayer">✕</button></div><p id="duelStatus" role="status" aria-live="polite"></p><p class="duel-help">Two players · same Wi-Fi · finish 24 lots and own a gun. Hosting or joining agrees to player combat. Indoors and paused players are safe.</p><div class="duel-actions"><button id="duelHost">1. Host &amp; make invite</button><button id="duelLeave">Leave duel</button></div><label for="duelInput">Guest: paste invite. Host: paste guest’s reply.</label><textarea id="duelInput" rows="2" placeholder="Paste the complete link or Mango code" autocapitalize="off" autocomplete="off" spellcheck="false"></textarea><button id="duelConnect">2. Use pasted invite / reply</button><div id="duelOutputSection" hidden><label for="duelOutput" id="duelOutputLabel">Your invite</label><textarea id="duelOutput" rows="2" readonly></textarea><div class="duel-actions"><button id="duelShare">Share</button><button id="duelCopy">Copy</button></div><p id="duelStep" class="duel-help"></p></div><p class="duel-help">No nearby scanning or Bluetooth pairing. Open both games in Safari, keep them in the foreground, and avoid guest Wi-Fi. Network isolation can block direct connections.</p></div>`;document.body.append(panel);
 const hud=document.createElement('div');hud.id='duelHUD';hud.hidden=true;hud.innerHTML='<b id="duelHealth">Health 100</b><span id="duelScore">0 – 0</span><small id="duelHint">Invited rival</small>';document.body.append(hud);
 const $=id=>document.getElementById(id);let output='',outputRole='',busy=false,wasReady=false;
 const buttons=['duelHost','duelConnect'];
 function render(info){const connectedNow=info.ready&&!wasReady;wasReady=info.ready;$('duelStatus').textContent=info.status;$('duelLeave').hidden=!info.role;hud.hidden=!info.ready;$('duelHealth').textContent=info.health.hp===0?'Respawn · '+Math.ceil(info.health.respawn)+'s':'Health '+info.health.hp;$('duelScore').textContent=info.health.score+' – '+info.opponent.score;$('duelHint').textContent=info.health.hp===0?'Knocked out':info.health.shield>0?'Spawn shield':info.pose?.safe?'Rival is indoors · safe':info.pose&&!info.pose.active?'Rival is paused · safe':'Rival health '+info.opponent.hp;buttons.forEach(id=>$(id).disabled=busy||!info.eligible||!info.supported||info.ready);if(!info.eligible&&!info.connected)$('duelStatus').textContent='Locked · finish 24 lots and own a gun';if(!info.supported)$('duelStatus').textContent='Open in Safari to use peer connections';if(connectedNow&&!panel.hidden)hide();}
 const unsub=duel.subscribe(render);
 function show(){onOpen();panel.hidden=false;render(duel.info());$('duelClose').focus();}
 function hide(){panel.hidden=true;onClose();}
 async function run(fn){if(busy)return;busy=true;render(duel.info());try{await fn();}catch(e){$('duelStatus').textContent=e.message;}finally{busy=false;buttons.forEach(id=>$(id).disabled=!duel.info().eligible||!duel.info().supported||duel.info().ready);}}
 function setOutput(code,kind){output=code;outputRole=kind;$('duelOutputSection').hidden=false;$('duelOutputLabel').textContent=kind==='offer'?'Host invite':'Guest reply';$('duelOutput').value=code;$('duelStep').textContent=kind==='offer'?'Share this invite. Your friend taps Join and sends a reply. Paste their reply above to connect.':'Send this reply back. The host pastes it in their original game tab. Keep this page open.';}
 $('duelHost').onclick=()=>run(async()=>setOutput(await duel.host(),'offer'));
 $('duelConnect').onclick=()=>run(async()=>{const text=$('duelInput').value.trim();if(duel.info().role==='host'&&!duel.info().ready)await duel.accept(text);else setOutput(await duel.join(text),'answer');});
 const link=()=>{const url=new URL(location.href);url.hash='duel='+encodeURIComponent(output);return url.href;};
 $('duelCopy').onclick=async()=>{try{await navigator.clipboard.writeText(output);$('duelStatus').textContent='Copied '+(outputRole==='offer'?'invite':'reply');}catch{$('duelOutput').focus();$('duelOutput').select();$('duelStatus').textContent='Select and copy the code above.';}};
 $('duelShare').onclick=async()=>{if(!output)return;try{if(navigator.share)await navigator.share(outputRole==='offer'?{title:'Mango duel invite',url:link()}:{title:'Mango duel reply · paste in the original host tab',text:output});else{$('duelOutput').value=outputRole==='offer'?link():output;$('duelOutput').focus();$('duelOutput').select();$('duelStatus').textContent='Copy the selected link to your friend.';}}catch(e){if(e.name!=='AbortError')$('duelStatus').textContent='Use Copy to share the code.';}};
 $('duelClose').onclick=hide;$('duelLeave').onclick=()=>{duel.leave();output='';$('duelOutputSection').hidden=true;render(duel.info());};panel.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();hide();}if(e.key==='Tab'){const items=[...panel.querySelectorAll('button,textarea')].filter(n=>!n.disabled&&!n.closest('[hidden]'));const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
 function readLink(){if(!location.hash.startsWith('#duel='))return;try{$('duelInput').value=decodeURIComponent(location.hash.slice(6));history.replaceState(null,'',location.pathname+location.search);show();}catch{$('duelStatus').textContent='Invite link is incomplete.';}}window.addEventListener('hashchange',readLink);readLink();render(duel.info());
 return {show,hide,get open(){return !panel.hidden;},get menu(){return {menuRoot:panel,defaultButton:'duelConnect'};}};
}
