// NPC wrecks use their own model parts. Physics slots are pooled and capped.
import {createCrushContact} from './crush-contact.js?v=crush-12';
import {setDamageAppearance} from './damage-appearance.js?v=wreck-16';
export function createParkedTraffic({T,C,scene,world,lots,garage,onWreck}){
 const LIMIT=128,activeDebris=[],pool=[],boxGeo=new T.BoxGeometry(1,1,1),wheelGeo=new T.CylinderGeometry(.35,.35,.22,12),metal=new T.MeshStandardMaterial({color:0x687173,roughness:.7}),rubber=new T.MeshStandardMaterial({color:0x252928,roughness:.95}),glass=new T.MeshStandardMaterial({color:0x45616a,roughness:.25,metalness:.15});
 let active=[],clock=0;const pending=new Map(),v=new T.Vector3(),q=new T.Quaternion(),scale=new T.Vector3(),turn=new T.Quaternion(),axis=new T.Vector3(1,0,0),crushedCarMat=new C.Material({friction:.5,restitution:.05}),contact=createCrushContact(C);
 function prepare(item){if(item.prepared)return;item.prepared=true;item.homePosition=item.body.position.clone();item.homeQuaternion=item.body.quaternion.clone();item.physicsMaterial=item.body.material;item.collisionSize=item.body.shapes[0].halfExtents.clone();item.damage=0;item.charred=0;item.exploded=false;item.lastHit=-10;item.detached=new Set();item.frozen=new Map();
  item.body.addEventListener('collide',e=>{if(item.exploded||item.occupied)return;const force=Math.abs(e.contact.getImpactVelocityAlongNormal());if(force>1.3)pending.set(item,Math.max(pending.get(item)||0,force));});
 }
 function standardModel(item){const paint=new T.MeshStandardMaterial({name:'paint',userData:{garagePaint:true},color:item.mesh.children[0]?.material?.color||0x8d9b99,roughness:.55});item.mesh.clear();
  const part=(name,x,y,z,w,h,d,material=paint,geo=boxGeo)=>{const m=new T.Mesh(geo,material);m.name=name;m.position.set(x,y,z);m.scale.set(w,h,d);m.castShadow=m.receiveShadow=true;item.mesh.add(m);return m;};
  part('chassis',0,.48,0,1.8,.24,3.9,metal);part('hood',0,.88,-1.38,1.88,.28,1.25);part('trunk',0,.88,1.5,1.88,.30,1.0);part('roof',0,1.57,.15,1.52,.16,1.85);
  for(const side of [-1,1])for(const end of [-1,1]){part((side<0?'left':'right')+'-door-'+end,side*.94,.95,end*.52,.12,.75,.94);const wheel=part('wheel-'+side+'-'+end,side*.98,.4,end*1.36,1,1,1,rubber,wheelGeo);wheel.rotation.z=Math.PI/2;}
  for(const end of [-1,1]){part('bumper-'+end,0,.57,end*2.02,1.96,.18,.18,metal);const wind=part('glass-'+end,0,1.28,.15+end*.88,1.47,.46,.08,glass);wind.rotation.x=end*-.27;}
  for(const side of [-1,1])part('glass-side-'+side,side*.80,1.29,.15,.06,.43,1.62,glass);
 }
 function setupParts(item){item.parts=[...item.mesh.children];item.rest=item.parts.map(p=>({p:p.position.clone(),q:p.quaternion.clone(),s:p.scale.clone(),visible:p.visible}));item.materials=[];
  item.parts.forEach((p,i)=>{if(!p.name)p.name='detail-'+i;p.traverse(n=>{if(n.isMesh&&!Array.isArray(n.material)){n.material=n.material.clone();item.materials.push({material:n.material,color:n.material.color.clone(),roughness:n.material.roughness,metalness:n.material.metalness,emissive:n.material.emissive?.clone()});setDamageAppearance(T,n.material,0,0);}});});
 }
 function freeze(d,keep=true){world.removeBody(d.body);if(keep&&d.item){if(d.body.sleepState!==C.Body.SLEEPING){d.body.updateAABB();const h=(d.body.aabb.upperBound.y-d.body.aabb.lowerBound.y)/2;d.body.position.y=Math.min(d.body.position.y,h+.04);}localPose(d.item,d.part,d.body.position,d.body.quaternion);d.item.frozen.set(d.part,{p:new T.Vector3().copy(d.body.position),q:new T.Quaternion().copy(d.body.quaternion)});}d.active=false;d.part=null;d.item=null;const i=activeDebris.indexOf(d);if(i>=0)activeDebris.splice(i,1);}
 function restoreItem(item){for(const d of [...activeDebris])if(d.item===item)freeze(d,false);item.detached.clear();item.frozen.clear();item.charred=0;item.exploded=false;
  item.body.material=item.physicsMaterial;const shape=item.body.shapes[0];shape.halfExtents.copy(item.collisionSize);shape.updateConvexPolyhedronRepresentation();shape.updateBoundingSphereRadius();item.body.updateBoundingRadius();item.body.mass=0;item.body.type=C.Body.STATIC;item.body.collisionFilterGroup=1;item.body.updateMassProperties();item.body.position.copy(item.homePosition);item.body.quaternion.copy(item.homeQuaternion);item.body.velocity.setZero();item.body.angularVelocity.setZero();item.body.force.setZero();item.body.torque.setZero();item.body.aabbNeedsUpdate=true;item.mesh.position.set(item.homePosition.x,0,item.homePosition.z);item.mesh.quaternion.copy(item.homeQuaternion);
  if(item.rest)item.parts.forEach((p,i)=>{p.position.copy(item.rest[i].p);p.quaternion.copy(item.rest[i].q);p.scale.copy(item.rest[i].s);p.visible=item.rest[i].visible;});setTint(item,0);item.lastHit=-10;item.body.wakeUp();
 }
 function resetDistrict(d){for(const item of active)if(item.district===d&&!item.occupied){pending.delete(item);restoreItem(item);}}
 function reset(level){for(const d of [...activeDebris])freeze(d,false);pending.clear();for(const item of active)restoreItem(item);active=lots.parked.filter(p=>p.level===level);clock=0;let specials=0;
  active.forEach((item,i)=>{prepare(item);if(!item.parts){
   const featured=level===24?garage.find(g=>g.config.id===['montecarlo','suburban','impala','colorado','maybach'][i]):null;
   if(featured||(i+level)%4===1&&specials<2){const model=featured||garage[(i+level)%garage.length],copy=model.root.clone(true);copy.visible=true;copy.position.set(0,0,0);copy.quaternion.identity();copy.traverse(n=>{if(n.userData.home){n.position.copy(n.userData.home);n.quaternion.identity();}});copy.updateMatrixWorld(true);const bounds=new T.Box3().setFromObject(copy),size=bounds.getSize(new T.Vector3()),factor=Math.min(2/size.x,4.25/size.z,1);item.mesh.clear();for(const child of [...copy.children]){child.position.multiplyScalar(factor);child.scale.multiplyScalar(factor);item.mesh.add(child);}item.model=model.config.id;item.name=model.config.name;specials++;}
   else{standardModel(item);item.model='standard';}setupParts(item);
  }else if(item.model!=='standard')specials++;restoreItem(item);});
 }
 function setTint(item,damage){item.damage=damage;for(const m of item.materials||[]){m.material.color.copy(m.color).multiplyScalar(1-damage*.4);if(m.roughness!==undefined)m.material.roughness=m.roughness+(1-m.roughness)*Math.max(damage,item.charred);if(m.metalness!==undefined)m.material.metalness=m.metalness*(1-item.charred);if(m.emissive)m.material.emissive.copy(m.emissive).multiplyScalar(1-item.charred);setDamageAppearance(T,m.material,damage,item.charred);}}
 function wake(item){if(item.body.mass)return;item.body.mass=1150;item.body.type=C.Body.DYNAMIC;if(item.level===24){item.body.collisionFilterGroup=8;item.body.material=crushedCarMat;}item.body.linearDamping=.28;item.body.angularDamping=.48;item.body.allowSleep=true;item.body.updateMassProperties();item.body.wakeUp();}
 function detach(item,p,direction,strength){if(item.detached.has(p))return;
  let d=pool.find(d=>!d.active);if(!d&&pool.length<LIMIT){d={body:new C.Body({mass:18,material:crushedCarMat,shape:new C.Box(new C.Vec3(.2,.2,.2)),collisionFilterGroup:2,collisionFilterMask:9,linearDamping:.2,angularDamping:.35,allowSleep:true,sleepSpeedLimit:.3,sleepTimeLimit:1.5}),active:false};d.body.userData={kind:'car wreckage'};pool.push(d);}if(!d){d=activeDebris.reduce((a,b)=>a.age>b.age?a:b);freeze(d);}
  p.updateWorldMatrix(true,true);p.getWorldPosition(v);p.getWorldQuaternion(q);const dimensions=new T.Box3().setFromObject(p).getSize(scale),body=d.body;body.removeShape(body.shapes[0]);body.addShape(new C.Box(new C.Vec3(Math.max(.1,Math.min(1.2,dimensions.x/2)),Math.max(.08,Math.min(.7,dimensions.y/2)),Math.max(.1,Math.min(1.7,dimensions.z/2)))));body.mass=/wheel/.test(p.name)?24:18;body.position.copy(v);body.quaternion.copy(q);body.updateMassProperties();body.updateBoundingRadius();body.aabbNeedsUpdate=true;body.force.setZero();body.torque.setZero();
  const dx=v.x-item.body.position.x,dz=v.z-item.body.position.z,length=Math.max(.25,Math.hypot(dx,dz));body.velocity.set(item.body.velocity.x*.4+direction.x*strength+dx/length*strength*.65,2+strength*.5,item.body.velocity.z*.4+direction.z*strength+dz/length*strength*.65);body.angularVelocity.set((dx||.3)*2,1.5,(dz||.3)*2);body.wakeUp();world.addBody(body);Object.assign(d,{part:p,item,age:0,active:true});activeDebris.push(d);item.detached.add(p);
 }
 function explode(item,direction,strength){if(item.exploded)return;item.exploded=true;item.charred=1;setTint(item,1);const choices=item.parts.filter(p=>p.visible&&!/chassis|engine|tub|glass|windshield/.test(p.name));choices.sort((a,b)=>Number(/wheel|door|hood|bonnet|roof|trunk|bumper/.test(b.name))-Number(/wheel|door|hood|bonnet|roof|trunk|bumper/.test(a.name)));for(const p of choices.slice(0,12))detach(item,p,direction,Math.max(3,Math.min(9,strength)));
  for(const p of item.parts){if(/glass|windshield/.test(p.name))p.visible=false;if(!item.detached.has(p)){const i=item.parts.indexOf(p);p.scale.y=item.rest[i].s.y*.35;p.position.y=Math.min(.55,item.rest[i].p.y*.6);}}
  const shape=item.body.shapes[0];shape.halfExtents.set(item.collisionSize.x,.3,item.collisionSize.z*.85);shape.updateConvexPolyhedronRepresentation();shape.updateBoundingSphereRadius();item.body.updateBoundingRadius();item.body.updateMassProperties();item.body.aabbNeedsUpdate=true;onWreck?.(new T.Vector3().copy(item.body.position),item);
 }
 function damage(item,amount,direction,strength,burning=false){if(!active.includes(item)||item.exploded||item.occupied)return;wake(item);const before=item.damage;if(burning)item.charred=Math.max(item.charred,Math.min(1,amount*.9));setTint(item,Math.min(1,item.damage+amount));item.lastHit=clock;
  if(item.level===24){const shape=item.body.shapes[0],original=item.collisionSize;shape.halfExtents.set(original.x,original.y*(1-item.damage*.45),original.z*(1-item.damage*.16));shape.updateConvexPolyhedronRepresentation();shape.updateBoundingSphereRadius();item.body.updateBoundingRadius();item.body.updateMassProperties();item.body.aabbNeedsUpdate=true;}
  item.parts.forEach((p,i)=>{if(item.detached.has(p))return;const home=item.rest[i];if(/hood|bonnet|body|roof|door|trunk|grille|tub/.test(p.name)){p.scale.y=home.s.y*(1-item.damage*.28);p.scale.z=home.s.z*(1-item.damage*.12);p.quaternion.copy(home.q).multiply(turn.setFromAxisAngle(axis,item.damage*.075*(i%2?1:-1)));p.position.y=home.p.y-item.damage*.1;}});
  if(item.damage>=.86)explode(item,direction,strength);else if(before<.45&&item.damage>=.45){for(const p of item.parts.filter(p=>/bumper|hood|door/.test(p.name)).slice(0,2))detach(item,p,direction,Math.max(1,strength));}
  item.body.applyImpulse(new C.Vec3(direction.x*strength*650,Math.min(3,strength*.3)*650,direction.z*strength*650),new C.Vec3(0,.2,.4));
 }
 function blast(point,power=1){for(const item of active){const dx=item.body.position.x-point.x,dz=item.body.position.z-point.z,distance=Math.hypot(dx,dz);if(distance>13)continue;const falloff=1-distance/13,dir={x:dx/Math.max(.2,distance),z:dz/Math.max(.2,distance)};if(distance<.2)dir.x=1;damage(item,(.25+falloff*.8)*Math.min(1.5,power),dir,(2+falloff*7)*Math.min(1.25,power),true);}}
 function ram(chassis,dt,driveForce=0){const speed=Math.hypot(chassis.velocity.x,chassis.velocity.z);if(speed<.15&&driveForce<1)return;for(const item of active){const shape=item.body.shapes[0],size=[shape.halfExtents.x*2,shape.halfExtents.y*2,shape.halfExtents.z*2];if(!contact(chassis,item.body,size))continue;wake(item);item.body.wakeUp();if(driveForce>0&&clock-item.lastHit>.1)damage(item,Math.min(1,driveForce/88000)*dt*.8,{x:0,z:0},0);}}
 function localPose(item,p,position,quaternion){v.copy(position);item.mesh.worldToLocal(v);p.position.copy(v);item.mesh.getWorldQuaternion(q);p.quaternion.copy(q).invert().multiply(quaternion);}
 function update(dt){clock+=dt;for(const [item,impact]of pending)if(active.includes(item)&&clock-item.lastHit>.5){const speed=item.body.velocity.length(),dir=speed>.1?{x:item.body.velocity.x/speed,z:item.body.velocity.z/speed}:{x:.3,z:1};damage(item,Math.min(.75,impact*.08),dir,Math.min(6,impact*.3));}pending.clear();
  for(const item of active){if(item.occupied)continue;item.mesh.quaternion.copy(item.body.quaternion);item.mesh.position.copy(item.body.position);v.set(0,item.exploded?-.48:-.8*(item.level===24?1-item.damage*.45:1),0).applyQuaternion(item.mesh.quaternion);item.mesh.position.add(v);item.mesh.updateMatrixWorld(true);for(const [p,pose]of item.frozen)localPose(item,p,pose.p,pose.q);}
  for(const d of [...activeDebris]){d.age+=dt;localPose(d.item,d.part,d.body.position,d.body.quaternion);if(d.age>16||d.age>3&&d.body.sleepState===C.Body.SLEEPING)freeze(d);}
 }
 function snapshot(){const data=[];for(const item of active){data.push(...item.mesh.position.toArray(),...item.mesh.quaternion.toArray(),item.damage,item.charred,item.exploded?1:0);for(const p of item.parts)data.push(...p.position.toArray(),...p.quaternion.toArray(),...p.scale.toArray(),p.visible?1:0);}return new Float32Array(data);}
 function apply(a,b,u){if(!a||!b)return;let k=0;const vec=o=>{o.set(a[k]+(b[k]-a[k])*u,a[k+1]+(b[k+1]-a[k+1])*u,a[k+2]+(b[k+2]-a[k+2])*u);k+=3;},rot=o=>{o.fromArray(a,k).slerp(q.fromArray(b,k),u);k+=4;};for(const item of active){vec(item.mesh.position);rot(item.mesh.quaternion);const amount=a[k]+(b[k]-a[k])*u;item.charred=a[k+1]+(b[k+1]-a[k+1])*u;item.exploded=(u<.5?a:b)[k+2]>.5;setTint(item,amount);k+=3;for(const p of item.parts){vec(p.position);rot(p.quaternion);vec(p.scale);p.visible=(u<.5?a:b)[k++]>.5;}}}
 function strike(body,point,power){const item=active.find(p=>p.body===body);if(item)damage(item,power*.045,{x:(body.position.x-point.x)*.2,z:(body.position.z-point.z)*.2},Math.min(3,power*.2));}
 return{strike,reset,resetDistrict,blast,ram,update,snapshot,apply,get active(){return active;},get debris(){return activeDebris;},getInfo:()=>({count:active.length,damaged:active.filter(p=>p.damage>0).length,exploded:active.filter(p=>p.exploded).length,charred:active.filter(p=>p.charred>.1).length,moving:active.filter(p=>p.body.mass>0).length,models:active.map(p=>p.model),debris:activeDebris.length,debrisPool:pool.length,debrisLimit:LIMIT,frozenParts:active.reduce((n,p)=>n+p.frozen.size,0)})};
}
