import {createClubRoom} from './club-room.js?v=mango-5';
import {createWebShooter} from './web-shooter.js?v=street-31';
import {createGarageUI} from './garage-ui.js?v=street-27';
import {createInteriorBreakage} from './interior-breakage.js?v=street-25';
import {createHulkMode} from './hulk-mode.js?v=street-24';
import {createScratchUI} from './scratch-ui.js?v=street-29';
import {createCasinoUI} from './casino-ui.js?v=street-29';
import {createCasinoRoom,CASINO_STATIONS} from './casino-room.js?v=street-29';
import {createShopEconomy,WEAPONS} from './shop-economy.js?v=street-29';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
// A single furnished room is reused for every doorway; no city-sized indoor scene.
import {buildSteveAvatar} from './player-likeness.js?v=mango-2';
export function createStreetLife({T,C,scene,world,lots,chassis,crowd,groundMat,getView,getLevel,getCar,getState,getCamera,getAim,clearInput,notify,onCamera,onEnterCar,onExitCar,onHit,onBlast,getFleet,getRepair,onTune,onRepair,getContracts}){
 const $=id=>document.getElementById(id),economy=createShopEconomy(),avatar=new T.Group(),room=new T.Group();scene.add(avatar,room);avatar.visible=room.visible=false;
 const clubRoom=createClubRoom(T),webs=createWebShooter(T,scene);
 const casinoRoom=createCasinoRoom(T),casinoUI=createCasinoUI(economy,closeShop,game=>shopOpen&&seated&&seatStation?.game===game&&inside?.type==='casino'&&getState()==='running'),scratchUI=createScratchUI(economy,notify,()=>{$('shopCash').textContent='$'+economy.info().cash.toLocaleString();});
 const garageUI=createGarageUI({economy,getCar,getFleet,getRepair,onTune,onRepair,getContracts,close:closeShop});
 const geo=new T.BoxGeometry(1,1,1),sphere=new T.IcosahedronGeometry(1,1),mats=new Map(),origin=-6000,colliders=[],projectiles=[],grenadePool=[],labelTextures=[];
 const breakage=createInteriorBreakage(T,geo);
 const mat=color=>{if(!mats.has(color))mats.set(color,new T.MeshStandardMaterial({color,roughness:.78}));return mats.get(color);};
 function box(parent,w,h,d,x,y,z,color,solid=false){const m=new T.Mesh(geo,mat(color));m.scale.set(w,h,d);m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;parent.add(m);if(solid)colliders.push({x,z,w,d,mesh:m});return m;}
 box(avatar,.56,.65,.28,0,1.08,0,0x377f85);box(avatar,.3,.32,.3,0,1.57,0,0xc5a184);
 const legs=[box(avatar,.2,.67,.22,-.16,.4,0,0x303943),box(avatar,.2,.67,.22,.16,.4,0,0x303943)],arms=[box(avatar,.17,.57,.2,-.4,1.06,0,0x377f85),box(avatar,.17,.57,.2,.4,1.06,0,0x377f85)];
 const tool=new T.Group();tool.position.set(.38,.91,-.25);avatar.add(tool);
 const walkMat=new C.Material('walker');world.addContactMaterial(new C.ContactMaterial(walkMat,groundMat,{friction:0,restitution:0}));world.addContactMaterial(new C.ContactMaterial(walkMat,world.defaultMaterial,{friction:0,restitution:0}));const body=new C.Body({mass:75,material:walkMat,fixedRotation:true,linearDamping:0,angularDamping:1,collisionFilterGroup:16,collisionFilterMask:1|8,allowSleep:false});
 body.addShape(new C.Sphere(.35),new C.Vec3(0,-.48,0));body.addShape(new C.Box(new C.Vec3(.28,.48,.28)),new C.Vec3(0,.1,0));body.updateMassProperties();body.userData={kind:'walker'};
 const firstHands=new T.Group();firstHands.name='First-person hands';firstHands.visible=false;box(firstHands,.13,.3,.18,-.18,-.29,-.46,0xc5a184);box(firstHands,.13,.3,.18,.18,-.29,-.46,0xc5a184);
 const likeness=buildSteveAvatar(T,avatar,firstHands);
 let mode='vehicle',inside=null,shopOpen=false,current=null,walkX=0,walkY=0,fireHeld=false,cooldown=0,anim=0,toolId='',firstToolId=null,swing=0,markers=[],markerLevel=-1,roomBuilt=0,seated=false,seatStation=null,standingPos=null,aim=new T.Vector3(),stickPointer=null;
 const roomExit={x:0,z:5.2},counter={x:0,z:-3.1};
 const normalSkin=mat(0xd5a88c),normalShirt=mat(0x17191d),hulkSkin=mat(0x70a850);
 function hulkVisual(active,held){likeness.setHulk(active);for(const hand of firstHands.children.slice(0,2)){hand.material=active?hulkSkin:normalSkin;hand.scale.x=active?.19:.13;}firstHands.children.slice(2).forEach(m=>m.visible=!active);tool.visible=!active;}
 const hulk=createHulkMode({T,C,scene,world,crowd,body,getCamera,allowed:()=>mode==='foot'&&!inside&&!shopOpen&&getState()==='running',notify,onVisual:hulkVisual});

 function label(parent,text,x,y,z,w=3){const cv=document.createElement('canvas');cv.width=512;cv.height=128;const c=cv.getContext('2d');c.fillStyle='#173c3a';c.fillRect(0,0,512,128);c.fillStyle='#ffe7a2';c.textAlign='center';c.font='bold 36px system-ui';c.fillText(text,256,77);const tx=new T.CanvasTexture(cv);tx.colorSpace=T.SRGBColorSpace;labelTextures.push(tx);const material=new T.MeshBasicMaterial({map:tx,side:T.DoubleSide});const m=new T.Mesh(new T.PlaneGeometry(w,w/4),material);m.position.set(x,y,z);parent.add(m);return m;}
 function makeDoors(){const level=getLevel();if(markerLevel===level)return;for(const m of markers){if(m.userData.building)m.userData.building.marker=null;m.parent?.remove(m);m.traverse(n=>{if(n.geometry!==geo&&n.geometry!==sphere&&!casinoRoom.geometries.has(n.geometry))n.geometry?.dispose();if(n.material?.map&&!casinoRoom.materials.has(n.material)){n.material.map.dispose();n.material.dispose();}});}markers=[];markerLevel=level;
  const v=getView();for(const b of v.buildings||[]){
   const dx=v.ox-b.x,dz=-b.z;let nx=0,nz=1;if(Math.abs(dx)/(b.w||1)>Math.abs(dz)/(b.d||1)){nx=Math.sign(dx)||1;nz=0;}else nz=Math.sign(dz)||1;
   b.door={x:b.x+nx*(b.w/2+.8),z:b.z+nz*(b.d/2+.8),nx,nz};
   const g=new T.Group();g.position.set(b.door.x,0,b.door.z);g.rotation.y=nx?nx*Math.PI/2:nz<0?Math.PI:0;v.group.add(g);
   box(g,1.3,2.2,.09,0,1.1,0,b.type==='convenience'?0x338b6d:b.type==='gun'?0x945440:0x345e62);
   box(g,1,.65,.03,0,1.62,.06,0x87aaa9);box(g,.07,.1,.08,.43,1,.07,0xf2cb70);
   if(['convenience','gun','casino','garage','club'].includes(b.type)){const sign=label(g,b.name,0,2.8,.12,Math.min(b.w*.8,6));sign.userData.doorSign=true;}
   if(b.type==='casino'||b.type==='club'){box(g,6,.22,1.5,0,2.45,.4,0x73455e);for(const x of [-2.8,2.8])box(g,.24,2.5,.24,x,1.25,.35,0xccaa61);box(g,3,.02,3,0,.02,1.2,0x914e76);for(let i=0;i<12;i++)box(g,.11,.1,.1,-2.7+i*.49,2.67,.7,0xf4d994);}
   if(b.type==='garage'){
    b.service={x:b.door.x+nx*7,z:b.door.z+nz*7};
    box(g,9,.025,12,0,.05,7,0x345e62);for(const x of [-4.3,4.3])box(g,.13,.03,12,x,.07,7,0xe2b958);for(const z of [1,13])box(g,8.6,.03,.13,0,.07,z,0xe2b958);
    for(const x of [-4.5,4.5])box(g,.25,4,.25,x,2,1.5,0x526968);box(g,9.5,.23,3,0,4,1.4,0x345e62);
   }
   b.marker=g;g.userData.building=b;markers.push(g);
  }
 }
 function ruined(b){return b.target&&b.target.entries.filter(e=>e.foundation).every(e=>e.broken);}
 function refreshDoors(){makeDoors();for(const b of getView().buildings||[]){if(b.marker)b.marker.visible=!ruined(b);}}
 function clearRoom(){clubRoom.clear();breakage.clear();seated=false;seatStation=null;standingPos=null;casinoRoom.clear();room.traverse(n=>{if(n.isInstancedMesh)n.dispose();if(n.geometry&&n.geometry!==geo&&n.geometry!==sphere&&!casinoRoom.geometries.has(n.geometry))n.geometry.dispose();if(n.material?.map&&!casinoRoom.materials.has(n.material)){n.material.map.dispose();n.material.dispose();}});room.clear();colliders.length=0;labelTextures.length=0;}
 function buildRoom(b){clearRoom();roomBuilt++;room.position.set(origin,0,0);const home=/house|motel|valet|apartments/.test(b.type)||/Apartments/.test(b.name),store=/market|garden|seaside|convenience|gun/.test(b.type),industrial=/garage|warehouse|factory|scrap|construction|harbour/.test(b.type);
  box(room,16,.15,14,0,-.075,0,home?0x92785b:industrial?0x8b9490:0xb1b7a7);box(room,16,3.6,.18,0,1.8,-7,b.type==='casino'?0x33263e:0xcac4b0);
  for(const x of [-8,8])box(room,.18,3.6,14,x,1.8,0,b.type==='casino'?0x33263e:0xcac4b0);
  // Open front wall and roof keep the third-person room readable on a phone.
  for(const x of [-4.8,4.8])box(room,6.4,3.6,.18,x,1.8,7,b.type==='casino'?0x33263e:0xcac4b0);
  box(room,2.6,.08,2,0,.025,5.7,0x426f6b);label(room,'EXIT',0,2.2,6.88,1.7);
  for(const x of [-7.86,7.86])for(const z of [-3,2]){const win=box(room,.025,1.4,1.7,x,2,z,0x81abb2);win.material=mat(0x81abb2);}
  for(const x of [-4,4])box(room,2,.07,1,x,3.2,0,0xe8e2b7);
  if(['convenience','gun','garage'].includes(b.type)){
   box(room,5,1.1,.85,0,.55,-4.3,0x566d65,true);box(room,5.2,.12,1.05,0,1.12,-4.3,0xdbbc78);
   box(room,.65,.4,.5,.8,1.39,-4.35,0x294346);label(room,b.name,0,2.65,-6.85,6);
   box(room,.6,.75,.35,-.8,1.52,-4.3,b.type==='gun'?0x805b46:0xe2b958);
  }
  if(b.type==='garage'){
   for(const x of [-4.6,4.6]){box(room,.35,2.5,.35,x,1.25,.2,0xdbbc78,true);box(room,2.3,.15,.35,x,1,.2,0x526968);box(room,2,1.1,.7,x,.55,-5.6,0xc45f45,true);for(const y of [.25,.55,.85])box(room,1.7,.035,.04,x,y,-5.22,0xd1c6a5);}
   box(room,4,.035,6,0,.04,0,0x426f6b);for(const z of [-2,2])box(room,4.5,.05,.12,0,.075,z,0xe2b958);label(room,'UPGRADES & CONTRACTS',0,2.6,-6.82,6);
  }else if(b.type==='club'){clubRoom.build({room,box,label});}else if(b.type==='casino'){casinoRoom.build({room,box,label});}else if(store){
   for(const x of [-5.4,5.4]){box(room,1.15,1.65,7,x,.83,-.5,0x49655e,true);for(const y of [.5,1,1.55]){box(room,1.3,.08,7.1,x,y,-.5,0xd1c6a5);for(let i=0;i<11;i++)box(room,.38,.32,.38,x,y+.2,-3.55+i*.58,[0xc45f45,0xe0bc62,0x608e9d,0x89a574][i%4]);}}
   if(b.type==='gun')for(let i=0;i<4;i++){const x=-3+i*2;box(room,.8,.15,.2,x,1.95,-6.83,0x344248);box(room,.15,.42,.12,x-.25,1.75,-6.81,0x886346);}else for(const x of [-2.3,2.3]){box(room,1.2,2.3,.6,x,1.15,-6.5,0x6b8584,true);box(room,.97,1.8,.025,x,1.2,-6.18,0x88b4ba);}
  }else if(home){
   box(room,3,.5,1.25,-4,.4,-3.5,0x78856d,true);box(room,3,.7,.28,-4,.95,-4,0x78856d);for(const x of [-5.4,-2.6])box(room,.25,.8,1.3,x,.65,-3.5,0x66795f);
   box(room,2,.5,1.1,-3,.3,-1,0x7c624b,true);box(room,2.7,.5,3.5,4,.4,-3.6,0xe3d8ba,true);box(room,2.7,.2,.9,4,.79,-4.7,0xf6ecd3);
   box(room,3.4,1,.75,3,.5,2.5,0x799897,true);box(room,.75,1.8,.7,6.3,.9,2.5,0xb5c6b9,true);box(room,2,1.1,.13,-3,1.8,-6.83,0x31505c);box(room,.9,.1,.5,3,1.05,2.5,0x526b6e);
  }else if(industrial){
   for(const x of [-5,4])for(const z of [-4,-1,2]){box(room,2,1.8,1.6,x,.9,z,0xa8875b,true);for(const y of [.25,1.5])box(room,2.03,.12,1.63,x,y,z,0x6f674e);}
   box(room,3,1,.75,0,.5,-5.7,0x526968,true);
  }else{
   for(const x of [-4,4])for(const z of [-3,1]){box(room,2.2,.15,1.25,x,.82,z,0xb29a73,true);for(const a of [-.85,.85])for(const d of [-.45,.45])box(room,.1,.75,.1,x+a,.4,z+d,0x526864);box(room,.8,.7,.7,x,.36,z+1.3,0x5d807d,true);box(room,.75,.08,.55,x,1,-.07+z,0x364c52);box(room,.7,.5,.08,x,1.23,z-.28,0x74979e);}
   box(room,4,1.8,.45,0,.9,-6.5,0x6c7b6b,true);for(let i=0;i<12;i++)box(room,.23,.5,.3,-1.65+i*.3,1.4,-6.2,[0xb07a61,0xd4b573,0x657f8b][i%3]);
  }
  // Damage is reflected indoors; flattened buildings cannot be entered until rebuilt.
  if(b.target?.entries.some(e=>e.damage>.1)){for(let i=0;i<8;i++)box(room,.8,.06,.55,-6+(i*1.7)%12,.06,-4+(i*2.3)%8,0x4a4840);label(room,'DAMAGED',0,2.5,-6.75,3);}
  breakage.build(room,b,colliders);room.visible=true;
 }
 function freeAt(x,z,ignore=null){for(const b of world.bodies){if(b===body||b===ignore||!b.collisionResponse||b===chassis&&ignore===chassis||[C.Shape.types.PLANE,C.Shape.types.HEIGHTFIELD].includes(b.shapes[0]?.type)||b.collisionFilterGroup===2||b.collisionFilterGroup===4)continue;if(b.aabbNeedsUpdate)b.updateAABB();const a=b.aabb;if(a.upperBound.y<.25||a.lowerBound.y>1.8)continue;if(x>a.lowerBound.x-.42&&x<a.upperBound.x+.42&&z>a.lowerBound.z-.42&&z<a.upperBound.z+.42)return false;}return true;}
 function placeOutside(x,z,nx=0,nz=1,ignore=null){for(let r=0;r<=6;r+=.6)for(const side of [0,1,-1,2,-2]){const px=x+nx*r-nz*side*.6,pz=z+nz*r+nx*side*.6;if(freeAt(px,pz,ignore)){body.position.set(px,1.05,pz);body.velocity.setZero();body.aabbNeedsUpdate=true;return true;}}return false;}
 function exitVehicle(){if(getState()!=='running'||mode!=='vehicle')return false;if(chassis.velocity.length()>1.5){notify('Stop before getting out');return false;}const car=getCar(),q=chassis.quaternion,side=new C.Vec3(car.config.halfWidth+1.1||2.5,0,0);q.vmult(side,side);
  if(!placeOutside(chassis.position.x+side.x,chassis.position.z+side.z,side.x/side.length(),side.z/side.length(),null)&&!placeOutside(chassis.position.x-side.x,chassis.position.z-side.z,-side.x/side.length(),-side.z/side.length(),null)){notify('Both doors are blocked');return false;}
  onExitCar();mode='foot';world.addBody(body);avatar.visible=true;clearInput();onCamera('foot');notify('Walk · E / Xbox X to interact',1.5);return true;
 }
 function enterVehicle(item=null){if(mode!=='foot'||inside||getState()!=='running')return false;const target=item?.body||chassis;if(Math.hypot(body.position.x-target.position.x,body.position.z-target.position.z)>4.6||target.velocity.length()>1.5||item&&(item.exploded||item.damage>.3||item.occupied))return false;
  if(item&&!onEnterCar(item))return false;hulk.stop();world.removeBody(body);mode='vehicle';avatar.visible=false;clearInput();onCamera('vehicle');return true;
 }
 function enterBuilding(b){if(mode!=='foot'||inside||getState()!=='running'||!b||ruined(b)||Math.hypot(body.position.x-b.door.x,body.position.z-b.door.z)>2.7)return false;hulk.stop();clearProjectiles();inside=b;world.removeBody(body);getView().group.visible=false;crowd?.setVisible(false);getCar().root.visible=false;buildRoom(b);body.position.set(origin, .83,4.8);body.velocity.setZero();clearInput();onCamera('interior');notify(b.name,1.3);return true;}
 function leaveBuilding(){if(!inside)return false;const b=inside;if(!placeOutside(b.door.x+b.door.nx*.9,b.door.z+b.door.nz*.9,b.door.nx,b.door.nz)){notify('Exit blocked · clear nearby debris first');return false;}clearProjectiles();closeShop();seated=false;inside=null;room.visible=false;getView().group.visible=true;crowd?.setVisible(true);getCar().root.visible=true;world.addBody(body);clearInput();onCamera('foot');return true;}
 function context(){if(mode==='vehicle'){refreshDoors();const garage=(getView().buildings||[]).find(b=>b.type==='garage'&&b.service&&!ruined(b)&&Math.hypot(chassis.position.x-b.service.x,chassis.position.z-b.service.z)<5.8);if(garage)return {kind:'garage',label:'Upgrade garage'};return {kind:'exit',label:'Exit vehicle'};}if(hulk.held)return {kind:'drop',label:'Drop pedestrian'};if(hulk.active){const person=hulk.nearest();if(person)return {kind:'grab',person,label:'Grab pedestrian'};}if(!inside)refreshDoors();if(inside){if(seated)return {kind:'casino',game:seatStation?.game||'sit',label:seatStation?.game==='sit'?'Stand up':'Play '+seatStation.name};const x=body.position.x-origin,z=body.position.z;if(inside.type==='club'){if(Math.hypot(x,z+2.0)<1.5)return {kind:'tip',label:'Tip stage · $10'};if(Math.hypot(x,z-.8)<1.5)return {kind:'dance',label:'Change dance-floor lights'};}if(inside.type==='casino'){const station=CASINO_STATIONS.map(s=>({...s,d:Math.hypot(x-s.x,z-s.z)})).sort((a,b)=>a.d-b.d)[0];if(station.d<1.25)return {kind:'casino',game:station.game,label:station.game==='sit'?(seated?'Stand up':'Sit in lounge'):['lobby','bar'].includes(station.game)?station.name:'Sit & play '+station.name};}if(Math.hypot(x-roomExit.x,z-roomExit.z)<2.3)return {kind:'leave',label:'Leave '+inside.name};if(['convenience','gun','garage'].includes(inside.type)&&Math.hypot(x-counter.x,z-counter.z)<2.4)return {kind:inside.type==='garage'?'garage':'shop',label:inside.type==='garage'?'Upgrades & contracts':inside.type==='gun'?'Browse weapons':'Buy scratch-off'};return null;}
  let best=null,dist=Infinity;for(const b of getView().buildings||[]){const d=Math.hypot(body.position.x-b.door.x,body.position.z-b.door.z);if(d<2.7&&d<dist&&!ruined(b)){best={kind:'building',building:b,label:'Enter '+b.name};dist=d;}}
  for(const item of [null,...lots.parked.filter(p=>p.level===getLevel()),...(getView().rideables||[])]){const b=item?.body||chassis,d=Math.hypot(body.position.x-b.position.x,body.position.z-b.position.z);if(d<4.6&&d<dist&&b.velocity.length()<1.5&&(!item||!item.exploded&&item.damage<=.3&&!item.occupied)){best={kind:'car',car:item,label:(item?.kind==='bike'?'Ride ':'Drive ')+(item?.name|| (item?'parked car':getCar().config.name))};dist=d;}}
  for(const person of crowd?.people||[]){if(person.robbed)continue;const pos=person.pose[0].p,d=Math.hypot(body.position.x-pos.x,body.position.z-pos.z);if(d<2.2&&d<dist){const from=new C.Vec3(body.position.x,body.position.y+.45,body.position.z),to=new C.Vec3(pos.x,pos.y,pos.z),hit=new C.RaycastResult();if(!world.raycastClosest(from,to,{collisionFilterMask:1|8,skipBackfaces:true},hit)||hit.distance>from.distanceTo(to)-.25){best={kind:'person',person,label:person.down?'Search pockets':'Rob pedestrian'};dist=d;}}}
  return best;
 }
 function rob(person){if(mode!=='foot'||inside||shopOpen||getState()!=='running')return false;const c=context();if(c?.kind!=='person'||c.person!==person)return false;const amount=crowd.takeCash(person);if(amount===null)return false;economy.earn(amount);notify('+$'+amount+' cash',1.5);ui();return true;}
 function interact(){if(getState()!=='running'||shopOpen)return false;const c=context();if(!c)return false;if(c.kind==='tip'){if(economy.spend(10)){clubRoom.tip();notify('Stage tip · $10',1.2);return true;}notify('Need $10 to tip');return false;}if(c.kind==='dance'){clubRoom.changeLights();notify('Dance-floor lights changed',1.2);return true;}return c.kind==='garage'?openGarage():c.kind==='drop'?hulk.drop():c.kind==='grab'?hulk.use():c.kind==='exit'?exitVehicle():c.kind==='leave'?leaveBuilding():c.kind==='shop'?openShop():c.kind==='casino'?openCasino(c.game):c.kind==='building'?enterBuilding(c.building):c.kind==='person'?rob(c.person):enterVehicle(c.car);}
 function renderShop(){const s=economy.info(),gun=inside?.type==='gun';$('shopTitle').textContent=gun?'Golden Arms':'Mint Mart';$('shopCash').textContent='$'+s.cash.toLocaleString();$('shopStock').replaceChildren();$('scratchArea').hidden=gun;
  if(gun){scratchUI.hide();for(const w of WEAPONS){const row=document.createElement('div');row.className='shop-row';const text=document.createElement('div');text.textContent=w.name;const small=document.createElement('small');small.textContent=s.owned.includes(w.id)?w.rounds?s.ammo[w.id]+' rounds':w.id==='web'?'Unlimited webs':'Unlimited swings':w.rounds?w.rounds+' rounds included':w.id==='web'?'Unlimited webs':'Unlimited swings';text.append(small);row.append(text);const buy=document.createElement('button');buy.textContent=s.owned.includes(w.id)?s.equipped===w.id?'Equipped':'Equip':'Buy · $'+w.price;buy.disabled=s.owned.includes(w.id)?s.equipped===w.id:s.cash<w.price;buy.onclick=()=>{s.owned.includes(w.id)?economy.equip(w.id):economy.buy(w.id);renderShop();};row.append(buy);if(s.owned.includes(w.id)&&w.refill){const refill=document.createElement('button');refill.textContent='+'+w.rounds+' · $'+w.refill;refill.disabled=s.cash<w.refill||s.ammo[w.id]>9999-w.rounds;refill.onclick=()=>{economy.refill(w.id);renderShop();};row.append(refill);}$('shopStock').append(row);}}
  else scratchUI.render();
 }
 function openGarage(){if(getState()!=='running'||shopOpen||context()?.kind!=='garage'||mode==='vehicle'&&chassis.velocity.length()>1.5)return false;closeShop();shopOpen=true;document.body.classList.add('menu-open');clearInput();garageUI.open();return true;}
 function openShop(){if(!inside||!['convenience','gun'].includes(inside.type))return false;closeShop();shopOpen=true;document.body.classList.add('menu-open');clearInput();$('shopPanel').hidden=false;renderShop();if(inside.type==='convenience')scratchUI.open();return true;}
 function openCasino(game){
  if(inside?.type!=='casino'||getState()!=='running'||shopOpen)return false;
  const x=body.position.x-origin,z=body.position.z;
  const station=seated&&seatStation?.game===game?seatStation:CASINO_STATIONS.filter(s=>s.game===game).sort((a,b)=>Math.hypot(x-a.x,z-a.z)-Math.hypot(x-b.x,z-b.z))[0];
  if(!station||!(seated&&seatStation===station)&&Math.hypot(x-station.x,z-station.z)>=1.25)return false;
  if(game==='sit'){setSeated(!seated,station);notify(seated?'Take a seat · move or interact to stand':'Back on your feet');return true;}
  closeShop();if(station.seatX!==undefined)setSeated(true,station);
  shopOpen=true;document.body.classList.add('menu-open');clearInput();casinoUI.open(game);return true;
 }
 function setSeated(value,station=null){if(value&&station){standingPos={x:body.position.x,z:body.position.z};seatStation=station;body.position.set(origin+station.seatX,.63,station.seatZ);}else if(standingPos){body.position.set(standingPos.x,.83,standingPos.z);standingPos=null;seatStation=null;}seated=value;avatar.position.set(body.position.x,body.position.y-.83,body.position.z);if(value)avatar.rotation.y=station.yaw||0;for(const leg of legs){leg.position.y=value?.55:.4;leg.rotation.x=value?-1.1:0;}for(const arm of arms)arm.rotation.x=value?-.7:0;}
 function closeShop(){scratchUI.hide();const wasOpen=shopOpen;shopOpen=false;document.body.classList.remove('menu-open');$('shopPanel').hidden=true;garageUI.hide();casinoUI.hide();if(seated&&seatStation?.game!=='sit')setSeated(false);fireHeld=false;walkX=walkY=0;if(wasOpen)clearInput();}
 $('closeShop').onclick=$('shopClose').onclick=closeShop;
 $('hulkButton').onclick=()=>{hulk.toggle();ui();};$('ripButton').onclick=()=>{hulk.split();ui();};$('interactButton').onclick=interact;$('weaponButton').onclick=cycleWeapon;
 const stick=$('walkStick');function stickMove(e){const r=stick.getBoundingClientRect();walkX=clamp((e.clientX-r.left-r.width/2)/(r.width*.36),-1,1);walkY=clamp((e.clientY-r.top-r.height/2)/(r.height*.36),-1,1);$('walkKnob').style.transform='translate('+walkX*26+'px,'+walkY*26+'px)';}
 stick.addEventListener('pointerdown',e=>{if(mode!=='foot'||stickPointer!==null)return;e.preventDefault();stickPointer=e.pointerId;stick.setPointerCapture(e.pointerId);stickMove(e);});stick.addEventListener('pointermove',e=>{if(e.pointerId===stickPointer)stickMove(e);});for(const ev of ['pointerup','pointercancel','lostpointercapture'])stick.addEventListener(ev,e=>{if(e.pointerId===stickPointer){stickPointer=null;walkX=walkY=0;$('walkKnob').style.transform='translate(0,0)';}});
 $('fireButton').addEventListener('pointerdown',e=>{e.preventDefault();$('fireButton').setPointerCapture(e.pointerId);fireHeld=true;if(hulk.active){hulk.use();hulk.latch();}});for(const ev of ['pointerup','pointercancel','lostpointercapture'])$('fireButton').addEventListener(ev,()=>fireHeld=false);
 function cycleWeapon(){const s=economy.info();if(!s.owned.length){notify('Buy tools at Golden Arms');return;}economy.equip(s.owned[(s.owned.indexOf(s.equipped)+1)%s.owned.length]);}
 function toolVisual(){const s=economy.info();if(toolId===s.equipped)return;toolId=s.equipped;tool.clear();if(!toolId)return;if(toolId==='web'){box(tool,.18,.12,.23,0,0,-.1,0xd8e8ee);box(tool,.06,.06,.07,0,0,-.25,0xf6fcff);return;}const w=toolId==='hammer'?.17:toolId==='grenade'?.3:.12,d=toolId==='machine'?.85:toolId==='grenade'?.68:.35;box(tool,w,.13,d,0,0,-d/2,0x34414a);box(tool,.1,.25,.12,0,-.1,-.06,0x836547);if(toolId==='hammer'){tool.children[0].scale.set(.4,.18,.2);tool.children[0].position.set(0,.24,0);tool.children[1].scale.set(.08,.55,.08);}}
 const rayFrom=new C.Vec3(),rayTo=new C.Vec3(),rayResult=new C.RaycastResult();
 function fire(){if(mode!=='foot'||shopOpen||getState()!=='running'||cooldown>0)return false;if(hulk.active)return hulk.use();const selected=WEAPONS.find(w=>w.id===economy.info().equipped);if(!selected)return false;
  if(inside&&seated)setSeated(false);if(selected.id==='grenade'&&projectiles.length>=12)return false;const w=economy.consume();if(!w){notify('Out of ammo · refill at Golden Arms');cooldown=.5;return false;}cooldown=w.rate;swing=.2;rayFrom.set(body.position.x,body.position.y+.64,body.position.z);let target=getAim();if(inside){const camera=getCamera().camera,end=camera.position.clone().addScaledVector(camera.getWorldDirection(new T.Vector3()),100);target=breakage.trace(camera.position,end)?.point||end;}aim.copy(target).sub(new T.Vector3().copy(rayFrom)).normalize();
  if(w.id==='web'){
   rayTo.set(rayFrom.x+aim.x*w.range,rayFrom.y+aim.y*w.range,rayFrom.z+aim.z*w.range);rayResult.reset();const hit=inside?breakage.trace(new T.Vector3().copy(rayFrom),new T.Vector3().copy(rayTo)):null;const outsideHit=!inside&&world.raycastClosest(rayFrom,rayTo,{collisionFilterMask:1|4|8,checkCollisionResponse:false,skipBackfaces:true},rayResult);const end=hit?.point||(outsideHit?rayResult.hitPointWorld:rayTo),normal=outsideHit?rayResult.hitNormalWorld:hit?new T.Vector3().copy(aim).negate():null,target=outsideHit?rayResult.body:null;webs.shoot(rayFrom,end,normal,target);if(target){crowd?.snare(target);if(target.mass>0&&!target.userData?.person){target.velocity.scale(.45,target.velocity);target.angularVelocity.scale(.6,target.angularVelocity);}}
  }else if(w.id==='grenade'){
   let p=grenadePool.find(p=>!p.active);if(!p){const mesh=new T.Mesh(sphere,mat(0xeac76e));mesh.scale.setScalar(.13);scene.add(mesh);p={mesh,p:new C.Vec3(),v:new C.Vec3(),active:false,life:0};grenadePool.push(p);}p.active=true;p.mesh.visible=true;p.p.copy(rayFrom);p.v.set(aim.x*26,aim.y*26+3,aim.z*26);p.life=1.7;p.power=w.power/24;projectiles.push(p);
  }else if(inside){breakage.strike(new T.Vector3().copy(rayFrom),aim,w.range,w.power);}
  else{rayTo.set(rayFrom.x+aim.x*w.range,rayFrom.y+aim.y*w.range,rayFrom.z+aim.z*w.range);rayResult.reset();if(world.raycastClosest(rayFrom,rayTo,{collisionFilterMask:1|4|8,checkCollisionResponse:false,skipBackfaces:true},rayResult))onHit(rayResult.body,new T.Vector3().copy(rayResult.hitPointWorld),w.power,w.id,aim);}
  return true;
 }
 function clearProjectiles(){webs.clear();for(const p of projectiles){p.active=false;p.mesh.visible=false;}projectiles.length=0;}
 function updateProjectiles(dt){for(let i=projectiles.length-1;i>=0;i--){const p=projectiles[i];p.life-=dt;p.v.y-=9.82*dt;rayTo.set(p.p.x+p.v.x*dt,p.p.y+p.v.y*dt,p.p.z+p.v.z*dt);rayResult.reset();const indoorHit=inside?breakage.trace(new T.Vector3().copy(p.p),new T.Vector3().copy(rayTo)):null;const hit=inside?!!indoorHit:world.raycastClosest(p.p,rayTo,{collisionFilterMask:1|4|8,checkCollisionResponse:false,skipBackfaces:true},rayResult);if(hit||p.life<=0){if(hit)p.p.copy(inside?indoorHit.point:rayResult.hitPointWorld);if(inside)breakage.blast(new T.Vector3().copy(p.p),p.power||1);else onBlast(new T.Vector3().copy(p.p),p.power||1);p.active=false;p.mesh.visible=false;projectiles.splice(i,1);}else{p.p.copy(rayTo);p.mesh.position.copy(p.p);}}}
 function indoorBlocked(x,z){return Math.abs(x)>7.5||Math.abs(z)>6.5||colliders.some(c=>!c.broken&&x>c.x-c.w/2-.35&&x<c.x+c.w/2+.35&&z>c.z-c.d/2-.35&&z<c.z+c.d/2+.35);}
 function beforeStep(dt,keys,pad){webs.update(dt);cooldown=Math.max(0,cooldown-dt);swing=Math.max(0,swing-dt);updateProjectiles(dt);refreshDoors();hulk.update(dt);if(mode!=='foot')return;
  let x=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0)+walkX+(pad.moveX||0),z=(keys.KeyS||keys.ArrowDown?1:0)-(keys.KeyW||keys.ArrowUp?1:0)+walkY+(pad.moveY||0),length=Math.hypot(x,z);if(length>1){x/=length;z/=length;}const cam=getCamera(),c=Math.cos(cam.yaw),s=Math.sin(cam.yaw),pace=hulk.active?5.6:4.2,vx=(c*x+s*z)*pace,vz=(-s*x+c*z)*pace;
  if(inside){breakage.update(dt);if(length>.1&&seated)setSeated(false);const px=body.position.x-origin,pz=body.position.z;if(!indoorBlocked(px+vx*dt,pz))body.position.x+=vx*dt;if(!indoorBlocked(body.position.x-origin,pz+vz*dt))body.position.z+=vz*dt;body.position.y=seated?.63:.83;}
  else{const limit=getLevel()===24?247:104,ox=getView().ox;body.velocity.x=body.position.x+vx*dt<ox-limit||body.position.x+vx*dt>ox+limit?0:vx;body.velocity.z=Math.abs(body.position.z+vz*dt)>limit?0:vz;}
  if(length>.1){anim+=dt*9;avatar.rotation.y=Math.atan2(-vx,-vz);}else avatar.rotation.y=cam.yaw;legs[0].rotation.x=Math.sin(anim)*(length>.1?.45:0);legs[1].rotation.x=-legs[0].rotation.x;arms[0].rotation.x=-legs[0].rotation.x;arms[1].rotation.x=legs[0].rotation.x-swing*5;tool.rotation.x=-swing*5;
  if(seated){avatar.rotation.y=seatStation?.yaw||0;for(const leg of legs){leg.position.y=.55;leg.rotation.x=-1.1;}arms[0].rotation.x=arms[1].rotation.x=-.7;}else for(const leg of legs)leg.position.y=.4;
  if(hulk.active){avatar.rotation.y=cam.yaw;hulk.pollUse(!!(fireHeld||keys.Space||pad.fire>.08));if(hulk.held){for(const arm of arms){arm.position.y=1.45;arm.rotation.x=-.7;}}else for(const arm of arms)arm.position.y=1.06;}else{for(const arm of arms)arm.position.y=1.06;if(fireHeld||keys.Space||pad.fire>.08){avatar.rotation.y=cam.yaw;fire();}}
 }
 function updateVisuals(dt){if(getState()!=='running')return;if(inside?.type==='casino')casinoRoom.update(dt,economy.info().casinoResult,casinoUI.busy&&casinoUI.game==='slots',seatStation?.z);if(inside?.type==='club')clubRoom.update(dt);}
 function afterStep(){hulk.follow();const cam=getCamera();if(inside?.type==='casino')casinoRoom.setFirstPerson(cam.first);if(!firstHands.parent)cam.camera.add(firstHands);firstHands.visible=mode==='foot'&&cam.first&&!shopOpen;if(firstToolId!==economy.info().equipped){firstToolId=economy.info().equipped;while(firstHands.children.length>2)firstHands.remove(firstHands.children.at(-1));toolVisual();const copy=tool.clone(true);copy.position.set(.1,-.18,-.47);copy.scale.setScalar(.7);firstHands.add(copy);}if(mode==='foot'){if(!inside&&body.position.y<-4){placeOutside(chassis.position.x+4,chassis.position.z,1,0);notify('Back on your feet');}avatar.position.set(body.position.x,body.position.y-.83,body.position.z);avatar.visible=!getCamera().first;toolVisual();tool.visible=!hulk.active;hulkVisual(hulk.active,!!hulk.held);}}
 function ui(){const running=getState()==='running',foot=mode==='foot',s=economy.info();document.body.classList.toggle('on-foot',foot);document.body.classList.toggle('indoors',!!inside);$('streetControls').hidden=!running||shopOpen;$('footControls').hidden=!running||!foot||shopOpen;$('crosshair').hidden=!running||!foot||shopOpen||(!s.equipped&&!hulk.active);
  current=context();$('interactButton').disabled=!current||mode==='vehicle'&&chassis.velocity.length()>1.5;$('interactButton').textContent=(current?.label||'Move closer')+(foot?' · X':' · ⧉');$('cashHUD').textContent='$'+s.cash.toLocaleString();const w=WEAPONS.find(w=>w.id===s.equipped);$('weaponButton').textContent=w?w.name+(w.rounds?' · '+s.ammo[w.id]:''):'Unarmed';$('footWeaponHUD').hidden=!running||!foot||shopOpen;$('footWeaponHUD').textContent=$('weaponButton').textContent+' · Y switch · RT use';$('fireButton').disabled=hulk.active?!hulk.held&&!hulk.nearest():!w;$('fireButton').textContent=hulk.active?hulk.held?'THROW':'GRAB':w?.id==='hammer'?'SWING':w?.id==='web'?'WEB':'FIRE';$('hulkButton').hidden=!foot||!!inside;$('hulkButton').textContent=hulk.active?'CALM DOWN · D↓':'HULK · D↓';$('hulkButton').setAttribute('aria-pressed',String(hulk.active));$('ripButton').hidden=!hulk.held;$('ripButton').textContent='SPLIT · LT';$('weaponButton').hidden=hulk.active;if(hulk.active)$('footWeaponHUD').textContent=hulk.held?'RT throw · LT split · X drop':'Hulk · RT / X grab · D↓ calm down';
  if(foot&&running){$('objectiveLabel').textContent=inside?'INSIDE · '+inside.name:hulk.active?'HULK':'ON FOOT';$('parkingHelp').textContent=current?.label|| (inside?'Explore the room':'Explore the neighborhood');$('objectiveHint').textContent=inside?['convenience','gun','garage'].includes(inside.type)?'Walk to the counter to shop · exit by the green mat':inside.type==='casino'?'Sit at a table to play · green mat to leave':'Walk to the green mat to leave':'Left stick / WASD · RT / Space to use tool';$('objectiveDistance').textContent='';$('objectiveArrow').style.transform='';if(!inside&&!current&&getLevel()===24){const next=(getView().buildings||[]).filter(b=>['convenience','gun','casino','garage','club'].includes(b.type)&&!ruined(b)).sort((a,b)=>Math.hypot(a.x-body.position.x,a.z-body.position.z)-Math.hypot(b.x-body.position.x,b.z-body.position.z))[0];if(next){const dx=next.door.x-body.position.x,dz=next.door.z-body.position.z,bearing=Math.atan2(-dx,-dz);$('parkingHelp').textContent=next.name;$('objectiveHint').textContent='Walk to the entrance · demolition earns more cash';$('objectiveDistance').textContent=Math.round(Math.hypot(dx,dz))+' m';$('objectiveArrow').style.transform='rotate('+((getCamera().yaw-bearing)*180/Math.PI)+'deg)';}}const contract=getContracts()?.getInfo();if(!inside&&!current&&contract?.active){const target=contract.target,dx=getView().ox+target.x-body.position.x,dz=target.z-body.position.z,bearing=Math.atan2(-dx,-dz);$('objectiveLabel').textContent=contract.title;$('parkingHelp').textContent=target.name;$('objectiveHint').textContent=contract.step;$('objectiveDistance').textContent=Math.round(Math.hypot(dx,dz))+' m';$('objectiveArrow').style.transform='rotate('+((getCamera().yaw-bearing)*180/Math.PI)+'deg)';}$('speed').textContent='0';$('vehicleFault').hidden=true;}
  if(shopOpen){firstHands.visible=false;$('footControls').hidden=true;$('streetControls').hidden=true;}
 }
 function reset(){crowd?.setVisible(true);hulk.stop();firstHands.visible=false;closeShop();if(inside){getView().group.visible=true;crowd?.setVisible(true);getCar().root.visible=true;}inside=null;seated=false;seatStation=null;breakage.clear();room.visible=false;world.removeBody(body);mode='vehicle';avatar.visible=false;resetInput();clearProjectiles();onExitCar();}
 function resetInput(){hulk.resetInput();walkX=walkY=0;fireHeld=false;stickPointer=null;cooldown=.2;$('walkKnob').style.transform='translate(0,0)';}
 function cameraTarget(){return mode==='foot'?new T.Vector3(body.position.x,body.position.y+(hulk.active?1.12:.6),body.position.z):null;}
 return{updateVisuals,webs,clubRoom,casinoRoom,garageUI,openGarage,hulk,breakage,casinoUI,scratchUI,openCasino,get menu(){return !$('garagePanel').hidden?garageUI.menu:!$('casinoPanel').hidden?casinoUI.menu:{menuRoot:$('shopPanel'),defaultButton:inside?.type==='convenience'?economy.info().ticket?'revealScratch':scratchUI.getInfo().selected?'buyScratch':'scratchGame-numbers':'closeShop'};},interact,rob,exitVehicle,enterVehicle,enterBuilding,leaveBuilding,openShop,closeShop,cycleWeapon,fire,reset,resetInput,beforeStep,afterStep,ui,cameraTarget,economy,body,room,refreshDoors,get mode(){return mode;},get inside(){return inside;},get shopOpen(){return shopOpen;},get focus(){return inside?new C.Vec3(inside.x,0,inside.z):mode==='foot'?body.position:chassis.position;},getInfo:()=>({playerDetailMeshes:likeness.meshCount,webs:webs.getInfo(),club:clubRoom.getInfo(),hulk:hulk.getInfo(),mode,inside:inside?.name||null,shopOpen,position:{...body.position},cash:economy.info().cash,owned:economy.info().owned,equipped:economy.info().equipped,ammo:economy.info().ammo,buildings:(getView().buildings||[]).length,interiorRooms:roomBuilt?1:0,roomObjects:room.children.length,grenades:projectiles.length,grenadePool:grenadePool.length,grenadeLimit:12,materials:mats.size,seated,seatGame:seatStation?.game||null,interiorBreakage:breakage.getInfo(),casino:casinoRoom.getInfo()})};
}
