import {createCasinoGames,blackjackValue,cardRank,cardSuit,pokerRank,SLOT_ICONS,SLOT_PAY,RED_NUMBERS,WHEEL_ORDER} from './casino-games.js?v=casino-19';
const SUITS=['♣','♦','♥','♠'],NAMES={slots:'Mango Five-Line',roulette:'European roulette',poker:'Draw poker',blackjack:'Blackjack'},LABELS={slots:'Slots',roulette:'Roulette',poker:'Poker',blackjack:'Blackjack'};
export function createCasinoUI(economy,onClose,canPlay=()=>false){
 const $=id=>document.getElementById(id),games=createCasinoGames(economy);let selected='lobby',seatGame=null,bet=10,bets=[],undo=[],busy=false,timer=null,animation=null,shownResult=null,message='';
 function button(label,id,action,parent,disabled=false){const b=document.createElement('button');b.type='button';b.textContent=label;b.id=id;b.disabled=disabled||busy;b.onclick=()=>{if(busy||$('casinoPanel').hidden||Object.hasOwn(NAMES,selected)&&!canPlay(selected))return;const focus=b.id;action();render();const next=$(focus);if(next&&!next.disabled)next.focus({preventScroll:true});};parent.append(b);return b;}
 function text(parent,value,tag='p',cls=''){const e=document.createElement(tag);e.textContent=value;e.className=cls;parent.append(e);return e;}
 function card(parent,c,id,action,held=false){const e=action?button('',id,action,parent):document.createElement('span');if(!action)parent.append(e);const suit=cardSuit(c),rank=cardRank(c);e.className='playing-card'+(suit===1||suit===2?' red':'')+(held?' held':'');e.textContent=(rank===14?'A':rank===13?'K':rank===12?'Q':rank===11?'J':rank)+SUITS[suit];if(action){e.setAttribute('aria-pressed',String(held));e.setAttribute('aria-label',e.textContent+' · '+(held?'held; select to replace':'select to hold'));text(e,held?'HOLD':'REPLACE','small');}return e;}
 function finishReveal(){if(timer!==null)clearTimeout(timer);timer=null;busy=false;animation=null;shownResult=games.info().result;if(!$('casinoPanel').hidden)render();}
 function act(fn,kind){if(seatGame!==selected||!canPlay(selected)){message='Sit at the corresponding table to play.';return;}shownResult=games.info().result;if(!fn()){message='Action unavailable · check your balance and hand.';return;}message='';busy=true;animation=kind;timer=setTimeout(finishReveal,kind==='roulette'?2200:kind==='slots'?1400:450);}
 const total=()=>bets.reduce((n,b)=>n+b.amount,0);
 function addChip(choice){if(total()+bet>Math.min(1000,economy.info().cash)){message='Not enough cash, or the $1,000 table limit was reached.';return;}if(bets.length>=24&&!bets.some(b=>b.choice===choice)){message='Maximum 24 betting positions.';return;}undo.push(bets.map(b=>({...b})));undo=undo.slice(-100);const b=bets.find(b=>b.choice===choice);if(b)b.amount+=bet;else bets.push({choice,amount:bet});message='';}
 function render(){const {pending:r,result:last}=games.info(),result=(busy?shownResult:last)?.game===selected?(busy?shownResult:last):null,account=economy.info(),stats=account.casinoStats;$('casinoCash').textContent='$'+account.cash.toLocaleString();$('casinoName').textContent=NAMES[selected]|| (selected==='bar'?'Velvet lounge':'Cashier & player card');
  for(const el of [$('casinoTabs'),$('casinoBets'),$('casinoVisual'),$('casinoChoices'),$('casinoActions')])el.replaceChildren();
  for(const [id,name]of Object.entries(LABELS)){if(id!==seatGame)continue;const b=button(name,'casinoTab-'+id,()=>{selected=id;message='';$('casinoContent').scrollTop=0;},$('casinoTabs'),!!r&&r.game!==id);b.classList.toggle('active',id===selected);b.setAttribute('aria-pressed',String(id===selected));}
  const infoButton=button('Player card','casinoTab-lobby',()=>selected='lobby',$('casinoTabs'));infoButton.classList.toggle('active',selected==='lobby');
  const playing=Object.hasOwn(NAMES,selected);document.querySelector('#casinoPanel .bet-label').hidden=!playing;$('casinoBets').hidden=!playing;
  if(playing)for(const amount of [10,20,50,100]){const b=button('$'+amount,'casinoBet-'+amount,()=>bet=amount,$('casinoBets'),!!r);b.className='casino-chip'+(bet===amount?' active':'');b.setAttribute('aria-pressed',String(bet===amount));}
  document.querySelector('#casinoPanel .bet-label').textContent=selected==='roulette'?'CHIP VALUE · TAP A POSITION TO ADD':'TOTAL STAKE';
  const visual=$('casinoVisual');visual.className=busy?'casino-busy casino-animate-'+animation:'';const actions=$('casinoActions'),choices=$('casinoChoices');
  if(playing&&r&&r.game!==selected){text(visual,'Your '+LABELS[r.game]+' hand is saved. Return to that table to finish it.');$('casinoRules').textContent='An unfinished hand keeps its original stake and cards.';$('casinoResult').textContent='No wager placed at this table.';$('casinoResume').textContent='Leave this seat and walk to '+LABELS[r.game]+'.';$('casinoLeave').textContent='Stand up';return;}
  if(selected==='slots'){
   const reels=text(visual,'','div','slot-grid'),values=result?.reels?.length===9?result.reels:[0,3,4,1,2,0,4,1,3],winning=new Set(result?.wins?.flatMap(w=>w.indices)||[]);for(const [i,index]of values.entries()){const e=text(reels,busy?'?':SLOT_ICONS[index],'span','slot-symbol'+(winning.has(i)&&!busy?' winning':''));e.setAttribute('aria-label',busy?'Reel spinning':['Cherry','Bell','Star','Seven','Diamond'][index]);e.style.setProperty('--reel-delay',(i%3)*.13+'s');}
   text(visual,busy?'Reels spinning…':'Five lines · three across + two diagonals','p','casino-table-caption');
   if(!busy&&result?.wins?.length)text(visual,result.wins.map(w=>'Line '+w.line+' +$'+w.amount).join(' · '));
   $('casinoRules').textContent='Stake is divided equally over five paylines. Three matching cherries/bells/stars/sevens/diamonds return 5×/10×/15×/25×/50× the line stake. Exactly two cherries return that line’s stake. Each line pays independently.';
  }else if(selected==='roulette'){
   const winner=result?.number,wheel=text(visual,'','div','roulette-wheel');wheel.style.background='conic-gradient('+WHEEL_ORDER.map((n,i)=>(n===0?'#397452':RED_NUMBERS.has(n)?'#953d52':'#192827')+' '+i*360/37+'deg '+(i+1)*360/37+'deg').join(',')+')';text(wheel,busy?'•':winner===undefined?'0':String(winner),'strong');
   text(visual,busy?'No more bets · ball is rolling…':'On the felt: $'+total()+' · chips $'+bet);
   const history=account.casinoHistory.filter(h=>h.game==='roulette'&&h.number!==undefined).slice(busy?-9:-8,busy?-1:undefined);if(history.length)text(visual,'Recent: '+history.map(h=>h.number).reverse().join(' · '),'p','casino-table-caption');
   const pick=(choice,label,parent)=>{const chip=bets.find(b=>b.choice===choice)?.amount||0,b=button(label+(chip?' · $'+chip:''),'roulette-'+choice,()=>addChip(choice),parent);b.className='roulette-pick '+(choice===0?'green':choice==='red'||Number.isInteger(choice)&&RED_NUMBERS.has(choice)?'red':choice==='black'||Number.isInteger(choice)?'black':'');b.classList.toggle('active',!!chip);b.setAttribute('aria-label',label+' · $'+chip+' placed; add $'+bet);};
   const grid=text(choices,'','div','roulette-grid');pick(0,'0',grid);for(let n=1;n<=36;n++)pick(n,String(n),grid);
   for(const [choice,label]of [['col1','Column 1'],['col2','Column 2'],['col3','Column 3'],['first','1–12'],['second','13–24'],['third','25–36'],['low','1–18'],['even','Even'],['red','Red'],['black','Black'],['odd','Odd'],['high','19–36']])pick(choice,label,choices);
   button('Undo chip','rouletteUndo',()=>{bets=undo.pop()||[];},choices,!undo.length);button('Clear felt','rouletteClear',()=>{bets=[];undo=[];},choices,!bets.length);
   $('casinoRules').textContent='Add chips to multiple positions. Number pays 35:1; dozens and columns 2:1; outside bets 1:1. One green zero loses outside bets. Maximum total stake $1,000. Recent results do not change the odds of the next spin.';
  }else if(selected==='poker'){
   const hand=text(visual,'','div','card-hand');for(const [i,c]of (r?.cards||result?.cards||[9,22,35,48,12]).entries())card(hand,c,'pokerHold-'+i,r?()=>games.hold(i):null,!!r?.held[i]);
   if(r){text(visual,pokerRank(r.cards).name+' · '+r.held.filter(Boolean).length+' held');text(visual,'Tap a card to HOLD it. Draw replaces every unheld card.');}
   $('casinoRules').textContent='Jacks or Better · one draw. Royal 800× · straight flush 50× · four 25× · full house 9× · flush 6× · straight 4× · three 3× · two pair 2× · jacks-or-better pair 1×. Returns include the original stake.';
  }else if(selected==='blackjack'){
   text(visual,'DEALER · '+(r?'showing '+blackjackValue([r.dealer[0]]):result?blackjackValue(result.dealer):'stands on 17'),'small');const dealer=text(visual,'','div','card-hand');for(const [i,c]of (r?.dealer||result?.dealer||[]).entries()){if(r&&i===1)text(dealer,'◆','span','playing-card card-back');else card(dealer,c);}
   const hands=r?.hands||result?.hands|| (result?[{cards:result.player,bet:result.bet}]:[]);hands.forEach((h,i)=>{const holder=text(visual,'','div','blackjack-hand'+(r?.active===i?' current':''));text(holder,'HAND '+(i+1)+' · $'+h.bet+' · '+blackjackValue(h.cards)+(r?.active===i?' · YOUR TURN':h.message?' · '+h.message:''),'small');const hand=text(holder,'','div','card-hand');for(const c of h.cards)card(hand,c);});
   $('casinoRules').textContent='Dealer stands on soft 17. Natural blackjack 3:2; regular wins 1:1. Double on a two-card hand for one extra card. Split equal ranks once into two hands; split aces receive one card each. Split 21 pays 1:1. No insurance or surrender.';
  }else{
   text(visual,selected==='bar'?'A quiet break between tables':'YOUR LUCKY MANGO PLAYER CARD','h3');
   text(visual,stats.rounds+' rounds · '+stats.wins+' profitable rounds');text(visual,'Casino record: '+(stats.returned-stats.wagered<0?'−':'+')+'$'+Math.abs(stats.returned-stats.wagered).toLocaleString()+' · best net win $'+stats.best.toLocaleString());
   const visited=Object.keys(NAMES).filter(g=>stats.played[g]);text(visual,'Tables tried: '+visited.length+'/4 · '+(visited.length===4?'All-rounder badge earned':visited.map(g=>LABELS[g]).join(', ')||'Explore a table to begin'));
   if(selected==='bar')text(visual,'The bar serves a complimentary mango soda. It doesn’t change the odds or your balance.');
   else {const history=text(choices,'','div','casino-ledger');for(const h of account.casinoHistory.slice(-6).reverse())text(history,LABELS[h.game]+' · stake $'+h.bet+' · returned $'+h.payout);}
   $('casinoRules').textContent='Casino cash is the same fictional wallet used at Mint Mart and Golden Arms. Earn more by completing demolition jobs. The player card tracks net results, not just payouts. Every wager and unfinished hand saves automatically.';
   if(selected==='bar')button('Sip mango soda','casinoDrink',()=>message='You enjoy a complimentary mango soda. Cheers!',actions);
   if(seatGame)button('Back to '+LABELS[seatGame],'casinoPlay',()=>selected=seatGame,actions);else text(actions,r?'Your '+LABELS[r.game]+' hand is saved at that table.':'Walk to a table or slot machine and take a seat.');
  }
  if(playing){if(r?.game==='blackjack'){const h=r.hands[r.active];button('Hit','casinoHit',()=>act(()=>games.hit(),'blackjack'),actions);button('Stand','casinoPlay',()=>act(()=>games.stand(),'blackjack'),actions);button('Double · $'+h.bet,'casinoDouble',()=>act(()=>games.double(),'blackjack'),actions,h.cards.length!==2||h.splitAces||account.cash<h.bet);button('Split · $'+h.bet,'casinoSplit',()=>act(()=>games.split(),'blackjack'),actions,r.hands.length!==1||h.cards.length!==2||cardRank(h.cards[0])!==cardRank(h.cards[1])||account.cash<h.bet);}else if(r?.game==='poker')button('Draw '+(5-r.held.filter(Boolean).length)+' cards','casinoPlay',()=>act(()=>games.draw(),'poker'),actions);else {const stake=selected==='roulette'?total():bet;button((selected==='slots'?'Spin five lines':selected==='roulette'?'Spin wheel':'Deal')+' · $'+stake,'casinoPlay',()=>act(()=>games.play(selected,bet,selected==='roulette'?bets:undefined),selected),actions,stake<10||account.cash<stake);}}
  $('casinoResult').textContent=busy?'Dealing…':message|| (r?'Hand saved · total stake $'+r.bet:result?result.message+' · Returned $'+result.payout+' · Net '+(result.payout-result.bet>=0?'+':'−')+'$'+Math.abs(result.payout-result.bet):'Choose your chips and take a seat.');
  if(busy)$('casinoResult').textContent=animation==='roulette'?'Ball in motion…':animation==='slots'?'Reels in motion…':'Dealing…';
  $('casinoResume').textContent=r?'Leaving saves this exact hand.':'Game cash only · no purchases or cash-out';$('casinoLeave').textContent=seatGame?'Stand up':'Back to casino floor';
 }
 $('casinoLeave').onclick=$('casinoClose').onclick=onClose;
 return{games,finishReveal,open(game){finishReveal();seatGame=Object.hasOwn(NAMES,game)?game:null;selected=game;bet=games.info().pending?.unitBet||games.info().pending?.bet||bet;message='';$('casinoPanel').hidden=false;render();$('casinoContent').scrollTop=0;},hide(){ $('casinoPanel').hidden=true;finishReveal();},render,get busy(){return busy;},get menu(){return {menuRoot:$('casinoPanel'),defaultButton:$('casinoPlay')?'casinoPlay':'casinoLeave'};}};
}
