import {tunedConfig,vehicleKey,paintVehicle,disposeVehiclePaint} from './garage-upgrades.js?v=street-27';
import {createDemolitionContracts} from './demolition-contracts.js?v=street-27';
import {createBikeDynamics} from './bike-dynamics.js?v=street-22';
import {createWorldBoundary} from './world-boundary.js?v=street-20';
import {createStreetLife} from './street-life.js?v=street-27';
import {createDestructionLoop} from './destruction-loop.js?v=street-17';
import {createSky} from './scenery-detail.js?v=street-22';
import {createXboxControls} from './xbox-controls.js?v=street-24';
import {buildGoldenVehicle} from './golden-fleet.js?v=street-27';
import {buildMonsterTruck} from './monster-truck.js?v=street-27';
import {createVehicleMotion,motorForce} from './vehicle-motion.js?v=smooth-9';
import {SECRET_LEVEL,DISTRICTS,buildSecretCity} from './secret-city.js?v=street-27';
import {createDestructionObjective,createBarrelEffects} from './destruction-objective.js?v=street-22';
import {buildDetailedVehicle} from './detailed-vehicles.js?v=street-27';
import {createRunScoring} from './run-scoring.js?v=endless-15';
import {createVanFailures} from './van-failures.js?v=game-5';
import {sizeChallengeVehicle} from './vehicle-sizing.js?v=game-5';
import {createHitFeedback} from './hit-feedback.js?v=clarity-14';
import {createParkedTraffic} from './parked-traffic.js?v=street-27';
import {createPedestrians} from './pedestrians.js?v=street-24';
import * as C from './cannon-es.js';
import {installTouchGuard} from './touch-guard.js?v=street-27';
import {buildRoadster} from './roadster-model.js?v=gold-8';
import {VEHICLES} from './garage-models.js?v=game-5';
import {createCrashDirector} from './crash-replay.js?v=fleet-1';
import {createDestructibleEnvironment} from './destructible-environment.js?v=street-27';
import {createDestructibleTerrain} from './destructible-terrain.js?v=clarity-14';
import {LOTS,buildLots,assessParking,completedThrough,isLotUnlocked,nextLotIndex} from './parking-lots.js?v=street-26';
const T=window.THREE,$=id=>document.getElementById(id),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
installTouchGuard();
try{boot()}catch(e){console.error(e);$('fatal').hidden=false;$('errorText').textContent=e.message;}
function boot(){
const scene=new T.Scene();const sky=createSky(T,scene);scene.background=new T.Color(0xb9c9bc);scene.fog=new T.Fog(0xb9c9bc,110,240);
const renderer=new T.WebGLRenderer({canvas:$('view'),antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
const camera=new T.PerspectiveCamera(54,1,.15,520);scene.add(new T.HemisphereLight(0xfff3d9,0x667d50,1.5));
const sun=new T.DirectionalLight(0xffdfaa,2.5);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-23,right:23,top:23,bottom:-23,near:1,far:120});sun.shadow.bias=-.0007;sun.shadow.normalBias=.035;scene.add(sun,sun.target);
const world=new C.World({gravity:new C.Vec3(0,-9.82,0),allowSleep:true});world.broadphase=new C.SAPBroadphase(world);world.solver.iterations=8;world.defaultContactMaterial.friction=.45;world.defaultContactMaterial.restitution=.12;
const tireProxyMat=new C.Material({friction:.06,restitution:.05}),skidMat=new C.Material({friction:.1,restitution:.04});
const groundMat=new C.Material('ground'),carMat=new C.Material('car'),rampMat=new C.Material('launch deck');world.addContactMaterial(new C.ContactMaterial(carMat,rampMat,{friction:.025,restitution:0}));world.addContactMaterial(new C.ContactMaterial(tireProxyMat,rampMat,{friction:.015,restitution:0}));world.addContactMaterial(new C.ContactMaterial(skidMat,rampMat,{friction:.015,restitution:0}));world.addContactMaterial(new C.ContactMaterial(carMat,groundMat,{friction:.35,restitution:.1}));
const ground=new C.Body({mass:0,material:groundMat,shape:new C.Plane()});ground.quaternion.setFromEuler(-Math.PI/2,0,0);ground.updateAABB();world.addBody(ground);
const palette={road:0x535956,grass:0x84986a,dirt:0xb5a27c,wood:0x776346,hay:0xc2a258,red:0x9d4638,stone:0x89908a,white:0xede5cf};
const mat=(c,r=.9)=>new T.MeshStandardMaterial({color:c,roughness:r});const mats=Object.fromEntries(Object.entries(palette).map(([k,c])=>[k,mat(c)]));
const unitBox=new T.BoxGeometry(1,1,1),unitSphere=new T.IcosahedronGeometry(1,1);
function visualBox(w,h,d,material,x=0,y=0,z=0){const m=new T.Mesh(unitBox,material);m.scale.set(w,h,d);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;return m;}
function boxBody(w,h,d,mass,x,y,z,quaternion=null){const b=new C.Body({mass,material:mass?carMat:groundMat,shape:new C.Box(new C.Vec3(w/2,h/2,d/2)),position:new C.Vec3(x,y,z)});if(quaternion)b.quaternion.copy(quaternion);world.addBody(b);return b;}
scene.add(camera);const boundary=createWorldBoundary({T,C,world,groundMat});
const lots=buildLots({T,C,scene,world,groundMat}),obstacles=lots.obstacles,loose=[],sparks=[],sparkPool=[],sparkMaterials=[new T.MeshBasicMaterial({color:0xffba56}),new T.MeshBasicMaterial({color:0xfff4c5})];
const barrelEffects=createBarrelEffects(T,scene);let contracts=null;let secretView=null,objective=null,destructionLoop=null,objectiveClock=0,secretClear=null;try{secretClear=JSON.parse(localStorage.getItem('parkside-streets-secret-clear-v1')||'null');}catch{}
const environment=createDestructibleEnvironment({T,C,world,lots,onContact:(entry,body,speed,impactBody)=>contracts?.contact(entry,body,speed,impactBody),onExplode:(point,strength)=>{barrelEffects.show(point);traffic.blast(point,strength);crowd.blast(point,strength);burst(point,18);crashSound(32);}}),terrain=createDestructibleTerrain({T,C,scene,world,ground});
let gateProgress=0;
let runScore=0;
const scoring=createRunScoring();
const failures=createVanFailures({random:rand,onLoosePart:()=>{syncCar();const parts=car.assemblies.filter(p=>p.userData.attached&&(p.name.startsWith('mirror-')||p.name.startsWith('exhaust-')));if(parts.length)detach(parts[Math.floor(rand()*parts.length)],0);}});
let seed=842,totalLost=0,levelIndex=0,parkingHold=0,parkingState=null,bumps=0,lastDirection=0,reverseTravel=0,selectedGear=1;
let saves=[];try{saves=JSON.parse(localStorage.getItem('parkside-chaos-saves-v1')||'[]');if(!Array.isArray(saves))saves=[];}catch{}
function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
const baseComplete=()=>completedThrough(saves,8),goldUnlocked=()=>completedThrough(saves,LOTS.length),unlocked=i=>i===LOTS.length?goldUnlocked():isLotUnlocked(i,saves),isSecret=()=>levelIndex===LOTS.length;
let completionNext=null;
const lot=()=>isSecret()?SECRET_LEVEL:LOTS[levelIndex],view=()=>lots.views[levelIndex];
const garage=VEHICLES.map(config=>sizeChallengeVehicle(T,config.id==='roadster'?buildRoadster(T):buildDetailedVehicle(T,config),config));
let savedVehicle='';try{savedVehicle=localStorage.getItem('parkside-chaos-car')||'';}catch{}
let vehicleIndex=Math.max(0,VEHICLES.findIndex(v=>v.id===savedVehicle.replace(/-gold$/,''))),goldenMode=goldUnlocked()&&savedVehicle.endsWith('-gold');
const goldenGarage=new Map();let monster=null;for(const item of garage){scene.add(item.root);item.root.visible=false;}
function goldenItem(index){if(!goldenGarage.has(index)){const item=buildGoldenVehicle(T,garage[index]);goldenGarage.set(index,item);scene.add(item.root);}return goldenGarage.get(index);}
function monsterItem(){if(!monster){monster=buildMonsterTruck(T);monster.root.visible=false;scene.add(monster.root);}return monster;}
let car=goldenMode?goldenItem(vehicleIndex):garage[vehicleIndex],spec=car.config;car.root.visible=true;
const chassis=new C.Body({mass:950,allowSleep:false,material:carMat,position:new C.Vec3(0,1.2,0),linearDamping:.025,angularDamping:.48});chassis.addShape(new C.Box(new C.Vec3(1.16,.26,2.28)),new C.Vec3(0,.05,0));world.addBody(chassis);
const vehicle=new C.RaycastVehicle({chassisBody:chassis,indexRightAxis:0,indexUpAxis:1,indexForwardAxis:2});
const traffic=createParkedTraffic({T,C,scene,world,lots,garage,onWreck:point=>{barrelEffects.show(point);burst(point,16);crashSound(30);}});
const hitFeedback=createHitFeedback();
const crowd=createPedestrians({T,C,scene,world,chassis,groundMat,onThrownImpact:(body,point,power)=>{if(state!=='running')return;environment.strike(body,point,power);traffic.strike(body,point,power);burst(point,5);crashSound(power*.4);},getImpactView:()=>({first:firstPerson&&streetLife.mode==='vehicle'&&!spec.bike,eyeX:car.root.userData.steeringX||-.42,eyeY:spec.monster?3.55:1.45,offset:spec.offset,halfWidth:spec.halfWidth||spec.box[0]}),onHit:()=>{if(state!=='running')return;const award=scoring.hit(time);if(award){runScore=award.pending;hitFeedback.show(award.points,runScore,award.combo,spec.scoreMultiplier);}}});
const replayExtras={snapshot:()=>({crowd:crowd.snapshot(),traffic:traffic.snapshot(),environment:environment.snapshot(),terrain:terrain.snapshot()}),apply:(a,b,u)=>{if(a&&b){crowd.apply(a.crowd,b.crowd,u);traffic.apply(a.traffic,b.traffic,u);environment.apply(a.environment,b.environment,u);terrain.apply(a.terrain,b.terrain,u);}}};
for(const z of [-1.48,1.45])for(const x of [-1.04,1.04])vehicle.addWheel({radius:.525,directionLocal:new C.Vec3(0,-1,0),axleLocal:new C.Vec3(-1,0,0),chassisConnectionPointLocal:new C.Vec3(x,-.04,z),suspensionStiffness:32,suspensionRestLength:.29,maxSuspensionTravel:.22,frictionSlip:3.4,dampingRelaxation:2.3,dampingCompression:4.4,maxSuspensionForce:90000,rollInfluence:.07,customSlidingRotationalSpeed:-25,useCustomSlidingRotationalSpeed:true});vehicle.addToWorld(world);
// Tires can climb solid rubble and damaged cars; tiny detached trim and pedestrian
// sensors do not become suspension platforms. The chassis still collides with all.
const castWheelRay=vehicle.castRay.bind(vehicle),groundRay=(from,to,result)=>world.raycastClosest(from,to,{skipBackfaces:true,collisionFilterMask:1|8},result);
vehicle.castRay=wheel=>{if(!spec.monster)return castWheelRay(wheel);const rayTest=world.rayTest;world.rayTest=groundRay;try{return castWheelRay(wheel);}finally{world.rayTest=rayTest;}};
let wheelParts=vehicle.wheelInfos.map((w,i)=>car.assemblies.find(p=>p.name===(spec.bike?'wheel-'+(i===0?'front':'rear'):'wheel-'+(i<2?'front':'rear')+'-'+(i%2?'left':'right'))));
const visualWheelAngle=[0,0,0,0],visualWheelOmega=[0,0,0,0],visualWheelSlip=[0,0,0,0];
const bikeDynamics=createBikeDynamics(C),vehicleMotion=createVehicleMotion(T),fixedStep=1/60;let physicsAccumulator=0;
const wheelPointVelocity=new C.Vec3(),wheelForwardLocal=new C.Vec3(),wheelForwardWorld=new C.Vec3();
function resetVisualWheelSpin(){visualWheelAngle.fill(0);visualWheelOmega.fill(0);visualWheelSlip.fill(0);}
function updateVisualWheelSpin(dt){
 for(let i=0;i<vehicle.wheelInfos.length;i++){
  const w=vehicle.wheelInfos[i],part=wheelParts[i];
  if(!part?.userData.attached){visualWheelOmega[i]=0;visualWheelSlip[i]=0;continue;}
  const steering=(spec.bike?i===0:i<2)?w.steering:0;
  wheelForwardLocal.set(-Math.sin(steering),0,-Math.cos(steering));
  chassis.vectorToWorldFrame(wheelForwardLocal,wheelForwardWorld);
  chassis.getVelocityAtWorldPoint(w.chassisConnectionPointWorld,wheelPointVelocity);
  const longitudinal=wheelForwardWorld.dot(wheelPointVelocity),radius=Math.max(.05,w.radius),roadOmega=longitudinal/radius;
  const fullBrake=(spec.bike?i===1:i>=2)&&input.handbrake?70:40,brakeRatio=clamp((Math.abs(w.brake)*950/spec.mass-8)/Math.max(1,fullBrake-8),0,1);
  let targetOmega=roadOmega;
  if(w.isInContact){
   if(brakeRatio>0&&Math.abs(longitudinal)>.12){
    const minimumRolling=(spec.bike?i===1:i>=2)&&input.handbrake?.22:.48;
    targetOmega*=1-brakeRatio*(1-minimumRolling);
   }
   const engineRatio=clamp(Math.abs(w.engineForce)/(spec.power||1),0,1);
   if(w.sliding&&engineRatio>.01&&Math.abs(longitudinal)<6){
    const launchSlip=(1-clamp(Math.abs(longitudinal)/6,0,1))*engineRatio;
    targetOmega+=Math.sign(w.engineForce||1)*launchSlip*5;
   }
   visualWheelSlip[i]=Math.abs(roadOmega-targetOmega)/Math.max(.5,Math.abs(roadOmega));
   // Rolling contact is distance / radius, with no throttle-dependent lag.
   visualWheelOmega[i]=targetOmega;
  }else{
   visualWheelSlip[i]=1;
   if(Math.abs(w.engineForce)>0){
    const freeTarget=Math.sign(w.engineForce)*(10+8*clamp(Math.abs(w.engineForce)/(spec.power||1),0,1));
    visualWheelOmega[i]+=(freeTarget-visualWheelOmega[i])*(1-Math.exp(-dt*7));
   }else visualWheelOmega[i]*=Math.exp(-dt*1.8);
  }
  if(Math.abs(longitudinal)<.025&&Math.abs(w.engineForce)<1)visualWheelOmega[i]*=Math.exp(-dt*10);
  visualWheelAngle[i]+=visualWheelOmega[i]*dt;
  if(Math.abs(visualWheelAngle[i])>Math.PI*4096)visualWheelAngle[i]%=Math.PI*2;
 }
}
let mode='run',state='menu',health=100,time=0,distance=0,passed=0,speed=0,forwardSpeed=0,steer=0,cameraMode=0,clock=0,physicsTime=0,lastImpact=-10,flash=0,noticeUntil=0,countdown=0,deadTime=0,penalty=0,slow=false,wreckTime=0,pendingHit=null,pausedFrom='running';const keys={},touch={};let input={};
const camGoal=new T.Vector3(),camLook=new T.Vector3(),look=new T.Vector3(),carPos=new T.Vector3();let camInit=false;
let controller=null,padInput={gas:0,brake:0,steering:0,handbrake:false};
const wheel=$('steeringWheel');let wheelAngle=0,wheelPointer=null,wheelLast=0;
const director=createCrashDirector({T,scene,camera,parts:car.assemblies,obstacles,extras:replayExtras,onComplete:showWreck});
function wheelPolar(e){const r=wheel.getBoundingClientRect();return Math.atan2(e.clientX-r.left-r.width/2,-(e.clientY-r.top-r.height/2));}
wheel.addEventListener('pointerdown',e=>{if(state!=='running'&&state!=='countdown')return;if(wheelPointer!==null)return;e.preventDefault();wheelPointer=e.pointerId;wheelLast=wheelPolar(e);wheel.setPointerCapture(e.pointerId);resumeAudio();});
wheel.addEventListener('pointermove',e=>{if(e.pointerId!==wheelPointer)return;e.preventDefault();const a=wheelPolar(e);let delta=a-wheelLast;if(delta>Math.PI)delta-=Math.PI*2;if(delta<-Math.PI)delta+=Math.PI*2;wheelAngle=clamp(wheelAngle+delta*180/Math.PI,-135,135);wheelLast=a;paintWheel();});
function releaseWheel(e){if(e.pointerId===wheelPointer)wheelPointer=null;}
wheel.addEventListener('pointerup',releaseWheel);wheel.addEventListener('pointercancel',releaseWheel);wheel.addEventListener('lostpointercapture',releaseWheel);
function paintWheel(){const keyboard=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0),angle=keyboard?keyboard*95:wheelPointer!==null?wheelAngle:padInput.active?padInput.steering*135:wheelAngle;$('wheelArt').style.transform='rotate('+angle+'deg)';wheel.setAttribute('aria-valuenow',String(Math.round(angle)));}
function updateWheel(dt){if(wheelPointer===null)wheelAngle*=Math.exp(-dt*7);if(Math.abs(wheelAngle)<.05)wheelAngle=0;paintWheel();}
function notify(message,seconds=2){$('notice').textContent=message;noticeUntil=clock+seconds;$('notice').style.opacity='1';}
function syncCar(){car.root.position.copy(chassis.position);car.root.quaternion.copy(chassis.quaternion);car.root.position.add(new T.Vector3(0,-spec.offset,0).applyQuaternion(car.root.quaternion));if(spec.bike)car.root.rotateZ(bikeDynamics.lean);car.root.updateMatrixWorld(true);for(let i=0;i<vehicle.wheelInfos.length;i++){const p=wheelParts[i];if(!p.userData.attached)continue;const w=vehicle.wheelInfos[i],physicsRotation=w.rotation,contact=w.isInContact;w.rotation=visualWheelAngle[i];vehicle.updateWheelTransform(i);w.rotation=physicsRotation;w.isInContact=contact;const t=w.worldTransform;const local=new T.Vector3().copy(t.position);car.root.worldToLocal(local);p.position.copy(local);p.quaternion.copy(car.root.quaternion).invert().multiply(new T.Quaternion().copy(t.quaternion));}if(spec.bike){const rider=car.root.getObjectByName('rider');if(rider)rider.visible=streetLife?.mode==='vehicle'&&!firstPerson;const fork=car.root.getObjectByName('fork');if(fork)fork.rotation.y=steer;}}
// Integrate once per fixed step, even on displays rendering faster than physics.
world.addEventListener('postStep',()=>updateVisualWheelSpin(world.dt));
function resetVehicleMotion(){physicsAccumulator=0;syncCar();vehicleMotion.capture(car,true);}
function restore(){chassis.collisionResponse=true;chassis.collisionFilterMask=-1;for(const d of loose){world.removeBody(d.body);scene.remove(d.mesh)}loose.length=0;for(const p of car.assemblies){car.root.add(p);p.position.copy(p.userData.home);p.quaternion.identity();p.scale.set(1,1,1);p.userData.attached=true;p.visible=true;}for(const w of vehicle.wheelInfos){w.radius=spec.radius;w.suspensionStiffness=(spec.bike?65:spec.monster?52:32)*(spec.springMultiplier||1);w.frictionSlip=spec.monster?5:3.4;}resetVisualWheelSpin();health=100;}
function detach(part,kick=0,all=false){if(spec.golden)return;if(!part||!part.userData.attached||(!all&&(part.name==='chassis'||part.name==='tub')))return;part.userData.attached=false;totalLost++;scene.attach(part);const sz=part.userData.size;const body=boxBody(clamp(sz.x,.12,2.3),clamp(sz.y,.12,1.4),clamp(sz.z,.12,2.6),part.name==='engine'?65:part.name==='chassis'?90:part.name==='tub'?45:part.name.startsWith('wheel')?25:12,part.position.x,part.position.y,part.position.z);body.quaternion.copy(part.quaternion);body.velocity.copy(chassis.velocity);const outward=new T.Vector3(part.position.x-chassis.position.x,0,part.position.z-chassis.position.z).normalize();body.velocity.x+=outward.x*kick*.7+(rand()-.5)*4;body.velocity.y+=1+rand()*3+kick*.27;body.velocity.z+=outward.z*kick*.7+(rand()-.5)*4;body.angularVelocity.set((rand()-.5)*8,(rand()-.5)*8,(rand()-.5)*8);body.collisionFilterGroup=2;body.collisionFilterMask=1;body.sleepSpeedLimit=.35;loose.push({mesh:part,body,age:0});let i=wheelParts.indexOf(part);if(i>=0){vehicle.wheelInfos[i].radius=.14;vehicle.wheelInfos[i].suspensionStiffness=8;vehicle.wheelInfos[i].frictionSlip=.4;}while(loose.length>64){const d=loose.shift();world.removeBody(d.body);scene.remove(d.mesh);}}
function burst(point,strength){for(let i=0;i<Math.min(18,5+strength);i++){let p=sparkPool.find(p=>!p.active);if(!p&&sparkPool.length<72){const mesh=new T.Mesh(unitBox,sparkMaterials[i%2]);mesh.scale.set(.035,.035,.16);p={mesh,v:new T.Vector3(),life:0,active:false};sparkPool.push(p);}if(!p)break;p.active=true;p.mesh.position.copy(point);p.mesh.visible=true;scene.add(p.mesh);p.v.set((rand()-.5)*9,rand()*6,(rand()-.5)*9);p.life=.5+rand()*.5;sparks.push(p);}flash=Math.min(.65,strength/35);}

// Defer all body mutations until after the physics solver finishes its step.
chassis.addEventListener('collide',event=>{if(state!=='running'||streetLife?.mode==='foot'||physicsTime-lastImpact<.7)return;const impact=Math.abs(event.contact.getImpactVelocityAlongNormal());if(impact<.8||event.body.collisionFilterGroup===2)return;const kind=event.body.userData?.kind;if(kind==='pedestrian'||kind==='ramp')return;if(event.body===ground&&impact<8)return;const cp=event.contact.bi===chassis?event.contact.ri:event.contact.rj;const point=new T.Vector3(chassis.position.x+cp.x,chassis.position.y+cp.y,chassis.position.z+cp.z);if(!pendingHit||impact>pendingHit.impact)pendingHit={impact,kind:event.body===ground?'ground':kind,point,velocity:new T.Vector3().copy(chassis.velocity)};});
function goldenImpact(hit){lastImpact=physicsTime;health=100;parkingHold=0;if(hit.kind==='ground')return;if(spec.monster){burst(hit.point,Math.min(12,hit.impact));crashSound(Math.min(18,hit.impact));return;}const strength=clamp(hit.impact/8,.8,1.8);environment.blast(hit.point,strength);traffic.blast(hit.point,strength);burst(hit.point,Math.min(12,hit.impact));crashSound(Math.min(10,hit.impact));if(hit.velocity.length()>1){chassis.velocity.x=hit.velocity.x*.8;chassis.velocity.z=hit.velocity.z*.8;chassis.wakeUp();}}
function handleHit(hit){if(spec.golden){goldenImpact(hit);return;}lastImpact=physicsTime;bumps++;parkingHold=0;const damage=clamp((hit.impact-2.7)*(hit.kind==='hay'?1.1:1.8)/(spec.armorMultiplier||1),1,60);health=Math.max(0,health-damage);if(hit.impact>=6.5*(spec.armorMultiplier||1)||health<=20){beginWreck(hit);return;}burst(hit.point,hit.impact);crashSound(hit.impact);const candidates=car.assemblies.filter(p=>p.userData.attached&&(p.name.startsWith('fender')||p.name.startsWith('pipes')||p.name==='grille'||p.name==='rear-bumper'));candidates.sort((a,b)=>a.getWorldPosition(new T.Vector3()).distanceToSquared(hit.point)-b.getWorldPosition(new T.Vector3()).distanceToSquared(hit.point));if(hit.impact>5)detach(candidates[0],2);notify('Scraped it — keep going',1.3);}
function beginWreck(hit){if(spec.golden){goldenImpact(hit);return;}if(state==='wreck'||state==='replay'||state==='wreckReview')return;syncCar();director.record(physicsTime,true);const forward=hit.velocity.clone();forward.y=0;if(forward.length()<1)forward.set(0,0,-1).applyQuaternion(car.root.quaternion);forward.normalize();director.mark({point:hit.point,forward,speed:Math.max(hit.impact,hit.velocity.length())},physicsTime);scoring.bank({parked:false,lot:levelIndex,vehicle:spec.id});state='wreck';const blastStrength=Math.max(.8,hit.impact/16);traffic.blast(hit.point,blastStrength);environment.blast(hit.point,blastStrength);terrain.blast(hit.point,blastStrength);wreckTime=0;clearInput();health=0;const kick=clamp(hit.impact*.42,6,13);for(const part of car.assemblies)detach(part,kick,true);chassis.collisionResponse=false;chassis.collisionFilterMask=0;document.body.classList.add('cinematic');$('replayHUD').hidden=false;$('replayTitle').textContent='WRECKED';$('replayAngle').textContent='REPLAY INCOMING';$('replayProgress').style.width='0%';$('impactStats').textContent=Math.round(Math.max(hit.impact,hit.velocity.length())*2.237)+' MPH / '+car.assemblies.length+' PARTS SCATTERED';$('skipReplay').textContent='Skip →';flash=.85;crashSound(35);}
function explode(){if(state!=='running')return;beginWreck({impact:25,point:new T.Vector3().copy(chassis.position),velocity:new T.Vector3().copy(chassis.velocity)});}
function startReplay(){state='replay';clearInput();$('wreckPanel').hidden=true;$('replayHUD').hidden=false;$('replayTitle').textContent='INSTANT REPLAY';$('skipReplay').textContent='Skip replay →';document.body.classList.add('cinematic');if(!director.begin())showWreck();}
function showWreck(){state='wreckReview';$('replayHUD').hidden=true;$('wreckPanel').hidden=false;const info=director.getImpact();$('wreckSpeed').textContent=Math.round((info?.speed||0)*2.237);$('wreckParts').textContent=car.assemblies.filter(p=>!p.userData.attached).length;$('wreckPenalty').textContent='25% of earned points banked';renderScoreResults('wreckScoring',scoring.snapshot(time).result);}
function continueWreck(){start();}
$('skipReplay').onclick=()=>{director.stop();showWreck();};$('continueWreck').onclick=continueWreck;$('watchAgain').onclick=startReplay;
function recover(initial=false){streetLife?.reset();const preserveScore=spec.golden&&!initial;gateProgress=0;const resetWorld=initial||!isSecret();if(resetWorld){environment.reset(levelIndex);terrain.reset(view().ox,lot().style);barrelEffects.clear();}if(initial){contracts?.reset();for(const item of view().rideables||[]){item.body.position.copy(item.homePosition);item.body.quaternion.copy(item.homeQuaternion);item.body.aabbNeedsUpdate=true;item.mesh.position.copy(item.homePosition);item.mesh.position.y=0;item.mesh.quaternion.copy(item.homeQuaternion);}objective?.reset();objectiveClock=0;}if(!preserveScore){scoring.reset(spec.scoreMultiplier);runScore=0;}failures.reset(spec.id==='e250');hitFeedback.clear();if(initial)crowd.reset(levelIndex,view().ox,isSecret()?{count:160,routes:secretView.routes}:{});pendingHit=null;director.reset();restore();if(resetWorld)traffic.reset(levelIndex);const [x,z,yaw]=lot().spawn;chassis.position.set(view().ox+x,Math.max(1.05,spec.offset+.2),z);chassis.quaternion.setFromEuler(0,yaw,0);chassis.velocity.setZero();chassis.angularVelocity.setZero();chassis.force.setZero();chassis.torque.setZero();chassis.aabbNeedsUpdate=true;chassis.wakeUp();for(let i=0;i<vehicle.wheelInfos.length;i++){const w=vehicle.wheelInfos[i];w.rotation=0;w.deltaRotation=0;w.suspensionLength=spec.suspension||.29;vehicle.applyEngineForce(0,i);vehicle.setBrake(0,i);}steer=0;wheelAngle=0;parkingHold=0;lastDirection=0;reverseTravel=0;selectedGear=1;lastImpact=physicsTime+.4;camInit=false;orbitMode='follow';paintCamera();orbitPitch=.52;orbitDistance=spec.monster?18:13;clearInput();if(!initial){if(spec.golden)notify('Golden recovery · no penalty',1.2);else{bumps++;penalty+=10;notify('Unbanked points lost · reset +10s');}}resetVehicleMotion();if(initial&&isSecret()){destructionLoop.reset();secretView.detail.update(0,chassis.position.x-view().ox,chassis.position.z,true);}}
function useLevelVehicle(){releaseBorrowed();director.reset();restore();car.root.visible=false;car=isSecret()?monsterItem():goldenMode?goldenItem(vehicleIndex):garage[vehicleIndex];spec=car.config;car.root.visible=true;configureVehicle();}
function loadLevel(i){i=clamp(i,0,LOTS.length);if(!unlocked(i))return false;if(i===LOTS.length){ensureSecretCity();goldenMode=true;}streetLife?.reset();levelIndex=i;useLevelVehicle();document.body.classList.toggle('secret-level',isSecret());lots.show(levelIndex);boundary.show(view(),isSecret());scene.background.setHex(lot().theme);scene.fog.color.setHex(lot().theme);sky.theme(lot().theme);scene.fog.near=isSecret()?180:110;scene.fog.far=isSecret()?600:240;camera.far=isSecret()?900:520;recover(true);renderGarage();renderLots();return true;}
function ensureSecretCity(){if(secretView)return;secretView=buildSecretCity({T,C,scene,lots,groundMat,rampMat});environment.register(lots.breakables.filter(e=>e.level===LOTS.length));objective=createDestructionObjective({view:secretView,crowd,onClear:t=>{destructionLoop?.clear(t);if(t.kind!=='person')streetLife?.economy.earn(t.kind==='building'?15:4);}});destructionLoop=createDestructionLoop({view:secretView,objective,environment,traffic,scoring,protectedPositions:()=>[...(borrowed?[borrowed.position]:[]),...(contracts?.protectedPositions()||[])],onAward:(points,chain,mult)=>{if(chain===1||chain%3===0)hitFeedback.show(points,scoring.snapshot(time).pending,chain,mult);},onJob:job=>{streetLife?.economy.earn(75);notify('Job '+job.number+' complete · $75 cash · '+job.banked.toLocaleString()+' banked'+(job.quick?' · quick bonus':''),2);}});contracts=createDemolitionContracts({T,view:secretView,economy:streetLife.economy,notify});}
function start(){if(!unlocked(levelIndex))return;if(isSecret()&&['running','paused'].includes(state))destructionLoop.save(spec.id,time);document.body.append(document.querySelector('.top'));if(isSecret()&&!spec.monster)useLevelVehicle();document.body.classList.add('playing');director.reset();document.body.classList.remove('cinematic');$('replayHUD').hidden=true;$('wreckPanel').hidden=true;time=0;runScore=0;totalLost=0;penalty=0;bumps=0;deadTime=0;recover(true);state='running';$('intro').hidden=true;$('finish').hidden=true;$('pausePanel').hidden=true;$('hud').hidden=false;$('touch').hidden=false;$('cameraTools').hidden=false;$('explodeButton').hidden=true;notify(spec.noBrakes?'No brakes · opposite gear + gas slows you down':spec.id==='nova'?'1,200 HP · use a light throttle':'',spec.noBrakes||spec.id==='nova'?3:0);hud();resumeAudio();}
function finish(){
 if(isSecret()){finishDestruction();return;}
 $('resultDistance').parentElement.querySelector('small').textContent='RATING';$('resultParts').parentElement.querySelector('small').textContent='BUMPS';
 const previouslyOpen=LOTS.filter((_,i)=>unlocked(i)).length,wasGoldUnlocked=goldUnlocked();
 document.body.classList.remove('playing');state='ended';clearInput();$('touch').hidden=true;$('cameraTools').hidden=true;$('finish').hidden=false;
 const elapsed=time+penalty,stars=spec.golden?3:bumps===0&&elapsed<=lot().par?3:bumps<=2?2:1,previous=saves[levelIndex];
 const result=scoring.bank({parked:true,stars,elapsed,par:lot().par,failures:failures.snapshot().count,lot:levelIndex,vehicle:spec.id});runScore=result.total;renderScoreResults('finishScoring',result);
 if(!spec.golden&&(!previous||stars>previous.stars||(stars===previous.stars&&elapsed<previous.time)))saves[levelIndex]={stars,time:Math.round(elapsed)};
 try{localStorage.setItem('parkside-chaos-saves-v1',JSON.stringify(saves))}catch{}
 $('finishTag').textContent='BAY '+lot().code+' / PARKED';$('finishTitle').textContent=stars===3?'Perfect parking.':'Nicely parked.';
 $('resultDistance').textContent='★'.repeat(stars)+'☆'.repeat(3-stars);$('resultTime').textContent=Math.round(elapsed);$('resultParts').textContent=bumps;
 $('best').textContent=stars===3?'Clean, accurate and on time.':'For three stars: no bumps, within '+lot().par+' seconds.';
 const nowOpen=LOTS.filter((_,i)=>unlocked(i)).length,newChapter=nowOpen>previouslyOpen;
 completionNext=newChapter?previouslyOpen:nextLotIndex(levelIndex,saves);
 if(newChapter){$('finishTag').textContent='LOTS '+(previouslyOpen+1)+'–'+nowOpen+' UNLOCKED';$('best').textContent='Eight new parking challenges are open.';}
 else if(!wasGoldUnlocked&&goldUnlocked()){$('finishTag').textContent='GOLD FLEET UNLOCKED';$('finishTitle').textContent='Go for gold.';$('best').textContent='Golden fleet and Golden Grounds unlocked.';}
 else if(spec.golden){$('finishTag').textContent='GOLDEN RUN COMPLETE';$('best').textContent='No penalties · original challenge ratings preserved.';}
 else if(goldUnlocked()){$('finishTag').textContent='ALL '+LOTS.length+' LOTS COMPLETE';$('finishTitle').textContent='Parking mastered.';$('best').textContent='Your golden fleet is unlocked in the garage.';}
 $('nextLot').textContent=!wasGoldUnlocked&&goldUnlocked()?'Try the golden fleet →':completionNext===null?'Choose a lot':newChapter?'Enter new lots →':'Next lot →';renderLots();renderGarage();
}
function finishDestruction(){if(!['running','paused'].includes(state)||!isSecret())return;$('pausePanel').hidden=true;state='ended';document.body.classList.remove('playing');clearInput();$('touch').hidden=true;$('cameraTools').hidden=true;$('finish').hidden=false;const progress=destructionLoop.getInfo();destructionLoop.save(spec.id,time);const result=scoring.bank({parked:true,endless:true,stars:3,elapsed:time,lot:LOTS.length,vehicle:spec.id});runScore=result.total;renderScoreResults('finishScoring',result);secretClear={time:Math.round(time),score:result.total,vehicle:spec.id};try{localStorage.setItem('parkside-streets-secret-clear-v1',JSON.stringify(secretClear));}catch{}$('finishTag').textContent='GOLDEN GROUNDS / RUN BANKED';$('finishTitle').textContent='Demolition payday.';$('resultDistance').textContent=progress.jobs;$('resultDistance').parentElement.querySelector('small').textContent='JOBS';$('resultTime').textContent=Math.round(time);$('resultParts').textContent=progress.total;$('resultParts').parentElement.querySelector('small').textContent='TARGETS';$('best').textContent='Best chain: '+progress.record.chain+' · Destroyed: '+progress.total+' · Restart for another run.';completionNext=null;$('nextLot').textContent='Back to garage →';renderLots();}

function renderScoreResults(id,result){if(!result)return;const el=$(id);el.replaceChildren();const title=document.createElement('b');title.className='score-result-title';title.textContent=spec.name+' · '+(result.destructionComplete?'City cleared':result.parked?'Score banked':'Wreck · 25% retained');el.append(title);for(const [label,value] of [[result.destructionComplete?'Clear bonus':'Parking',result.parkingPoints],['Destruction',result.destructionPoints],['Pedestrians',result.pedestrianPoints],['Limped Home',result.failurePoints],['Vehicle multiplier','×'+spec.scoreMultiplier+' included'],['Earned',result.total],['BANKED',result.banked]]){if((label==='Limped Home'||label==='Destruction')&&!value)continue;const row=document.createElement('div');row.className='score-result-row'+(label==='BANKED'?' total':'');const a=document.createElement('span'),b=document.createElement('b');a.textContent=label;b.textContent=typeof value==='number'?value.toLocaleString():value;row.append(a,b);el.append(row);}const best=document.createElement('small');best.textContent=(result.newBest?'NEW BEST · ':'BEST · ')+result.best.toLocaleString()+'  /  BANK '+result.bank.toLocaleString();el.append(best);}
function nextLevel(){return state==='ended'?completionNext:nextLotIndex(levelIndex,saves);}

function paintGear(){document.querySelectorAll('[data-gear]').forEach(b=>{const active=Number(b.dataset.gear)===selectedGear;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});}
function configureVehicle(){
 spec=tunedConfig(car.config,streetLife.economy.upgradeInfo(vehicleKey(car)));paintVehicle(car,streetLife.economy.upgradeInfo(vehicleKey(car)).paint);
 chassis.mass=spec.mass;chassis.angularDamping=spec.monster?.65:.48;bikeDynamics.reset();chassis.angularFactor.set(spec.monster?.55:1,1,spec.monster?.55:1);chassis.collisionFilterMask=-1;chassis.userData={kind:spec.monster?'monster truck':'player car',monster:!!spec.monster};world.solver.iterations=spec.monster?12:8;while(chassis.shapes.length)chassis.removeShape(chassis.shapes[0]);chassis.addShape(new C.Box(new C.Vec3(...spec.box)),new C.Vec3(0,spec.center+(spec.monster?.5:0),0));if(spec.monster){const bumper=new C.Box(new C.Vec3(1.46,.18,2.88));bumper.material=skidMat;chassis.addShape(bumper,new C.Vec3(0,-.22,0));for(const z of [spec.front,spec.rear])for(const x of [-spec.track,spec.track]){const tire=new C.Cylinder(1.02,1.02,.75,12);tire.material=tireProxyMat;chassis.addShape(tire,new C.Vec3(x,-.05,z),new C.Quaternion().setFromEuler(0,0,Math.PI/2));}}chassis.updateMassProperties();chassis.updateBoundingRadius();chassis.aabbNeedsUpdate=true;
 if(vehicle.wheelInfos.length!==(spec.bike?2:4)){vehicle.wheelInfos.length=0;for(let i=0;i<(spec.bike?2:4);i++)vehicle.addWheel({radius:spec.radius,directionLocal:new C.Vec3(0,-1,0),axleLocal:new C.Vec3(-1,0,0),chassisConnectionPointLocal:new C.Vec3(),suspensionStiffness:32,suspensionRestLength:.29,maxSuspensionTravel:.22,frictionSlip:3.8,dampingRelaxation:2.3,dampingCompression:4.4,maxSuspensionForce:90000,rollInfluence:.07});}
 vehicle.wheelInfos.forEach((w,i)=>{w.radius=spec.radius;w.chassisConnectionPointLocal.set(spec.bike?0:i%2?spec.track:-spec.track,spec.bike?0:spec.monster?.46:-.04,(spec.bike?i===0:i<2)?spec.front:spec.rear);w.suspensionRestLength=spec.suspension||.29;w.maxSuspensionTravel=(spec.monster?.48:.22)*(spec.travelMultiplier||1);w.suspensionStiffness=(spec.bike?65:spec.monster?52:32)*(spec.springMultiplier||1);w.maxSuspensionForce=spec.bike?10000:spec.monster?240000:90000;w.dampingRelaxation=(spec.monster?4:2.3)*Math.sqrt(spec.springMultiplier||1);w.dampingCompression=(spec.monster?6:4.4)*Math.sqrt(spec.springMultiplier||1);w.rollInfluence=spec.bike?0:spec.monster?.04:.07;});
 wheelParts=vehicle.wheelInfos.map((w,i)=>car.assemblies.find(p=>p.name===(spec.bike?'wheel-'+(i===0?'front':'rear'):'wheel-'+(i<2?'front':'rear')+'-'+(i%2?'left':'right'))));
 director.setParts(car.assemblies);
 const brakeButton=document.querySelector('[data-input=brake]'),holdButton=document.querySelector('[data-input=handbrake]');for(const b of [brakeButton,holdButton]){b.disabled=!!spec.noBrakes;b.classList.toggle('broken',!!spec.noBrakes);}brakeButton.querySelector('span').textContent=spec.noBrakes?'BROKEN':'BRAKE';holdButton.querySelector('span').textContent=spec.noBrakes?'Broken':'Hold';
}
function selectVehicle(i){
 if(state!=='menu'||isSecret()||!garage[i]||goldenMode&&!goldUnlocked())return;director.reset();restore();car.root.visible=false;vehicleIndex=i;car=goldenMode?goldenItem(i):garage[i];spec=car.config;car.root.visible=true;configureVehicle();recover(true);
 try{localStorage.setItem('parkside-chaos-car',spec.id);}catch{}renderGarage();renderLots();
}
function vehicleThumbnail(item){
 if(item.thumbnail)return item.thumbnail;
 const preview=new T.Scene();preview.background=new T.Color(0x243b3a);preview.add(new T.HemisphereLight(0xf7faf2,0x6e8d89,2.6));const light=new T.DirectionalLight(0xffebcd,3);light.position.set(-3,6,-4);preview.add(light);
 const model=item.root.clone(true);model.position.set(0,-.6,0);model.quaternion.identity();model.visible=true;preview.add(model);const cam=new T.PerspectiveCamera(36,1.8,.1,50),span=item.config.halfLength||2.4;cam.position.set(-4.2-span*.28,(item.config.monster?4.8:2.9)+span*.08,-5.5-span*.45);cam.lookAt(0,item.config.monster?1.7:.55,0);
 renderer.setSize(252,140,false);renderer.render(preview,cam);item.thumbnail=renderer.domElement.toDataURL('image/png');resize();return item.thumbnail;
}
function setGoldenMode(value){if(state!=='menu'||value&&!goldUnlocked())return;if(!value&&isSecret())loadLevel(0);goldenMode=!!value;selectVehicle(vehicleIndex);}
function renderGarage(){
 const unlockedGold=goldUnlocked(),done=saves.filter(s=>s?.stars>=1).slice(0,LOTS.length).length;
 $('goldFleet').disabled=!unlockedGold;for(const button of document.querySelectorAll('[data-fleet]')){const selected=(button.dataset.fleet==='gold')===goldenMode;button.classList.toggle('active',selected);button.setAttribute('aria-pressed',String(selected));}
 $('fleetStatus').textContent=isSecret()?'Monster truck · invincible ram':goldenMode?'Invincible · no penalties':unlockedGold?'Gold fleet unlocked':done+' / '+LOTS.length+' lots to unlock gold';
 if(isSecret()){const wrap=$('garage'),b=document.createElement('button');wrap.replaceChildren();b.className='car-card selected golden';b.setAttribute('aria-pressed','true');b.setAttribute('aria-label','Golden Monster Truck');const img=document.createElement('img');img.src=vehicleThumbnail(monsterItem());img.alt='';b.append(img);const name=document.createElement('b');name.textContent='Golden Monster Truck';b.append(name);const badge=document.createElement('span');badge.className='vehicle-multiplier';badge.textContent='INVINCIBLE RAM';b.append(badge);wrap.append(b);return;}
 const wrap=$('garage');wrap.replaceChildren();garage.forEach((base,i)=>{const item=goldenMode?goldenItem(i):base,b=document.createElement('button');b.className='car-card'+(i===vehicleIndex?' selected':'')+(goldenMode?' golden':'');b.setAttribute('aria-pressed',String(i===vehicleIndex));b.setAttribute('aria-label','Choose '+item.config.name);const img=document.createElement('img');img.src=vehicleThumbnail(item);img.alt='';b.append(img);const name=document.createElement('b');name.textContent=item.config.name;b.append(name);const badge=document.createElement('span');badge.className='vehicle-multiplier';badge.textContent=goldenMode?'INVINCIBLE':'×'+item.config.scoreMultiplier;b.append(badge);b.onclick=()=>selectVehicle(i);wrap.append(b);});
}
for(const button of document.querySelectorAll('[data-fleet]'))button.onclick=()=>setGoldenMode(button.dataset.fleet==='gold');


function renderLots(){
 const wrap=$('lotList');wrap.replaceChildren();
 LOTS.forEach((l,i)=>{
  if(i%8===0){const d=document.createElement('div'),open=unlocked(i),done=saves.slice(i,i+8).filter(s=>s?.stars>=1).length;d.className='bonus-divider'+(open?' open':'');
   const title=['FOUNDATIONS','BONUS CHALLENGES','MASTER CHALLENGES'][Math.floor(i/8)];
   d.innerHTML='<b>'+title+' · '+(i+1)+'–'+Math.min(i+8,LOTS.length)+'</b><span>'+(open?done+' / 8 complete':'Complete lots 1–'+i)+'</span>';wrap.append(d);}
  const locked=!unlocked(i),b=document.createElement('button');b.className='lot-card'+(i===levelIndex?' selected':'')+(locked?' locked':'');b.disabled=locked;
  b.setAttribute('aria-label','Lot '+(i+1)+': '+l.name+(locked?', locked':''));b.setAttribute('aria-pressed',String(i===levelIndex));
  b.innerHTML='<span class="lot-num">'+String(i+1).padStart(2,'0')+'</span><span><b>'+l.name+'</b><small>'+(locked?'Finish lots 1–'+(Math.floor(i/8)*8):l.kind+(scoring.best(i,spec.id)?' · BEST '+scoring.best(i,spec.id).toLocaleString():''))+'</small></span><em>'+(locked?'🔒':('★'.repeat(saves[i]?.stars||0)||'—'))+'</em>';
  b.onclick=()=>loadLevel(i);wrap.append(b);
 });const secretButton=document.createElement('button');secretButton.id='secretLot';secretButton.className='lot-card secret-lot'+(isSecret()?' selected':'')+(!goldUnlocked()?' locked':'');secretButton.disabled=!goldUnlocked();secretButton.setAttribute('aria-pressed',String(isSecret()));secretButton.innerHTML='<span class="lot-num">✦</span><span><b>Golden Grounds</b><small>'+(goldUnlocked()?'City · suburbs · harbor · forest':'Unlock the golden fleet')+'</small></span><em>'+(goldUnlocked()?(secretClear?'ENDLESS':'SECRET'):'🔒')+'</em>';secretButton.onclick=()=>loadLevel(LOTS.length);wrap.prepend(secretButton);$('start').disabled=!unlocked(levelIndex);$('start').textContent=unlocked(levelIndex)?(isSecret()?'Enter Golden Grounds →':'Drive '+lot().name+' →'):'Complete the previous chapters';if($('introGoal'))$('introGoal').textContent=isSecret()?'Finish demolition jobs. Chain hits for ×3 scoring. Jobs bank automatically; cleared districts rebuild when you leave.':'Clear gates 1 → 2 → 3, then park in the green bay.';
}
function openMenu(){if(isSecret()&&['running','paused','ended'].includes(state))destructionLoop.save(spec.id,time);$('intro').querySelector('.panel').prepend(document.querySelector('.top'));const freshGold=state==='ended'&&$('finishTag').textContent==='GOLD FLEET UNLOCKED';document.body.classList.remove('playing');state='menu';clearInput();$('finish').hidden=true;$('pausePanel').hidden=true;$('intro').hidden=false;$('hud').hidden=true;$('touch').hidden=true;$('cameraTools').hidden=true;recover(true);if(freshGold)setGoldenMode(true);renderGarage();renderLots();}
function pause(){streetLife?.closeShop();if(state==='running'||state==='countdown'){pausedFrom=state;state='paused';clearInput();$('pausePanel').hidden=false;$('touch').hidden=true;}else if(state==='paused'){state=pausedFrom;$('pausePanel').hidden=true;$('touch').hidden=false;}}
function clearInput(){streetLife?.resetInput();if(typeof cameraPointers!=='undefined')cameraPointers.clear();controller?.suspend();padInput={gas:0,brake:0,steering:0,handbrake:false};wheelPointer=null;wheelAngle=0;paintWheel();for(const k in keys)delete keys[k];for(const k in touch)delete touch[k];document.querySelectorAll('.pressed').forEach(b=>b.classList.remove('pressed'));}
$('start').onclick=start;$('again').onclick=start;$('restart').onclick=start;$('resume').onclick=pause;$('pauseButton').onclick=pause;$('cameraButton').onclick=()=>setCamera(orbitMode==='follow'?'back':orbitMode==='back'?'top':'follow');$('recover').onclick=()=>{if(state==='paused')pause();if(state==='running')recover()};$('menu').onclick=openMenu;$('pauseMenu').onclick=openMenu;$('nextLot').onclick=()=>{const next=nextLevel();if(next===null)openMenu();else if(loadLevel(next))start();};for(const b of document.querySelectorAll('[data-gear]'))b.onclick=()=>{selectedGear=Number(b.dataset.gear);paintGear();};$('explodeButton').onclick=()=>{pause();explode()};$('endDestruction').onclick=finishDestruction;
window.addEventListener('keydown',e=>{if(streetLife.shopOpen){if(e.code==='Escape'){e.preventDefault();streetLife.closeShop();}return;}if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();keys[e.code]=true;if(e.repeat)return;if(e.code==='KeyP'||e.code==='Escape'){if(state==='replay'||state==='wreck'){director.stop();showWreck();}else pause();}if(e.code==='KeyF'&&state==='running')togglePerspective();if(e.code==='KeyC')setCamera(orbitMode==='follow'?'back':orbitMode==='back'?'top':'follow');if(e.code==='KeyX'){if(streetLife.mode==='foot')streetLife.cycleWeapon();else selectedGear*=-1;}if(e.code==='KeyR'&&state==='running')recover();if(e.code==='KeyH'&&state==='running')streetLife.hulk.toggle();if(e.code==='KeyQ'&&state==='running')streetLife.hulk.split();if(e.code==='KeyE'&&state==='running')streetLife.interact();});window.addEventListener('keyup',e=>delete keys[e.code]);
for(const b of document.querySelectorAll('[data-input]')){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);touch[b.dataset.input]=true;b.classList.add('pressed');resumeAudio()});const release=()=>{touch[b.dataset.input]=false;b.classList.remove('pressed')};b.addEventListener('pointerup',release);b.addEventListener('pointercancel',release);b.addEventListener('lostpointercapture',release);}
window.addEventListener('blur',()=>{clearInput();if(state==='running'||state==='countdown')pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();if(state==='running'||state==='countdown')pause()}});
let audioCtx,engineOsc,gain,sound=false;function resumeAudio(){if(sound){if(!audioCtx){audioCtx=new(window.AudioContext||window.webkitAudioContext)();engineOsc=audioCtx.createOscillator();engineOsc.type='sawtooth';gain=audioCtx.createGain();gain.gain.value=0;const filter=audioCtx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=480;engineOsc.connect(filter).connect(gain).connect(audioCtx.destination);engineOsc.start();}audioCtx.resume().catch(()=>{});}}
$('sound').onclick=()=>{sound=!sound;$('sound').classList.toggle('active',sound);$('sound').setAttribute('aria-pressed',String(sound));$('sound').querySelector('span').textContent=sound?'Sound on':'Sound off';resumeAudio();};let lastCrashAudio=-1,crashNoise=null;function crashSound(n){if(!sound||!audioCtx||physicsTime-lastCrashAudio<.08)return;lastCrashAudio=physicsTime;if(!crashNoise){const count=Math.floor(audioCtx.sampleRate*.22);crashNoise=audioCtx.createBuffer(1,count,audioCtx.sampleRate);const data=crashNoise.getChannelData(0);for(let i=0;i<count;i++)data[i]=(Math.random()*2-1)*(1-i/count);}const buffer=crashNoise;const src=audioCtx.createBufferSource(),g=audioCtx.createGain();g.gain.value=Math.min(.35,n*.012);src.buffer=buffer;src.connect(g).connect(audioCtx.destination);src.start();if(n>=30){const bass=audioCtx.createOscillator(),boom=audioCtx.createGain();bass.type='triangle';bass.frequency.setValueAtTime(135,audioCtx.currentTime);bass.frequency.exponentialRampToValueAtTime(28,audioCtx.currentTime+.8);boom.gain.setValueAtTime(.45,audioCtx.currentTime);boom.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+1.1);bass.connect(boom).connect(audioCtx.destination);bass.start();bass.stop(audioCtx.currentTime+1.2);}}
function physics(dt){
 physicsAccumulator+=Math.max(0,Math.min(dt,.1));
 while(physicsAccumulator+1e-9>=fixedStep){physicsAccumulator=Math.max(0,physicsAccumulator-fixedStep);physicsStep(fixedStep);vehicleMotion.capture(car);if(!['running','countdown','menu','wreck'].includes(state))break;}
 if(state!=='replay'&&state!=='wreckReview')vehicleMotion.render(Math.min(1,physicsAccumulator/fixedStep));
}
function physicsStep(dt){physicsTime+=dt;input={gas:Math.max(keys.KeyW||keys.ArrowUp||keys.KeyS||keys.ArrowDown||touch.gas?1:0,padInput.gas||0),brake:Math.max(touch.brake?1:0,padInput.brake||0),left:keys.KeyA||keys.ArrowLeft||touch.left,right:keys.KeyD||keys.ArrowRight||touch.right,handbrake:keys.Space||touch.handbrake||padInput.handbrake};const active=state==='running'&&streetLife.mode==='vehicle';streetLife.beforeStep(dt,active?{}:keys,padInput);if(!active)input={gas:0,brake:0,left:false,right:false,handbrake:false};if(spec.noBrakes)input.handbrake=false;const fwd=chassis.quaternion.vmult(new C.Vec3(0,0,-1));forwardSpeed=chassis.velocity.dot(fwd);speed=chassis.velocity.length();const off=Math.abs(chassis.position.x-view().ox)>(lot().halfSize||48)||Math.abs(chassis.position.z)>(lot().halfSize||48);const axis=(input.left?1:0)-(input.right?1:0)||(wheelPointer!==null?-wheelAngle/135:padInput.active?-padInput.steering:-wheelAngle/135);const desired=active?axis*(spec.bike?.48/(1+speed*.07):.69/(1+speed*.025)):0;steer+=(desired-steer)*Math.min(1,dt*10);vehicle.setSteeringValue(steer,0);vehicle.setSteeringValue(spec.bike?0:steer,1);
 let engine=0,brake=spec.noBrakes?0:active?3:45;const motor=car.assemblies.find(p=>p.name==='engine').userData.attached;
 const desiredGear=keys.KeyW||keys.ArrowUp?1:keys.KeyS||keys.ArrowDown?-1:selectedGear;
 const throttle=input.gas;
 if(active){const nearBay=!isSecret()&&Math.hypot(chassis.position.x-view().ox-lot().target.x,chassis.position.z-lot().target.z)<8;failures.update(dt,{moving:speed>.8,nearBay});}
 const fault=failures.snapshot();
 if(active&&health>0&&motor){if(spec.noBrakes){if(throttle)engine=throttle*motorForce(spec.power,desiredGear,forwardSpeed,desiredGear>0?spec.maxSpeed:(spec.reverseSpeed||4));}else if(input.brake>0||input.handbrake)brake=input.handbrake?40:3+37*input.brake;else if(throttle){if(forwardSpeed*desiredGear<-.3)brake=32*throttle;else{engine=throttle*motorForce(spec.power,desiredGear,forwardSpeed,desiredGear>0?spec.maxSpeed:(spec.reverseSpeed||4));brake=0;}}}
 engine*=fault.throttleFactor;brake*=fault.brakeFactor*(spec.brakeMultiplier||1);
 for(let i=0;i<vehicle.wheelInfos.length;i++){const attached=wheelParts[i].userData.attached;vehicle.applyEngineForce((spec.monster||(spec.bike?i===1:i>=2))&&attached?engine:0,i);vehicle.setBrake(spec.noBrakes?0:(input.handbrake&&active&&(spec.bike?i===1:i>=2)?70*fault.brakeFactor*(spec.brakeMultiplier||1):brake)*spec.mass/950,i);vehicle.wheelInfos[i].frictionSlip=attached?(spec.bike?5.5:off?(spec.monster?4:1.8):input.handbrake&&i>=2?1.05:spec.monster?5:3.8)*(spec.gripMultiplier||1):.4;}
 if(off&&speed>0){chassis.applyForce(chassis.velocity.scale(-40),new C.Vec3());}else if(speed>0){chassis.applyForce(chassis.velocity.scale(-8-speed*.6),new C.Vec3());}
 if((spec.monster||spec.ramTier)&&active){const push=Math.abs(engine)*4*(spec.ramMultiplier||1);environment.ram(chassis,dt,push,spec.ramMultiplier||1);traffic.ram(chassis,dt,push);}crowd.beforeStep(dt,state==='running');if(spec.bike)bikeDynamics.update(dt,chassis,vehicle,steer,active);world.step(dt);crowd.afterStep(dt,state==='running'||state==='wreck');streetLife.afterStep();traffic.update(dt);environment.update(dt,isSecret()?streetLife.focus:null);barrelEffects.update(dt);syncCar();if(isSecret()&&state==='running'){objectiveClock+=dt;if(objectiveClock>=.1){const objectiveDt=objectiveClock;objectiveClock=0;const focus=streetLife.focus;destructionLoop.update(objectiveDt,focus.x-view().ox,focus.z,spec.id,time,streetLife.mode==='vehicle');objective.update(focus.x-view().ox,focus.z,destructionLoop.preferred);contracts?.update(objectiveDt);secretView.detail.update(objectiveDt,focus.x-view().ox,focus.z);}}
 // Raycast wheels can touch a low curb without the chassis hitting it.
 if(active&&spec.golden&&state==='running'&&!pendingHit&&speed>2&&physicsTime-lastImpact>.7){const wheel=vehicle.wheelInfos.find(w=>w.isInContact&&w.raycastResult.body&&w.raycastResult.body!==ground&&w.raycastResult.body.userData?.kind!=='ramp');if(wheel)pendingHit={impact:Math.max(3,speed),kind:'scenery',point:new T.Vector3().copy(wheel.raycastResult.hitPointWorld),velocity:new T.Vector3().copy(chassis.velocity)};}
 if(streetLife.mode==='foot')pendingHit=null;if(pendingHit){const hit=pendingHit;pendingHit=null;handleHit(hit);}
 if(state==='running')time+=dt;if(active&&state==='running'){forwardSpeed=chassis.velocity.dot(chassis.quaternion.vmult(new C.Vec3(0,0,-1)));speed=chassis.velocity.length();if(Math.abs(forwardSpeed)>.3)lastDirection=forwardSpeed>0?1:-1;
 if(!isSecret()){const bayDistance=Math.hypot(chassis.position.x-view().ox-lot().target.x,chassis.position.z-lot().target.z);if(bayDistance>8)reverseTravel=0;else if(forwardSpeed<-.4)reverseTravel+=-forwardSpeed*dt;
 const f=chassis.quaternion.vmult(new C.Vec3(0,0,-1)),up=chassis.quaternion.vmult(new C.Vec3(0,1,0));parkingState=assessParking({x:chassis.position.x-view().ox,z:chassis.position.z,yaw:Math.atan2(-f.x,-f.z),halfWidth:spec.halfWidth||1.27,halfLength:spec.halfLength||2.4,speed,up:up.y,lastDirection:lot().target.reverse?(reverseTravel>.35?-1:0):lastDirection},lot().target);
 const gate=lot().gates[gateProgress];if(gate){const dx=chassis.position.x-view().ox-gate.x,dz=chassis.position.z-gate.z,c=Math.cos(gate.yaw),s=Math.sin(gate.yaw),across=c*dx-s*dz,along=s*dx+c*dz,yaw=Math.atan2(-f.x,-f.z),angle=Math.atan2(Math.sin(yaw-gate.yaw),Math.cos(yaw-gate.yaw));
 if(Math.abs(across)+(spec.halfWidth||1.27)<lot().gateWidth/2&&Math.abs(along)<1.8&&Math.abs(angle)<Math.PI/4&&(gate.reverse?forwardSpeed<-.4:forwardSpeed>.4)){gateProgress++;notify(gateProgress===3?'Route clear · park in '+lot().code:'Gate '+gateProgress+'/3 · follow the next marker');}}
 parkingState.routeComplete=gateProgress===3;parkingState.valid=parkingState.valid&&parkingState.routeComplete;
 if(parkingState.valid&&physicsTime-lastImpact>.8)parkingHold+=dt;else parkingHold=0;if(parkingHold>=1.35)finish();}
 if(chassis.position.y<-8||Math.abs(chassis.position.x-view().ox)>(lot().worldHalf?lot().worldHalf-8:108)||Math.abs(chassis.position.z)>(lot().worldHalf?lot().worldHalf-8:108))recover();}
 for(const o of obstacles){o.mesh.position.copy(o.body.position);o.mesh.quaternion.copy(o.body.quaternion);}for(const d of loose){d.age+=dt;if(d.age>.45)d.body.collisionFilterMask=3;d.mesh.position.copy(d.body.position);d.mesh.quaternion.copy(d.body.quaternion);}for(let i=sparks.length-1;i>=0;i--){const p=sparks[i];p.life-=dt;p.v.y-=9.8*dt;p.mesh.position.addScaledVector(p.v,dt);if(p.life<0){scene.remove(p.mesh);p.active=false;sparks.splice(i,1);}}
 if(!isSecret()&&streetLife.mode==='vehicle'&&(state==='running'||state==='wreck'))director.record(physicsTime);if(state==='wreck'){wreckTime+=dt;director.renderEffects(wreckTime);$('replayProgress').style.width=Math.min(100,wreckTime/2.4*100)+'%';if(wreckTime>=2.4)startReplay();}
}
const mapCtx=$('map').getContext('2d');function hud(){
 const points=scoring.snapshot(time);runScore=points.pending;const compact=n=>n<10000?n.toLocaleString():(n/1000).toFixed(1)+'K';$('hitScore').textContent=compact(runScore)+' PTS';$('scoreMeta').textContent=(points.settled?'BANKED ×':'UNBANKED ×')+spec.scoreMultiplier+' · BANK '+compact(points.bank);$('comboState').textContent=points.combo>1?points.combo+' HIT · '+points.comboRemaining.toFixed(1)+'s':'';const fault=failures.snapshot();$('vehicleFault').textContent=state==='running'?fault.message:'';$('vehicleFault').hidden=!$('vehicleFault').textContent;
 $('destructionCounts').hidden=!isSecret();$('endDestruction').hidden=!isSecret();if(isSecret()){hudDestruction();return;}
 $('speed').textContent=Math.round(Math.abs(forwardSpeed)*2.237);$('distance').textContent=(levelIndex+1)+' / '+LOTS.length+' · '+lot().code;$('timer').textContent=Math.floor((time+penalty)/60)+':'+String(Math.floor((time+penalty)%60)).padStart(2,'0');$('progress').style.width=Math.min(100,(gateProgress+parkingHold/1.35)/4*100)+'%';$('healthBar').style.width=health+'%';$('condition').textContent=spec.golden?'INVINCIBLE':bumps+' bump'+(bumps===1?'':'s');$('gear').textContent=(forwardSpeed<-.3?'R':forwardSpeed>.3?'D':selectedGear===1?'D':'R')+'';paintGear();
 const p=parkingState;let hint='Park in '+lot().code+' · '+lot().kind;if(gateProgress<3)hint='Gate '+(gateProgress+1)+'/3'+(lot().gates[gateProgress].reverse?' · back through in R':' · follow the arrow');else if(p?.near){hint=!p.contained?'Get all four corners inside':!p.aligned?'Face the bay’s arrow':!p.approach?'Back into this space in R':!p.stopped?(spec.noBrakes?'Coast or use opposite gear to stop':'Brake to a complete stop'):'Hold still…';}if(state==='ended')hint='Parked!';$('parkingHelp').textContent=gateProgress<3?'Gate '+(gateProgress+1)+' / 3':'Park · '+lot().code;$('objectiveHint').textContent=gateProgress<3?(lot().gates[gateProgress].reverse?'Reverse through the amber gate':'Drive through the amber gate'):hint;$('objectiveLabel').textContent=gateProgress<3?'NEXT GATE':'PARKING BAY';const objectiveTarget=lot().gates[gateProgress]||lot().target;updateObjectiveDirection(objectiveTarget);
 view().marker.fill.material.opacity=.18+(Math.sin(clock*3)+1)*.05;view().marker.fill.material.color.setHex(parkingHold>0?0xd3f59f:0x74e6ab);view().beacon.quaternion.copy(camera.quaternion);view().beacon.visible=gateProgress===3;
 view().gates.forEach((gate,i)=>{gate.label.visible=i===gateProgress;gate.label.quaternion.copy(camera.quaternion);gate.line.material.color.setHex(i<gateProgress?0x74e6ab:i===gateProgress?0xffcf72:0x81918a);gate.line.material.opacity=i===gateProgress?.95:i<gateProgress?.25:.13;gate.label.scale.setScalar(i===gateProgress?1.2:1);});
 const c=mapCtx;c.clearRect(0,0,168,230);c.fillStyle='#536660';c.fillRect(8,35,152,152);const scale=152/128,xy=(x,z)=>[84+x*scale,111+z*scale];for(const m of view().mini){const [x,y]=xy(m.x,m.z);c.save();c.translate(x,y);c.rotate(-m.yaw);c.fillStyle=m.color;c.fillRect(-m.w*scale/2,-m.d*scale/2,m.w*scale,m.d*scale);c.restore();}lot().gates.forEach((a,i)=>{const [gx,gz]=xy(a.x,a.z);c.fillStyle=i<gateProgress?'#76d4a2':i===gateProgress?'#ffcf72':'#869892';c.beginPath();c.arc(gx,gz,i===gateProgress?5:3,0,Math.PI*2);c.fill();c.fillStyle='#183b37';c.font='bold 8px system-ui';c.fillText(String(i+1),gx,gz+3);});const t=lot().target,[tx,ty]=xy(t.x,t.z);c.save();c.translate(tx,ty);c.rotate(-t.yaw);c.fillStyle='#a4f3ad';c.fillRect(-t.w*scale/2,-t.d*scale/2,t.w*scale,t.d*scale);c.restore();const [x,y]=xy(chassis.position.x-view().ox,chassis.position.z),f=chassis.quaternion.vmult(new C.Vec3(0,0,-1));c.save();c.translate(x,y);c.rotate(-Math.atan2(-f.x,-f.z));c.fillStyle='#fff4d7';c.beginPath();c.moveTo(0,-7);c.lineTo(-4,5);c.lineTo(4,5);c.closePath();c.fill();c.restore();c.fillStyle='#fff4d7';c.font='bold 11px system-ui';c.textAlign='center';c.fillText(lot().name,84,19);
}
function updateObjectiveDirection(target){const dx=view().ox+target.x-chassis.position.x,dz=target.z-chassis.position.z,f=chassis.quaternion.vmult(new C.Vec3(0,0,-1)),heading=Math.atan2(-f.x,-f.z),bearing=Math.atan2(-dx,-dz),turn=Math.atan2(Math.sin(bearing-heading),Math.cos(bearing-heading));$('objectiveArrow').style.transform='rotate('+(-turn*180/Math.PI)+'deg)';$('objectiveDistance').textContent=Math.round(Math.hypot(dx,dz))+' m';}
function hudDestruction(){
 const p=objective.getInfo(),loop=destructionLoop.getInfo(),job=loop.job,contract=contracts?.getInfo(),next=contract?.active?contract.target:loop.waiting?loop.escape:p.next;$('speed').textContent=Math.round(Math.abs(forwardSpeed)*2.237);$('distance').textContent=loop.jobs+' JOBS · '+loop.total+' DESTROYED';$('timer').textContent=Math.floor(time/60)+':'+String(Math.floor(time%60)).padStart(2,'0');$('progress').style.width=(job.done/Math.max(1,job.quota)*100)+'%';$('healthBar').style.width='100%';$('condition').textContent='INVINCIBLE';$('gear').textContent=(forwardSpeed<-.3?'R':selectedGear===1?'D':'R')+' · FREE ROAM';paintGear();
 $('destructionCounts').textContent='Best chain '+loop.record.chain+' · Best run '+loop.record.score.toLocaleString()+' · '+p.byKind.people.done+'/'+p.byKind.people.total+' pedestrians down';
 $('objectiveLabel').textContent='JOB '+job.number+' · '+DISTRICTS[job.district].name+ (loop.chain>1?' · ×'+loop.multiplier.toFixed(1):'');$('parkingHelp').textContent=loop.completed?'Job complete!':next?next.name:'Find a target';$('objectiveHint').textContent=loop.waiting?'Drive to the marker to rebuild safely':loop.completed?'Payday incoming · keep smashing':job.done+'/'+job.quota+' '+job.type+' · '+Math.ceil(loop.bonusRemaining)+'s quick bonus';if(next)updateObjectiveDirection(next);else $('objectiveDistance').textContent='';

 if(contract?.active){$('objectiveLabel').textContent=contract.title+' · $'+contract.reward;$('parkingHelp').textContent=contract.target.name;$('objectiveHint').textContent=contract.step;}
 view().marker.fill.visible=view().beacon.visible=state==='running'&&!!next;if(next){view().marker.fill.position.set(view().ox+next.x,.12,next.z);view().beacon.position.set(view().ox+next.x,5+Math.sin(clock*3)*.35,next.z);}
 const c=mapCtx,scale=152/500,xy=(x,z)=>[84+x*scale,111+z*scale];c.clearRect(0,0,168,230);c.fillStyle='#526d60';c.fillRect(8,35,152,152);
 for(const d of DISTRICTS){const [x,y]=xy(d.x,d.z);c.fillStyle='#'+d.color.toString(16).padStart(6,'0');c.fillRect(x-35,y-35,70,70);}
 for(const m of view().mini){const [x,y]=xy(m.x,m.z);c.fillStyle=m.color;c.fillRect(x-m.w*scale/2,y-m.d*scale/2,m.w*scale,m.d*scale);}
 for(const t of objective.remaining()){const [x,y]=xy(t.x,t.z);c.fillStyle=t.kind==='person'?'#fff5d2':t.kind==='barrel'?'#ff784c':'#e8be71';c.fillRect(x-1,y-1,2,2);}
 for(const item of view().rideables||[]){const [bx,bz]=xy(item.body.position.x-view().ox,item.body.position.z);c.fillStyle='#74c6ff';c.fillRect(bx-2,bz-2,4,4);c.font='bold 8px system-ui';c.textAlign='center';c.fillText('BIKE',bx,bz-5);}for(const b of view().buildings||[])if(['convenience','gun','casino','garage'].includes(b.type)){const [sx,sy]=xy(b.x-view().ox,b.z);c.fillStyle=b.type==='convenience'?'#a6f3b5':'#ffcb8f';c.fillRect(sx-3,sy-3,6,6);c.font='bold 8px system-ui';c.textAlign='center';c.fillText(b.type==='convenience'?'MART':b.type==='casino'?'CASINO':b.type==='garage'?'GARAGE':'GUNS',sx,sy-5);}DISTRICTS.forEach((d,i)=>{const [x,y]=xy(d.x,d.z);c.fillStyle='#133c35';c.font='bold 9px system-ui';c.textAlign='center';c.fillText(d.name,x,y);c.font='8px system-ui';c.fillText(p.districts[i].done+'/'+p.districts[i].total,x,y+11);});
 if(next){const [x,y]=xy(next.x,next.z);c.strokeStyle='#fff4a4';c.lineWidth=2;c.beginPath();c.arc(x,y,4,0,Math.PI*2);c.stroke();}const [x,y]=xy(chassis.position.x-view().ox,chassis.position.z),f=chassis.quaternion.vmult(new C.Vec3(0,0,-1));c.save();c.translate(x,y);c.rotate(-Math.atan2(-f.x,-f.z));c.fillStyle='#ffffff';c.beginPath();c.moveTo(0,-5);c.lineTo(-3,4);c.lineTo(3,4);c.closePath();c.fill();c.restore();c.fillStyle='#fff4d7';c.font='bold 11px system-ui';c.textAlign='center';c.fillText('Golden Grounds',84,19);
}
let orbitYaw=0,orbitPitch=.52,orbitDistance=13,orbitMode='follow',firstPerson=false,vehicleLookYaw=0,pinchLast=0;const cameraPointers=new Map(),canvas=$('view');
function paintCamera(){document.querySelectorAll('[data-camera]').forEach(b=>{const active=b.dataset.camera===orbitMode;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});}
function setCamera(m){firstPerson=m==='first';vehicleLookYaw=0;orbitMode=m;document.body.classList.toggle('first-person',firstPerson);paintCamera();orbitPitch=m==='top'?(isSecret()?1.22:1.43):.52;orbitDistance=m==='top'?(isSecret()?52:18):spec.monster?18:13;if(firstPerson)orbitPitch=0;camInit=false;}
function togglePerspective(){firstPerson=!firstPerson;vehicleLookYaw=0;orbitPitch=firstPerson?0:streetLife.mode==='foot'?.28:.52;camInit=false;document.body.classList.toggle('first-person',firstPerson);}
$('perspectiveButton').onclick=togglePerspective;
for(const b of document.querySelectorAll('[data-camera]'))b.onclick=()=>setCamera(b.dataset.camera);
canvas.addEventListener('pointerdown',e=>{if(!['running','paused','menu'].includes(state))return;canvas.setPointerCapture(e.pointerId);cameraPointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(cameraPointers.size===2){const [a,b]=[...cameraPointers.values()];pinchLast=Math.hypot(a.x-b.x,a.y-b.y);}});
canvas.addEventListener('pointermove',e=>{const old=cameraPointers.get(e.pointerId);if(!old)return;const dx=e.clientX-old.x,dy=e.clientY-old.y;cameraPointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(cameraPointers.size===2){const [a,b]=[...cameraPointers.values()],d=Math.hypot(a.x-b.x,a.y-b.y);orbitDistance=clamp(orbitDistance*pinchLast/Math.max(1,d),streetLife.mode==='foot'?2.8:6,streetLife.mode==='foot'?(streetLife.inside?5.5:12):isSecret()?240:29);pinchLast=d;}else{if(!firstPerson){orbitMode='orbit';paintCamera();}if(firstPerson&&streetLife.mode==='vehicle')vehicleLookYaw-=dx*.009;else orbitYaw-=dx*.009;orbitPitch=clamp(orbitPitch+dy*.006,firstPerson?-1.25:.25,firstPerson?1.25:1.48);}});
for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,e=>cameraPointers.delete(e.pointerId));
canvas.addEventListener('wheel',e=>{e.preventDefault();orbitDistance=clamp(orbitDistance+e.deltaY*.014,streetLife.mode==='foot'?2.8:6,streetLife.mode==='foot'?(streetLife.inside?5.5:12):isSecret()?240:29);},{passive:false});
function controllerMenu(){if(streetLife?.shopOpen)return streetLife.menu;if(!$('fatal').hidden)return {menuRoot:$('fatal'),defaultButton:''};const panels={menu:['intro','start'],paused:['pausePanel','resume'],ended:['finish','nextLot'],wreckReview:['wreckPanel','continueWreck'],replay:['replayHUD','skipReplay'],wreck:['replayHUD','skipReplay']},panel=panels[state];return panel?{menuRoot:$(panel[0]),defaultButton:panel[1]}:{};}
for(const b of document.querySelectorAll('[data-controller-help]'))b.onclick=()=>{const bindings=b.parentElement.querySelector('.controller-bindings');bindings.hidden=!bindings.hidden;b.setAttribute('aria-expanded',String(!bindings.hidden));};
controller=createXboxControls({
 onMode:active=>document.body.classList.toggle('controller-active',active),
 onConnection:connected=>{document.querySelectorAll('.controller-status').forEach(el=>el.textContent=connected?'Controller connected':'Pair in Bluetooth, then press a controller button.');if(!connected){clearInput();if(state==='running'||state==='countdown')pause();}},
 onAction:action=>{
  if(action==='sound'){$('sound').click();return;}
  if(action==='back'&&streetLife.shopOpen){streetLife.closeShop();return;}if(action==='back'){if(state==='paused')pause();else if(state==='ended')openMenu();else if(state==='wreckReview')continueWreck();else if(state==='replay'||state==='wreck')$('skipReplay').click();return;}
  if(action==='menu'){if(streetLife.shopOpen){pause();return;}if(state==='menu')start();else if(state==='paused')pause();else{const button=$(controllerMenu().defaultButton);button?.click();}return;}
  if(action==='hulk'&&state==='running'){streetLife.hulk.toggle();return;}if(action==='rip'&&state==='running'){streetLife.hulk.split();return;}if(action==='drop'&&state==='running'){streetLife.hulk.drop();return;}if(action==='pause'){pause();return;}if(action==='interact'&&state==='running'){streetLife.interact();return;}if(action==='weapon'&&state==='running'){streetLife.cycleWeapon();return;}
  if(!['running','countdown','paused'].includes(state))return;
  if(action==='gear'||action==='drive'||action==='reverse'){selectedGear=action==='gear'?-selectedGear:action==='drive'?1:-1;paintGear();}
  if(action==='camera')setCamera(orbitMode==='follow'?'back':orbitMode==='back'?'top':'follow');
  if(action==='center')togglePerspective();
  if(action==='recover'&&state==='running')recover();
 }
});
function pollController(dt){
 padInput=controller.poll(dt,{...controllerMenu(),driving:state==='running'&&streetLife.mode==='vehicle',walking:state==='running'&&streetLife.mode==='foot'&&!streetLife.shopOpen});
 if(padInput.active&&!streetLife.shopOpen&&['running','countdown','paused'].includes(state)){
  if(padInput.cameraX||padInput.cameraY){if(!firstPerson&&orbitMode!=='orbit'){orbitMode='orbit';paintCamera();}if(firstPerson&&streetLife.mode==='vehicle')vehicleLookYaw-=padInput.cameraX*2.25*dt;else orbitYaw-=padInput.cameraX*2.25*dt;orbitPitch=clamp(orbitPitch+(firstPerson?1:-1)*padInput.cameraY*1.15*dt,firstPerson?-1.25:streetLife.mode==='foot'?.05:.25,firstPerson?1.25:1.48);}
  if(padInput.zoom&&!firstPerson)orbitDistance=clamp(orbitDistance*Math.exp(padInput.zoom*1.25*dt),streetLife.mode==='foot'?2.8:6,streetLife.mode==='foot'?(streetLife.inside?5.5:12):isSecret()?240:29);
 }
 $('controllerGas').style.width=(padInput.gas*100)+'%';$('controllerBrake').style.width=(padInput.brake*100)+'%';
}
const guideGeometry=new T.BufferGeometry(),guidePositions=new Float32Array(2*19*2*3);guideGeometry.setAttribute('position',new T.BufferAttribute(guidePositions,3));const guides=new T.LineSegments(guideGeometry,new T.LineBasicMaterial({color:0xf4d686,transparent:true,opacity:.8,depthTest:false}));guides.frustumCulled=false;guides.renderOrder=3;scene.add(guides);
function updateGuides(){guides.visible=streetLife.mode==='vehicle'&&!isSecret()&&state==='running'&&(selectedGear===-1||forwardSpeed<-.2);if(!guides.visible)return;let k=0;const q=new T.Quaternion().copy(car.root.quaternion);for(const side of [-1,1])for(let i=0;i<19;i++)for(let j=0;j<2;j++){let d=2.5+(i+j)*.22;const p=new T.Vector3(side*1.25-Math.tan(steer)*d*d/5.86,0,d).applyQuaternion(q);guidePositions[k++]=carPos.x+p.x;guidePositions[k++]=.065;guidePositions[k++]=carPos.z+p.z;}guideGeometry.attributes.position.needsUpdate=true;}
function updateCamera(dt){if(state==='replay'||state==='wreckReview')return;carPos.set(0,spec.offset,0).applyQuaternion(car.root.quaternion).add(car.root.position);if(firstPerson&&state!=='wreck'){if(streetLife.mode==='foot')carPos.copy(streetLife.cameraTarget());else{const eye=new T.Vector3(spec.bike?0:car.root.userData.steeringX||-.42,spec.bike?1.45:spec.monster?3.55:1.45,spec.bike?-.15:spec.monster?-.25:.25);carPos.copy(eye.applyQuaternion(car.root.quaternion).add(car.root.position));const f=new T.Vector3(0,0,-1).applyQuaternion(car.root.quaternion);orbitYaw=Math.atan2(-f.x,-f.z)+vehicleLookYaw;}camGoal.copy(carPos);look.copy(carPos).add(new T.Vector3(-Math.sin(orbitYaw)*Math.cos(orbitPitch),-Math.sin(orbitPitch),-Math.cos(orbitYaw)*Math.cos(orbitPitch)).multiplyScalar(12));}else if(streetLife.mode==='foot'){carPos.copy(streetLife.cameraTarget());look.copy(carPos);if(!streetLife.inside)look.add(new T.Vector3(-Math.sin(orbitYaw)*6,-Math.sin(orbitPitch)*3,-Math.cos(orbitYaw)*6));const d=streetLife.inside?Math.min(5,orbitDistance):Math.min(12,orbitDistance);camGoal.set(carPos.x+Math.sin(orbitYaw)*Math.cos(orbitPitch)*d,carPos.y+Math.sin(orbitPitch)*d,carPos.z+Math.cos(orbitYaw)*Math.cos(orbitPitch)*d);if(streetLife.inside){camGoal.x=clamp(camGoal.x,-6007.7,-5992.3);camGoal.z=clamp(camGoal.z,-6.7,6.7);camGoal.y=Math.min(3.3,camGoal.y);}else{const hit=new C.RaycastResult();if(world.raycastClosest(new C.Vec3(carPos.x,carPos.y,carPos.z),new C.Vec3(camGoal.x,camGoal.y,camGoal.z),{collisionFilterMask:1|8,skipBackfaces:true},hit)){const v=new T.Vector3().copy(hit.hitPointWorld).sub(carPos),len=v.length();camGoal.copy(carPos).addScaledVector(v,Math.max(.1,(len-.3)/Math.max(.1,len)));}}}else if(state==='wreck'){look.set(0,0,0);for(const p of car.assemblies)look.add(p.position);look.multiplyScalar(1/car.assemblies.length);camGoal.copy(look).add(new T.Vector3(11,8,11));}else{const forward=new T.Vector3(0,0,-1).applyQuaternion(car.root.quaternion);const yaw=Math.atan2(-forward.x,-forward.z);if(orbitMode!=='orbit')orbitYaw=yaw+(orbitMode==='back'?Math.PI:0);const d=orbitDistance*(camera.aspect<.8?1.18:1);look.copy(carPos);look.y+=spec.monster?.9:.35;camGoal.set(look.x+Math.sin(orbitYaw)*Math.cos(orbitPitch)*d,look.y+Math.sin(orbitPitch)*d,look.z+Math.cos(orbitYaw)*Math.cos(orbitPitch)*d);}
 if(!camInit){camera.position.copy(camGoal);camLook.copy(look);camInit=true;}else{camera.position.lerp(camGoal,firstPerson?1:1-Math.exp(-dt*9));camLook.lerp(look,firstPerson?1:1-Math.exp(-dt*9));}camera.lookAt(camLook);camera.fov=firstPerson?72:isSecret()?60:54;camera.near=firstPerson?.035:.15;camera.updateProjectionMatrix();sun.position.set(carPos.x-20,45,carPos.z+15);sun.target.position.copy(carPos);updateGuides();}
let borrowed=null;
function releaseBorrowed(){if(!borrowed)return;const b=borrowed,item=b.item;item.occupied=false;item.body.position.copy(chassis.position);if(!item.asset?.config.bike)item.body.position.y=.8;item.body.quaternion.copy(chassis.quaternion);item.body.mass=0;item.body.type=C.Body.STATIC;item.body.updateMassProperties();item.body.velocity.setZero();item.body.angularVelocity.setZero();item.body.aabbNeedsUpdate=true;item.mesh.visible=true;if(item.asset?.config.bike){item.mesh.position.copy(item.body.position);item.mesh.position.y-=item.asset.config.offset;item.mesh.quaternion.copy(item.body.quaternion);item.mesh.getObjectByName('rider').visible=false;}world.addBody(item.body);disposeVehiclePaint(car.root);scene.remove(car.root);world.removeBody(b.parkedBody);car=b.car;spec=car.config;chassis.position.copy(b.position);chassis.quaternion.copy(b.quaternion);chassis.velocity.setZero();chassis.angularVelocity.setZero();chassis.aabbNeedsUpdate=true;car.root.visible=true;borrowed=null;configureVehicle();syncCar();resetVehicleMotion();}
function borrowVehicle(item){if(item.occupied||item.exploded||item.damage>.3)return false;const parkedBody=new C.Body({mass:0,material:carMat,position:chassis.position.clone(),quaternion:chassis.quaternion.clone()});for(let i=0;i<chassis.shapes.length;i++)parkedBody.addShape(chassis.shapes[i],chassis.shapeOffsets[i],chassis.shapeOrientations[i]);parkedBody.userData={kind:'parked player car'};world.addBody(parkedBody);borrowed={item,car,position:chassis.position.clone(),quaternion:chassis.quaternion.clone(),parkedBody};
 if(item.asset?.config.bike){const source=item.asset.root.clone(true);source.visible=true;source.position.set(0,0,0);source.quaternion.identity();const config={...item.asset.config,golden:!!spec.golden,scoreMultiplier:spec.scoreMultiplier},parts=source.children.filter(p=>p.userData.home);for(const p of parts){p.position.copy(p.userData.home);p.quaternion.identity();p.userData={...p.userData,home:p.position.clone(),attached:true};}return activateBorrowed(item,source,config,parts);}
 const source=item.mesh.clone(true);source.visible=true;source.position.set(0,0,0);source.quaternion.identity();const config={...VEHICLES[0],id:'borrowed-car',baseId:'street-'+(item.model||'standard'),name:'Street car',radius:.35,track:.98,front:-1.36,rear:1.36,offset:.8,halfWidth:1.1,halfLength:2.2,box:[1.04,.35,2.18],center:.05,power:1900,mass:1150,maxSpeed:19,scoreMultiplier:spec.scoreMultiplier,golden:!!spec.golden};const parts=[...source.children].map(mesh=>{const g=new T.Group();g.name=mesh.name;g.position.copy(mesh.position);mesh.position.set(0,0,0);source.add(g);g.add(mesh);return g;});
 for(const p of parts){if(p.name.startsWith('wheel-')&&item.model==='standard'){const sx=p.position.x<0?'right':'left',end=p.position.z<0?'front':'rear';p.name='wheel-'+end+'-'+sx;}p.userData={home:p.position.clone(),attached:true};}
 if(item.model!=='standard'){const model=garage.find(g=>g.config.id===item.model),front=parts.find(p=>p.name==='wheel-front-right'),rear=parts.find(p=>p.name==='wheel-rear-right');if(model&&front&&rear){const factor=Math.abs(front.position.z/model.config.front);Object.assign(config,{name:model.config.name,radius:model.config.radius*factor,track:Math.abs(front.position.x),front:front.position.z,rear:rear.position.z,offset:.8});}}
 for(const name of ['engine','wheel-front-right','wheel-front-left','wheel-rear-right','wheel-rear-left'])if(!parts.find(p=>p.name===name)){const p=new T.Group();p.name=name;p.userData={home:p.position.clone(),attached:true};source.add(p);parts.push(p);}
 return activateBorrowed(item,source,config,parts);
}
function activateBorrowed(item,source,config,parts){car={root:source,assemblies:parts,config,materials:item.asset?.materials||garage.find(g=>g.config.id===item.model)?.materials||{}};spec=config;scene.add(source);item.occupied=true;item.mesh.visible=false;world.removeBody(item.body);chassis.position.copy(item.body.position);chassis.position.y=Math.max(spec.bike?.65:1.05,spec.offset+.2);chassis.quaternion.copy(item.body.quaternion);chassis.velocity.setZero();chassis.angularVelocity.setZero();chassis.aabbNeedsUpdate=true;configureVehicle();restore();syncCar();resetVehicleMotion();if(spec.bike)notify('Mango RR · RT throttle · LT brake · R3 rider view',2);return true;
}

const streetLife=createStreetLife({T,C,scene,world,lots,chassis,crowd,groundMat,getView:view,getLevel:()=>levelIndex,getCar:()=>car,getState:()=>state,getCamera:()=>({yaw:orbitYaw,pitch:orbitPitch,first:firstPerson,camera}),getAim:()=>{const from=new C.Vec3(camera.position.x,camera.position.y,camera.position.z),direction=camera.getWorldDirection(new T.Vector3()),to=new C.Vec3(from.x+direction.x*100,from.y+direction.y*100,from.z+direction.z*100),hit=new C.RaycastResult();return world.raycastClosest(from,to,{collisionFilterMask:1|4|8,checkCollisionResponse:false,skipBackfaces:true},hit)?new T.Vector3().copy(hit.hitPointWorld):new T.Vector3().copy(to);},getContracts:()=>contracts,getFleet:()=>[car,...garage.filter(g=>vehicleKey(g)!==vehicleKey(car))],getRepair:target=>({needed:(!target||target===car)&&(health<99.5||car.assemblies.some(p=>!p.userData.attached)),price:40+Math.ceil((100-health)*1.5)+car.assemblies.filter(p=>!p.userData.attached).length*10}),onTune:target=>{target.thumbnail=null;if(target===car){configureVehicle();resetVehicleMotion();}else paintVehicle(target,streetLife.economy.upgradeInfo(vehicleKey(target)).paint);},onRepair:()=>{restore();configureVehicle();failures.reset(spec.id==='e250');pendingHit=null;notify('Vehicle repaired',1.3);},clearInput,notify,onEnterCar:borrowVehicle,onExitCar:releaseBorrowed,onCamera:kind=>{camInit=false;orbitMode='orbit';orbitPitch=kind==='vehicle'?.52:.28;orbitDistance=kind==='vehicle'?(spec.bike?7:spec.monster?18:13):kind==='interior'?4.2:5.5;if(kind==='vehicle'){orbitMode='follow';vehicleLookYaw=0;}if(firstPerson)orbitPitch=0;},onHit:(body,point,power,weapon,direction)=>{crowd.strike(body,point,power,weapon,direction);environment.strike(body,point,power);traffic.strike(body,point,power);burst(point,weapon==='hammer'?4:2);crashSound(power*.25);},onBlast:(point,power)=>{crowd.blast(point,power);environment.blast(point,power);traffic.blast(point,power);barrelEffects.show(point);burst(point,18);crashSound(25);}});
function resize(){if(wheelPointer!==null)clearInput();renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();camInit=false;}window.addEventListener('resize',resize);resize();$('intro').querySelector('.panel').prepend(document.querySelector('.top'));configureVehicle();renderGarage();loadLevel(0);$('start').disabled=false;renderLots();
$('view').addEventListener('webglcontextlost',e=>{e.preventDefault();if(state==='running')pause();$('fatal').hidden=false;$('errorText').textContent='The graphics context was interrupted. Reload to resume.';});
let last=performance.now(),hudClock=0;function frame(now){requestAnimationFrame(frame);const realDt=Math.max(0,Math.min(.06,(now-last)/1000));last=now;if(document.hidden)return;clock+=realDt;pollController(realDt);updateWheel(realDt);slow=state==='running'&&(keys.ShiftLeft||keys.ShiftRight||touch.slow);$('slowBadge').hidden=!slow;const dt=realDt*(slow?.24:1);if(state==='countdown'){countdown-=realDt;if(countdown<=0){state='running';notify('Go!',1);}}
 if(!streetLife.shopOpen&&(state==='running'||state==='countdown'||state==='menu'||state==='wreck'))physics(dt);else if(state==='replay')director.update(realDt);updateCamera(realDt);if(clock>noticeUntil)$('notice').style.opacity='0';flash*=Math.exp(-realDt*6);$('crashFlash').style.opacity=flash;hudClock+=realDt;if(hudClock>.1){hud();streetLife.ui();$('perspectiveButton').hidden=state!=='running'||streetLife.shopOpen;$('perspectiveButton').textContent=firstPerson?'3rd person · R3':'1st person · R3';$('perspectiveButton').setAttribute('aria-pressed',String(firstPerson));hudClock=0;}if(gain){gain.gain.setTargetAtTime(sound&&state==='running'&&streetLife.mode==='vehicle'&&health>0?.024+(input.gas||0)*.026:0,audioCtx.currentTime,.12);engineOsc.frequency.setTargetAtTime(30+Math.abs(forwardSpeed)*3+(input.gas||0)*12,audioCtx.currentTime,.1);}sky.follow(camera);renderer.render(scene,camera);}
requestAnimationFrame(frame);
// Read-only state inspection plus deterministic integration hooks for local development.
window.roadster={getState:()=>({contracts:contracts?.getInfo(),upgrades:streetLife.economy.upgradeInfo(vehicleKey(car)),vehiclePower:spec.power,streetLife:streetLife.getInfo(),state,health,distance,time,speed,forwardSpeed,position:{...chassis.position},vehicle:spec.id,partsLost:totalLost,golden:!!spec.golden,monster:!!spec.monster,goldUnlocked:goldUnlocked(),driverSide:car.root.userData.driverSide,penalty,attached:car.assemblies.filter(p=>p.userData.attached).map(p=>p.name),drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,level:levelIndex,secretUnlocked:goldUnlocked(),secret:isSecret(),destruction:isSecret()?objective?.getInfo():null,bonusUnlocked:baseComplete(),noBrakes:!!spec.noBrakes,parking:parkingState,parkingHold,bumps,gear:selectedGear,firstPerson,boundary:boundary.getInfo(),orbitMode,orbitYaw,orbitPitch,orbitDistance,controller:controller.getState(),pedals:{gas:input.gas||0,brake:input.brake||0},mode:isSecret()?'destruction':mode,steering:steer,wheelAngle,wheelVisualOmega:visualWheelOmega.slice(0,vehicle.wheelInfos.length),wheelVisualAngle:visualWheelAngle.slice(0,vehicle.wheelInfos.length),wheelSlip:visualWheelSlip.slice(0,vehicle.wheelInfos.length),score:runScore,scoring:scoring.snapshot(time),failure:failures.snapshot(),dimensions:{halfWidth:spec.halfWidth||1.27,halfLength:spec.halfLength||2.4,track:spec.track,front:spec.front,rear:spec.rear,radius:spec.radius},route:{cleared:gateProgress,total:isSecret()?0:3,next:lot().gates[gateProgress]||null},endless:isSecret()?destructionLoop?.getInfo():null,effects:{sparks:sparks.length,sparkPool:sparkPool.length,sparkLimit:72},memory:renderer.info.memory||null,secretDetail:secretView?.detail.getInfo()||null,environment:environment.getInfo(),terrain:terrain.getInfo(),parkedTraffic:traffic.getInfo(),pedestrians:crowd.getInfo(),replay:director.getInfo()}),start,renderer,scene,camera};
if(location.hostname==='localhost'||location.hostname==='127.0.0.1')window.roadster.test={boundary,togglePerspective,setFootCamera:(yaw,pitch=.28)=>{orbitYaw=yaw;orbitPitch=pitch;camInit=false;},streetLife,environment,terrain,lots,scoring,failures,chassis,world,vehicle,obstacles,crowd,traffic,get car(){return car;},get objective(){return objective;},get destructionLoop(){return destructionLoop;},get contracts(){return contracts;},get spec(){return spec;},get secretView(){return secretView;},selectVehicle,detach,explode,restore,recover,step:physics,loadLevel,assessParking,setGoldenMode,handleHit,finish,setCamera,setGear:v=>selectedGear=v,director,continueWreck,startReplay,updateWheel,updateVisualWheelSpin,setMode:v=>mode=v,setState:v=>state=v,teleport:(x,z,yaw=0,v=0)=>{chassis.position.set(view().ox+x,Math.max(1,spec.offset+.15),z);chassis.quaternion.setFromEuler(0,yaw,0);const f=chassis.quaternion.vmult(new C.Vec3(0,0,-1));chassis.velocity.set(f.x*v,0,f.z*v);chassis.angularVelocity.setZero();chassis.aabbNeedsUpdate=true;chassis.wakeUp();resetVehicleMotion();},input:keys};
}

