// Instanced animated pedestrians; only struck characters become articulated physics bodies.
export function createPedestrians({T,C,scene,world,chassis,groundMat,onHit,onThrownImpact=()=>{},getImpactView=()=>null,lowDetail=false,random=()=>Math.random()}){
 const max=160,people=[],pending=new Set(),pendingThrows=new Map(),root=new T.Group();scene.add(root);
 const skin=[0xf0c7a2,0xc99169,0x875a40,0x5e3d2e],shirts=[0x327c8c,0xa94443,0xd6ac47,0x64588c,0x548863,0xd0d0bc],pants=[0x35495e,0x45433d,0x252b38];
 const defs=[
  {n:'torso',p:[0,1.08,0],s:[.35,.56,.25],color:'shirt'},
  {n:'hips',p:[0,.78,0],s:[.34,.23,.24],color:'pants'},
  {n:'head',p:[0,1.53,0],s:[.27,.33,.27],color:'skin',sphere:true},
  {n:'armL',p:[-.27,1.03,0],s:[.135,.55,.135],color:'shirt'},
  {n:'armR',p:[.27,1.03,0],s:[.135,.55,.135],color:'shirt'},
  {n:'legL',p:[-.105,.40,0],s:[.16,.68,.17],color:'pants'},
  {n:'legR',p:[.105,.40,0],s:[.16,.68,.17],color:'pants'},
  {n:'handL',parent:3,offset:[0,-.285,0],s:[.12,.15,.12],color:'skin',sphere:true},
  {n:'handR',parent:4,offset:[0,-.285,0],s:[.12,.15,.12],color:'skin',sphere:true},
  {n:'shoeL',parent:5,offset:[0,-.325,-.055],s:[.18,.12,.28],color:'shoe'},
  {n:'shoeR',parent:6,offset:[0,-.325,-.055],s:[.18,.12,.28],color:'shoe'},
  {n:'hair',parent:2,offset:[0,.095,.024],s:[.285,.19,.275],color:'hair',sphere:true},
  {n:'nose',parent:2,offset:[0,-.01,-.143],s:[.055,.067,.068],color:'skin',sphere:true},
  {n:'eyeL',parent:2,offset:[-.055,.04,-.127],s:[.026,.026,.025],color:'shoe',sphere:true},
  {n:'eyeR',parent:2,offset:[.055,.04,-.127],s:[.026,.026,.025],color:'shoe',sphere:true}
 ];
 const sphere=new T.SphereGeometry(.5,lowDetail?8:12,lowDetail?6:8),capsule=new T.CapsuleGeometry(.5,.5,lowDetail?3:4,lowDetail?6:10);capsule.scale(1,2/3,1);
 const material=new T.MeshStandardMaterial({color:0xffffff,roughness:.87});
 const meshes=defs.map(d=>{const m=new T.InstancedMesh(d.sphere?sphere:capsule,material,max);m.instanceMatrix.setUsage(T.DynamicDrawUsage);m.frustumCulled=false;m.castShadow=true;root.add(m);return m;});
 const path=new T.Mesh(new T.PlaneGeometry(85,8),new T.MeshStandardMaterial({color:0xb2b2a3,roughness:1}));path.rotation.x=-Math.PI/2;path.position.set(0,.004,55);root.add(path);
 const obj=new T.Object3D(),q=new T.Quaternion(),yAxis=new T.Vector3(0,1,0),xAxis=new T.Vector3(1,0,0),v=new T.Vector3();let origin=0,hitCount=0,elapsed=0,lastWindshield=-10,windshieldHits=0,heldPerson=null;
 const routeLength=172;
 function route(distance,p){if(p?.route){const r=p.route,w=r.x1-r.x0,d=r.z1-r.z0,len=2*(w+d);let t=((distance%len)+len)%len;if(t<w)return{x:origin+r.x0+t,z:r.z0,yaw:-Math.PI/2};t-=w;if(t<d)return{x:origin+r.x1,z:r.z0+t,yaw:Math.PI};t-=d;if(t<w)return{x:origin+r.x1-t,z:r.z1,yaw:Math.PI/2};return{x:origin+r.x0,z:r.z1-(t-w),yaw:0};}let t=((distance%routeLength)+routeLength)%routeLength;if(t<80)return{x:origin-40+t,z:52,yaw:-Math.PI/2};t-=80;if(t<6)return{x:origin+40,z:52+t,yaw:Math.PI};t-=6;if(t<80)return{x:origin+40-t,z:58,yaw:Math.PI/2};return{x:origin-40,z:58-(t-80),yaw:0};}
 function cleanup(p){if(heldPerson===p)heldPerson=null;p.held=false;if(p.sensor)world.removeBody(p.sensor);if(p.bodies){for(const c of p.constraints)world.removeConstraint(c);for(const b of p.bodies)world.removeBody(b);p.bodies=null;p.constraints=[];p.windshield=0;}}
 function walkingPose(p){const r=route(p.distance,p),base=new T.Vector3(r.x,0,r.z),turn=new T.Quaternion().setFromAxisAngle(yAxis,r.yaw+(p.direction<0?Math.PI:0)),stride=Math.sin(p.phase)*.47;
  for(let i=0;i<7;i++){const d=defs[i],pos=new T.Vector3(...d.p),rot=new T.Quaternion();if(i>=3){const a=i<5&&p.robPose>0?-1.8:(i%2?1:-1)*stride*(i<5?-.8:1);rot.setFromAxisAngle(xAxis,a);const pivot=new T.Vector3(d.p[0],i<5?1.29:.76,0);pos.sub(pivot).applyQuaternion(rot).add(pivot);}pos.y+=Math.abs(Math.sin(p.phase))*.022;p.pose[i].p.copy(pos).multiplyScalar(p.scale).applyQuaternion(turn).add(base);p.pose[i].q.copy(turn).multiply(rot);}
  if(p.sensor){p.sensor.position.set(r.x,.87*p.scale,r.z);p.sensor.aabbNeedsUpdate=true;}
 }
 function makeSensor(p){const b=new C.Body({mass:0,type:C.Body.KINEMATIC,shape:new C.Box(new C.Vec3(.34*p.scale,.86*p.scale,.24*p.scale)),collisionResponse:false,collisionFilterGroup:4,collisionFilterMask:32});b.userData={kind:'pedestrian',person:p};b.addEventListener('collide',e=>{if(e.body===chassis&&chassis.velocity.length()>.8&&!p.down)pending.add(p);});world.addBody(b);p.sensor=b;}
 function reset(level,ox,options={}){for(const p of people)cleanup(p);people.length=0;pending.clear();pendingThrows.clear();origin=ox;hitCount=0;elapsed=0;lastWindshield=-10;windshieldHits=0;path.position.x=ox;path.visible=!options.routes;const count=Math.min(max,options.count||6+2*level);meshes.forEach(m=>m.count=count);
  for(let i=0;i<count;i++){const route=options.routes?.[i%options.routes.length],length=route?2*(route.x1-route.x0+route.z1-route.z0):routeLength,p={i,route,district:route?.district??0,distance:route?Math.floor(i/options.routes.length)*length/(count/options.routes.length):i*length/count,phase:i*1.7,speed:.65+(i%5)*.10,direction:i%3?1:-1,scale:.94+(i%4)*.035,pose:Array.from({length:7},()=>({p:new T.Vector3(),q:new T.Quaternion()})),bodies:null,down:false,age:0,held:false,split:false,throwTime:0,throwHit:false,health:100,robbed:false,cash:8+(i*17+level*11)%53,robPose:0,flee:0,hurt:0,windshield:0};people.push(p);const colors={skin:skin[i%4],shirt:shirts[i%6],pants:pants[i%3],shoe:0x222625,hair:[0x302720,0x62503a,0x292421,0x8b6944][i%4]};p.shirtColor=colors.shirt;meshes.forEach((m,j)=>m.setColorAt(i,new T.Color(colors[defs[j].color])));makeSensor(p);walkingPose(p);}
  meshes.forEach(m=>{m.instanceColor.needsUpdate=true;});render();
 }
 function knockDown(p,kick=null,windshield=false){if(p.down&&p.bodies)return false;const wasDown=p.down,live=people.filter(p=>p.bodies&&!p.held&&!p.impacting);if(people.filter(p=>p.bodies).length>=16)freeze(live.sort((a,b)=>b.age-a.age)[0]);p.down=true;p.health=0;if(p.sensor)world.removeBody(p.sensor);p.sensor=null;p.age=0;if(!wasDown){hitCount++;onHit?.();}p.bodies=[];p.constraints=[];
  const motion=kick?kick.clone():chassis.velocity.clone(),speed=motion.length();motion.scale(Math.min(.72,8/Math.max(1,speed)),motion);
  for(let i=0;i<7;i++){const d=defs[i],s=p.scale,b=new C.Body({mass:i===0?23:i===1?12:i===2?5:7,material:groundMat,linearDamping:.20,angularDamping:.35,collisionFilterGroup:4,collisionFilterMask:3,allowSleep:true});b.addShape(i===2?new C.Sphere(.145*s):new C.Box(new C.Vec3(d.s[0]*s/2,d.s[1]*s/2,d.s[2]*s/2)));b.position.copy(p.pose[i].p);b.quaternion.copy(p.pose[i].q);b.velocity.set(motion.x,Math.min(3,.7+speed*.15),motion.z);b.angularVelocity.set((p.i%2?1:-1)*1.2,0,.8);b.userData={kind:'pedestrian',person:p};b.addEventListener('collide',e=>{if(p.throwTime>0&&!p.throwHit&&!p.held&&Math.abs(e.contact.getImpactVelocityAlongNormal())>5&&!pendingThrows.has(p))pendingThrows.set(p,{target:e.body,point:b.position.clone(),velocity:b.velocity.clone()});});world.addBody(b);p.bodies.push(b);}
  const links=[[0,1,[0,.83,0]],[0,2,[0,1.38,0]],[0,3,[-.24,1.29,0]],[0,4,[.24,1.29,0]],[1,5,[-.105,.76,0]],[1,6,[.105,.76,0]]];
  const r=route(p.distance,p),turn=new T.Quaternion().setFromAxisAngle(yAxis,r.yaw+(p.direction<0?Math.PI:0));for(const [a,b,pt]of links){const joint=wasDown?p.pose[a].p.clone().lerp(p.pose[b].p,.5):new T.Vector3(...pt).multiplyScalar(p.scale).applyQuaternion(turn).add(new T.Vector3(r.x,0,r.z)),pa=new C.Vec3(),pb=new C.Vec3();p.bodies[a].pointToLocalFrame(new C.Vec3(...joint.toArray()),pa);p.bodies[b].pointToLocalFrame(new C.Vec3(...joint.toArray()),pb);const constraint=new C.ConeTwistConstraint(p.bodies[a],p.bodies[b],{pivotA:pa,pivotB:pb,axisA:new C.Vec3(0,1,0),axisB:new C.Vec3(0,1,0),angle:Math.PI*.40,twistAngle:.6,maxForce:3500,collideConnected:false});world.addConstraint(constraint);p.constraints.push(constraint);}
  if(windshield)windshieldLaunch(p);return true;
 }
 function freeze(p){if(!p.split&&p.pose[0].p.y>.85){const base=p.pose[1].p.clone();base.y=.22;const turn=new T.Quaternion().setFromAxisAngle(yAxis,p.i*.8).multiply(new T.Quaternion().setFromAxisAngle(new T.Vector3(0,0,1),Math.PI/2));for(let i=0;i<7;i++){p.pose[i].p.set(...defs[i].p).sub(new T.Vector3(0,.78,0)).multiplyScalar(p.scale).applyQuaternion(turn).add(base);p.pose[i].q.copy(turn);}}if(p.split){const dx=p.pose[0].p.x-p.pose[1].p.x,dz=p.pose[0].p.z-p.pose[1].p.z,d=Math.hypot(dx,dz),move=Math.max(0,(.85-d)/2),nx=d>.001?dx/d:1,nz=d>.001?dz/d:0;for(const i of [0,2,3,4]){p.pose[i].p.x+=nx*move;p.pose[i].p.z+=nz*move;}for(const i of [1,5,6]){p.pose[i].p.x-=nx*move;p.pose[i].p.z-=nz*move;}}if(p.split)for(const [anchor,indices] of [[0,[0,2,3,4]],[1,[1,5,6]]]){if(p.pose[anchor].p.y>.85){const drop=p.pose[anchor].p.y-.28;for(const i of indices)p.pose[i].p.y-=drop;}}cleanup(p);p.sensor=null;}
 function grab(p){if(heldPerson||!people.includes(p)||p.split)return false;if(!p.bodies)knockDown(p,new C.Vec3());heldPerson=p;p.held=true;p.carryConfigured=false;p.windshield=0;p.age=0;p.throwTime=0;for(const b of p.bodies){b.type=C.Body.KINEMATIC;b.collisionFilterMask=0;b.collisionResponse=false;b.velocity.setZero();b.angularVelocity.setZero();b.force.setZero();b.torque.setZero();b.updateMassProperties();b.wakeUp();}return true;}
 const carryTurn=new T.Quaternion(),carryTilt=new T.Quaternion().setFromAxisAngle(new T.Vector3(0,0,1),Math.PI/2),carryOffset=new T.Vector3();
 function carry(position,yaw){const p=heldPerson;if(!p?.bodies)return false;carryTurn.setFromAxisAngle(yAxis,yaw).multiply(carryTilt);for(let i=0;i<7;i++){const b=p.bodies[i];carryOffset.set(...defs[i].p).sub(v.set(...defs[0].p)).multiplyScalar(p.scale).applyQuaternion(carryTurn);b.position.set(position.x+carryOffset.x,position.y+carryOffset.y,position.z+carryOffset.z);b.quaternion.copy(carryTurn);b.velocity.setZero();b.angularVelocity.setZero();b.aabbNeedsUpdate=true;p.pose[i].p.copy(b.position);p.pose[i].q.copy(b.quaternion);}if(!p.carryConfigured){const links=[[0,1,[0,.83,0]],[0,2,[0,1.38,0]],[0,3,[-.24,1.29,0]],[0,4,[.24,1.29,0]],[1,5,[-.105,.76,0]],[1,6,[.105,.76,0]]];links.forEach(([a,b,pt],i)=>{carryOffset.set(...pt).sub(v.set(...defs[0].p)).multiplyScalar(p.scale).applyQuaternion(carryTurn);const joint=new C.Vec3(position.x+carryOffset.x,position.y+carryOffset.y,position.z+carryOffset.z),c=p.constraints[i];p.bodies[a].pointToLocalFrame(joint,c.pivotA);p.bodies[b].pointToLocalFrame(joint,c.pivotB);});p.carryConfigured=true;}p.age=0;renderPerson(p);for(const m of meshes)m.instanceMatrix.needsUpdate=true;return true;}
 function releaseHeld(velocity=new C.Vec3(),split=false){const p=heldPerson;if(!p?.bodies)return false;heldPerson=null;p.held=false;p.age=0;p.throwTime=velocity.length()>5?3:0;p.throwHit=false;p.lastFlight=p.bodies[0].position.clone();if(split){p.split=true;const waist=p.constraints.shift();if(waist)world.removeConstraint(waist);}
  const right=p.bodies[0].quaternion.vmult(new C.Vec3(0,1,0));for(let i=0;i<7;i++){const b=p.bodies[i],side=i===1||i>=5?1:-1;b.type=C.Body.DYNAMIC;b.collisionFilterMask=1|2|4|8;b.collisionResponse=true;b.updateMassProperties();b.velocity.copy(velocity);if(split){b.velocity.x+=right.x*side*5;b.velocity.z+=right.z*side*5;b.velocity.y+=side*2;}b.angularVelocity.set(split?side*3:2,1,.7);b.aabbNeedsUpdate=true;b.wakeUp();}return true;
 }
 function thrownImpact(p,target,point,velocity){if(p.throwHit||target?.userData?.person===p||target?.userData?.kind==='walker'||!target?.shapes||[C.Shape.types.PLANE,C.Shape.types.HEIGHTFIELD].includes(target.shapes[0]?.type))return;p.throwHit=true;p.throwTime=0;const power=Math.max(5,Math.min(16,velocity.length()*.7));p.impacting=true;try{strike(target,point,power,'throw',velocity);}finally{p.impacting=false;}onThrownImpact(target,new T.Vector3().copy(point),power,velocity);}
 function sweptThrow(p){if(!p.lastFlight||p.throwTime<=0||p.throwHit||p.held)return;const to=p.bodies[0].position,from=p.lastFlight;if(from.distanceTo(to)<.001)return;let target=null,point=null,nearest=Infinity;world.raycastAll(from,to,{collisionFilterMask:1|4|8,checkCollisionResponse:false,skipBackfaces:true},hit=>{const b=hit.body;if(b.userData?.person===p||b.userData?.kind==='walker'||[C.Shape.types.PLANE,C.Shape.types.HEIGHTFIELD].includes(b.shapes[0]?.type))return;if(hit.distance<nearest){nearest=hit.distance;target=b;point=hit.hitPointWorld.clone();}});if(target)thrownImpact(p,target,point,p.bodies[0].velocity);p.lastFlight.copy(to);}
 function flash(p,value){for(const i of [0,3,4]){meshes[i].setColorAt(p.i,new T.Color(value));meshes[i].instanceColor.needsUpdate=true;}}
 function takeCash(p){if(!people.includes(p)||p.robbed)return null;p.robbed=true;if(!p.down){p.robPose=.8;p.flee=5;}return p.cash;}
 function strike(body,point,power,weapon,direction=null){const p=body?.userData?.person;if(!people.includes(p)||!Number.isFinite(power)||power<=0)return false;
  const kick=direction?new C.Vec3(direction.x,direction.y,direction.z):new C.Vec3(p.pose[0].p.x-point.x,0,p.pose[0].p.z-point.z);if(kick.length()<.01)kick.set(0,0,-1);kick.normalize();kick.scale(Math.min(22,power*2),kick);
  if(p.down){if(p.bodies){for(const b of p.bodies){b.velocity.x+=kick.x*.18;b.velocity.z+=kick.z*.18;b.velocity.y=Math.max(b.velocity.y,1.2);b.wakeUp();}}return true;}
  p.health=Math.max(0,p.health-power*18);p.hurt=.18;flash(p,0xe6c06d);if(p.health===0)knockDown(p,kick);return true;
 }
 // A short ballistic lift uses the existing seven bodies, not an overlay or extra actor.
 function windshieldLaunch(p){const view=getImpactView();if(!view?.first||elapsed-lastWindshield<3||random()>=.35)return false;
  const forward=chassis.quaternion.vmult(new C.Vec3(0,0,-1)),speed=chassis.velocity.dot(forward),local=new C.Vec3();chassis.pointToLocalFrame(p.bodies[0].position,local);
  if(speed<7||local.z>-.35||Math.abs(local.x)>view.halfWidth+.35)return false;
  const follow=.55,t=Math.max(.12,Math.min(.45,(-.85-local.z)/(speed*(1-follow)))),target=new C.Vec3(view.eyeX,view.eyeY-view.offset-.12,-.85),worldTarget=new C.Vec3();chassis.pointToWorldFrame(target,worldTarget);
  const right=chassis.quaternion.vmult(new C.Vec3(1,0,0)),side=Math.max(-5,Math.min(5,(target.x-local.x)/t)),lift=Math.max(5,Math.min(19,(worldTarget.y-p.bodies[0].position.y+4.91*t*t)/t));
  for(const b of p.bodies){b.velocity.set(chassis.velocity.x*follow+right.x*side,lift,chassis.velocity.z*follow+right.z*side);b.angularVelocity.set(right.x*2.5,0,right.z*2.5);b.collisionFilterMask=2;b.wakeUp();}
  p.windshield=t+.22;lastWindshield=elapsed;windshieldHits++;return true;
 }
 function beforeStep(dt,walking){elapsed+=dt;for(const p of people){p.robPose=Math.max(0,p.robPose-dt);p.flee=Math.max(0,p.flee-dt);if(p.hurt>0){p.hurt=Math.max(0,p.hurt-dt);if(!p.hurt)flash(p,p.shirtColor);}if(p.down||p.held)continue;if(walking&&p.robPose===0&&p.hurt===0){const pace=p.speed*(p.flee>0?2.2:1);p.distance+=pace*p.direction*dt;p.phase+=dt*pace*7;}walkingPose(p);}}
 function afterStep(dt,active){if(active)for(const p of pending)knockDown(p,null,true);pending.clear();for(const [p,hit] of pendingThrows)if(p.bodies&&!p.held)thrownImpact(p,hit.target,hit.point,hit.velocity);pendingThrows.clear();const live=people.filter(p=>p.bodies);for(const p of live){if(!p.bodies||p.held)continue;p.age+=dt;sweptThrow(p);p.throwTime=Math.max(0,p.throwTime-dt);if(p.windshield>0){p.windshield=Math.max(0,p.windshield-dt);if(!p.windshield)for(const b of p.bodies)b.collisionFilterMask=3;}for(let i=0;i<7;i++){p.pose[i].p.copy(p.bodies[i].position);p.pose[i].q.copy(p.bodies[i].quaternion);}const settled=p.bodies.every(b=>b.sleepState===C.Body.SLEEPING||b.velocity.length()<.22);if(p.age>9||p.age>2&&settled)freeze(p);}while(people.filter(p=>p.bodies).length>16){const oldest=people.filter(p=>p.bodies&&!p.held).sort((a,b)=>b.age-a.age)[0];freeze(oldest);}render();}
 function blast(point,strength=1){for(const p of people){if(p.down)continue;const dx=p.pose[0].p.x-point.x,dy=p.pose[0].p.y-point.y,dz=p.pose[0].p.z-point.z,d=Math.hypot(dx,dy,dz);if(d<18)strike(p.sensor,point,strength*12*(1-d/18),'grenade',new C.Vec3(dx,Math.max(1,dy),dz));}}
 function renderPerson(p){defs.forEach((d,j)=>{const pose=p.pose[d.parent??j];obj.position.copy(pose.p);obj.quaternion.copy(pose.q);if(d.parent!==undefined)obj.position.add(v.set(...d.offset).multiplyScalar(p.scale).applyQuaternion(obj.quaternion));obj.scale.set(...d.s).multiplyScalar(p.scale);obj.updateMatrix();meshes[j].setMatrixAt(p.i,obj.matrix);});}
 function render(){for(const p of people)renderPerson(p);for(const m of meshes)m.instanceMatrix.needsUpdate=true;}
 function snapshot(){const data=new Float32Array(people.length*7*7);for(const p of people)for(let i=0;i<7;i++){const offset=(p.i*7+i)*7;data.set([...p.pose[i].p.toArray(),...p.pose[i].q.toArray()],offset);}return data;}
 function apply(a,b,u){if(!a||!b)return;for(const p of people)for(let i=0;i<7;i++){const off=(p.i*7+i)*7;p.pose[i].p.fromArray(a,off).lerp(v.fromArray(b,off),u);p.pose[i].q.fromArray(a,off+3).slerp(q.fromArray(b,off+3),u);}render();}
 return{setVisible:value=>root.visible=value,reset,beforeStep,afterStep,blast,strike,takeCash,grab,carry,releaseHeld,get held(){return heldPerson;},snapshot,apply,getInfo:()=>({count:people.length,down:people.filter(p=>p.down).length,hits:hitCount,robbed:people.filter(p=>p.robbed).length,injured:people.filter(p=>p.health<100&&!p.down).length,windshieldHits,held:heldPerson?.i??null,split:people.filter(p=>p.split).length,ragdollLimit:16,activeRagdolls:people.filter(p=>p.bodies).length}),get people(){return people;}};
}
