import {SCRATCH_GAMES,createScratchBoard,ticketProgress,TICKET_WIDTH as W,TICKET_HEIGHT as H,CELLS_PER_ZONE} from './scratch-tickets.js?v=street-20';
export function createScratchUI(economy,notify,onCashChange){
 const $=id=>document.getElementById(id),art=$('scratchArt'),foil=$('scratchCanvas'),coin=$('scratchCoin');let selected=null,rackOpen=true,active=null,board=null,cells=new Set(),pointer=null,previous=null,dirty=false,lastSaved=0;
 art.width=foil.width=W;art.height=foil.height=H;
 const rect=(c,x,y,w,h,r=7)=>{c.beginPath();c.roundRect(x,y,w,h,r);};
 function wrapped(c,value,x,y,width,line=14){let current='';for(const word of value.split(' ')){const next=current?current+' '+word:word;if(c.measureText(next).width>width&&current){c.fillText(current,x,y);y+=line;current=word;}else current=next;}c.fillText(current,x,y);}
 function paintPaper(ticket,settled){const c=art.getContext('2d'),d=board.design;c.clearRect(0,0,W,H);c.fillStyle='#efe5c5';c.fillRect(0,0,W,H);const g=c.createLinearGradient(0,0,W,142);g.addColorStop(0,d.color);g.addColorStop(1,d.accent);c.fillStyle=g;c.fillRect(0,0,W,139);c.strokeStyle='#ffffff16';c.lineWidth=1;for(let i=-160;i<W+160;i+=13){c.beginPath();c.moveTo(i,0);c.bezierCurveTo(i+90,60,i-40,95,i+70,139);c.stroke();}c.textAlign='center';c.fillStyle='#ffebac';c.font='700 10px system-ui';c.fillText('MINT MART · INSTANT GAMES',W/2,24);c.font='900 27px Georgia';wrapped(c,d.name,W/2,59,325,29);c.font='700 13px system-ui';c.fillText('WIN UP TO $500',W/2,106);c.font='800 18px system-ui';c.fillText('$10',326,26);
  for(const [i,z]of board.zones.entries()){c.fillStyle=i<board.zones.length-9?'#f6ebbd':'#faf3db';rect(c,z.x,z.y,z.w,z.h);c.fill();c.strokeStyle=d.color;c.lineWidth=1.5;c.stroke();z.lines.forEach((line,j)=>{c.fillStyle=j===0?'#607068':'#1c343d';let size=j===0?8:j===1?24:13;const family=j===0?'system-ui':'monospace';c.font='700 '+size+'px '+family;if(j===1){size=Math.min(size,Math.max(11,size*(z.w-12)/Math.max(1,c.measureText(line).width)));c.font='800 '+size+'px '+family;}if(board.design.id==='dice'&&z.play>=0&&j===1){const values=board.plays[z.play].values;for(let a=0;a<2;a++){const dx=z.x+21+a*40,dy=z.y+22;c.fillStyle='#f7f4df';rect(c,dx,dy,25,25,4);c.fill();c.strokeStyle='#33463d';c.lineWidth=1;c.stroke();c.fillStyle='#233a38';const dots={1:[[1,1]],2:[[0,0],[2,2]],3:[[0,0],[1,1],[2,2]],4:[[0,0],[2,0],[0,2],[2,2]],5:[[0,0],[2,0],[1,1],[0,2],[2,2]],6:[[0,0],[2,0],[0,1],[2,1],[0,2],[2,2]]};for(const [px,py]of dots[values[a]]){c.beginPath();c.arc(dx+6+px*6.5,dy+6+py*6.5,2,0,Math.PI*2);c.fill();}}}else c.fillText(line,z.x+z.w/2,z.y+(z.lines.length===2?17:15)+j*(z.lines.length===2?24:22));});}
  c.textAlign='left';c.font='10px system-ui';c.fillStyle='#33473e';wrapped(c,d.rule,18,488,324,13);c.font='8px monospace';c.fillText('PACK '+String(ticket.id%99999).padStart(5,'0')+' · GAME '+String(SCRATCH_GAMES.indexOf(d)+1).padStart(2,'0')+' · #'+String(ticket.id).padStart(8,'0'),18,530);let seed=ticket.seed||ticket.id;for(let x=20;x<245;x+=3){seed=(Math.imul(seed,1664525)+1013904223)>>>0;c.fillRect(x,537,seed%2?2:1,13);}c.font='8px system-ui';c.fillText('GAME CASH',267,548);
  if(settled){c.save();c.translate(286,511);c.rotate(-.18);c.strokeStyle='#963a4b';c.lineWidth=2;c.strokeRect(-42,-16,84,32);c.fillStyle='#963a4b';c.textAlign='center';c.font='900 14px system-ui';c.fillText(ticket.payout?'PAID':'VALIDATED',0,5);c.restore();}
 }
 function clearZone(c,z){c.clearRect(z.x-1,z.y-1,z.w+2,z.h+2);}
 function paintFoil(settled){const c=foil.getContext('2d');c.clearRect(0,0,W,H);if(settled)return;let seed=active.seed||1;
  for(const [i,z]of board.zones.entries()){if(z.covered===false)continue;let exposed=0;for(let j=0;j<CELLS_PER_ZONE;j++)if(cells.has(i*CELLS_PER_ZONE+j))exposed++;if(exposed>=CELLS_PER_ZONE*.62)continue;const g=c.createLinearGradient(z.x,z.y,z.x+z.w,z.y+z.h);g.addColorStop(0,'#bcc2c2');g.addColorStop(.27,'#e2e5dc');g.addColorStop(.55,'#929f9f');g.addColorStop(.76,'#cdd1c8');g.addColorStop(1,'#a4aaaa');c.fillStyle=g;rect(c,z.x,z.y,z.w,z.h);c.fill();c.save();rect(c,z.x,z.y,z.w,z.h);c.clip();for(let k=0;k<95;k++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;c.fillStyle=k%2?'#fff4':'#30454b25';c.fillRect(z.x+seed%Math.floor(z.w),z.y+(seed>>>9)%Math.floor(z.h),1+(seed%3),1);}c.strokeStyle='#55645c38';c.lineWidth=.4;for(let a=-z.h;a<z.w;a+=8){c.beginPath();c.moveTo(z.x+a,z.y);c.lineTo(z.x+a+z.h,z.y+z.h);c.stroke();}c.textAlign='center';c.fillStyle='#435751';c.font='700 10px system-ui';c.fillText(i<board.zones.length-9?'SCRATCH TO REVEAL':'MINT MART',z.x+z.w/2,z.y+z.h/2+3);c.restore();}
  c.globalCompositeOperation='destination-out';for(const cell of cells){const z=board.zones[Math.floor(cell/CELLS_PER_ZONE)];if(!z||z.covered===false)continue;const j=cell%CELLS_PER_ZONE;c.beginPath();c.ellipse(z.x+(j%12+.5)*z.w/12,z.y+(Math.floor(j/12)+.5)*z.h/8,z.w/12*.8,z.h/8*.8,0,0,Math.PI*2);c.fill();}c.globalCompositeOperation='source-over';
 }
 function flush(){if(dirty&&active){economy.scratchTicket(active.id,[...cells]);dirty=false;lastSaved=Date.now();}}
 function updateProgress(){if(!active||!board)return;const progress=ticketProgress({...active,scratched:[...cells]},board);$('scratchProgress').textContent=progress.revealed+' / '+progress.total+' panels revealed';$('scratchResult').textContent='Rub the silver coating to reveal the printed game.';if(progress.complete){flush();collect();}}
 function collect(){flush();const payout=economy.claimTicket();if(payout===null)return false;pointer=null;previous=null;coin.hidden=true;selected=null;rackOpen=true;render();onCashChange();notify(payout?'Scratch-off win · $'+payout:'No win this time',2);return true;}
 function revealAll(){if(!active||!economy.info().ticket)return false;return collect();}
 function hide(){flush();pointer=null;previous=null;active=null;board=null;cells.clear();coin.hidden=true;$('scratchBuy').hidden=true;$('scratchBuy').replaceChildren();$('revealScratch').hidden=true;$('scratchResult').textContent='';}
 function open(){flush();if(!economy.info().ticket){selected=null;rackOpen=true;}render();}
 function render(){flush();$('scratchBuy').hidden=false;const s=economy.info();$('shopStock').replaceChildren();$('scratchBuy').replaceChildren();const chooser=document.createElement('button');chooser.id='scratchChooser';chooser.className='scratch-chooser';chooser.textContent=s.ticket?'Finish your '+SCRATCH_GAMES.find(g=>g.id===s.ticket.design).name+' ticket':selected?(rackOpen?'Hide ticket rack':'Choose another game')+' · '+SCRATCH_GAMES.find(g=>g.id===selected).name:'Choose a fresh ticket';chooser.disabled=!!s.ticket;chooser.setAttribute('aria-expanded',String(rackOpen&&!s.ticket));chooser.onclick=()=>{rackOpen=!rackOpen;render();};$('shopStock').append(chooser);const rack=document.createElement('div');rack.className='scratch-rack';rack.hidden=!!s.ticket||!rackOpen;rack.setAttribute('aria-label','Choose scratch-off game');for(const d of SCRATCH_GAMES){const b=document.createElement('button');b.id='scratchGame-'+d.id;b.className='scratch-choice'+(selected===d.id?' active':'');b.style.setProperty('--ticket-color',d.color);b.style.setProperty('--ticket-accent',d.accent);b.textContent=d.name;b.setAttribute('aria-pressed',String(selected===d.id));b.disabled=!!s.ticket;b.onclick=()=>{selected=d.id;rackOpen=false;render();$('shopContent').scrollTop=0;};rack.append(b);}$('shopStock').append(rack);const buy=document.createElement('button');buy.id='buyScratch';buy.className='start';buy.textContent=s.ticket?'Finish current ticket':selected?'Buy '+SCRATCH_GAMES.find(g=>g.id===selected).name+' · $10':'Select a ticket · $10';buy.disabled=!!s.ticket||!selected||s.cash<10;buy.onclick=()=>{if(selected&&economy.buyTicket(selected)){rackOpen=false;render();$('shopContent').scrollTop=0;}onCashChange();};buy.hidden=!!s.ticket;$('scratchBuy').append(buy);
  $('scratchRules').textContent=SCRATCH_GAMES.find(g=>g.id===(s.ticket?.design||selected))?.rule||'Choose a game from the ticket rack.';active=s.ticket;const ticket=active;board=ticket?createScratchBoard(ticket):null;cells=new Set(active?.scratched||[]);$('scratchTicket').hidden=!ticket;$('scratchPrize').textContent='';$('revealScratch').hidden=!active;coin.hidden=true;pointer=null;previous=null;if(ticket){paintPaper(ticket,!active);paintFoil(!active);const p=ticketProgress(active||{...ticket,scratched:[]},board);$('scratchProgress').textContent=active?p.revealed+' / '+p.total+' panels revealed':'Ticket #'+ticket.id+' · validated';$('scratchResult').textContent=active?'Scratch the silver panels or reveal the whole ticket.':ticket.payout?'Won $'+ticket.payout+' · added to your cash.':'No winning play on this ticket.';foil.setAttribute('aria-label',board.design.name+' scratch coating');$('revealScratch').textContent=active&&p.complete?'Collect ticket':'Reveal & collect';}else{art.getContext('2d').clearRect(0,0,W,H);foil.getContext('2d').clearRect(0,0,W,H);$('scratchProgress').textContent='10 games · $10 each';$('scratchResult').textContent='Choose a ticket from the rack.';}
 }
 function rub(x,y,radius){if(!active||!board)return;const c=foil.getContext('2d');c.globalCompositeOperation='destination-out';c.beginPath();c.ellipse(x,y,radius,radius*.68,-.45,0,Math.PI*2);c.fill();c.globalCompositeOperation='source-over';for(const [i,z]of board.zones.entries()){if(z.covered===false||x<z.x-radius||x>z.x+z.w+radius||y<z.y-radius||y>z.y+z.h+radius)continue;for(let j=0;j<CELLS_PER_ZONE;j++){const px=z.x+(j%12+.5)*z.w/12,py=z.y+(Math.floor(j/12)+.5)*z.h/8;if(((px-x)/radius)**2+((py-y)/(radius*.68))**2<1){cells.add(i*CELLS_PER_ZONE+j);dirty=true;}}let count=0;for(let j=0;j<CELLS_PER_ZONE;j++)if(cells.has(i*CELLS_PER_ZONE+j))count++;if(count>=CELLS_PER_ZONE*.62)clearZone(c,z);}}
 function move(e){const box=foil.getBoundingClientRect(),x=(e.clientX-box.left)/box.width*W,y=(e.clientY-box.top)/box.height*H,radius=18+Math.min(1,Math.max(0,e.pressure||.5))*8,start=previous||{x,y},length=Math.hypot(x-start.x,y-start.y),steps=Math.min(100,Math.max(1,Math.ceil(length/6)));for(let i=1;i<=steps;i++)rub(start.x+(x-start.x)*i/steps,start.y+(y-start.y)*i/steps,radius);previous={x,y};coin.hidden=false;coin.style.left=x/W*100+'%';coin.style.top=y/H*100+'%';if(Date.now()-lastSaved>120)flush();updateProgress();}
 foil.addEventListener('pointerdown',e=>{if(!active||pointer!==null)return;e.preventDefault();pointer=e.pointerId;previous=null;foil.setPointerCapture(e.pointerId);move(e);});foil.addEventListener('pointermove',e=>{if(e.pointerId===pointer){e.preventDefault();move(e);}});for(const name of ['pointerup','pointercancel','lostpointercapture'])foil.addEventListener(name,e=>{if(pointer===e.pointerId){flush();pointer=null;previous=null;coin.hidden=true;}});window.addEventListener('pagehide',flush);$('revealScratch').onclick=revealAll;
 return {open,render,hide,flush,revealAll,select:id=>{if(SCRATCH_GAMES.some(g=>g.id===id))selected=id;},getInfo:()=>({selected,ticket:active?.id||null,panels:board?.zones.length||0,cells:cells.size})};
}
