window.WH40K_DATA={
version:'Expanded Atlas v2 · August 2026',
sources:[
['Warhammer Community — What is Warhammer 40,000?','https://www.warhammer-community.com/en-gb/articles/VQFlu0K2/what-is-warhammer-40000/'],
['Warhammer Community — Horus Heresy explained','https://www.warhammer-community.com/en-gb/articles/y7oihj6s/the-horus-heresy-explained-a-short-history-of-the-warmasters-betrayal/'],
['Warhammer Community — Necrons','https://www.warhammer-community.com/en-gb/articles/h2NwHfnF/starting-a-necron-army-in-warhammer-40000-everything-you-need-to-know-from-painting-to-lore/'],
['Warhammer Community — Biotransference','https://www.warhammer-community.com/en-gb/articles/10vZnrg0/what-is-biotransference/'],
['Warhammer Community — Aeldari','https://www.warhammer-community.com/en-gb/articles/s9vyktok/starting-an-aeldari-army-in-warhammer-40000-everything-you-need-to-know-from-painting-to-lore/'],
['Warhammer Community — Tyrannic Wars','https://www.warhammer-community.com/en-gb/articles/gsgP4Jht/a-brief-and-bloody-history-of-the-tyrannic-wars/'],
['Warhammer Community — Pariah Nexus','https://www.warhammer-community.com/en-gb/articles/roKJmNzz/battlezone-pariah-the-story-so-far/'],
['Warhammer Community — The Scouring timeline','https://www.warhammer-community.com/en-gb/articles/xmlkha5o/the-scouring-timeline-how-the-warhammer-studio-worked-with-black-library-authors-on-the-new-series/'],
['Warhammer Community — Red Corsairs 2026','https://www.warhammer-community.com/en-gb/articles/oozg3yry/the-new-year-preview-prepare-to-be-boarded-by-the-new-red-corsairs/'],
['Warhammer Community — Maelstrom: Lair of the Tyrant','https://www.warhammer-community.com/en-gb/articles/lke65sad/sunday-preview-huron-blackheart-sets-sail-from-the-maelstrom/'],
['Lexicanum — main index','https://wh40k.lexicanum.com/wiki/Main_Page']
],
timeline:[
{date:'~60+ million years before M41',title:'The Old Ones and the War in Heaven',era:'Ancient Galaxy',summary:'The Old Ones dominate psychic and Webway science while the short-lived Necrontyr build a rival stellar civilization. Conflict escalates into the galaxy-shaping War in Heaven.',uncertain:true},
{date:'War in Heaven',title:'The Necrontyr discover the C’tan',era:'Ancient Galaxy',summary:'Star-gods of living energy become allies and then masters of the Necrontyr. Their bargain offers victory over mortality at a terrible price.',uncertain:true},
{date:'War in Heaven',title:'Biotransference creates the Necrons',era:'Ancient Galaxy',summary:'The Necrontyr are converted into living-metal bodies. Nobles retain varying degrees of personality while much of the population becomes near-automated soldiery.'},
{date:'War in Heaven',title:'Old Ones create or uplift warrior races',era:'Ancient Galaxy',summary:'Traditions tie the ancient Aeldari and the Krork—the ancestors of modern Orks—to the Old Ones’ war effort. Exact origins remain fragmentary.',uncertain:true},
{date:'Late War in Heaven',title:'Warp catastrophe and the fall of the Old Ones',era:'Ancient Galaxy',summary:'Mass psychic warfare destabilizes the Immaterium. Later accounts associate the era with Enslaver disasters and the destruction or disappearance of the Old Ones.',uncertain:true},
{date:'End of War in Heaven',title:'Necrons shatter the C’tan',era:'Ancient Galaxy',summary:'The Silent King turns on the C’tan, breaking them into shards. Necron dynasties then enter the Great Sleep as younger powers rise.'},
{date:'Millions of years',title:'Aeldari ascendancy',era:'Ancient Galaxy',summary:'The Aeldari become the dominant civilization of the galaxy, mastering psychic technology and the Webway while Necrons sleep and Orks persist.'},
{date:'Human prehistory–M15',title:'Humanity develops and reaches the stars',era:'Humanity',summary:'Human civilization grows from Terra into the Solar System and eventually begins interstellar colonization.'},
{date:'~M15–M25',title:'Dark Age of Technology',era:'Humanity',summary:'Humanity reaches its technological zenith with powerful artificial intelligence, Standard Template Construct systems, advanced genetics and enormous interstellar reach.'},
{date:'Dark Age',title:'The ancestors of the Kin enter the galactic core',era:'Humanity',summary:'Human-derived populations that become the Leagues of Votann develop separately in the dangerous galactic core around Ancestor Cores and clone skeins.',uncertain:true},
{date:'Late Dark Age',title:'Men of Iron wars',era:'Humanity',summary:'Human traditions describe catastrophic wars involving autonomous machine intelligences. Causes, participants and exact chronology are badly preserved.',uncertain:true},
{date:'~M25–M30',title:'Age of Strife / Old Night',era:'Humanity',summary:'Warp storms isolate worlds, psykers proliferate, governments collapse and many human civilizations regress, mutate or die.'},
{date:'Late M30',title:'Fall of the Aeldari and birth of Slaanesh',era:'Ancient Galaxy',summary:'Aeldari excess culminates in the birth of Slaanesh. Most of the old empire is destroyed, the Eye of Terror forms and surviving Aeldari cultures diverge dramatically.'},
{date:'Late M30',title:'Unification Wars',era:'Imperium Rising',summary:'The Emperor conquers techno-barbarian Terra. Thunder Warriors and early Imperial institutions pave the way for the Legiones Astartes.'},
{date:'Late M30',title:'Thunder Warriors purged and Astartes ascend',era:'Imperium Rising',summary:'The unstable Thunder Warriors are removed as the Emperor’s new Space Marine Legions become the principal transhuman army of expansion.',uncertain:true},
{date:'Late M30',title:'Treaty of Mars',era:'Imperium Rising',summary:'Terra and Mars align. The Mechanicum supplies ships, weapons and industrial power while recognizing the Emperor through the Omnissian settlement.'},
{date:'Late M30–early M31',title:'Great Crusade begins',era:'Great Crusade',summary:'Expeditionary fleets spread across the galaxy, reuniting human worlds, exterminating rivals and enforcing the secular Imperial Truth.'},
{date:'Great Crusade',title:'Primarchs are recovered',era:'Great Crusade',summary:'The Emperor finds his scattered gene-sons and gives them command of their Legions. Eighteen become known to history; II and XI are deliberately erased.'},
{date:'Great Crusade',title:'Interex and Diasporex destroyed',era:'Great Crusade',summary:'The Crusade encounters human and mixed civilizations that challenge the Imperium’s assumptions. Their destruction illustrates the uncompromising nature of Imperial expansion.'},
{date:'Great Crusade',title:'Rangdan Xenocides',era:'Great Crusade',summary:'A series of exceptionally costly wars against the Rangda involves multiple Legions and remains one of the most deliberately obscure Great Crusade conflicts.',uncertain:true},
{date:'~M31',title:'Triumph of Ullanor',era:'Great Crusade',summary:'A massive Ork empire is defeated. Horus is elevated to Warmaster while the Emperor returns to Terra for a secret project.'},
{date:'~M31',title:'Council of Nikaea',era:'Great Crusade',summary:'A major dispute over Legion psykers ends with restrictions on Librarians, deepening tensions around Magnus and the Thousand Sons.'},
{date:'~M31',title:'Horus is wounded and corrupted',era:'Horus Heresy',summary:'Events on Davin turn the Warmaster against the Emperor. Existing resentment among several Primarchs becomes the fault line Chaos exploits.'},
{date:'~M31',title:'Isstvan III Atrocity',era:'Horus Heresy',summary:'Traitor Legions attempt to purge their own loyalist elements. Survivors resist and expose the rebellion.'},
{date:'~M31',title:'Drop Site Massacre — Isstvan V',era:'Horus Heresy',summary:'Iron Hands, Salamanders and Raven Guard are betrayed by supposed reinforcements. Ferrus Manus dies and loyalist strength is crippled.'},
{date:'~M31',title:'Burning of Prospero',era:'Horus Heresy',summary:'Magnus’s psychic warning damages the Emperor’s Webway project. Russ attacks Prospero and the Thousand Sons are pushed into Tzeentch’s embrace.'},
{date:'~M31',title:'Battle of Phall',era:'Horus Heresy',summary:'Imperial Fists and Iron Warriors clash in a major fleet battle that intensifies the rivalry between Dorn and Perturabo.'},
{date:'~M31',title:'Thramas Crusade',era:'Horus Heresy',summary:'Dark Angels and Night Lords wage a prolonged campaign across the Thramas Sector, tying down forces far from Terra.'},
{date:'~M31',title:'Calth',era:'Horus Heresy',summary:'Word Bearers ambush the Ultramarines at Calth, turning an allied mustering into a massacre and opening the wider Shadow Crusade.'},
{date:'~M31',title:'Shadow Crusade and Ruinstorm',era:'Horus Heresy',summary:'Lorgar and Angron ravage Ultramar while the Ruinstorm isolates huge regions from Terra.'},
{date:'~M31',title:'Signus Prime',era:'Horus Heresy',summary:'The Blood Angels are lured into a daemonic trap intended to corrupt Sanguinius and his Legion.'},
{date:'~M31',title:'Imperium Secundus',era:'Horus Heresy',summary:'Believing Terra may have fallen, Guilliman creates a contingency empire with Sanguinius as regent and Lion El’Jonson as protector.'},
{date:'~M31',title:'Battle of Molech',era:'Horus Heresy',summary:'Horus returns to a world tied to the Emperor’s hidden past and gains further supernatural power after entering a warp gate.'},
{date:'~M31',title:'Tallarn',era:'Horus Heresy',summary:'Iron Warriors and loyalists fight one of the largest armored wars of the Heresy after Tallarn is devastated by virus bombardment.'},
{date:'~M31',title:'Webway War',era:'Horus Heresy',summary:'Custodes, Sisters of Silence and Mechanicum forces fight beneath Terra to contain the daemonic breach in the Emperor’s failed human Webway project.'},
{date:'Late Heresy',title:'Beta-Garmon and the Titandeath',era:'Horus Heresy',summary:'A gigantic battle intended to delay Horus consumes Titans, Astartes and armies on the road to Terra.'},
{date:'~M31',title:'Solar War',era:'Siege of Terra',summary:'Traitor fleets assault the Solar System, forcing the last defenses back toward Terra.'},
{date:'~M31',title:'Siege of Terra',era:'Siege of Terra',summary:'The final Heresy campaign consumes the Imperial Palace. Sanguinius dies, Horus is destroyed and the Emperor is mortally wounded.'},
{date:'Immediately after',title:'The Emperor is enthroned',era:'The Scouring',summary:'The Golden Throne sustains the Emperor and anchors crucial Imperial psychic functions. The Great Crusade vision is effectively dead.'},
{date:'Early M31',title:'The Great Scouring',era:'The Scouring',summary:'Loyalists drive traitors toward the Eye of Terror and punish worlds that supported Horus.'},
{date:'Early M31',title:'Battle of the Iron Cage',era:'The Scouring',summary:'Imperial Fists and Iron Warriors fight a ruinous post-Heresy siege conflict emblematic of Dorn and Perturabo’s rivalry.'},
{date:'Early M31',title:'Destruction of Caliban',era:'The Scouring',summary:'Dark Angels return to Caliban and fight their own fallen brethren. The world is destroyed and the secret of the Fallen becomes central to the Chapter’s future.'},
{date:'Early M31',title:'Second Founding and Codex Astartes',era:'The Scouring',summary:'Most loyalist Legions are divided into smaller Chapters to prevent another commander from controlling Legion-scale power.'},
{date:'M31 onward',title:'The Primarchs disappear',era:'Imperial Decline',summary:'Loyalist Primarchs die, vanish, enter stasis or pass into legend. Traitor Primarchs become daemon princes or retreat into the Eye.'},
{date:'Early post-Heresy',title:'Legion Wars in the Eye of Terror',era:'Chaos Ascendant',summary:'Traitor Legions turn on one another over territory, slaves and resources. The Sons of Horus collapse before Abaddon eventually creates the Black Legion.'},
{date:'M31',title:'First Black Crusade',era:'Chaos Ascendant',summary:'Abaddon emerges as a new Warmaster of Chaos and begins the long sequence of Black Crusades against the Imperium.'},
{date:'M32',title:'War of the Beast',era:'Imperial Decline',summary:'An unprecedented Ork empire nearly destroys the Imperium, attacks Terra’s political order and forces major reforms.'},
{date:'M35',title:'Nova Terra Interregnum',era:'Imperial Decline',summary:'Large parts of the Imperium reject Terra’s authority for centuries, producing a prolonged political and religious division.'},
{date:'M35',title:'Moirae Schism',era:'Imperial Decline',summary:'A Mechanicus doctrinal crisis spreads into the wider Imperium and even divides Space Marine Chapters.',uncertain:true},
{date:'M36',title:'Age of Apostasy / Reign of Blood',era:'Imperial Decline',summary:'Goge Vandire seizes political and religious power. His fall helps shape the modern Ecclesiarchy and Adepta Sororitas.'},
{date:'M36',title:'Abyssal Crusade',era:'Imperial Decline',summary:'Numerous Space Marine Chapters are ordered into the Eye of Terror under corrupt judgment; many are destroyed or corrupted.'},
{date:'M37–M39',title:'Age of Redemption and countless crusades',era:'Imperial Decline',summary:'Imperial expansion surges again through crusades and reconquests, but the empire remains technologically stagnant and politically fragmented.'},
{date:'M41',title:'Macharian Crusade',era:'Imperial Decline',summary:'Lord Solar Macharius leads one of the greatest post-Heresy Imperial expansions before his death triggers instability and civil war.'},
{date:'M41',title:'12th Black Crusade / Gothic War',era:'Chaos Ascendant',summary:'Abaddon fights across the Gothic Sector in a campaign centered on Blackstone Fortresses and control of strategic space.'},
{date:'587.M41',title:'Maelstrom Warders formed',era:'Badab & Maelstrom',summary:'Astral Claws, Lamenters, Mantis Warriors and Charnel Guard are among Chapters tasked with containing threats around the Maelstrom.'},
{date:'697/715.M41',title:'Lufgt Huron becomes Astral Claws Chapter Master',era:'Badab & Maelstrom',summary:'Huron rises to command a prestigious crusading Chapter. Surviving sources disagree on the exact year of his elevation.',uncertain:true},
{date:'718.M41',title:'Huron assumes rule of Badab',era:'Badab & Maelstrom',summary:'The Astral Claws increasingly centralize military and political control over the Badab Sector.'},
{date:'748.M41 onward',title:'Astral Claws withhold gene-seed tithe',era:'Badab & Maelstrom',summary:'Huron begins withholding obligations and secretly expands the Chapter beyond Codex norms, laying institutional groundwork for rebellion.'},
{date:'888.M41',title:'Crusade of Wrath',era:'Badab & Maelstrom',summary:'Astral Claws, Black Templars, Lamenters and Mantis Warriors mount a major offensive into the Maelstrom.'},
{date:'901–912.M41',title:'Badab War',era:'Badab & Maelstrom',summary:'A dispute over authority, tithes and autonomy becomes one of the largest Space Marine rebellions since the Heresy. Astral Claws, Lamenters, Mantis Warriors and Executioners fight forces loyal to Terra.'},
{date:'912.M41',title:'Astral Claws become Red Corsairs',era:'Badab & Maelstrom',summary:'Badab falls. Roughly a few hundred Astral Claws escape with Huron into the Maelstrom, forming the nucleus of the Red Corsairs while other rebel Chapters receive penitent sentences.'},
{date:'M41',title:'Siege of Vraks',era:'Imperial Decline',summary:'A long Imperial siege against renegades escalates into a major Chaos war involving traitor Astartes, daemons and the Death Korps of Krieg.'},
{date:'M41',title:'First War for Armageddon',era:'Imperial Decline',summary:'Angron and daemonic forces invade Armageddon. The conflict is followed by extreme Imperial secrecy and purges.'},
{date:'M41',title:'Second and Third Wars for Armageddon',era:'Imperial Decline',summary:'Ghazghkull Thraka leads enormous Ork invasions. Armageddon becomes one of the setting’s defining human-vs-Ork war zones.'},
{date:'M41',title:'Sabbat Worlds Crusade',era:'Imperial Decline',summary:'Imperial armies fight to reclaim the Sabbat Worlds from Chaos, providing one of the setting’s richest portraits of ordinary Guard warfare.'},
{date:'M41',title:'T’au Spheres of Expansion',era:'Xenos Ascendant',summary:'The T’au expand from a young regional civilization into a multi-species empire, colliding with Orks, Imperials and Tyranids.'},
{date:'M41',title:'Damocles Gulf conflicts',era:'Xenos Ascendant',summary:'Imperial and T’au expansion collide across the Damocles region, revealing both the T’au’s technological sophistication and the overwhelming scale of the Imperium.'},
{date:'745.M41',title:'First Tyrannic War',era:'Tyrannic Wars',summary:'Hive Fleet Behemoth attacks Macragge and confirms the arrival of an extragalactic predator.'},
{date:'990s.M41',title:'Second Tyrannic War',era:'Tyrannic Wars',summary:'Hive Fleet Kraken attacks on a dispersed front and catastrophically mauls Craftworld Iyanden.'},
{date:'Late M41',title:'Third Tyrannic War',era:'Tyrannic Wars',summary:'Hive Fleet Leviathan enters from below the galactic plane, overturning assumptions about the direction and scale of Tyranid invasion.'},
{date:'Late M41',title:'Kryptman’s Octarius Gambit',era:'Tyrannic Wars',summary:'Inquisitor Kryptman redirects Tyranids into a major Ork empire hoping the enemies destroy each other; instead the conflict selects for stronger survivors.'},
{date:'Late M41',title:'Devastation of Baal',era:'Time of Ending',summary:'Leviathan attacks the Blood Angels’ home system. The battle intersects with the opening of the Great Rift and leaves the sons of Sanguinius devastated.'},
{date:'Late M41',title:'Necron awakening accelerates',era:'Time of Ending',summary:'Tomb worlds awaken in greater numbers and the Silent King returns from exile as dynasties pursue competing visions of Necron restoration.'},
{date:'999.M41',title:'13th Black Crusade and Fall of Cadia',era:'Time of Ending',summary:'Abaddon’s offensive finally destroys Cadia, collapsing a key region of pylons and triggering galaxy-wide consequences.'},
{date:'Opening of modern era',title:'Cicatrix Maledictum / Great Rift',era:'Era Indomitus',summary:'A galaxy-spanning warp rift tears the Imperium apart. Imperium Nihilus is cut off from reliable access to the Astronomican.'},
{date:'Modern era',title:'Ynnari emerge',era:'Era Indomitus',summary:'Yvraine and followers of Ynnead unite Aeldari from traditionally hostile cultures around a possible path beyond Slaanesh.'},
{date:'Modern era',title:'Roboute Guilliman returns',era:'Era Indomitus',summary:'Guilliman is revived through a coalition involving Cawl and Yvraine, becomes Lord Commander and confronts the nightmare the Imperium has become.'},
{date:'Modern era',title:'Primaris Space Marines deployed',era:'Era Indomitus',summary:'Belisarius Cawl unveils new Space Marines produced through a project stretching back millennia.'},
{date:'Modern era',title:'Indomitus Crusade',era:'Era Indomitus',summary:'Guilliman launches vast crusade fleets to stabilize the Imperium and relieve isolated worlds after the Rift.'},
{date:'Modern era',title:'Plague Wars',era:'Era Indomitus',summary:'Mortarion and the Death Guard attack Ultramar in a war tied directly to the designs of Nurgle and the returned Guilliman.'},
{date:'Modern era',title:'Vigilus wars',era:'Era Indomitus',summary:'Imperium, Chaos, Orks, Aeldari and other forces fight for a strategically crucial region near the Nachmund route through the Great Rift.'},
{date:'Modern era',title:'Psychic Awakening',era:'Era Indomitus',summary:'Psychic phenomena intensify across the galaxy and numerous factions pursue campaigns shaped by the Great Rift.'},
{date:'Modern era',title:'Pariah Nexus',era:'Era Indomitus',summary:'Necron pylon technology creates a zone of suppressed warp influence, producing psychic deadening and a major Imperial-Necron war zone.'},
{date:'Modern era',title:'Octarius erupts beyond containment',era:'Era Indomitus',summary:'The Ork–Tyranid war becomes a strategic disaster for the Imperium as the conflict breeds ever more dangerous survivors.'},
{date:'Modern era',title:'War Zone Nachmund',era:'Era Indomitus',summary:'Imperial and Chaos forces fight for one of the few relatively stable passages through the Great Rift.'},
{date:'Modern era',title:'Arks of Omen',era:'Era Indomitus',summary:'Abaddon and Vashtorr deploy enormous Arks to recover components of a mysterious Key, drawing in Angron, Farsight, the Dark Angels and others.'},
{date:'Modern era',title:'Lion El’Jonson returns',era:'Era Indomitus',summary:'The Lion re-emerges, defeats Angron during the Arks crisis and begins reconnecting with the Dark Angels and scattered sons of his bloodline.'},
{date:'Modern era',title:'Fourth Tyrannic War',era:'Era Indomitus',summary:'Leviathan attacks from a new vector with overwhelming force, opening a massive western-front war against the Imperium.'},
{date:'2026 setting material',title:'The Maelstrom: Lair of the Tyrant',era:'Era Indomitus',summary:'Huron Blackheart launches a fresh Red Corsairs raid from the Maelstrom while Prince Yriel’s Aeldari Corsairs pursue their own agenda. New lore reconnects current Red Corsair leaders directly to Badab-era factions.'},
{date:'Present setting',title:'No single front line',era:'Era Indomitus',summary:'The galaxy is a mesh of simultaneous wars: Tyranids, Chaos, Necrons, Orks, T’au, Aeldari powers and the fractured Imperium all fight for incompatible futures.'}
],
factions:[
{name:'Imperium of Man',type:'Superfaction',summary:'The galaxy-spanning human empire founded by the Emperor and transformed after the Heresy into a theocratic, bureaucratic war-state.'},
{name:'Adeptus Astartes',type:'Imperium',summary:'Space Marine Chapters descended from the gene-lines of the Primarchs.'},
{name:'Astra Militarum',type:'Imperium',summary:'The Imperial Guard: human infantry, armor and artillery fighting wars on a civilization-sized scale.'},
{name:'Adeptus Mechanicus',type:'Imperium',summary:'The Martian machine cult controlling much of Imperial industry and technical knowledge.'},
{name:'Adepta Sororitas',type:'Imperium',summary:'Militant orders of the Imperial faith, descended institutionally from the Brides of the Emperor and the Age of Apostasy.'},
{name:'Adeptus Custodes',type:'Imperium',summary:'The Emperor’s individually crafted guardians and one of the oldest surviving Imperial military orders.'},
{name:'Inquisition',type:'Imperium',summary:'Highly autonomous Imperial investigators divided into Ordos and philosophies rather than a single unified police force.'},
{name:'Imperial Knights',type:'Imperium',summary:'Noble houses piloting ancient walking war engines whose traditions often predate the Imperium.'},
{name:'Chaos Space Marines',type:'Chaos',summary:'Traitor Legions and later renegades who wage the Long War or pursue their own power.'},
{name:'Chaos Daemons',type:'Chaos',summary:'Warp entities shaped by the great Chaos powers and lesser forces of the Immaterium.'},
{name:'Chaos Knights',type:'Chaos',summary:'Knight houses and engines fallen to Chaos, predation and warp corruption.'},
{name:'Aeldari',type:'Aeldari',summary:'Craftworld survivors of the Fall who discipline their intense psychic nature through the Paths.'},
{name:'Drukhari',type:'Aeldari',summary:'The predatory Aeldari civilization of Commorragh, surviving Slaanesh through inflicted suffering.'},
{name:'Harlequins',type:'Aeldari',summary:'Warrior-performers of Cegorach who preserve Aeldari myth and move through the Webway.'},
{name:'Ynnari',type:'Aeldari',summary:'Followers of Ynnead seeking an Aeldari future beyond Slaanesh.'},
{name:'Aeldari Corsairs',type:'Aeldari',summary:'Independent Aeldari raiders and voidfarers existing outside the strict structures of Craftworld, Drukhari or Exodite society.'},
{name:'Necrons',type:'Xenos',summary:'Ancient dynasties of living-metal immortals awakening after millions of years.'},
{name:'Orks',type:'Xenos',summary:'Self-sustaining warrior species whose culture and psychic gestalt amplify as Waaaghs grow.'},
{name:'Tyranids',type:'Xenos',summary:'Extragalactic hive fleets consuming biomass and adapting organisms for war.'},
{name:'Genestealer Cults',type:'Xenos',summary:'Hybrid infiltrator societies that subvert worlds before Tyranid arrival.'},
{name:'T’au Empire',type:'Xenos',summary:'Young multi-species expansionist empire organized around the Greater Good and the caste system.'},
{name:'Leagues of Votann',type:'Xenos/Human-derived',summary:'Kin civilizations of the galactic core descended from ancient human expansion and guided by Ancestor Cores.'}
],
subfactions:[
{name:'Dark Angels',parent:'Adeptus Astartes',type:'I Legion',summary:'First Legion of Lion El’Jonson. Their post-Heresy identity is dominated by the secret hunt for the Fallen.',tags:['Lion','Caliban','Unforgiven']},
{name:'Emperor’s Children',parent:'Chaos Space Marines',type:'III Legion',summary:'Fulgrim’s Legion, corrupted by Slaanesh and obsessed with perfection, sensation and excess.',tags:['Fulgrim','Slaanesh','Traitor Legion']},
{name:'Iron Warriors',parent:'Chaos Space Marines',type:'IV Legion',summary:'Perturabo’s siege specialists, defined by grinding warfare, bitterness and daemon-engine industry.',tags:['Perturabo','Siege','Traitor Legion']},
{name:'White Scars',parent:'Adeptus Astartes',type:'V Legion',summary:'Jaghatai Khan’s highly mobile Legion and later Chapter, combining speed with an independent warrior culture.',tags:['Jaghatai Khan','Chogoris']},
{name:'Space Wolves',parent:'Adeptus Astartes',type:'VI Legion',summary:'Leman Russ’s fierce Legion, associated with the Burning of Prospero and a distinctive Fenrisian culture.',tags:['Leman Russ','Fenris','Prospero']},
{name:'Imperial Fists',parent:'Adeptus Astartes',type:'VII Legion',summary:'Rogal Dorn’s masters of fortification and siege defense; central defenders of Terra.',tags:['Rogal Dorn','Terra','Siege']},
{name:'Night Lords',parent:'Chaos Space Marines',type:'VIII Legion',summary:'Konrad Curze’s terror specialists, fragmented after the Heresy and often only loosely aligned with Chaos worship.',tags:['Curze','Terror','Traitor Legion']},
{name:'Blood Angels',parent:'Adeptus Astartes',type:'IX Legion',summary:'Sanguinius’s sons, balancing nobility with the Red Thirst and Black Rage.',tags:['Sanguinius','Baal']},
{name:'Iron Hands',parent:'Adeptus Astartes',type:'X Legion',summary:'Ferrus Manus’s Legion, traumatized by his death at Isstvan V and increasingly devoted to cybernetic replacement.',tags:['Ferrus Manus','Medusa']},
{name:'World Eaters',parent:'Chaos Space Marines',type:'XII Legion',summary:'Angron’s Legion, mutilated by the Butcher’s Nails and devoted to Khorne.',tags:['Angron','Khorne','Traitor Legion']},
{name:'Ultramarines',parent:'Adeptus Astartes',type:'XIII Legion',summary:'Roboute Guilliman’s Legion and Chapter; central to Ultramar, the Codex Astartes and the modern Imperium.',tags:['Guilliman','Ultramar']},
{name:'Death Guard',parent:'Chaos Space Marines',type:'XIV Legion',summary:'Mortarion’s plague-ridden Legion, servants of Nurgle and major antagonists of the Plague Wars.',tags:['Mortarion','Nurgle']},
{name:'Thousand Sons',parent:'Chaos Space Marines',type:'XV Legion',summary:'Magnus’s psychic Legion, transformed by Prospero, Tzeentch and Ahriman’s Rubric.',tags:['Magnus','Tzeentch','Prospero']},
{name:'Black Legion',parent:'Chaos Space Marines',type:'XVI lineage',summary:'Abaddon’s coalition built from the ruins of the Sons of Horus and warriors from many other backgrounds.',tags:['Abaddon','Sons of Horus','Black Crusades']},
{name:'Word Bearers',parent:'Chaos Space Marines',type:'XVII Legion',summary:'Lorgar’s Legion and the first major Astartes force to embrace Chaos as religion.',tags:['Lorgar','Chaos Undivided']},
{name:'Salamanders',parent:'Adeptus Astartes',type:'XVIII Legion',summary:'Vulkan’s sons, famous for endurance, craftsmanship and unusual concern for civilian humans.',tags:['Vulkan','Nocturne']},
{name:'Raven Guard',parent:'Adeptus Astartes',type:'XIX Legion',summary:'Corvus Corax’s stealth-oriented Legion, devastated at Isstvan V.',tags:['Corax','Deliverance']},
{name:'Alpha Legion',parent:'Chaos Space Marines',type:'XX Legion',summary:'Alpharius/Omegon’s Legion of infiltration, cells and contradictory motives; their true loyalty remains deliberately murky.',tags:['Alpharius','Omegon','Hydra']},
{name:'Legions II and XI',parent:'Adeptus Astartes',type:'Lost Legions',summary:'Two original Legions and Primarchs deliberately erased from Imperial history. Their exact fates are intentionally unrevealed.',tags:['Lost Primarchs'],uncertain:true},
{name:'Black Templars',parent:'Adeptus Astartes',type:'Imperial Fists successor',summary:'Zealous crusading Chapter descended from Sigismund; rejects the usual fixed Chapter structure in favor of ongoing crusades.',tags:['Sigismund','Dorn']},
{name:'Crimson Fists',parent:'Adeptus Astartes',type:'Imperial Fists successor',summary:'Second Founding sons of Dorn with a long history of fighting Orks.',tags:['Rynn’s World','Orks']},
{name:'Excoriators',parent:'Adeptus Astartes',type:'Imperial Fists successor',summary:'Dorn-descended Chapter strongly associated with endurance and remembrance of the Siege.',tags:['Dorn']},
{name:'Executioners',parent:'Adeptus Astartes',type:'Imperial Fists successor',summary:'Chapter traditionally linked to Fafnir Rann. Sided with Huron during Badab, withdrew late in the war and received a penitent crusade before later absolution.',tags:['Badab War','Fafnir Rann','Huron']},
{name:'Blood Ravens',parent:'Adeptus Astartes',type:'Successor — origin uncertain',summary:'Knowledge-seeking Chapter with an intentionally uncertain gene-line, famous through the Dawn of War series.',tags:['Dawn of War'],uncertain:true},
{name:'Flesh Tearers',parent:'Adeptus Astartes',type:'Blood Angels successor',summary:'Second Founding sons of Sanguinius led historically by Nassir Amit; especially afflicted by the Black Rage and Red Thirst.',tags:['Sanguinius','Amit']},
{name:'Lamenters',parent:'Adeptus Astartes',type:'Blood Angels successor',summary:'Cursed Founding Chapter with a history of disasters. Joined Huron in Badab largely from honor and sovereignty concerns, was mauled by the Minotaurs and sentenced to penance.',tags:['Badab War','Cursed Founding','Minotaurs']},
{name:'Angels Encarmine',parent:'Adeptus Astartes',type:'Blood Angels successor',summary:'A prominent son-Chapter of Sanguinius with traditions closely tied to the Blood Angels.',tags:['Sanguinius']},
{name:'Charnel Guard',parent:'Adeptus Astartes',type:'Blood Angels successor',summary:'Secretive Blood Angels successor and one of the Chapters associated with the Maelstrom Warders.',tags:['Maelstrom Warders']},
{name:'Novamarines',parent:'Adeptus Astartes',type:'Ultramarines successor',summary:'Second Founding Chapter with a long record of crusading warfare and participation on the loyalist side of Badab.',tags:['Badab War','Guilliman']},
{name:'Mortifactors',parent:'Adeptus Astartes',type:'Ultramarines successor',summary:'Macabre Ultramarines successor whose death-focused culture differs sharply from classical Ultramar.',tags:['Guilliman']},
{name:'Howling Griffons',parent:'Adeptus Astartes',type:'Ultramarines successor',summary:'Oath-bound Chapter known for quartered heraldry and service on the loyalist side of Badab.',tags:['Badab War']},
{name:'Marines Errant',parent:'Adeptus Astartes',type:'Ultramarines successor',summary:'Fleet-oriented Chapter that fought against Huron in the Badab War and has deep ties to crusading warfare.',tags:['Badab War']},
{name:'Mantis Warriors',parent:'Adeptus Astartes',type:'White Scars lineage',summary:'Maelstrom Warder Chapter that sided with the Astral Claws in Badab out of oath and regional loyalty. Later sentenced to a century-long penitent crusade.',tags:['Badab War','Maelstrom Warders','White Scars']},
{name:'Astral Claws',parent:'Adeptus Astartes',type:'Renegade Chapter',summary:'Prestigious crusading Chapter of uncertain gene-line, probably founded around M35. Became a Maelstrom Warder, expanded illegally under Lufgt Huron, rebelled in Badab and formed the core of the Red Corsairs after defeat.',tags:['Badab War','Huron','Red Corsairs','Maelstrom Warders'],url:'https://wh40k.lexicanum.com/wiki/Astral_Claws'},
{name:'Tiger Claws',parent:'Adeptus Astartes',type:'Astral Claws successor',summary:'A successor of the Astral Claws thought lost in the warp. Survivors were secretly absorbed into the Astral Claws before Badab; some may have survived into the Red Corsairs.',tags:['Astral Claws','Badab War','Red Corsairs'],url:'https://wh40k.lexicanum.com/wiki/Tiger_Claws'},
{name:'Red Corsairs',parent:'Chaos Space Marines',type:'Renegade warband/empire',summary:'Huron Blackheart’s Maelstrom power, built from surviving Astral Claws and a constant flow of renegades, pirates, traitors and mercenaries.',tags:['Astral Claws','Huron','Maelstrom','Badab War'],url:'https://wh40k.lexicanum.com/wiki/Red_Corsairs'},
{name:'Masters of the Maelstrom',parent:'Red Corsairs',type:'Command circle',summary:'Huron’s modern inner circle. The 2026 lineup includes Badab veterans Garreon, Katar Garrix and Garlon Souleater alongside Captain Sargotta and the Enforcer.',tags:['Huron','2026','Badab War'],url:'https://wh40k.lexicanum.com/wiki/Masters_of_the_Maelstrom'},
{name:'Maelstrom Warders',parent:'Adeptus Astartes',type:'Defensive alliance',summary:'Space Marine Chapters assigned to contain threats near the Maelstrom; known members included Astral Claws, Lamenters, Mantis Warriors and Charnel Guard.',tags:['Astral Claws','Badab War'],url:'https://wh40k.lexicanum.com/wiki/Maelstrom_Warders'},
{name:'Fire Hawks',parent:'Adeptus Astartes',type:'Loyalist Chapter',summary:'Major loyalist participant in the Badab War. Later disappearance is famously associated in-setting with speculation around the Legion of the Damned.',tags:['Badab War'],uncertain:true},
{name:'Red Scorpions',parent:'Adeptus Astartes',type:'Loyalist Chapter',summary:'Highly purity-conscious Chapter that fought prominently on the loyalist side of Badab.',tags:['Badab War']},
{name:'Raptors',parent:'Adeptus Astartes',type:'Raven Guard successor',summary:'Pragmatic Raven Guard successor known for camouflage and flexible tactics; fought loyalist during Badab.',tags:['Badab War','Raven Guard']},
{name:'Fire Angels',parent:'Adeptus Astartes',type:'Loyalist Chapter',summary:'Chapter that committed major forces to the loyalist campaign in the Badab War.',tags:['Badab War']},
{name:'Sons of Medusa',parent:'Adeptus Astartes',type:'Iron Hands successor',summary:'Iron Hands successor born from the Moirae Schism; later fought on the loyalist side of Badab.',tags:['Badab War','Moirae Schism']},
{name:'Exorcists',parent:'Adeptus Astartes',type:'Specialized Chapter',summary:'Daemon-fighting Chapter with unusual initiation traditions; participated in Badab and has close associations with the Inquisition.',tags:['Badab War','Daemons']},
{name:'Minotaurs',parent:'Adeptus Astartes',type:'Loyalist Chapter',summary:'Aggressive Chapter often associated with the High Lords. During Badab they shattered the Lamenters in a major fleet engagement.',tags:['Badab War','Lamenters']},
{name:'Star Phantoms',parent:'Adeptus Astartes',type:'Loyalist Chapter',summary:'Heavy-firepower Chapter whose forces played a decisive role in the final assault on Badab.',tags:['Badab War']},
{name:'Carcharodons',parent:'Adeptus Astartes',type:'Nomad-predation fleet Chapter',summary:'The Carcharodons Astra are a mysterious fleet-based Chapter known for extreme violence; they fought for the loyalists in Badab.',tags:['Badab War','Tyberos']},
{name:'Celestial Lions',parent:'Adeptus Astartes',type:'Imperial Fists successor',summary:'Chapter nearly destroyed after openly challenging Inquisitorial conduct, later closely associated with the Spears of the Emperor.',tags:['Inquisition']},
{name:'Grey Knights',parent:'Adeptus Astartes',type:'Daemon-hunting Chapter',summary:'Secretive psychic Space Marine Chapter founded for war against daemons and closely linked to the Ordo Malleus.',tags:['Inquisition','Daemons']},
{name:'Deathwatch',parent:'Adeptus Astartes',type:'Ordo Xenos chamber militant',summary:'Veteran Space Marines seconded from many Chapters to specialized xenos-hunting kill teams.',tags:['Inquisition','Xenos']},
{name:'Legion of the Damned',parent:'Adeptus Astartes',type:'Mysterious apparitions',summary:'Ghostly or supernatural Space Marines who appear in desperate battles. Their true nature remains unresolved.',tags:['Fire Hawks'],uncertain:true},
{name:'Cadian Shock Troops',parent:'Astra Militarum',type:'Regiment tradition',summary:'Iconic soldiers of Cadia whose military culture survives the destruction of their homeworld.'},
{name:'Death Korps of Krieg',parent:'Astra Militarum',type:'Regiment tradition',summary:'Siege and attrition specialists from Krieg, culturally shaped by their world’s civil war and nuclear devastation.'},
{name:'Catachan Jungle Fighters',parent:'Astra Militarum',type:'Regiment tradition',summary:'Soldiers from the lethal death world Catachan, famous for survival skills and aggressive infantry warfare.'},
{name:'Armageddon Steel Legion',parent:'Astra Militarum',type:'Regiment tradition',summary:'Mechanized forces from Armageddon shaped by repeated wars against Orks.'},
{name:'Tallarn Desert Raiders',parent:'Astra Militarum',type:'Regiment tradition',summary:'Mobile desert-warfare regiments descended from survivors of the Heresy-era devastation of Tallarn.'},
{name:'Mordian Iron Guard',parent:'Astra Militarum',type:'Regiment tradition',summary:'Highly disciplined troops known for rigid drill and massed firing lines.'},
{name:'Valhallan Ice Warriors',parent:'Astra Militarum',type:'Regiment tradition',summary:'Cold-world regiments famous for endurance, mass infantry and wars against Orks.'},
{name:'Vostroyan Firstborn',parent:'Astra Militarum',type:'Regiment tradition',summary:'Vostroya’s firstborn sons serve to repay an ancient debt dating to the Horus Heresy.'},
{name:'Tanith First-and-Only',parent:'Astra Militarum',type:'Regiment',summary:'Reconnaissance-focused survivors of destroyed Tanith, central to the Sabbat Worlds Crusade.'},
{name:'Attilan Rough Riders',parent:'Astra Militarum',type:'Regiment tradition',summary:'Mounted cavalry regiments from Attila combining tribal culture with Imperial warfare.'},
{name:'Mars',parent:'Adeptus Mechanicus',type:'Forge World',summary:'Birthplace and political center of the Mechanicus; site of the Treaty of Mars and Mechanicum civil war during the Heresy.'},
{name:'Ryza',parent:'Adeptus Mechanicus',type:'Forge World',summary:'Forge World especially renowned for plasma technology.'},
{name:'Metalica',parent:'Adeptus Mechanicus',type:'Forge World',summary:'Militarized Forge World with a history of major campaigns against Orks and Chaos.'},
{name:'Stygies VIII',parent:'Adeptus Mechanicus',type:'Forge World',summary:'Secretive Forge World notorious for intense interest in xenos technology.'},
{name:'Lucius',parent:'Adeptus Mechanicus',type:'Forge World',summary:'Hollow Forge World famed for unusual technology and teleportation-related warfare.'},
{name:'Graia',parent:'Adeptus Mechanicus',type:'Forge World',summary:'Mechanicus world associated with extreme doctrinal resistance and heavily fortified industry.'},
{name:'Agripinaa',parent:'Adeptus Mechanicus',type:'Forge World',summary:'Strategic Forge World near the Eye of Terror heavily affected by wars around Cadia.'},
{name:'Order of Our Martyred Lady',parent:'Adepta Sororitas',type:'Major Order Militant',summary:'One of the great Orders Militant, closely associated with sacrifice and martyrdom.'},
{name:'Order of the Bloody Rose',parent:'Adepta Sororitas',type:'Major Order Militant',summary:'Aggressive Sororitas order famous for close combat zeal.'},
{name:'Order of the Valorous Heart',parent:'Adepta Sororitas',type:'Major Order Militant',summary:'Order emphasizing endurance through suffering.'},
{name:'Order of the Ebon Chalice',parent:'Adepta Sororitas',type:'Major Order Militant',summary:'Ancient and prestigious order tracing its traditions to the earliest Sisters of Battle.'},
{name:'Order of the Argent Shroud',parent:'Adepta Sororitas',type:'Major Order Militant',summary:'Order noted for direct action and austere devotion.'},
{name:'Order of the Sacred Rose',parent:'Adepta Sororitas',type:'Major Order Militant',summary:'Order emphasizing discipline, faith and controlled firepower.'},
{name:'Emperor’s Chosen',parent:'Adeptus Custodes',type:'Shield Host',summary:'Archetypal Custodian shield host serving the Emperor’s will.'},
{name:'Shadowkeepers',parent:'Adeptus Custodes',type:'Shield Host',summary:'Custodians tasked with guarding the Dark Cells beneath the Imperial Palace.'},
{name:'Solar Watch',parent:'Adeptus Custodes',type:'Shield Host',summary:'Custodians focused on defense of the Sol System and routes to Terra.'},
{name:'Dread Host',parent:'Adeptus Custodes',type:'Shield Host',summary:'Aggressive Custodian force used to carry the Emperor’s judgment beyond Terra.'},
{name:'Aquilan Shield',parent:'Adeptus Custodes',type:'Shield Host',summary:'Custodians who protect individuals believed crucial to the Emperor’s future designs.'},
{name:'Ordo Malleus',parent:'Inquisition',type:'Major Ordo',summary:'Inquisitorial branch focused on daemons and Chaos; closely associated with the Grey Knights.'},
{name:'Ordo Xenos',parent:'Inquisition',type:'Major Ordo',summary:'Inquisitorial branch specializing in alien threats; closely associated with the Deathwatch.'},
{name:'Ordo Hereticus',parent:'Inquisition',type:'Major Ordo',summary:'Inquisitorial branch focused on internal heresy, witchcraft and threats within the Imperium.'},
{name:'Officio Assassinorum',parent:'Imperium of Man',type:'Imperial institution',summary:'Imperial assassination organization containing specialized temples such as Vindicare, Callidus, Eversor and Culexus.'},
{name:'Navis Nobilite',parent:'Imperium of Man',type:'Imperial institution',summary:'Navigator houses whose mutant third eye makes practical long-range warp travel possible.'},
{name:'Adeptus Astra Telepathica',parent:'Imperium of Man',type:'Imperial institution',summary:'Institution that identifies, trains, sanctions and deploys psykers for Imperial use.'},
{name:'Adeptus Arbites',parent:'Imperium of Man',type:'Imperial institution',summary:'Enforcers of Imperial law and tithe obligations rather than ordinary local police.'},
{name:'Sisters of Silence',parent:'Imperium of Man',type:'Null order',summary:'Order of psychic blanks that fought beside the Emperor and Custodes and has returned to greater prominence.'},
{name:'House Terryn',parent:'Imperial Knights',type:'Knight House',summary:'Major loyalist Knight house with a long martial tradition.'},
{name:'House Raven',parent:'Imperial Knights',type:'Knight House',summary:'One of the largest and most militarily powerful loyalist Knight houses.'},
{name:'House Hawkshroud',parent:'Imperial Knights',type:'Knight House',summary:'Knight house famous for honoring ancient debts and alliances.'},
{name:'House Griffith',parent:'Imperial Knights',type:'Knight House',summary:'Aggressive Knight house with traditions of hunting giant beasts and fighting at close range.'},
{name:'House Herpetrax',parent:'Chaos Knights',type:'Dread Household',summary:'Ancient Knight house that rejected Imperial dominion and became a major Chaos Knight power.'},
{name:'House Korvax',parent:'Chaos Knights',type:'Dread Household',summary:'Chaos Knight house tied to Be’lakor and the corruption of Kolossi.'},
{name:'Kabal of the Black Heart',parent:'Drukhari',type:'Kabal',summary:'Asdrubael Vect’s dominant Kabal and central political power in Commorragh.'},
{name:'Kabal of the Flayed Skull',parent:'Drukhari',type:'Kabal',summary:'Raiding Kabal famous for speed, aircraft and realspace attacks.'},
{name:'Kabal of the Obsidian Rose',parent:'Drukhari',type:'Kabal',summary:'Kabal renowned for weapon craftsmanship and precise ranged killing.'},
{name:'Kabal of the Poisoned Tongue',parent:'Drukhari',type:'Kabal',summary:'Kabal associated with poison, intrigue and Lady Malys.'},
{name:'Cult of Strife',parent:'Drukhari',type:'Wych Cult',summary:'Lelith Hesperax’s famous gladiatorial Wych Cult.'},
{name:'Prophets of Flesh',parent:'Drukhari',type:'Haemonculus Coven',summary:'Infamous fleshcrafting coven associated with Urien Rakarth.'},
{name:'Ulthwé',parent:'Aeldari',type:'Craftworld',summary:'Craftworld near the Eye of Terror, famous for seers, Guardians and Eldrad Ulthran.'},
{name:'Biel-Tan',parent:'Aeldari',type:'Craftworld',summary:'Militant Craftworld seeking restoration of Aeldari power and strongly associated with Aspect Warriors.'},
{name:'Iyanden',parent:'Aeldari',type:'Craftworld',summary:'Once-populous Craftworld devastated by Hive Fleet Kraken; now unusually dependent on Wraith constructs.'},
{name:'Saim-Hann',parent:'Aeldari',type:'Craftworld',summary:'Clan-oriented Craftworld famed for jetbikes, Wild Riders and speed.'},
{name:'Alaitoc',parent:'Aeldari',type:'Craftworld',summary:'Strict Craftworld whose culture produces many Rangers and Pathfinders.'},
{name:'Altansar',parent:'Aeldari',type:'Craftworld',summary:'Craftworld trapped in the Eye of Terror for millennia before returning under Maugan Ra’s influence.'},
{name:'Exodites',parent:'Aeldari',type:'Aeldari culture',summary:'Aeldari who rejected pre-Fall decadence and settled austere maiden worlds.'},
{name:'Eldritch Raiders',parent:'Aeldari Corsairs',type:'Corsair fleet',summary:'Prince Yriel’s famous Corsair force, returned to prominence in the 2026 Maelstrom campaign.',tags:['Prince Yriel','Maelstrom 2026']},
{name:'Masque of the Midnight Sorrow',parent:'Harlequins',type:'Masque',summary:'Prominent Harlequin masque with a reputation for relentless pursuit of destiny.'},
{name:'Masque of the Frozen Stars',parent:'Harlequins',type:'Masque',summary:'Warrior-heavy masque known for aggression toward younger races.'},
{name:'Masque of the Soaring Spite',parent:'Harlequins',type:'Masque',summary:'Fast-moving masque emphasizing skyborne and jetbike warfare.'},
{name:'Szarekhan Dynasty',parent:'Necrons',type:'Dynasty',summary:'Dynastic power tied directly to the Silent King and his modern agenda.'},
{name:'Sautekh Dynasty',parent:'Necrons',type:'Dynasty',summary:'Large, aggressively expanding dynasty ruled by Imotekh the Stormlord.'},
{name:'Mephrit Dynasty',parent:'Necrons',type:'Dynasty',summary:'Dynasty famed for destructive stellar and energy weaponry.'},
{name:'Novokh Dynasty',parent:'Necrons',type:'Dynasty',summary:'Bloodthirsty Necron dynasty favoring close combat and ritualized slaughter.'},
{name:'Nihilakh Dynasty',parent:'Necrons',type:'Dynasty',summary:'Territorial dynasty known for guarding holdings, treasures and ancient domains.'},
{name:'Nephrekh Dynasty',parent:'Necrons',type:'Dynasty',summary:'Dynasty obsessed with transforming into beings of pure energy and light.'},
{name:'Ogdobekh Dynasty',parent:'Necrons',type:'Dynasty',summary:'Powerful dynasty noted for unusually strong military-industrial resources.'},
{name:'Goffs',parent:'Orks',type:'Clan',summary:'Hard-fighting Ork clan favoring direct violence; Ghazghkull is strongly associated with Goff culture.'},
{name:'Bad Moons',parent:'Orks',type:'Clan',summary:'Wealthy Ork clan whose rapidly growing teeth support lavish weapons and equipment.'},
{name:'Evil Sunz',parent:'Orks',type:'Clan',summary:'Speed-obsessed clan devoted to bikes, vehicles and going faster.'},
{name:'Deathskulls',parent:'Orks',type:'Clan',summary:'Looting, scavenging clan famous for blue lucky markings and repurposed enemy gear.'},
{name:'Blood Axes',parent:'Orks',type:'Clan',summary:'Unusually tactical Orks willing to imitate or even negotiate with humans when useful.'},
{name:'Snakebites',parent:'Orks',type:'Clan',summary:'Traditionalist Orks favoring older ways, beasts and rugged self-reliance.'},
{name:'Freebooterz',parent:'Orks',type:'Pirates',summary:'Orks who leave conventional clan structures to become mercenary pirates and void raiders.'},
{name:'Beast Snaggas',parent:'Orks',type:'Subculture',summary:'Orks focused on hunting giant monsters, vehicles and other worthy prey.'},
{name:'Hive Fleet Behemoth',parent:'Tyranids',type:'Hive Fleet',summary:'First major Tyranid hive fleet recognized by the Imperium; fought at Macragge.'},
{name:'Hive Fleet Kraken',parent:'Tyranids',type:'Hive Fleet',summary:'Dispersed invasion fleet responsible for the Second Tyrannic War and devastation of Iyanden.'},
{name:'Hive Fleet Leviathan',parent:'Tyranids',type:'Hive Fleet',summary:'Enormous hive fleet attacking from below the galactic plane and central to the Third and Fourth Tyrannic Wars.'},
{name:'Hive Fleet Kronos',parent:'Tyranids',type:'Hive Fleet',summary:'Hive fleet adapted heavily toward fighting Chaos and warp-spawned threats.'},
{name:'Hive Fleet Gorgon',parent:'Tyranids',type:'Hive Fleet',summary:'Hive fleet noted for exceptionally rapid biochemical adaptation.'},
{name:'Hive Fleet Jormungandr',parent:'Tyranids',type:'Hive Fleet',summary:'Fleet associated with subterranean assault and heavily armored organisms.'},
{name:'Hive Fleet Hydra',parent:'Tyranids',type:'Hive Fleet',summary:'Hive fleet known for attacking and absorbing weakened Tyranid organisms as well as other prey.'},
{name:'Hive Fleet Tiamet',parent:'Tyranids',type:'Hive Fleet',summary:'Unusual hive fleet associated with holding territory and constructing mysterious continent-scale biological structures.',uncertain:true},
{name:'Cult of the Four-Armed Emperor',parent:'Genestealer Cults',type:'Cult',summary:'Archetypal Genestealer Cult centered on religious devotion to the coming Star Children.'},
{name:'The Twisted Helix',parent:'Genestealer Cults',type:'Cult',summary:'Cult originating in genetic experimentation and medical-industrial corruption.'},
{name:'Rusted Claw',parent:'Genestealer Cults',type:'Cult',summary:'Nomadic, scavenger-heavy cult associated with industrial wastelands and vehicles.'},
{name:'Bladed Cog',parent:'Genestealer Cults',type:'Cult',summary:'Cult rooted deeply within Mechanicus populations, combining cybernetics with Genestealer infection.'},
{name:'Pauper Princes',parent:'Genestealer Cults',type:'Cult',summary:'Cult emphasizing fanatical self-sacrifice and devotion to its leadership.'},
{name:'Hivecult',parent:'Genestealer Cults',type:'Cult',summary:'Militarized cult heavily infiltrated into planetary defense and Guard-like organizations.'},
{name:'T’au Sept',parent:'T’au Empire',type:'Sept',summary:'Political and cultural heartland of the T’au Empire.'},
{name:'Vior’la',parent:'T’au Empire',type:'Sept',summary:'Militaristic sept producing aggressive Fire Caste traditions and many famous commanders.'},
{name:'Sa’cea',parent:'T’au Empire',type:'Sept',summary:'Urbanized, disciplined sept associated with tactical warfare and dense population centers.'},
{name:'Bork’an',parent:'T’au Empire',type:'Sept',summary:'Scientific and educational center noted for experimental technology.'},
{name:'Dal’yth',parent:'T’au Empire',type:'Sept',summary:'Cosmopolitan sept strongly associated with trade and cooperation with auxiliary species.'},
{name:'Farsight Enclaves',parent:'T’au Empire',type:'Breakaway polity',summary:'Independent frontier realm founded by Commander Farsight after breaking from Ethereal rule.'},
{name:'Kroot',parent:'T’au Empire',type:'Auxiliary species',summary:'Mercenary and allied species with a culture built around controlled consumption and genetic adaptation.'},
{name:'Vespid',parent:'T’au Empire',type:'Auxiliary species',summary:'Winged allied species contributing fast-moving combat units to T’au forces.'},
{name:'Greater Thurian League',parent:'Leagues of Votann',type:'League',summary:'Largest and most influential major League of the Kin.'},
{name:'Ymyr Conglomerate',parent:'Leagues of Votann',type:'League',summary:'Wealthy League known for advanced equipment and exceptional craftsmanship.'},
{name:'Kronus Hegemony',parent:'Leagues of Votann',type:'League',summary:'Aggressive, expansionist League with a strongly martial culture.'},
{name:'Trans-Hyperian Alliance',parent:'Leagues of Votann',type:'League',summary:'Exploration-focused League with highly mobile fleets and prospecting traditions.'},
{name:'Urani-Surtr Regulates',parent:'Leagues of Votann',type:'League',summary:'Stoic League known for stubborn endurance and hazardous industrial territories.'},
{name:'Blackstone Legion',parent:'Chaos Space Marines',type:'Historical Black Legion force',summary:'One of many Black Legion formations associated with Abaddon’s wider campaigns.'},
{name:'Crimson Slaughter',parent:'Chaos Space Marines',type:'Renegade warband',summary:'Formerly loyal Chapter driven into madness and Chaos by supernatural persecution.'},
{name:'The Purge',parent:'Chaos Space Marines',type:'Renegade warband',summary:'Nurgle-aligned warband seeking the extermination of all life as an end to suffering.'},
{name:'The Scourged',parent:'Chaos Space Marines',type:'Renegade warband',summary:'Tzeentch-aligned renegades cursed to hear lies, driving them toward madness and betrayal.'},
{name:'Creations of Bile',parent:'Chaos Space Marines',type:'Warband network',summary:'Followers, experiments and clients of Fabius Bile rather than a conventional Legion organization.'},
{name:'Flawless Host',parent:'Chaos Space Marines',type:'Slaanesh warband',summary:'Slaanesh-aligned renegades obsessed with superiority and perfection.'}
],
people:[
{name:'The Emperor of Mankind',group:'Imperium',summary:'Founder of the Imperium, supreme psyker and architect of the Great Crusade; bound to the Golden Throne after defeating Horus.'},
{name:'Malcador the Sigillite',group:'Imperium',summary:'The Emperor’s closest human regent and administrator, crucial to Imperial institutions and the defense of Terra.'},
{name:'Horus Lupercal',group:'Primarch',summary:'Warmaster and Primarch of the XVI Legion whose rebellion gives the Horus Heresy its name.'},
{name:'Lion El’Jonson',group:'Primarch',summary:'Primarch of the Dark Angels; lost after Caliban and returned in the Era Indomitus.'},
{name:'Fulgrim',group:'Primarch',summary:'Primarch of the Emperor’s Children and Daemon Primarch of Slaanesh.'},
{name:'Perturabo',group:'Primarch',summary:'Primarch of the Iron Warriors and master of siege warfare.'},
{name:'Jaghatai Khan',group:'Primarch',summary:'Primarch of the White Scars, later lost pursuing enemies into the Webway.'},
{name:'Leman Russ',group:'Primarch',summary:'Primarch of the Space Wolves and central figure in the Burning of Prospero.'},
{name:'Rogal Dorn',group:'Primarch',summary:'Primarch of the Imperial Fists and architect of Terra’s defenses.'},
{name:'Konrad Curze',group:'Primarch',summary:'Primarch of the Night Lords, obsessed with terror, predestination and punitive justice.'},
{name:'Sanguinius',group:'Primarch',summary:'Primarch of the Blood Angels, beloved loyalist martyr killed by Horus.'},
{name:'Ferrus Manus',group:'Primarch',summary:'Primarch of the Iron Hands, killed by Fulgrim at Isstvan V.'},
{name:'Angron',group:'Primarch',summary:'Primarch of the World Eaters, mutilated by the Butcher’s Nails and ascended to Khorne.'},
{name:'Roboute Guilliman',group:'Primarch',summary:'Primarch of the Ultramarines, authorial force behind the Codex Astartes and returned Lord Commander.'},
{name:'Mortarion',group:'Primarch',summary:'Primarch of the Death Guard and Daemon Primarch of Nurgle.'},
{name:'Magnus the Red',group:'Primarch',summary:'Psychic Primarch of the Thousand Sons and Daemon Primarch of Tzeentch.'},
{name:'Lorgar Aurelian',group:'Primarch',summary:'Primarch of the Word Bearers whose religious quest becomes a central ideological cause of the Heresy.'},
{name:'Vulkan',group:'Primarch',summary:'Primarch of the Salamanders and a legendary Perpetual.'},
{name:'Corvus Corax',group:'Primarch',summary:'Primarch of the Raven Guard and survivor of the Drop Site Massacre.'},
{name:'Alpharius / Omegon',group:'Primarch',summary:'Twin mystery at the heart of the Alpha Legion; identities, deaths and motives are intentionally confused.',uncertain:true},
{name:'Abaddon the Despoiler',group:'Chaos',summary:'Former First Captain of the Sons of Horus, founder of the Black Legion and Warmaster of Chaos.'},
{name:'Huron Blackheart / Lufgt Huron',group:'Red Corsairs',summary:'Former Astral Claws Chapter Master and Tyrant of Badab who survives defeat to become master of the Red Corsairs and Maelstrom.'},
{name:'Garreon the Corpsemaster',group:'Red Corsairs',summary:'Former Astral Claw and modern Lord-Apothecary in Huron’s Masters of the Maelstrom.'},
{name:'Katar Garrix',group:'Red Corsairs',summary:'Former Executioner who followed Huron into the Maelstrom and serves as a headsman in his modern inner circle.'},
{name:'Garlon Souleater',group:'Red Corsairs',summary:'Former Mantis Warrior and sorcerer who became one of Huron’s Masters of the Maelstrom.'},
{name:'Captain Sargotta',group:'Red Corsairs',summary:'Heretic naval captain and one of Huron’s most trusted modern fleet commanders.'},
{name:'The Enforcer',group:'Red Corsairs',summary:'Tarellian bounty hunter serving Huron’s inner circle, accompanied by an enthralled Barghesi.'},
{name:'Belisarius Cawl',group:'Mechanicus',summary:'Ancient Archmagos tied to Primaris Space Marines and major modern Imperial technological projects.'},
{name:'Dante',group:'Blood Angels',summary:'Ancient Chapter Master of the Blood Angels and major commander in Imperium Nihilus.'},
{name:'Mephiston',group:'Blood Angels',summary:'Blood Angels Chief Librarian who uniquely overcame the Black Rage and became one of the Chapter’s most powerful psykers.'},
{name:'Marneus Calgar',group:'Ultramarines',summary:'Long-serving Ultramarines Chapter Master and one of the Imperium’s most famous modern commanders.'},
{name:'Azrael',group:'Dark Angels',summary:'Supreme Grand Master of the Dark Angels and central leader of the Unforgiven.'},
{name:'High Marshal Helbrecht',group:'Black Templars',summary:'Leader of the Black Templars’ vast crusading brotherhood.'},
{name:'Sigismund',group:'Imperial Fists / Black Templars',summary:'First Captain of the Imperial Fists, Emperor’s Champion at the Siege and first High Marshal of the Black Templars.'},
{name:'Fafnir Rann',group:'Imperial Fists',summary:'Heresy-era Imperial Fists commander traditionally associated with the founding lineage of the Executioners.'},
{name:'Tyberos the Red Wake',group:'Carcharodons',summary:'Formidable Chapter Master of the mysterious Carcharodons.'},
{name:'Asterion Moloc',group:'Minotaurs',summary:'Enigmatic Chapter Master of the Minotaurs, notorious for brutal Astartes-on-Astartes warfare.'},
{name:'Sebastian Yarrick',group:'Imperium',summary:'Legendary Commissar and nemesis of Ghazghkull during the Wars for Armageddon; remembered as one of the Guard’s great heroes.'},
{name:'Ghazghkull Mag Uruk Thraka',group:'Orks',summary:'Most famous modern Ork warlord, prophet of Gork and Mork and architect of enormous Waaaghs.'},
{name:'Makari',group:'Orks',summary:'Ghazghkull’s improbably lucky grot standard bearer.'},
{name:'The Beast',group:'Orks',summary:'Title associated with the enormous Ork warlords who led the M32 War of the Beast.'},
{name:'Szarekh, the Silent King',group:'Necrons',summary:'Last ruler of the united Necrontyr/Necron race; ordered biotransference, rebelled against the C’tan and later returned from exile.'},
{name:'Imotekh the Stormlord',group:'Necrons',summary:'Phaeron of the Sautekh Dynasty and one of the greatest modern Necron conquerors.'},
{name:'Trazyn the Infinite',group:'Necrons',summary:'Necron Overlord and obsessive collector who preserves people, artifacts and armies in his galleries.'},
{name:'Orikan the Diviner',group:'Necrons',summary:'Necron chronomancer and rival of Trazyn, obsessed with predicting and manipulating the future.'},
{name:'Illuminor Szeras',group:'Necrons',summary:'Cryptek and architect of horrific biological experimentation seeking understanding of life and apotheosis.'},
{name:'Eldrad Ulthran',group:'Aeldari',summary:'Legendary Farseer of Ulthwé who repeatedly manipulates events to preserve Aeldari survival.'},
{name:'Yvraine',group:'Ynnari',summary:'Emissary of Ynnead and leader of the Ynnari, central to Guilliman’s revival.'},
{name:'Yncarne',group:'Ynnari',summary:'Avatar of Ynnead, the Aeldari god of the dead.'},
{name:'Prince Yriel',group:'Aeldari Corsairs',summary:'Iyanden prince, hero of the defense against Kraken and legendary captain of the Eldritch Raiders; prominent again in the 2026 Maelstrom conflict.'},
{name:'Asdrubael Vect',group:'Drukhari',summary:'Supreme political predator of Commorragh and master of the Kabal of the Black Heart.'},
{name:'Lelith Hesperax',group:'Drukhari',summary:'Legendary gladiator of Commorragh and iconic master of the Cult of Strife.'},
{name:'Urien Rakarth',group:'Drukhari',summary:'Ancient Haemonculus and flesh-sculptor associated with the Prophets of Flesh.'},
{name:'Asurmen',group:'Aeldari',summary:'First and most archetypal Phoenix Lord, founder of the Dire Avenger tradition.'},
{name:'Jain Zar',group:'Aeldari',summary:'Phoenix Lord of the Howling Banshees.'},
{name:'Maugan Ra',group:'Aeldari',summary:'Phoenix Lord of the Dark Reapers, famously associated with Craftworld Altansar.'},
{name:'Commander Farsight',group:'T’au',summary:'T’au commander who broke from Ethereal authority and founded the Farsight Enclaves.'},
{name:'Commander Shadowsun',group:'T’au',summary:'One of the T’au Empire’s most celebrated loyal commanders and a master of Kauyon strategy.'},
{name:'Aun’Va',group:'T’au',summary:'Former supreme Ethereal whose death was concealed through technological simulation and propaganda.'},
{name:'The Hive Mind',group:'Tyranids',summary:'The vast gestalt psychic intelligence directing Tyranid organisms across hive fleets.'},
{name:'The Swarmlord',group:'Tyranids',summary:'Recurring apex Hive Tyrant consciousness deployed by the Hive Mind in critical wars.'},
{name:'Old One Eye',group:'Tyranids',summary:'Legendary Carnifex organism repeatedly encountered by Imperial forces.'},
{name:'The Four-Armed Emperor',group:'Genestealer Cults',summary:'Religious image through which Genestealer Cults often worship their Patriarch and the approaching Tyranid gods.'},
{name:'Khorne',group:'Chaos God',summary:'Chaos God of rage, violence, bloodshed and martial conflict.'},
{name:'Tzeentch',group:'Chaos God',summary:'Chaos God of change, ambition, sorcery and schemes.'},
{name:'Nurgle',group:'Chaos God',summary:'Chaos God of decay, disease, despair and grotesque resilience.'},
{name:'Slaanesh',group:'Chaos God',summary:'Chaos God of excess, obsession, sensation and perfection, born from the Fall of the Aeldari.'},
{name:'Vashtorr the Arkifane',group:'Chaos',summary:'Daemon power of invention and the Soul Forges, allied with Abaddon during Arks of Omen.'},
{name:'Be’lakor',group:'Chaos',summary:'Ancient Daemon Prince who pursues his own ambitions within the rivalries of Chaos.'}
],
glossary:[
['Abhuman','Stable human-derived strain tolerated to varying degrees by the Imperium.'],['Adeptus','High Gothic term used in names of official Imperial bodies and orders.'],['Astartes','Space Marines; Adeptus Astartes.'],['Astronomican','Psychic beacon projected from Terra and used by Navigators.'],['Astropath','Sanctioned psyker specialized in interstellar communication.'],['Black Crusade','Major Chaos campaign against the Imperium, especially those led by Abaddon.'],['Black Rage','Blood Angels gene-curse causing warriors to relive Sanguinius’s death.'],['Blackstone','Mysterious material capable of interacting with and suppressing or amplifying warp phenomena.'],['Blank / Pariah','Person with a null presence in the warp that suppresses psychic effects.'],['Biotransference','Conversion of Necrontyr into Necron living-metal bodies.'],['Butcher’s Nails','Pain-inducing neural implants forced on Angron and later widely implanted into World Eaters.'],['Chapter','Typical post-Heresy Space Marine organization.'],['Cicatrix Maledictum','The Great Rift dividing the galaxy.'],['Codex Astartes','Guilliman-associated doctrine governing Space Marine organization and warfare.'],['Commorragh','Vast Drukhari metropolis hidden in the Webway.'],['Craftworld','Colossal Aeldari world-ship carrying a surviving civilization.'],['C’tan','Ancient star-gods once allied to the Necrontyr and later shattered into shards.'],['Daemon','Warp entity capable of manifesting in realspace.'],['Daemon Engine','Machine fused with or inhabited by a daemon.'],['Daemon Primarch','Primarch ascended into a powerful daemonic state.'],['Ecclesiarchy','The Adeptus Ministorum, institutional church of the Imperial Cult.'],['Exterminatus','Imperial destruction of an entire world judged irrecoverable.'],['Eye of Terror','Huge warp-realspace overlap created by the Fall of the Aeldari.'],['Founding','Creation wave of new Space Marine Chapters.'],['Forge World','Planet dominated by Mechanicus industry.'],['Gene-seed','Biological material used to create Space Marines and preserve lineage.'],['Genestealer','Tyranid organism capable of founding hybrid cult bloodlines.'],['Gellar Field','Field shielding a ship from raw warp exposure.'],['Golden Throne','Ancient device sustaining the Emperor and critical Imperial psychic functions.'],['Great Rift','Common name for the Cicatrix Maledictum.'],['Greater Good','Central ideological principle of the T’au Empire.'],['Haemonculus','Drukhari flesh-sculptor, scientist and torturer capable of extreme biological reconstruction.'],['Hive Fleet','Major Tyranid invasion fleet and distributed super-organism.'],['Hive Mind','Psychic gestalt directing Tyranid organisms.'],['Hive World','Densely populated Imperial planet dominated by giant hive cities.'],['Imperial Cult','State religion worshipping the Emperor as a god.'],['Imperial Truth','Great Crusade secular doctrine rejecting religion and superstition.'],['Imperium Nihilus','Imperial territory on the dark side of the Great Rift.'],['Infinity Circuit','Craftworld psychic network preserving dead Aeldari souls.'],['Inquisitor','Highly autonomous Imperial agent empowered to investigate existential threats.'],['Krork','Ancient engineered warrior species ancestral to Orks.'],['Legion','Original massive Space Marine formation before most loyalists were divided into Chapters.'],['Long War','Chaos Space Marine term for the continuing struggle begun in the Horus Heresy.'],['Machine Spirit','Mechanicus concept of a machine’s sacred operational essence or will.'],['Maelstrom','Large warp anomaly and modern domain of the Red Corsairs.'],['Navigator','Mutant human able to perceive the warp and guide ships through it.'],['Noctis Aeterna','Period of darkness and isolation surrounding the opening of the Great Rift.'],['Old Ones','Ancient psychic civilization central to the War in Heaven.'],['Omnissiah','Sacred Mechanicus figure/aspect associated with the Machine God and divine knowledge.'],['Ordo','Inquisitorial organizational tradition focused on a type of threat.'],['Path','Aeldari discipline used to channel their intense psychology into controlled lives and vocations.'],['Perpetual','Rare being capable of extraordinary regeneration or resurrection.'],['Phoenix Lord','Legendary founder/master of an Aeldari Aspect Warrior tradition.'],['Primarch','One of the Emperor’s gene-crafted superhuman sons.'],['Primaris','Newer Space Marine type developed through Cawl’s long project.'],['Psyker','Being capable of drawing on the warp through psychic ability.'],['Red Thirst','Blood Angels gene-curse producing predatory hunger and rage.'],['Rogue Trader','Holder of a warrant granting extraordinary freedom to explore and act beyond normal Imperial borders.'],['Rubric Marine','Thousand Sons warrior reduced to dust sealed inside armor by Ahriman’s Rubric.'],['Segmentum','Enormous administrative division of Imperial space.'],['Servitor','Cyborg labor unit with drastically reduced autonomy.'],['Shadow in the Warp','Psychic smothering effect surrounding major Tyranid forces.'],['Soul Stone','Aeldari spirit stone that captures a soul at death.'],['STC','Standard Template Construct; foundational Dark Age technology system/template.'],['Successor Chapter','Space Marine Chapter descended from an earlier gene-seed lineage.'],['Synapse','Tyranid psychic control network.'],['Tomb World','Planetary Necron necropolis containing sleeping dynasties.'],['Traitor Legion','Original Space Marine Legion that rebelled during the Horus Heresy.'],['Waaagh!','Ork war cry and the mass psycho-social phenomenon of a huge Ork migration/war.'],['Warmaster','Supreme military title held by Horus and later claimed by Abaddon.'],['Warp / Immaterium','Psychic parallel dimension used for FTL travel and inhabited by daemons and Chaos powers.'],['Webway','Ancient network of stable extradimensional passages strongly associated with the Old Ones and Aeldari.'],['Wraithbone','Psychically shaped Aeldari material used for structures, weapons and technology.'],['Xenos','Imperial term for alien species.']
],
coverage:['War in Heaven','Old Ones','Necrontyr','C’tan','Biotransference','Krork','Aeldari Empire','Dark Age of Technology','STCs','Men of Iron','Age of Strife','Fall of Aeldari','Birth of Slaanesh','Unification Wars','Thunder Warriors','Treaty of Mars','Great Crusade','Interex','Diasporex','Primarch scattering','Lost Legions II and XI','Rangdan Xenocides','Ullanor','Council of Nikaea','Davin','Isstvan III','Isstvan V','Prospero','Phall','Thramas','Calth','Shadow Crusade','Signus','Imperium Secundus','Molech','Tallarn','Webway War','Beta-Garmon','Solar War','Siege of Terra','Golden Throne','Great Scouring','Iron Cage','Caliban','Second Founding','Codex Astartes','Legion Wars','First Black Crusade','War of the Beast','Nova Terra Interregnum','Moirae Schism','Age of Apostasy','Abyssal Crusade','Macharian Crusade','Gothic War','Maelstrom Warders','Astral Claws','Tiger Claws','Badab War','Red Corsairs','Siege of Vraks','Armageddon Wars','Sabbat Worlds','T’au expansion','Damocles','First Tyrannic War','Second Tyrannic War','Third Tyrannic War','Fourth Tyrannic War','Kryptman','Octarius','Devastation of Baal','Necron awakening','Fall of Cadia','Great Rift','Ynnari','Guilliman return','Primaris','Indomitus Crusade','Plague Wars','Vigilus','Psychic Awakening','Pariah Nexus','Nachmund','Arks of Omen','Lion return','2026 Maelstrom campaign','18 known Legions','major loyalist successor Chapters','Badab participants','Imperial Guard regiments','Forge Worlds','Sororitas Orders','Custodes Shield Hosts','Inquisition Ordos','Knight Houses','Craftworlds','Drukhari Kabals/Cults/Covens','Harlequin Masques','Necron Dynasties','Ork Clans','Hive Fleets','Genestealer Cults','T’au Septs and auxiliaries','Votann Leagues','Chaos warbands']
};