window.WH40K_EXTRAS={
wars:[
{name:'War in Heaven',era:'Ancient',summary:'Galaxy-shaping conflict between the Old Ones, Necrontyr/Necrons, C’tan and ancient engineered races. Most surviving accounts are mythic or reconstructed.',uncertain:true},
{name:'Unification Wars',era:'M30',summary:'The Emperor’s conquest of Terra and destruction or absorption of techno-barbarian states before the Great Crusade.'},
{name:'Great Crusade',era:'M30–M31',summary:'The Imperium’s massive expansion across the galaxy to reunite human worlds and crush rival civilizations.'},
{name:'Rangdan Xenocides',era:'Great Crusade',summary:'Extremely costly wars against the Rangda involving multiple Legions; one of the most deliberately obscure Crusade campaigns.',uncertain:true},
{name:'Ullanor Crusade',era:'Great Crusade',summary:'Imperial campaign against a vast Ork empire culminating in the Triumph of Ullanor and Horus becoming Warmaster.'},
{name:'Horus Heresy',era:'M31',summary:'Civil war caused by Horus’s rebellion that fractures the Imperium, destroys the original Legion order and ends with the Emperor enthroned.'},
{name:'Isstvan III Atrocity',era:'Horus Heresy',summary:'Traitor Legions purge loyalists from their own ranks, revealing the rebellion.'},
{name:'Drop Site Massacre',era:'Horus Heresy',summary:'Loyalist forces are betrayed at Isstvan V; Iron Hands, Salamanders and Raven Guard suffer catastrophic losses.'},
{name:'Burning of Prospero',era:'Horus Heresy',summary:'Space Wolves attack Prospero after Magnus’s psychic warning breaches the Emperor’s Webway project.'},
{name:'Battle of Calth',era:'Horus Heresy',summary:'Word Bearers ambush the Ultramarines and open the Shadow Crusade.'},
{name:'Shadow Crusade',era:'Horus Heresy',summary:'Word Bearers and World Eaters devastate Ultramar while the Ruinstorm isolates loyalist regions.'},
{name:'Thramas Crusade',era:'Horus Heresy',summary:'Dark Angels and Night Lords fight a prolonged campaign across the Thramas Sector.'},
{name:'Battle of Molech',era:'Horus Heresy',summary:'Horus returns to a world tied to the Emperor’s hidden past and emerges with greatly increased warp power.'},
{name:'Battle of Tallarn',era:'Horus Heresy',summary:'One of the largest armored wars in Imperial history after Tallarn is devastated by Iron Warriors.'},
{name:'Titandeath / Beta-Garmon',era:'Horus Heresy',summary:'Gigantic pre-Siege battle involving enormous Titan forces and massed Legions.'},
{name:'Solar War',era:'Siege of Terra',summary:'Traitor fleets invade the Sol System and drive loyalist defenses back toward Terra.'},
{name:'Siege of Terra',era:'M31',summary:'Final campaign of the Horus Heresy, ending with Horus dead and the Emperor mortally wounded.'},
{name:'Great Scouring',era:'M31',summary:'Post-Heresy loyalist campaigns driving traitors into the Eye of Terror and punishing rebel worlds.'},
{name:'Iron Cage',era:'Scouring',summary:'Ruinous Imperial Fists–Iron Warriors conflict after the Heresy, deeply tied to Dorn and Perturabo’s rivalry.'},
{name:'War of the Beast',era:'M32',summary:'Massive Ork invasion that nearly breaks the Imperium and forces political and military reform.'},
{name:'Nova Terra Interregnum',era:'M35',summary:'Long political schism in which large Imperial regions reject Terra’s authority.'},
{name:'Age of Apostasy',era:'M36',summary:'Goge Vandire’s tyranny and the Reign of Blood reshape the Ecclesiarchy and produce the modern Adepta Sororitas.'},
{name:'Abyssal Crusade',era:'M36',summary:'Dozens of Space Marine Chapters are ordered into the Eye of Terror; many are destroyed or corrupted.'},
{name:'Macharian Crusade',era:'M41',summary:'One of the largest Imperial conquests since the Great Crusade, led by Lord Solar Macharius.'},
{name:'Gothic War / 12th Black Crusade',era:'M41',summary:'Abaddon’s campaign across the Gothic Sector involving Blackstone Fortresses.'},
{name:'Badab War',era:'901–912.M41',summary:'Space Marine civil war centered on the Astral Claws, Badab Sector and Lufgt Huron. Rebel and loyalist Chapters fight over sovereignty, tithes and Imperial authority.',url:'https://wh40k.lexicanum.com/wiki/Badab_War'},
{name:'Siege of Vraks',era:'M41',summary:'Long siege that escalates from Imperial rebellion into a major Chaos war involving the Death Korps of Krieg and traitor forces.'},
{name:'First War for Armageddon',era:'M41',summary:'Chaos invasion led by Angron, followed by severe Imperial secrecy and purges.'},
{name:'Second War for Armageddon',era:'M41',summary:'Ghazghkull Thraka’s first enormous invasion of Armageddon.'},
{name:'Third War for Armageddon',era:'M41',summary:'Ghazghkull returns with an even larger Waaagh!, creating one of the setting’s defining Ork wars.'},
{name:'Sabbat Worlds Crusade',era:'M41',summary:'Imperial campaign to reconquer the Sabbat Worlds from Chaos, central to Gaunt’s Ghosts lore.'},
{name:'Damocles Crusade',era:'M41',summary:'Imperial crusade against the expanding T’au Empire; ends without permanently halting T’au growth.'},
{name:'First Tyrannic War',era:'745.M41',summary:'Hive Fleet Behemoth attacks Macragge and reveals the Tyranid threat to the Imperium.'},
{name:'Second Tyrannic War',era:'990s.M41',summary:'Hive Fleet Kraken launches a dispersed invasion and devastates Craftworld Iyanden.'},
{name:'Third Tyrannic War',era:'Late M41',summary:'Hive Fleet Leviathan invades from below the galactic plane.'},
{name:'Octarius War',era:'Late M41–Indomitus',summary:'Orks and Tyranids become locked in an escalating war originally encouraged by Inquisitor Kryptman.'},
{name:'Devastation of Baal',era:'Time of Ending',summary:'Hive Fleet Leviathan assaults the Blood Angels home system as the Great Rift opens.'},
{name:'13th Black Crusade',era:'999.M41',summary:'Abaddon’s offensive destroys Cadia and helps trigger the Great Rift.'},
{name:'Fall of Cadia',era:'999.M41',summary:'Cadia is shattered after its defenders resist Abaddon’s forces to the end.'},
{name:'Indomitus Crusade',era:'Era Indomitus',summary:'Guilliman’s vast campaign to stabilize and reconnect the Imperium after the Great Rift.'},
{name:'Plague Wars',era:'Era Indomitus',summary:'Death Guard invasion of Ultramar led by Mortarion against Guilliman’s realm.'},
{name:'Wars of Vigilus',era:'Era Indomitus',summary:'Multi-faction wars over a strategically vital region near the Nachmund Gauntlet.'},
{name:'Psychic Awakening',era:'Era Indomitus',summary:'Series of galaxy-wide conflicts accompanying a surge in psychic activity after the Great Rift.'},
{name:'Pariah Nexus Campaign',era:'Era Indomitus',summary:'Imperial forces fight Necrons in a region where warp energy is unnaturally suppressed.'},
{name:'War Zone Nachmund',era:'Era Indomitus',summary:'Imperial and Chaos wars over a rare stable route through the Great Rift.'},
{name:'Arks of Omen',era:'Era Indomitus',summary:'Abaddon and Vashtorr deploy Arks in search of the components of the Key.'},
{name:'Fourth Tyrannic War',era:'Era Indomitus',summary:'A renewed Leviathan offensive attacks from the western reaches of the galaxy with overwhelming force.'},
{name:'The Maelstrom: Lair of the Tyrant',era:'2026 setting',summary:'Modern Red Corsairs and Aeldari Corsairs clash around Huron Blackheart’s Maelstrom domain.',url:'https://www.warhammer-community.com/en-gb/articles/lke65sad/sunday-preview-huron-blackheart-sets-sail-from-the-maelstrom/'}
],
places:[
{name:'Terra',type:'World',summary:'Birthplace of humanity, capital of the Imperium and location of the Imperial Palace, Golden Throne and Astronomican.'},
{name:'Mars',type:'World',summary:'Sacred Forge World and political heart of the Adeptus Mechanicus.'},
{name:'Luna',type:'Moon',summary:'Terra’s moon and site of important gene-labs, shipyards and Great Crusade-era battles.'},
{name:'Sol System',type:'System',summary:'Fortified heart of the Imperium containing Terra, Mars and critical Imperial infrastructure.'},
{name:'Eye of Terror',type:'Warp region',summary:'Massive overlap of realspace and warp created by the Fall of the Aeldari; ancient refuge of the Traitor Legions.'},
{name:'Maelstrom',type:'Warp region',summary:'Large warp anomaly, pirate haven and modern dominion of Huron Blackheart and the Red Corsairs.',url:'https://wh40k.lexicanum.com/wiki/Maelstrom'},
{name:'Badab Primaris',type:'World',summary:'Former center of Lufgt Huron’s rule and principal world of the Badab Sector; devastated in the climax of the Badab War.',url:'https://wh40k.lexicanum.com/wiki/Badab_Primaris'},
{name:'Endymion Cluster',type:'Region',summary:'Region associated with the Mantis Warriors and strategic struggles around the Maelstrom.'},
{name:'Caliban',type:'Destroyed world',summary:'Homeworld of Lion El’Jonson and the Dark Angels; destroyed after a post-Heresy civil war.'},
{name:'Fenris',type:'World',summary:'Death world and home of the Space Wolves.'},
{name:'Baal',type:'World/System',summary:'Home system of the Blood Angels and site of the Devastation of Baal.'},
{name:'Macragge',type:'World',summary:'Homeworld of the Ultramarines and capital of Ultramar; major battlefield of the First Tyrannic War.'},
{name:'Ultramar',type:'Realm',summary:'Highly organized region ruled historically by Guilliman and the Ultramarines.'},
{name:'Prospero',type:'World',summary:'Former homeworld of Magnus and the Thousand Sons, devastated by the Space Wolves.'},
{name:'Chemos',type:'World',summary:'Homeworld associated with Fulgrim and the Emperor’s Children.'},
{name:'Olympia',type:'World',summary:'Perturabo’s adopted homeworld and source of the Iron Warriors’ culture.'},
{name:'Chogoris',type:'World',summary:'Homeworld of Jaghatai Khan and the White Scars.'},
{name:'Inwit',type:'World/realm',summary:'Realm associated with Rogal Dorn before his reunion with the Emperor.'},
{name:'Nostramo',type:'Destroyed world',summary:'Konrad Curze’s brutal homeworld, later destroyed by the Night Lords themselves.'},
{name:'Medusa',type:'World',summary:'Homeworld of Ferrus Manus and the Iron Hands.'},
{name:'Nuceria',type:'World',summary:'World where Angron was enslaved and implanted with the Butcher’s Nails.'},
{name:'Barbarus',type:'World',summary:'Toxic homeworld of Mortarion before the Great Crusade.'},
{name:'Colchis',type:'World',summary:'Religious homeworld of Lorgar and the Word Bearers.'},
{name:'Nocturne',type:'World',summary:'Volcanic homeworld of Vulkan and the Salamanders.'},
{name:'Deliverance',type:'Moon',summary:'Moon associated with Corvus Corax and the Raven Guard.'},
{name:'Cthonia',type:'World',summary:'World strongly associated with Horus and the XVI Legion.'},
{name:'Isstvan III',type:'World',summary:'Site of the traitor purge of loyalist elements at the start of the Heresy.'},
{name:'Isstvan V',type:'World',summary:'Site of the Drop Site Massacre.'},
{name:'Calth',type:'World',summary:'Ultramar world devastated by the Word Bearers during the Heresy.'},
{name:'Molech',type:'World',summary:'World containing a warp gate tied to the Emperor’s mysterious past and Horus’s later empowerment.'},
{name:'Tallarn',type:'World',summary:'Desert world created by Heresy-era devastation and home of the Tallarn Desert Raiders.'},
{name:'Beta-Garmon',type:'System',summary:'Strategic system and site of the Titandeath before the Siege of Terra.'},
{name:'Cadia',type:'Destroyed world',summary:'Fortress world guarding the Cadian Gate; destroyed in the 13th Black Crusade but culturally survives through its armies.'},
{name:'Cadian Gate',type:'Region',summary:'Strategic route around the Eye of Terror historically anchored by Cadia and Necron pylon networks.'},
{name:'Armageddon',type:'World',summary:'Industrial hive world repeatedly invaded by Chaos and Orks.'},
{name:'Krieg',type:'World',summary:'Devastated world whose militarized culture produces the Death Korps of Krieg.'},
{name:'Catachan',type:'Death world',summary:'Extremely lethal jungle world producing the Catachan Jungle Fighters.'},
{name:'Vostroya',type:'World',summary:'Industrial world whose Firstborn regiments serve an ancient hereditary military debt.'},
{name:'Tanith',type:'Destroyed world',summary:'Forest world destroyed as its Guard regiment was mustering; surviving soldiers become the Tanith First-and-Only.'},
{name:'Commorragh',type:'Webway city',summary:'Enormous Drukhari metropolis composed of linked sub-realms hidden in the Webway.'},
{name:'Black Library',type:'Webway realm',summary:'Secret Aeldari repository containing knowledge about Chaos.'},
{name:'Craftworld Ulthwé',type:'Craftworld',summary:'Aeldari craftworld near the Eye of Terror, famous for psykers and Eldrad Ulthran.'},
{name:'Craftworld Biel-Tan',type:'Craftworld',summary:'Militant craftworld historically devoted to restoring Aeldari dominance.'},
{name:'Craftworld Iyanden',type:'Craftworld',summary:'Craftworld devastated by Hive Fleet Kraken and now heavily dependent on Wraith constructs.'},
{name:'Craftworld Saim-Hann',type:'Craftworld',summary:'Clan-based craftworld famed for Wild Riders and jetbike warfare.'},
{name:'Craftworld Alaitoc',type:'Craftworld',summary:'Strict craftworld known for producing many Rangers.'},
{name:'Solemnace',type:'Necron world',summary:'Trazyn the Infinite’s gallery-world containing his immense collection.'},
{name:'Mandragora',type:'Necron world',summary:'Major Necron world associated with Imotekh and the Sautekh Dynasty.'},
{name:'T’au',type:'World',summary:'Homeworld and political heartland of the T’au species and Empire.'},
{name:'Farsight Enclaves',type:'Region',summary:'Independent T’au frontier realm ruled by Commander Farsight.'},
{name:'Octarius',type:'Region',summary:'Former Ork empire used as the center of Kryptman’s attempt to redirect Tyranids.'},
{name:'Nachmund Gauntlet',type:'Region',summary:'One of the few relatively stable passages through the Great Rift.'},
{name:'Vigilus',type:'World',summary:'Strategic world anchoring access through the Nachmund region.'},
{name:'Pariah Nexus',type:'Region',summary:'Necron-controlled zone where warp influence is suppressed.'},
{name:'Imperium Nihilus',type:'Galactic region',summary:'Dark half of the Imperium cut off from reliable sight of the Astronomican after the Great Rift.'}
],
tech:[
{name:'Golden Throne',type:'Imperial archeotech',summary:'Ancient device sustaining the Emperor and supporting critical psychic functions tied to Terra.'},
{name:'Astronomican',type:'Psychic beacon',summary:'Imperial psychic lighthouse used by Navigators for long-range warp travel.'},
{name:'Standard Template Construct (STC)',type:'Dark Age technology',summary:'Ancient systems and templates that underpin much surviving human technology.'},
{name:'Blackstone',type:'Ancient material',summary:'Material capable of suppressing or amplifying warp energy depending on configuration.'},
{name:'Blackstone Fortress',type:'Ancient megastructure',summary:'Mysterious space fortresses capable of catastrophic destruction and warp manipulation.'},
{name:'Webway',type:'Ancient infrastructure',summary:'Stable extradimensional transit network associated with the Old Ones and Aeldari.'},
{name:'Pylon network',type:'Necron technology',summary:'Blackstone structures capable of suppressing warp influence; historically crucial around Cadia and the Pariah Nexus.'},
{name:'Living Metal / Necrodermis',type:'Necron technology',summary:'Self-repairing metallic substance forming Necron bodies and many constructs.'},
{name:'Dolmen Gate',type:'Necron technology',summary:'Necron method for breaching and exploiting sections of the Webway.'},
{name:'Celestial Orrery',type:'Necron artifact',summary:'Necron device representing stars across the galaxy with terrifying potential to affect them directly.'},
{name:'Tesseract Labyrinth',type:'Necron artifact',summary:'Pocket-dimensional prison used to contain entities or dangerous phenomena.'},
{name:'C’tan Shard',type:'Necron weapon/entity',summary:'Fragment of a shattered star-god enslaved and deployed by Necron dynasties.'},
{name:'Soul Stone',type:'Aeldari artifact',summary:'Spirit stone capturing an Aeldari soul at death to protect it from Slaanesh.'},
{name:'Infinity Circuit',type:'Aeldari psychic network',summary:'Craftworld network preserving the souls of the dead.'},
{name:'Wraithbone',type:'Aeldari material',summary:'Psychically shaped material forming much Aeldari architecture and technology.'},
{name:'Avatar of Khaine',type:'Aeldari war construct',summary:'Manifestation of the shattered war god Khaine awakened within a Craftworld.'},
{name:'Crone Sword',type:'Ynnari relic',summary:'One of the legendary swords tied to Ynnead and Ynnari attempts to defeat Slaanesh.'},
{name:'Dawn Blade',type:'T’au relic',summary:'Ancient weapon wielded by Commander Farsight whose true origins remain mysterious.',uncertain:true},
{name:'Battlesuit',type:'T’au technology',summary:'Powered combat exoskeleton central to elite T’au Fire Caste warfare.'},
{name:'Railgun',type:'T’au technology',summary:'Hypervelocity electromagnetic weapon strongly associated with T’au warfare.'},
{name:'Ancestor Core / Votann',type:'Kin technology',summary:'Ancient supercomputing intelligences storing immense cultural and technical memory for the Leagues of Votann.'},
{name:'Ironkin',type:'Kin machine intelligence',summary:'Artificially intelligent Kin treated as full members of League society rather than forbidden machines.'},
{name:'Gene-seed',type:'Astartes biotechnology',summary:'Biological organs and genetic material used to transform humans into Space Marines and preserve Chapter lineages.'},
{name:'Black Carapace',type:'Astartes implant',summary:'Space Marine implant enabling direct neural integration with power armor.'},
{name:'Butcher’s Nails',type:'Neural implants',summary:'Pain-inducing implants forced on Angron and many World Eaters, amplifying rage and aggression.'},
{name:'Rubric of Ahriman',type:'Sorcerous event/ritual',summary:'Spell that saved Thousand Sons from mutation but reduced most non-psyker Legionaries to dust-filled armor.'},
{name:'Terminator Armor',type:'Imperial armor',summary:'Extremely heavy Tactical Dreadnought Armour used by elite Space Marines and other Imperial forces.'},
{name:'Dreadnought',type:'Astartes war machine',summary:'Armored sarcophagus allowing mortally wounded Space Marines to continue fighting.'},
{name:'Titan',type:'God-engine',summary:'Colossal war machine operated by the Collegia Titanica; classes range from Scout Titans to immense battle engines.'},
{name:'Imperial Knight',type:'Knight suit',summary:'Large hereditary war engine piloted by bonded nobles of Knight Houses.'},
{name:'Baneblade',type:'Imperial super-heavy tank',summary:'Iconic Imperial super-heavy battle tank used by the Astra Militarum.'},
{name:'Land Raider',type:'Astartes vehicle',summary:'Ancient heavily armored assault transport named after Arkhan Land.'},
{name:'Bolter',type:'Imperial weapon',summary:'Mass-reactive projectile weapon iconic to Space Marines and many Imperial organizations.'},
{name:'Chainsword',type:'Imperial weapon',summary:'Motorized chain-blade used throughout Imperial military forces.'},
{name:'Power Weapon',type:'Energy melee weapon',summary:'Melee weapon surrounded by a disruptive energy field capable of defeating heavy armor.'},
{name:'Force Weapon',type:'Psychic weapon',summary:'Weapon allowing a psyker to channel warp power through the blade or staff.'},
{name:'Gellar Field',type:'Warp technology',summary:'Protective field shielding ships from direct exposure to the warp during transit.'},
{name:'Warp Drive',type:'FTL technology',summary:'Human and Chaos technology enabling ships to enter the Immaterium for faster-than-light travel.'},
{name:'Teleportarium',type:'Transport technology',summary:'Dangerous matter-transport technology used by advanced Imperial forces and other factions.'},
{name:'Cyclonic Torpedo',type:'Exterminatus weapon',summary:'Strategic weapon used in some forms of planet-killing Exterminatus.'},
{name:'Virus Bomb',type:'Exterminatus weapon',summary:'Biological weapon used to rapidly destroy planetary life in certain Exterminatus protocols.'},
{name:'Phosphex',type:'Forbidden weapon',summary:'Extremely persistent incendiary substance notorious since the Great Crusade and Heresy.'},
{name:'Archeotech',type:'Technology category',summary:'Ancient technology, often from the Dark Age of Technology or other lost eras, no longer fully understood.'},
{name:'Daemon Engine',type:'Chaos technology',summary:'Machine fused with or inhabited by a daemon.'},
{name:'Defiler',type:'Chaos daemon engine',summary:'Large spider-like daemon engine used by Chaos Space Marines.'},
{name:'Heldrake',type:'Chaos daemon engine',summary:'Warp-corrupted flying daemon engine used by Chaos Space Marines.'},
{name:'Arks of Omen',type:'Chaos megavessels',summary:'Space hulks transformed into enormous invasion vessels for Abaddon and Vashtorr’s campaign.'},
{name:'Blackstone Key',type:'Arks of Omen objective',summary:'Mysterious composite artifact assembled by Vashtorr from recovered fragments during the Arks of Omen campaign.'},
{name:'Ork Shokk Attack Gun',type:'Ork technology',summary:'Unstable Ork weapon exploiting teleportation and warp phenomena in characteristic Mek fashion.'},
{name:'Kustom Force Field',type:'Ork technology',summary:'Ork energy-field technology constructed by Meks through a mix of engineering intuition and ramshackle improvisation.'},
{name:'Synapse Network',type:'Tyranid biology',summary:'Psychic command structure connecting Tyranid organisms to the Hive Mind.'},
{name:'Norn Queen',type:'Tyranid organism',summary:'Immense reproductive and genetic-control organism associated with hive fleet bio-ships.'},
{name:'Reclamation Pool',type:'Tyranid biology',summary:'Biological digestion system used to break consumed matter back into reusable biomass.'}
]};